# =====================================================================
# SLIM copy of true_akw_pipeline/precompute_adn_phi_table.py
#
# 8 top-level symbols (346 lines, 27% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   build_eps_grid, build_kjac_geometry_cache, build_phi_geometry_cache, build_phipanel_geometry_cache, enforce_safe_ranges, enrich_grid_with_feature_windows, load_akw_cube, precompute_kjac_integrated_slice, precompute_phi_integrated_slice, precompute_phi_integrated_table
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   _scalar_from_npz
#   load_cube_physics
#   load_cube_a_convention
#   parse_args
#   parse_q_values
#   parse_float_list
#   save_diagnostics
#   main
# =====================================================================
#!/usr/bin/env python3
r"""Precompute translated A_down table with phi integration.

Goal:
- Build grids with user-requested ranges:
  omega in [-20, 20], p in [0, 6]
- For each omega/p/eps, evaluate
    A_down(|q-p|_phi, omega-eps)
  on a phi grid and precompute phi-integrated table:
    A_down_phi_int(omega,p,eps) = \int_0^{2pi} dphi A_down(...)

This is useful when the integrand has A_up(p,eps) * A_down(...),
because A_up is phi-independent and phi can be absorbed into this table.
"""

from __future__ import annotations

import argparse
import os
from datetime import datetime
from pathlib import Path

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]

# --------------------------
# Editable settings
# --------------------------
Q_VALUES = [0.0]

ROUTING = "difference"  # "difference" -> |q-p| geometry, "sum" -> |q+p|

OMEGA_MIN = -20.0
OMEGA_MAX = 20.0
N_OMEGA = 601
OMEGA_FEATURE_DENSE = False
OMEGA_FEATURE_HALF_WIDTH = 1.0
OMEGA_FEATURE_N_LOCAL = 81

P_MIN = 0.0
P_MAX = 1.75
N_P = 241
P_FEATURE_DENSE = False
P_FEATURE_HALF_WIDTH = 0.06
P_FEATURE_N_LOCAL = 61

EPS_MIN = -20.0
EPS_MAX = 20.0
N_EPS = 601
EPS_GRID_MODE = "linear"   # "split" or "linear"
EPS_SPLIT_POWER = 2.5     # >1 -> denser near eps=0 when split mode is used
EPS_INCLUDE_OMEGA_NODES = False

N_PHI = 96

ENFORCE_SAFE_SUPPORT = False

OUT_BASE = REPO_ROOT / "true_akw_pipeline" / "translated_adn_tables"
SAVE_FLOAT32 = True














def load_akw_cube(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    with np.load(path) as data:
        k = np.asarray(data["k"], dtype=float)
        w = np.asarray(data["w"], dtype=float)
        a = np.asarray(data["A"], dtype=float)
        w_base = np.asarray(data["w_base"], dtype=float) if "w_base" in data.files else None
    if k.ndim != 1 or w.ndim not in (1, 2) or a.ndim != 2:
        raise ValueError(f"Invalid cube shapes in {path}: k{k.shape}, w{w.shape}, A{a.shape}")
    nw = w.shape[-1]
    if a.shape != (k.size, nw):
        raise ValueError(f"A shape mismatch in {path}: expected {(k.size, nw)}, got {a.shape}")
    if w.ndim == 2:
        if w.shape[0] != k.size:
            raise ValueError(f"w 2D but row count {w.shape[0]} != k.size {k.size}")
        rowaware = str(os.environ.get("PAIR_ROWAWARE_OMEGA", "1")).strip().lower() not in {"0", "false", "no", "off"}
        if not rowaware:
            w_1d = w_base if (w_base is not None and w_base.ndim == 1) else w[0]
            a_out = np.empty((k.size, w_1d.size), dtype=float)
            for ik in range(k.size):
                a_out[ik] = np.interp(w_1d, w[ik], a[ik], left=0.0, right=0.0)
            w = w_1d
            a = a_out
    return k, w, a


def partner_momentum(p: np.ndarray | float, q: float, phi: np.ndarray | float, routing: str) -> np.ndarray:
    p_arr = np.asarray(p, dtype=float)
    phi_arr = np.asarray(phi, dtype=float)
    qf = float(q)
    cphi = np.cos(phi_arr)
    if str(routing).strip().lower() == "sum":
        k2_sq = p_arr * p_arr + qf * qf + 2.0 * p_arr * qf * cphi
    else:
        k2_sq = p_arr * p_arr + qf * qf - 2.0 * p_arr * qf * cphi
    return np.sqrt(np.maximum(k2_sq, 0.0))


def interp_weights_1d(axis: np.ndarray, query: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    x = np.asarray(axis, dtype=float)
    q = np.asarray(query, dtype=float)
    inside = (q >= float(x[0])) & (q <= float(x[-1]))

    i0 = np.searchsorted(x, q, side="right") - 1
    i0 = np.clip(i0, 0, x.size - 2)
    i1 = i0 + 1

    x0 = x[i0]
    x1 = x[i1]
    t = (q - x0) / np.maximum(x1 - x0, 1.0e-14)
    return i0.astype(np.int32), i1.astype(np.int32), t.astype(float), inside


def eval_translated_a_rows(
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    a_vals: np.ndarray,
    ki0: np.ndarray,
    ki1: np.ndarray,
    tk: np.ndarray,
    kin: np.ndarray,
    w_query: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Evaluate A(k, w_query) for precomputed k interpolation geometry.

    ``w_axis`` can be a shared 1D grid or a row-local 2D grid.  The 2D path is
    intentionally a little more explicit: each translated momentum point has
    its own pair of bracketing k rows, and each bracketing row may have a
    different omega grid.
    """
    w = np.asarray(w_axis, dtype=float)
    wf = np.asarray(w_query, dtype=float)
    ki0_arr = np.asarray(ki0, dtype=np.intp)
    ki1_arr = np.asarray(ki1, dtype=np.intp)
    tk_arr = np.asarray(tk, dtype=float)
    kin_arr = np.asarray(kin, dtype=bool)
    base_shape = ki0_arr.shape
    n_wq = int(wf.size)

    if w.ndim == 1:
        wi0, wi1, tw, win = interp_weights_1d(w, wf)
        tw_b = tw.reshape((1,) * len(base_shape) + (n_wq,))
        win_b = win.reshape((1,) * len(base_shape) + (n_wq,))
        tk_b = tk_arr[..., None]
        kin_b = kin_arr[..., None]
        a00 = a_vals[ki0_arr[..., None], wi0.reshape((1,) * len(base_shape) + (n_wq,))]
        a10 = a_vals[ki1_arr[..., None], wi0.reshape((1,) * len(base_shape) + (n_wq,))]
        a01 = a_vals[ki0_arr[..., None], wi1.reshape((1,) * len(base_shape) + (n_wq,))]
        a11 = a_vals[ki1_arr[..., None], wi1.reshape((1,) * len(base_shape) + (n_wq,))]
        interp = (
            (1.0 - tk_b) * (1.0 - tw_b) * a00
            + tk_b * (1.0 - tw_b) * a10
            + (1.0 - tk_b) * tw_b * a01
            + tk_b * tw_b * a11
        )
        support = kin_b & win_b
        return np.where(support, interp, 0.0), support

    if w.ndim != 2:
        raise ValueError(f"w_axis must be 1D or 2D, got shape {w.shape}")

    out = np.zeros(base_shape + (n_wq,), dtype=float)
    support = np.zeros(base_shape + (n_wq,), dtype=bool)
    flat_out = out.reshape((-1, n_wq))
    flat_support = support.reshape((-1, n_wq))
    flat_ki0 = ki0_arr.ravel()
    flat_ki1 = ki1_arr.ravel()
    flat_tk = tk_arr.ravel()
    flat_kin = kin_arr.ravel()

    for idx in range(flat_ki0.size):
        if not bool(flat_kin[idx]):
            continue
        i0 = int(flat_ki0[idx])
        i1 = int(flat_ki1[idx])
        w0 = w[i0]
        w1 = w[i1]
        in_w = (wf >= max(float(w0[0]), float(w1[0]))) & (wf <= min(float(w0[-1]), float(w1[-1])))
        flat_support[idx, in_w] = True
        if not np.any(in_w):
            continue
        a0 = np.interp(wf[in_w], w0, a_vals[i0], left=0.0, right=0.0)
        a1 = np.interp(wf[in_w], w1, a_vals[i1], left=0.0, right=0.0)
        flat_out[idx, in_w] = (1.0 - float(flat_tk[idx])) * a0 + float(flat_tk[idx]) * a1

    return out, support


def rebuild_translated_a_rows(
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    re_sigma: np.ndarray,
    im_sigma: np.ndarray,
    ki0: np.ndarray,
    ki1: np.ndarray,
    tk: np.ndarray,
    kin: np.ndarray,
    w_query: np.ndarray,
    *,
    mu: float,
    sigma0: float,
    eta: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Interpolate smooth Sigma, then rebuild A at the exact query points."""
    re_i, re_support = eval_translated_a_rows(
        k_axis, w_axis, re_sigma, ki0, ki1, tk, kin, w_query
    )
    im_i, im_support = eval_translated_a_rows(
        k_axis, w_axis, im_sigma, ki0, ki1, tk, kin, w_query
    )
    support = np.asarray(re_support, dtype=bool) & np.asarray(im_support, dtype=bool)

    ki0_arr = np.asarray(ki0, dtype=np.intp)
    ki1_arr = np.asarray(ki1, dtype=np.intp)
    tk_arr = np.asarray(tk, dtype=float)
    k_query = (
        (1.0 - tk_arr) * np.asarray(k_axis, dtype=float)[ki0_arr]
        + tk_arr * np.asarray(k_axis, dtype=float)[ki1_arr]
    )
    wq = np.asarray(w_query, dtype=float).reshape(
        (1,) * k_query.ndim + (np.asarray(w_query).size,)
    )
    xi = k_query[..., None] ** 2 - float(mu)
    gamma = np.abs(im_i) + float(eta)
    rebuilt = (1.0 / np.pi) * gamma / (
        (wq - xi - (re_i - float(sigma0))) ** 2 + gamma * gamma
    )
    return np.where(support, rebuilt, 0.0), support


def build_eps_grid(
    a: float,
    b: float,
    n: int,
    mode: str,
    power: float,
    include_points: np.ndarray | None = None,
) -> np.ndarray:
    a = float(a)
    b = float(b)
    n = int(n)
    if n < 3:
        raise ValueError("N_EPS must be >= 3")
    m = str(mode).strip().lower()
    if m == "linear":
        grid = np.linspace(a, b, n, dtype=float)
    else:
        # split mode: include eps=0 exactly and cluster points near it.
        if not (a < 0.0 < b):
            # If interval does not cross zero, fall back to linear.
            grid = np.linspace(a, b, n, dtype=float)
        else:
            pw = float(max(power, 1.0))
            n_left = n // 2
            n_right = n - 1 - n_left

            t_left = np.linspace(0.0, 1.0, n_left + 1, dtype=float)
            left = a * np.power(1.0 - t_left, pw)    # a ... 0, dense near 0 for pw>1
            t_right = np.linspace(0.0, 1.0, n_right + 1, dtype=float)
            right = b * np.power(t_right, pw)        # 0 ... b

            grid = np.concatenate([left[:-1], right])
            # Ensure strict monotonicity and exact zero.
            i0 = int(np.argmin(np.abs(grid)))
            grid[i0] = 0.0
            if np.any(np.diff(grid) <= 0.0):
                # Robust fallback if numerical ties happen.
                grid = np.linspace(a, b, n, dtype=float)
                i0 = int(np.argmin(np.abs(grid)))
                grid[i0] = 0.0

    # Optionally inject anchor points (e.g. all omega nodes) so eps=omega
    # is always a mesh node and the integrand is split there.
    if include_points is not None:
        pts = np.asarray(include_points, dtype=float).reshape(-1)
        if pts.size > 0:
            pts = pts[(pts >= a) & (pts <= b)]
            if pts.size > 0:
                grid = np.unique(np.concatenate([grid, pts]))

    # Keep exact zero if present.
    i0 = int(np.argmin(np.abs(grid)))
    if abs(float(grid[i0])) < 1.0e-12:
        grid[i0] = 0.0

    if np.any(np.diff(grid) <= 0.0):
        grid = np.unique(np.asarray(grid, dtype=float))
        i0 = int(np.argmin(np.abs(grid)))
        if abs(float(grid[i0])) < 1.0e-12:
            grid[i0] = 0.0
    return grid


def enrich_grid_with_feature_windows(
    base_grid: np.ndarray,
    *,
    a: float,
    b: float,
    features: list[float],
    half_width: float,
    n_local: int,
) -> np.ndarray:
    grid = np.asarray(base_grid, dtype=float).reshape(-1)
    if grid.size == 0:
        return grid
    a = float(a)
    b = float(b)
    hw = max(float(half_width), 0.0)
    nloc = max(3, int(n_local))
    if nloc % 2 == 0:
        nloc += 1

    add: list[np.ndarray] = []
    for f in features:
        fv = float(f)
        if not np.isfinite(fv):
            continue
        if fv < a or fv > b:
            continue
        if hw <= 0.0:
            add.append(np.array([fv], dtype=float))
            continue
        l = max(a, fv - hw)
        r = min(b, fv + hw)
        if r <= l:
            add.append(np.array([fv], dtype=float))
        else:
            add.append(np.linspace(l, r, nloc, dtype=float))

    if add:
        grid = np.unique(np.concatenate([grid, *add]))
    else:
        grid = np.unique(grid)

    if np.any(np.diff(grid) <= 0.0):
        grid = np.unique(grid)
    return grid


def enforce_safe_ranges(
    *,
    q_values: list[float],
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    omega_min_req: float,
    omega_max_req: float,
    p_min_req: float,
    p_max_req: float,
    eps_min_req: float,
    eps_max_req: float,
) -> tuple[float, float, float, float, float, float]:
    """Clip requested ranges to stay strictly inside translated-cube support.

    Safe constraints enforced:
    - p_max <= k_max - max|q|            (so |q-p|_phi always <= k_max)
    - omega/eps clipped so omega-eps is always inside [w_min, w_max]
      for all omega in selected range and eps in selected range.
    """
    q_abs_max = max(abs(float(q)) for q in q_values) if q_values else 0.0
    k_min = float(k_axis[0])
    k_max = float(k_axis[-1])
    w = np.asarray(w_axis, dtype=float)
    if w.ndim == 2:
        # Require a common omega support window shared by all row-local grids.
        w_min = float(np.nanmax(w[:, 0]))
        w_max = float(np.nanmin(w[:, -1]))
    else:
        w_min = float(w[0])
        w_max = float(w[-1])

    p_min = max(float(p_min_req), k_min)
    p_max = min(float(p_max_req), k_max - q_abs_max)
    if not (p_max > p_min):
        raise ValueError(
            "Safe-support p-range is empty: "
            f"requested p=[{p_min_req:+.6g},{p_max_req:+.6g}], "
            f"cube k=[{k_min:+.6g},{k_max:+.6g}], max|q|={q_abs_max:+.6g}."
        )

    # First policy: keep requested omega as much as possible, clip eps.
    omega_min = float(omega_min_req)
    omega_max = float(omega_max_req)
    eps_min = max(float(eps_min_req), float(omega_max - w_max), w_min)
    eps_max = min(float(eps_max_req), float(omega_min - w_min), w_max)

    if not (eps_max > eps_min):
        # Fallback policy: keep requested eps as much as possible, clip omega.
        eps_min = max(float(eps_min_req), w_min)
        eps_max = min(float(eps_max_req), w_max)
        omega_min = max(float(omega_min_req), float(w_min + eps_max))
        omega_max = min(float(omega_max_req), float(w_max + eps_min))
        eps_min = max(float(eps_min), float(omega_max - w_max))
        eps_max = min(float(eps_max), float(omega_min - w_min))

    if not (omega_max > omega_min and eps_max > eps_min):
        raise ValueError(
            "Safe-support omega/eps ranges are empty after clipping. "
            f"Requested omega=[{omega_min_req:+.6g},{omega_max_req:+.6g}], "
            f"eps=[{eps_min_req:+.6g},{eps_max_req:+.6g}], cube w=[{w_min:+.6g},{w_max:+.6g}]."
        )

    return (
        float(omega_min),
        float(omega_max),
        float(p_min),
        float(p_max),
        float(eps_min),
        float(eps_max),
    )


def build_phi_geometry_cache(
    k_axis: np.ndarray,
    p_grid: np.ndarray,
    phi_grid: np.ndarray,
    *,
    q_value: float,
    routing: str,
    phi_chunk_size: int | None = None,
) -> tuple[list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]], float, int]:
    """Cache k-interpolation geometry for a fixed q and phi partition."""
    n_phi = int(phi_grid.size)
    dphi = (2.0 * np.pi) / float(n_phi)
    phi_chunk = n_phi if phi_chunk_size is None else int(max(1, min(int(phi_chunk_size), n_phi)))

    geom_chunks: list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]] = []
    for iph0 in range(0, n_phi, phi_chunk):
        iph1 = min(iph0 + phi_chunk, n_phi)
        k2 = partner_momentum(
            p_grid[None, :],
            float(q_value),
            phi_grid[iph0:iph1, None],
            str(routing),
        )
        ki0, ki1, tk, kin = interp_weights_1d(k_axis, k2)
        geom_chunks.append((ki0, ki1, tk[:, :, None], kin[:, :, None]))
    return geom_chunks, float(dphi), int(n_phi)


def build_kjac_geometry_cache(
    k_axis: np.ndarray,
    p_grid: np.ndarray,
    *,
    q_value: float,
    routing: str,
    n_kquad: int,
    kquad_chunk_size: int | None = None,
    kquad_kf_features: list[float] | None = None,
    kquad_feature_n_local: int = 11,
    kquad_feature_half_width: float = 0.05,
) -> tuple[list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]], float, int]:
    """Cache transformed angular geometry using Chebyshev nodes.

    The angular integral can be written as

        int_0^{2pi} dphi F(k(phi))
        = 2 int_{-1}^{1} du F(k(u)) / sqrt(1-u^2),

    so Gauss-Chebyshev quadrature resolves the endpoint structure much better
    than a coarse uniform phi grid.

    kquad_kf_features: list of kF values (e.g. [kF_up, kF_dn]) around which to
        add local dense nodes in k_- space.  Each kF that falls inside [|q-p|, q+p]
        gets kquad_feature_n_local trapezoidal nodes in
        k_- ∈ [kF - kquad_feature_half_width, kF + kquad_feature_half_width],
        converted to u = (p²+q²-k_-²)/(2pq) with uniform weights (the 1/sqrt(1-u²)
        Jacobian factor is applied explicitly so these nodes participate in the same
        accumulated integral).
    """
    n_quad = int(max(2, n_kquad))
    chunk = n_quad if kquad_chunk_size is None else int(max(1, min(int(kquad_chunk_size), n_quad)))
    u_nodes, u_weights = np.polynomial.chebyshev.chebgauss(n_quad)

    p = np.asarray(p_grid, dtype=float)[None, :]
    u = np.asarray(u_nodes, dtype=float)[:, None]
    qf = float(q_value)
    if str(routing).strip().lower() == "sum":
        k2_sq = p * p + qf * qf + 2.0 * p * qf * u
    else:
        k2_sq = p * p + qf * qf - 2.0 * p * qf * u
    k_nodes = np.sqrt(np.maximum(k2_sq, 0.0))

    # Full angular integral is 2 times the Chebyshev-weighted u integral.
    full_weights = 2.0 * np.asarray(u_weights, dtype=float)
    weight_total = float(np.sum(full_weights))

    geom_chunks: list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]] = []
    for iq0 in range(0, n_quad, chunk):
        iq1 = min(iq0 + chunk, n_quad)
        ki0, ki1, tk, kin = interp_weights_1d(k_axis, k_nodes[iq0:iq1])
        quad_w = full_weights[iq0:iq1, None, None]
        geom_chunks.append((ki0, ki1, tk[:, :, None], kin[:, :, None], quad_w))

    # NOTE: kF feature nodes in k_- space require a composite quadrature rule
    # (Chebyshev nodes in [k_lo,kF-hw]∪[kF+hw,k_hi] + trapezoidal in [kF-hw,kF+hw])
    # to avoid double-counting. The endpoint case kF≈|q-p| (FFLO resonance) requires
    # analytical QP-pole extraction. Both are tracked as future improvements.
    # For now the kquad_kf_features argument is accepted but not applied.
    _ = kquad_kf_features  # reserved for future composite-quadrature implementation

    return geom_chunks, float(weight_total), int(n_quad)


def _phi_from_partner_k(p: float, q: float, k_value: float, routing: str) -> float:
    """Return phi in [0, pi] such that |q +/- p| geometry gives k_value."""
    pf = float(p)
    qf = float(q)
    kf = float(k_value)
    denom = 2.0 * pf * qf
    if denom <= 1.0e-14:
        return float("nan")
    if str(routing).strip().lower() == "sum":
        cos_phi = (kf * kf - pf * pf - qf * qf) / denom
    else:
        cos_phi = (pf * pf + qf * qf - kf * kf) / denom
    return float(np.arccos(np.clip(cos_phi, -1.0, 1.0)))


def _merge_intervals(intervals: list[tuple[float, float]]) -> list[tuple[float, float]]:
    clean = []
    for a, b in intervals:
        af = max(0.0, min(float(a), np.pi))
        bf = max(0.0, min(float(b), np.pi))
        if bf > af + 1.0e-13:
            clean.append((af, bf))
    if not clean:
        return []
    clean.sort()
    merged: list[tuple[float, float]] = [clean[0]]
    for a, b in clean[1:]:
        prev_a, prev_b = merged[-1]
        if a <= prev_b + 1.0e-13:
            merged[-1] = (prev_a, max(prev_b, b))
        else:
            merged.append((a, b))
    return merged


def _add_gauss_legendre_panel(nodes: list[float], weights: list[float], a: float, b: float, n: int) -> None:
    if b <= a + 1.0e-14:
        return
    x, w = np.polynomial.legendre.leggauss(max(2, int(n)))
    mid = 0.5 * (float(a) + float(b))
    half = 0.5 * (float(b) - float(a))
    nodes.extend((mid + half * x).tolist())
    weights.extend((2.0 * half * w).tolist())  # 2 * int_0^pi = int_0^{2pi}


def _add_trapezoid_panel(nodes: list[float], weights: list[float], a: float, b: float, n: int) -> None:
    if b <= a + 1.0e-14:
        return
    nloc = max(3, int(n))
    if nloc % 2 == 0:
        nloc += 1
    x = np.linspace(float(a), float(b), nloc, dtype=float)
    dx = (float(b) - float(a)) / float(nloc - 1)
    w = np.full(nloc, 2.0 * dx, dtype=float)  # 2 * int_0^pi = int_0^{2pi}
    w[0] *= 0.5
    w[-1] *= 0.5
    nodes.extend(x.tolist())
    weights.extend(w.tolist())


def _add_chebyshev_full_panel(nodes: list[float], weights: list[float], n: int) -> None:
    """Gauss-Chebyshev panel over the full [0, pi] range via phi = arccos(u).

    k_-(phi)^2 = p^2 + q^2 - 2 p q cos(phi) has dk/dphi = 0 exactly at the two
    true geometric endpoints phi=0 and phi=pi, giving the integrand (as a
    function of phi) an integrable inverse-sqrt-type endpoint structure there.
    A plain Gauss-Legendre-in-phi panel resolves this only algebraically slowly
    (needs O(100+) nodes to converge at large q where no interior kF feature
    is in kinematic range to otherwise dominate the error); the u=cos(phi)
    substitution turns it into the classical Chebyshev weight 1/sqrt(1-u^2),
    which Gauss-Chebyshev quadrature integrates with the same accuracy using
    far fewer, non-oscillating-with-n nodes (validated directly against a
    resolution sweep of the full pole-aware energy_panels integrand at q=12).
    """
    n = max(2, int(n))
    u_nodes, u_weights = np.polynomial.chebyshev.chebgauss(n)
    phi = np.arccos(np.clip(u_nodes, -1.0, 1.0))
    nodes.extend(phi.tolist())
    weights.extend((2.0 * u_weights).tolist())  # 2 * int_{-1}^{1} = int_0^{2pi}


def build_phipanel_geometry_cache(
    k_axis: np.ndarray,
    p_grid: np.ndarray,
    *,
    q_value: float,
    routing: str,
    n_phi_panel: int,
    phi_panel_chunk_size: int | None = None,
    k_features: list[float] | None = None,
    k_feature_n_local: int = 31,
    k_feature_half_width: float = 0.05,
) -> tuple[list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]], float, int]:
    """Composite phi quadrature with local panels where k_-(phi) crosses kF.

    This is a diagnostic/robustness quadrature for the FFLO resonance.  The
    Chebyshev ``kjac`` rule clusters at angular endpoints but cannot place nodes
    at an interior kF crossing.  Here we work directly in phi:

        int_0^{2pi} dphi F(k(phi)) = 2 int_0^pi dphi F(k(phi)).

    For each p row we split [0, pi] around any requested k-space feature that
    lies in the partner-momentum interval [|p-q|, p+q].  Feature windows are
    integrated with a local trapezoid panel that includes the resonance center;
    the smooth remainder uses Gauss-Legendre panels.
    """
    p_vals = np.asarray(p_grid, dtype=float).reshape(-1)
    qf = abs(float(q_value))
    regular_n = max(2, int(n_phi_panel))
    local_n = max(3, int(k_feature_n_local))
    if local_n % 2 == 0:
        local_n += 1
    hw = max(float(k_feature_half_width), 0.0)
    features = [float(x) for x in (k_features or []) if np.isfinite(float(x))]

    per_p_nodes: list[np.ndarray] = []
    per_p_weights: list[np.ndarray] = []
    max_nodes = 1

    for pf in p_vals.tolist():
        nodes: list[float] = []
        weights: list[float] = []

        if abs(pf) <= 1.0e-14 or qf <= 1.0e-14:
            nodes.append(0.0)
            weights.append(2.0 * np.pi)
        else:
            k_lo = abs(pf - qf)
            k_hi = pf + qf
            intervals: list[tuple[float, float]] = []
            for kf in features:
                # Trigger on a margin equal to the panel's own half-width
                # (or the 2%-span fallback), not on bare membership in
                # [k_lo,k_hi]. A hard `k_lo<=kf<=k_hi` test makes the
                # refinement panel switch on/off as a step function of q (or
                # p) exactly as kf crosses the boundary -- right when the
                # resonance is closest to the edge and a coarse panel would
                # otherwise most need help. Clipping k_a/k_b into [k_lo,k_hi]
                # below then shrinks the panel's width to exactly zero at the
                # margin, so its contribution vanishes continuously instead
                # of the panel disappearing outright at kf=k_lo/k_hi.
                margin = hw if hw > 0.0 else 0.02 * max(k_hi - k_lo, 1.0e-8)
                if not (k_lo - margin <= kf <= k_hi + margin):
                    continue
                k_a = max(k_lo, kf - margin)
                k_b = min(k_hi, kf + margin)
                if k_b <= k_a:
                    continue
                phi_a = _phi_from_partner_k(pf, qf, k_a, routing)
                phi_b = _phi_from_partner_k(pf, qf, k_b, routing)
                if np.isfinite(phi_a) and np.isfinite(phi_b):
                    intervals.append((min(phi_a, phi_b), max(phi_a, phi_b)))

            feature_intervals = _merge_intervals(intervals)
            if not feature_intervals:
                # No k_-(phi) feature is kinematically reachable for this p
                # (the common case at large q, e.g. q=12 with p <= pair_pmax
                # << kF): the only structure left in [0,pi] is the true
                # phi=0/pi endpoint Jacobian singularity (dk/dphi=0 there),
                # which Gauss-Chebyshev resolves far better than a single
                # flat Gauss-Legendre panel of the same order (validated
                # directly against a resolution sweep of the full pole-aware
                # energy_panels integrand at q=12: GL still swings 50%+ at
                # n=128 while Chebyshev is converged by n=64).
                _add_chebyshev_full_panel(nodes, weights, regular_n)
            else:
                cursor = 0.0
                for a, b in feature_intervals:
                    _add_gauss_legendre_panel(nodes, weights, cursor, a, regular_n)
                    _add_trapezoid_panel(nodes, weights, a, b, local_n)
                    cursor = b
                _add_gauss_legendre_panel(nodes, weights, cursor, np.pi, regular_n)

        if not nodes:
            _add_gauss_legendre_panel(nodes, weights, 0.0, np.pi, regular_n)

        n_arr = np.asarray(nodes, dtype=float)
        w_arr = np.asarray(weights, dtype=float)
        per_p_nodes.append(n_arr)
        per_p_weights.append(w_arr)
        max_nodes = max(max_nodes, int(n_arr.size))

    phi_nodes = np.zeros((max_nodes, p_vals.size), dtype=float)
    phi_weights = np.zeros((max_nodes, p_vals.size), dtype=float)
    active = np.zeros((max_nodes, p_vals.size), dtype=bool)
    for ip, (n_arr, w_arr) in enumerate(zip(per_p_nodes, per_p_weights)):
        nn = int(n_arr.size)
        phi_nodes[:nn, ip] = n_arr
        phi_weights[:nn, ip] = w_arr
        active[:nn, ip] = True

    k_nodes = partner_momentum(
        p_vals[None, :],
        float(q_value),
        phi_nodes,
        str(routing),
    )
    ki0, ki1, tk, kin = interp_weights_1d(k_axis, k_nodes)
    kin = np.asarray(kin, dtype=bool) & active
    weight_total = np.sum(phi_weights, axis=0)
    mean_weight_total = float(np.mean(weight_total)) if weight_total.size else float(2.0 * np.pi)

    chunk = max_nodes if phi_panel_chunk_size is None else int(max(1, min(int(phi_panel_chunk_size), max_nodes)))
    geom_chunks: list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]] = []
    for i0 in range(0, max_nodes, chunk):
        i1 = min(i0 + chunk, max_nodes)
        geom_chunks.append((
            ki0[i0:i1],
            ki1[i0:i1],
            tk[i0:i1, :, None],
            kin[i0:i1, :, None],
            phi_weights[i0:i1, :, None],
        ))

    return geom_chunks, mean_weight_total, int(max_nodes)


def precompute_kjac_integrated_slice(
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    a_dn: np.ndarray,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    *,
    q_value: float,
    omega_value: float,
    routing: str,
    n_kquad: int,
    kquad_chunk_size: int | None = None,
    geom_cache: tuple[list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]], float, int] | None = None,
    re_sigma: np.ndarray | None = None,
    im_sigma: np.ndarray | None = None,
    sigma0: float = 0.0,
    mu: float = 0.0,
    eta: float = 1.0e-3,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the transformed-geometry angular integral for one omega slice."""
    n_p = p_grid.size
    n_eps = eps_grid.size

    if geom_cache is None:
        geom_chunks, weight_total, _ = build_kjac_geometry_cache(
            k_axis,
            p_grid,
            q_value=float(q_value),
            routing=str(routing),
            n_kquad=int(n_kquad),
            kquad_chunk_size=kquad_chunk_size,
        )
    else:
        geom_chunks, weight_total, _ = geom_cache

    wq = float(omega_value) - eps_grid
    accum_int = np.zeros((n_p, n_eps), dtype=float)
    accum_support = np.zeros((n_p, n_eps), dtype=float)

    for ki0, ki1, tk3, kin3, quad_w in geom_chunks:
        if re_sigma is None or im_sigma is None:
            interp, support = eval_translated_a_rows(
                k_axis,
                w_axis,
                a_dn,
                ki0,
                ki1,
                tk3[:, :, 0],
                kin3[:, :, 0],
                wq,
            )
        else:
            interp, support = rebuild_translated_a_rows(
                k_axis,
                w_axis,
                re_sigma,
                im_sigma,
                ki0,
                ki1,
                tk3[:, :, 0],
                kin3[:, :, 0],
                wq,
                mu=float(mu),
                sigma0=float(sigma0),
                eta=float(eta),
            )
        interp = np.where(support, interp, 0.0)

        accum_int += np.sum(quad_w * interp, axis=0)
        accum_support += np.sum(quad_w * support, axis=0)

    return accum_int, accum_support / max(float(weight_total), 1.0e-14)


def precompute_phi_integrated_slice(
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    a_dn: np.ndarray,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    phi_grid: np.ndarray,
    *,
    q_value: float,
    omega_value: float,
    routing: str,
    phi_chunk_size: int | None = None,
    geom_cache: tuple[list[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]], float, int] | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the phi-integrated translated A_down slice for one omega.

    Shapes:
    - out_int: (n_p, n_eps), integral over phi of translated A_down
    - out_support_frac: (n_p, n_eps), fraction of phi nodes inside cube support
    """
    n_p = p_grid.size
    n_eps = eps_grid.size

    if geom_cache is None:
        geom_chunks, dphi, n_phi = build_phi_geometry_cache(
            k_axis,
            p_grid,
            phi_grid,
            q_value=float(q_value),
            routing=str(routing),
            phi_chunk_size=phi_chunk_size,
        )
    else:
        geom_chunks, dphi, n_phi = geom_cache

    wq = float(omega_value) - eps_grid
    accum_int = np.zeros((n_p, n_eps), dtype=float)
    accum_support = np.zeros((n_p, n_eps), dtype=float)

    for ki0, ki1, tk3, kin3 in geom_chunks:
        interp, support = eval_translated_a_rows(
            k_axis,
            w_axis,
            a_dn,
            ki0,
            ki1,
            tk3[:, :, 0],
            kin3[:, :, 0],
            wq,
        )
        interp = np.where(support, interp, 0.0)

        accum_int += dphi * np.sum(interp, axis=0)
        accum_support += np.sum(support, axis=0)

    return accum_int, accum_support / float(n_phi)


def precompute_phi_integrated_table(
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    a_dn: np.ndarray,
    p_grid: np.ndarray,
    omega_grid: np.ndarray,
    eps_grid: np.ndarray,
    phi_grid: np.ndarray,
    *,
    q_value: float,
    routing: str,
    phi_chunk_size: int | None = None,
    progress: bool = True,
) -> tuple[np.ndarray, np.ndarray]:
    """Return (phi-integral table, support-fraction table).

    Shapes:
    - out_int: (n_omega, n_p, n_eps), integral over phi of translated A_down
    - out_support_frac: same shape, fraction of phi nodes inside cube support
    """
    n_omega = omega_grid.size
    n_p = p_grid.size
    n_eps = eps_grid.size
    geom_cache = build_phi_geometry_cache(
        k_axis,
        p_grid,
        phi_grid,
        q_value=float(q_value),
        routing=str(routing),
        phi_chunk_size=phi_chunk_size,
    )

    out_int = np.zeros((n_omega, n_p, n_eps), dtype=float)
    out_support_frac = np.zeros((n_omega, n_p, n_eps), dtype=float)

    for io, om in enumerate(omega_grid):
        accum_int, accum_support_frac = precompute_phi_integrated_slice(
            k_axis,
            w_axis,
            a_dn,
            p_grid,
            eps_grid,
            phi_grid,
            q_value=float(q_value),
            omega_value=float(om),
            routing=str(routing),
            phi_chunk_size=phi_chunk_size,
            geom_cache=geom_cache,
        )
        out_int[io] = accum_int
        out_support_frac[io] = accum_support_frac

        if progress and ((io + 1) % max(1, n_omega // 10) == 0 or (io + 1) == n_omega):
            print(f"[info] omega slice {io + 1}/{n_omega} done (omega={om:+.3f})")

    return out_int, out_support_frac






