# =====================================================================
# SLIM copy of true_akw_pipeline/analytic_qp_bubble.py
#
# 0 top-level symbols (0 lines, 0% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   _build_a_inc_interpolator, build_row_local_cube_interpolator, coherent_impi, coherent_impi_kjac, coherent_impi_phipanel, cross_impi_term
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
# =====================================================================
r"""Analytic-QP coherent pair bubble (route 2).

ImPi_coh(q,omega) = - \int d^2k/(2pi)^2  Z1 Z2 [1 - f(E1) - f(E2)]
                       * (1/pi) (G1+G2) / ((omega - E1 - E2)^2 + (G1+G2)^2)

legs: (k, up) and (q-k, down); E1=E_up(|k|), E2=E_dn(|q-k|), f=theta(-E) at T=0.
The QP fields E,Z,Gamma are the SMOOTH Dyson ones (qp_dyson_extract) -> the
k-integral is smooth in q and P (no razor on a grid), and carries the -1/8
vacuum tail to all omega by construction (no UV grid-starvation, no taper).
"""
from __future__ import annotations
import numpy as np
from scipy.integrate import quad

try:
    from fflo.adn_phi import build_kjac_geometry_cache, build_phipanel_geometry_cache
except Exception:  # pragma: no cover - keeps the standalone script importable
    build_kjac_geometry_cache = None
    build_phipanel_geometry_cache = None


def _interp(kq, k, v):
    return np.interp(np.clip(kq, k[0], k[-1]), k, v)


def _feature_grid(kmax, nk, features, half=0.25, n_local=240):
    """Uniform base grid plus dense clusters around each Fermi shell (where the
    integrand is sharply peaked at small q -> the Cooper threshold)."""
    g = [np.linspace(0.0, kmax, nk)]
    for kf in features:
        if 0.0 < kf < kmax:
            g.append(np.linspace(max(0.0, kf - half), min(kmax, kf + half), n_local))
    return np.unique(np.concatenate(g))


def coherent_impi(
    q, omega_grid,
    k_up, E_up, Z_up, G_up,
    k_dn, E_dn, Z_dn, G_dn,
    *, nk=600, nphi=192, kmax=None, gamma_floor=1.0e-3, kf_features=None,
):
    k_up = np.asarray(k_up, float); k_dn = np.asarray(k_dn, float)
    if kmax is None:
        kmax = float(min(k_up[-1], k_dn[-1]))
    if kf_features:
        kk = _feature_grid(kmax, nk, kf_features)
    else:
        kk = np.linspace(0.0, kmax, nk)
    phi = np.linspace(0.0, np.pi, nphi)          # symmetric -> factor 2
    K, PH = np.meshgrid(kk, phi, indexing="ij")
    k2 = np.sqrt(np.maximum(K * K + q * q - 2.0 * K * q * np.cos(PH), 0.0))  # |q-k|
    E1 = _interp(K, k_up, E_up); E2 = _interp(k2, k_dn, E_dn)
    Z1 = _interp(K, k_up, Z_up); Z2 = _interp(k2, k_dn, Z_dn)
    G1 = np.maximum(_interp(K, k_up, G_up), gamma_floor)
    # slight asymmetry on G2 avoids exact pole degeneracy in the residue formula
    G2 = np.maximum(_interp(k2, k_dn, G_dn), gamma_floor) * (1.0 + 1.0e-6)
    meas = (K * Z1 * Z2) / ((2.0 * np.pi) ** 2) * 2.0   # geometry x Z (k dk dphi, phi x2)
    # EXACT Pauli window: ImPi = -int d2k Z1 Z2 * int_0^omega L1(eps)L2(omega-eps) deps.
    # The eps-window [0,omega] is the T=0 Fermi factor [1-f(eps)-f(omega-eps)] -> the
    # integral VANISHES at omega=0 (zero-width window) so ImPi(q,0)=0 exactly (Pauli),
    # and -> the full Lorentzian convolution (-1/8 tail) as the window grows.
    # int_0^w L1 L2 deps = (G1 G2 / pi^2) * Re sum_k r_k [log(w - z_k) - log(-z_k)],
    # poles z = E1 +- i G1 (up razor in eps) and (w-E2) +- i G2 (down razor in eps).
    a = E1                       # up-leg razor center in eps (omega-independent)
    z1 = a + 1j * G1; z2 = a - 1j * G1
    out = np.empty(np.asarray(omega_grid).size, float)
    for i, w in enumerate(np.asarray(omega_grid, float)):
        b = w - E2               # down-leg razor center in eps
        z3 = b + 1j * G2; z4 = b - 1j * G2
        r1 = 1.0 / ((z1 - z2) * (z1 - z3) * (z1 - z4))
        r2 = 1.0 / ((z2 - z1) * (z2 - z3) * (z2 - z4))
        r3 = 1.0 / ((z3 - z1) * (z3 - z2) * (z3 - z4))
        r4 = 1.0 / ((z4 - z1) * (z4 - z2) * (z4 - z3))
        J = np.real(r1 * (np.log(w - z1) - np.log(-z1))
                    + r2 * (np.log(w - z2) - np.log(-z2))
                    + r3 * (np.log(w - z3) - np.log(-z3))
                    + r4 * (np.log(w - z4) - np.log(-z4)))
        fac = G1 * G2 * J / np.pi          # = int_0^w L1 L2 deps
        out[i] = -np.trapezoid(np.trapezoid(meas * fac, phi, axis=1), kk)
    return out


def _equal_lorentzian_bubble_factor(w, center, gamma):
    """Return ``pi * int_0^w L(eps; center, gamma)^2 d eps``.

    This is the exact coincident-pole limit needed by the pair-bubble
    accumulator.  Keeping the bubble's leading ``pi`` here is important: the
    surrounding residue expression computes ``G1*G2*J/pi``, which is
    ``pi * int L1*L2``, not the bare product integral.
    """
    gamma = float(gamma)
    if not np.isfinite(gamma) or gamma <= 0.0:
        raise ValueError(f"Need a positive finite Lorentzian width, got {gamma!r}")

    def primitive(u):
        return 0.5 / np.pi * (
            u / (u * u + gamma * gamma)
            + np.arctan(u / gamma) / gamma
        )

    return float(primitive(float(w) - float(center)) - primitive(-float(center)))


def _stable_lorentzian_product_window_factor(w, e1, g1, e2, g2):
    """Stable ``pi * integral_0^w L1(eps)L2(w-eps) d eps``.

    The residue formula loses precision when its poles nearly coincide.  Map
    the narrower Lorentzian to ``t=atan((x-E)/Gamma)`` instead; its Jacobian
    cancels exactly and leaves a smooth integral of the broader Lorentzian.
    """
    w = float(w); e1 = float(e1); e2 = float(e2)
    g1 = float(g1); g2 = float(g2)
    if w == 0.0:
        return 0.0
    if not all(np.isfinite(v) for v in (w, e1, g1, e2, g2)) or min(g1, g2) <= 0.0:
        return float("nan")

    if g1 <= g2:
        t0 = np.arctan((0.0 - e1) / g1)
        t1 = np.arctan((w - e1) / g1)
        t_peak = np.arctan((w - e2 - e1) / g1)
        def other(t):
            eps = e1 + g1 * np.tan(t)
            return (g2 / np.pi) / ((w - eps - e2) ** 2 + g2 * g2)
    else:
        # y=w-eps turns the second leg into the same oriented [0,w] integral.
        t0 = np.arctan((0.0 - e2) / g2)
        t1 = np.arctan((w - e2) / g2)
        t_peak = np.arctan((w - e1 - e2) / g2)
        def other(t):
            y = e2 + g2 * np.tan(t)
            return (g1 / np.pi) / ((w - y - e1) ** 2 + g1 * g1)

    points = [float(t_peak)] if min(t0, t1) < t_peak < max(t0, t1) else None
    value, _ = quad(
        lambda t: float(other(t)),
        float(t0),
        float(t1),
        points=points,
        epsabs=1.0e-11,
        epsrel=1.0e-10,
        limit=100,
    )
    return float(value)


def _coherent_impi_from_geometry(
    omega_grid,
    kk,
    E1_k,
    Z1_k,
    G1_k,
    k_dn,
    E_dn,
    Z_dn,
    G_dn,
    geom_chunks,
    *,
    gamma_floor=1.0e-3,
):
    """Shared coherent-QP accumulator for precomputed angular geometry."""
    out = np.zeros(np.asarray(omega_grid).size, float)
    pref_k = kk[None, :] * Z1_k[None, :] / ((2.0 * np.pi) ** 2)
    E1 = E1_k[None, :]
    G1 = G1_k[None, :]
    a = E1
    z1 = a + 1j * G1
    z2 = a - 1j * G1

    for ki0, ki1, tk3, kin3, quad_w in geom_chunks:
        tk = tk3[:, :, 0]
        kin = kin3[:, :, 0]
        angle_w = np.where(kin, quad_w[:, :, 0], 0.0)
        E2 = (1.0 - tk) * E_dn[ki0] + tk * E_dn[ki1]
        Z2 = (1.0 - tk) * Z_dn[ki0] + tk * Z_dn[ki1]
        G2 = np.maximum((1.0 - tk) * G_dn[ki0] + tk * G_dn[ki1], gamma_floor) * (1.0 + 1.0e-6)
        meas = pref_k * Z2 * angle_w

        for i, w in enumerate(np.asarray(omega_grid, float)):
            b = w - E2
            z3 = b + 1j * G2
            z4 = b - 1j * G2
            r1 = 1.0 / ((z1 - z2) * (z1 - z3) * (z1 - z4))
            r2 = 1.0 / ((z2 - z1) * (z2 - z3) * (z2 - z4))
            r3 = 1.0 / ((z3 - z1) * (z3 - z2) * (z3 - z4))
            r4 = 1.0 / ((z4 - z1) * (z4 - z2) * (z4 - z3))
            J = np.real(r1 * (np.log(w - z1) - np.log(-z1))
                        + r2 * (np.log(w - z2) - np.log(-z2))
                        + r3 * (np.log(w - z3) - np.log(-z3))
                        + r4 * (np.log(w - z4) - np.log(-z4)))
            fac = G1 * G2 * J / np.pi
            # The 1+1e-6 width split above makes the residue formula stable in
            # ordinary near-degenerate cells.  Only use the exact coincident
            # limit when two poles are indistinguishable at floating-point
            # precision.  A broad 0.1*Gamma trigger used here previously
            # replaced many well-conditioned cells by a uniform 400-point
            # epsilon integral.  That integral missed narrow Lorentzians and
            # was smaller by an additional factor pi.
            G1b = np.broadcast_to(G1, fac.shape)
            gap = np.minimum(np.abs(z1 - z3), np.abs(z1 - z4))
            pole_scale = np.maximum.reduce(
                (
                    np.ones_like(gap),
                    np.abs(np.broadcast_to(z1, gap.shape)),
                    np.abs(z3),
                    np.abs(z4),
                )
            )
            degen = gap <= 64.0 * np.finfo(float).eps * pole_scale
            if np.any(degen):
                E1b = np.broadcast_to(E1, fac.shape)
                idx = np.nonzero(degen)
                for ii, jj in zip(*idx):
                    center = 0.5 * (
                        float(E1b[ii, jj]) + float(w - E2[ii, jj])
                    )
                    gamma = 0.5 * (float(G1b[ii, jj]) + float(G2[ii, jj]))
                    fac[ii, jj] = _equal_lorentzian_bubble_factor(
                        w, center, gamma
                    )
            # Near-coincident poles can still make the residue expression
            # non-finite before the strict coincident-pole test fires.  Use a
            # stable transformed quadrature only for those exceptional cells.
            bad = ~np.isfinite(fac)
            if np.any(bad):
                E1b = np.broadcast_to(E1, fac.shape)
                G1b = np.broadcast_to(G1, fac.shape)
                for ii, jj in zip(*np.nonzero(bad)):
                    fac[ii, jj] = _stable_lorentzian_product_window_factor(
                        w,
                        E1b[ii, jj],
                        G1b[ii, jj],
                        E2[ii, jj],
                        G2[ii, jj],
                    )
            out[i] += -np.trapezoid(np.sum(meas * fac, axis=0), kk)

    return out


def coherent_impi_kjac(
    q, omega_grid,
    k_up, E_up, Z_up, G_up,
    k_dn, E_dn, Z_dn, G_dn,
    *,
    nk=600, n_kquad=160, kquad_chunk_size=16,
    kmax=None, gamma_floor=1.0e-3, kf_features=None,
):
    """Coherent QP bubble with analytic angular measure.

    Uses u=cos(phi):

        int_0^{2pi} dphi F(|q-k|)
        = 2 int_{-1}^{1} du F(sqrt(k^2+q^2-2kq u)) / sqrt(1-u^2).

    The epsilon integral is still the same closed-form Lorentzian convolution as
    ``coherent_impi``; this only removes the uniform phi trapezoid.
    """
    if build_kjac_geometry_cache is None:
        raise RuntimeError("build_kjac_geometry_cache is unavailable")

    k_up = np.asarray(k_up, float); k_dn = np.asarray(k_dn, float)
    if kmax is None:
        kmax = float(min(k_up[-1], k_dn[-1]))
    if kf_features:
        kk = _feature_grid(kmax, nk, kf_features)
    else:
        kk = np.linspace(0.0, kmax, nk)

    E1_k = _interp(kk, k_up, E_up)
    Z1_k = _interp(kk, k_up, Z_up)
    G1_k = np.maximum(_interp(kk, k_up, G_up), gamma_floor)

    geom_chunks, _, _ = build_kjac_geometry_cache(
        k_dn,
        kk,
        q_value=float(q),
        routing="difference",
        n_kquad=int(n_kquad),
        kquad_chunk_size=int(kquad_chunk_size),
        kquad_kf_features=[float(x) for x in (kf_features or [])],
    )
    return _coherent_impi_from_geometry(
        np.asarray(omega_grid, float),
        kk,
        E1_k,
        Z1_k,
        G1_k,
        k_dn,
        E_dn,
        Z_dn,
        G_dn,
        geom_chunks,
        gamma_floor=gamma_floor,
    )


def _build_a_inc_interpolator(k_cube, w_cube, A_cube, k_qp, E_qp, Z_qp, G_qp,
                              gamma_floor=1e-3, n_eps_uni=512):
    """Return a RegularGridInterpolator for A_inc(k, eps) = A_full - A_QP_Lorentz.

    A_inc is smooth (razor removed) so linear interpolation on a uniform eps grid
    is accurate.  Evaluates to 0 outside (k, eps) support.
    """
    from scipy.interpolate import RegularGridInterpolator
    k_cube = np.asarray(k_cube, float)
    w_cube = np.asarray(w_cube, float)
    A_cube = np.asarray(A_cube, float)
    k_qp   = np.asarray(k_qp,   float)
    E_qp   = np.asarray(E_qp,   float)
    Z_qp   = np.asarray(Z_qp,   float)
    G_qp   = np.asarray(G_qp,   float)

    eps_lo = w_cube.min(); eps_hi = w_cube.max()
    eps_uni = np.linspace(eps_lo, eps_hi, n_eps_uni)

    A_inc = np.zeros((len(k_cube), n_eps_uni))
    for i, kval in enumerate(k_cube):
        row_w = w_cube[i] if w_cube.ndim == 2 else w_cube
        A_full_i = np.interp(eps_uni, row_w, A_cube[i], left=0.0, right=0.0)
        E_k = float(np.interp(kval, k_qp, E_qp))
        Z_k = float(np.interp(kval, k_qp, Z_qp))
        G_k = max(float(np.interp(kval, k_qp, G_qp)), gamma_floor)
        A_inc[i] = A_full_i - Z_k / np.pi * G_k / ((eps_uni - E_k) ** 2 + G_k ** 2)

    return RegularGridInterpolator(
        (k_cube, eps_uni), A_inc, method="linear", bounds_error=False, fill_value=0.0,
    )


class _RowLocalCubeInterpolator:
    """Bilinear interpolation on a cube with a separate omega axis per k row.

    The legacy mixed-term path first projected every row onto 512 points over
    the complete [-240, 240] support.  That is nearly unit spacing and erases
    the low-energy structure of ``A_inc``.  This interpolator keeps every
    native row axis and only interpolates the two rows bracketing each query.
    """

    def __init__(self, k_cube, w_cube, values):
        self.k = np.asarray(k_cube, float)
        self.w = np.asarray(w_cube, float)
        self.values = np.asarray(values, float)
        if self.k.ndim != 1 or self.k.size < 2:
            raise ValueError("Need at least two k rows for row-local interpolation")
        if self.values.shape[0] != self.k.size:
            raise ValueError("Cube values and k axis disagree")
        if self.w.ndim == 1 and self.values.shape[1] != self.w.size:
            raise ValueError("Cube values and omega axis disagree")
        if self.w.ndim == 2 and self.w.shape != self.values.shape:
            raise ValueError("Row-local omega axes and cube values disagree")

    def _row(self, i):
        return self.w if self.w.ndim == 1 else self.w[i]

    def _eval_rows(self, indices, eps):
        out = np.empty(eps.size, float)
        for idx in np.unique(indices):
            mask = indices == idx
            out[mask] = np.interp(
                eps[mask], self._row(int(idx)), self.values[int(idx)],
                left=0.0, right=0.0,
            )
        return out

    def __call__(self, points):
        pts = np.asarray(points, float)
        shape = pts.shape[:-1]
        flat = pts.reshape(-1, 2)
        kval = flat[:, 0]
        eps = flat[:, 1]
        out = np.zeros(kval.size, float)
        inside = (kval >= self.k[0]) & (kval <= self.k[-1]) & np.isfinite(eps)
        if not np.any(inside):
            return out.reshape(shape)
        kv = kval[inside]
        ev = eps[inside]
        i1 = np.searchsorted(self.k, kv, side="right")
        i1 = np.clip(i1, 1, self.k.size - 1)
        i0 = i1 - 1
        denom = self.k[i1] - self.k[i0]
        t = np.divide(kv - self.k[i0], denom, out=np.zeros_like(kv), where=denom != 0.0)
        v0 = self._eval_rows(i0, ev)
        v1 = self._eval_rows(i1, ev)
        out[inside] = (1.0 - t) * v0 + t * v1
        return out.reshape(shape)


def build_row_local_cube_interpolator(k_cube, w_cube, values):
    """Return a native-axis interpolator for a precomputed residual cube."""
    return _RowLocalCubeInterpolator(k_cube, w_cube, values)


def cross_impi_term(
    q, omega_grid,
    k_qp, E_qp, Z_qp, G_qp,
    inc_interp,
    *, dn_qp_leg=False, nk=64, nphi=32, kmax=None, gamma_floor=1e-3,
    kf_features=None, n_eps_lor=0,
):
    """One cross term of the pair bubble: QP-leg × A_inc-leg.

    Two cases controlled by dn_qp_leg:

    dn_qp_leg=False — cross1: QP is the UP spin (appears as A_up(k, ε+ω)).
        The Lorentzian in ε is centred at E_u(k) − ω.
        window = [arctan((ω−E)/Γ) + arctan(E/Γ)] / π   (fraction of L in [−ω, 0])
        A_inc_dn evaluated at ε = E_u(k) − ω.

    dn_qp_leg=True  — cross2: QP is the DOWN spin (appears as A_dn(q−k, ε)).
        The Lorentzian in ε is centred at E_d(k_d).
        window = [arctan((ω+E)/Γ) + arctan(−E/Γ)] / π  (same physics, shifted sign)
        A_inc_up evaluated at ε+ω = E_d(k_d) + ω.

    Integration variable is always the QP-leg momentum k.
    Sign convention: returns a negative quantity for ω > 0 (ImPi < 0),
    matching coherent_impi.
    """
    omega_grid = np.asarray(omega_grid, float)
    k_qp = np.asarray(k_qp, float)
    if kmax is None:
        kmax = float(k_qp[-1])

    kk = _feature_grid(kmax, nk, kf_features) if kf_features else np.linspace(0.0, kmax, nk)
    phi = np.linspace(0.0, np.pi, nphi)

    K, PH = np.meshgrid(kk, phi, indexing="ij")          # (nk, nphi)
    k_other = np.sqrt(np.maximum(K**2 + q**2 - 2*K*q*np.cos(PH), 0.0))  # |q-k|

    E1 = _interp(kk, k_qp, E_qp)                         # (nk,)
    Z1 = _interp(kk, k_qp, Z_qp)
    G1 = np.maximum(_interp(kk, k_qp, G_qp), gamma_floor)

    n_eps_lor = int(n_eps_lor)
    if n_eps_lor < 0:
        raise ValueError("n_eps_lor must be non-negative")
    if n_eps_lor:
        gl_x, gl_w = np.polynomial.legendre.leggauss(n_eps_lor)

    result = np.zeros(omega_grid.size, float)
    for i, w in enumerate(omega_grid):
        if not dn_qp_leg:
            # cross1: QP_up in ε+ω; A_inc_dn in ε evaluated at E_u − ω
            window   = (np.arctan((w - E1) / G1) + np.arctan(E1 / G1)) / np.pi
            eps_pole = E1 - w
        else:
            # cross2: QP_dn in ε; A_inc_up in ε+ω evaluated at E_d + ω
            window   = (np.arctan((w + E1) / G1) + np.arctan(-E1 / G1)) / np.pi
            eps_pole = E1 + w

        if not n_eps_lor:
            pts = np.column_stack([k_other.ravel(), np.repeat(eps_pole, nphi)])
            A_inc_vals = inc_interp(pts).reshape(len(kk), len(phi))
            spectral_integral = Z1[:, None] * window[:, None] * A_inc_vals
        else:
            # Exact narrow-peak quadrature. For a normalized Lorentzian,
            # t=atan((eps-center)/Gamma) gives L(eps) d eps = dt/pi.
            # Gauss-Legendre in t therefore resolves arbitrarily small Gamma
            # without putting a razor on the original epsilon grid.
            if not dn_qp_leg:
                center = E1 - w
                t_lo = np.arctan((-w - center) / G1)
                t_hi = np.arctan((0.0 - center) / G1)
                eval_shift = 0.0
            else:
                center = E1
                t_lo = np.arctan((-w - center) / G1)
                t_hi = np.arctan((0.0 - center) / G1)
                eval_shift = w

            t_mid = 0.5 * (t_hi + t_lo)
            t_half = 0.5 * (t_hi - t_lo)
            spectral_integral = np.zeros((len(kk), len(phi)), float)
            for xj, wj in zip(gl_x, gl_w):
                tj = t_mid + t_half * xj
                eps_j = center + G1 * np.tan(tj) + eval_shift
                pts = np.column_stack([k_other.ravel(), np.repeat(eps_j, nphi)])
                vals = inc_interp(pts).reshape(len(kk), len(phi))
                spectral_integral += (
                    Z1[:, None] * (t_half * wj / np.pi)[:, None] * vals
                )

        meas = K / (2.0 * np.pi) ** 2 * 2.0
        result[i] = -np.trapezoid(
            np.trapezoid(meas * spectral_integral, phi, axis=1), kk
        )
    return result


def coherent_impi_phipanel(
    q, omega_grid,
    k_up, E_up, Z_up, G_up,
    k_dn, E_dn, Z_dn, G_dn,
    *,
    nk=600, n_phi_panel=24, phi_panel_chunk_size=8,
    phi_feature_half_width=0.08, phi_feature_n_local=81,
    kmax=None, gamma_floor=1.0e-3, kf_features=None,
):
    """Coherent QP bubble with feature-aware analytic angular geometry.

    This keeps the same closed-form epsilon/Lorentzian convolution used by
    ``coherent_impi`` but replaces the uniform phi trapezoid by the panel
    geometry used elsewhere in the pair code.  The panel boundaries are found
    analytically from ``|q-k| = kF`` so the FFLO endpoint/crossing feature is
    sampled directly instead of hoping a uniform phi node lands on it.
    """
    if build_phipanel_geometry_cache is None:
        raise RuntimeError("build_phipanel_geometry_cache is unavailable")

    k_up = np.asarray(k_up, float); k_dn = np.asarray(k_dn, float)
    if kmax is None:
        kmax = float(min(k_up[-1], k_dn[-1]))
    if kf_features:
        kk = _feature_grid(kmax, nk, kf_features)
    else:
        kk = np.linspace(0.0, kmax, nk)

    E1_k = _interp(kk, k_up, E_up)
    Z1_k = _interp(kk, k_up, Z_up)
    G1_k = np.maximum(_interp(kk, k_up, G_up), gamma_floor)

    geom_chunks, _, _ = build_phipanel_geometry_cache(
        k_dn,
        kk,
        q_value=float(q),
        routing="difference",
        n_phi_panel=int(n_phi_panel),
        phi_panel_chunk_size=int(phi_panel_chunk_size),
        k_features=[float(x) for x in (kf_features or [])],
        k_feature_n_local=int(phi_feature_n_local),
        k_feature_half_width=float(phi_feature_half_width),
    )

    return _coherent_impi_from_geometry(
        np.asarray(omega_grid, float),
        kk,
        E1_k,
        Z1_k,
        G1_k,
        k_dn,
        E_dn,
        Z_dn,
        G_dn,
        geom_chunks,
        gamma_floor=gamma_floor,
    )
