# =====================================================================
# SLIM copy of diagnostics/compare_sigma_from_pair_motors.py
#
# 6 top-level symbols (268 lines, 70% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   build_clean_smooth_pair
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   trap_weights
#   load_pinned_pair
#   load_cube
#   run_task
#   parse_ks
#   main
# =====================================================================
#!/usr/bin/env python3
"""Compare one-shot ImSigma generated by two dense-Q pair reconstructions.

Diagnostic only.  The two pair tables are pinned independently at
(Q_FFLO, Omega=0), then convolved with the same stored internal fermion cube
using pair-native (Q, theta, Omega) variables.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
PIPELINE = ROOT / "X_FFLO_FULLGRID_PROD"
if str(PIPELINE) not in sys.path:
    sys.path.insert(0, str(PIPELINE))

from fflo.sigma_engine import (
    _im_sigma_row_pair_native,
    _internal_a_eval,
    _pn_qp_tables,
)
from fflo.kramers_kronig import (
    g0_constant_from_cutoff,
    kk_re_pv_linear,
    vacuum_pi_from_cutoff,
)


DEFAULT_PAIR_ROOT = (
    ROOT
    / "diagnostics/subtract_product_benchmark_p065/results"
    / "pair_strategy_production"
)
DEFAULT_CLEAN_IMPI = (
    ROOT
    / "diagnostics/subtract_product_benchmark_p065/results"
    / "pair_strategy_production_inputs/impi_subtract_product.npz"
)
DEFAULT_SEED_ROOT = ROOT / "X_FFLO_v2/seeds/P0p65"
DEFAULT_OUT = (
    ROOT
    / "X_FFLO_FULLGRID_PROD/diagnostics"
    / "sigma_from_pair_motors_p065"
)






def build_clean_smooth_pair(
    path: Path,
    qff: float,
    eta: float,
    *,
    sign_guard: bool = True,
    subcritical_delta: float = 0.0,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float, np.ndarray, np.ndarray]:
    with np.load(path) as data:
        q = np.asarray(data["q"], dtype=float)
        omega = np.asarray(data["omega"], dtype=float)
        im_pi = np.asarray(data["ImPi"], dtype=float)
        eps0 = float(data["eps0"])
        mu_up = float(data["mu_up"])
        mu_dn = float(data["mu_dn"])
        cutoff = float(data["p_int_max"])
    re_pi = np.empty_like(im_pi)
    for iq, q_value in enumerate(q):
        vacuum = vacuum_pi_from_cutoff(
            omega,
            q=float(q_value),
            eps0=eps0,
            mu_up=mu_up,
            mu_dn=mu_dn,
            eta_gamma=float(eta),
            cutoff=cutoff,
        )
        residual = im_pi[iq] - np.imag(vacuum)
        re_pi[iq] = kk_re_pv_linear(omega, residual) + np.real(vacuum)
    g0 = g0_constant_from_cutoff(cutoff, eps0)
    inv = float(g0) - (re_pi + 1j * im_pi)
    # Retain the same causal sign guard used by the pair-table builder.
    sign = np.sign(omega)[None, :]
    if bool(sign_guard):
        wrong = np.where(sign != 0.0, np.imag(inv) * sign < 0.0, np.imag(inv) != 0.0)
        inv = np.real(inv) + 1j * np.where(wrong, 0.0, np.imag(inv))
    iqff = int(np.argmin(np.abs(q - float(qff))))
    iw0 = int(np.argmin(np.abs(omega)))
    shift = float(np.real(inv[iqff, iw0])) + float(subcritical_delta)
    inv = (np.real(inv) - shift) + 1j * np.imag(inv)
    gamma = np.zeros(inv.shape, dtype=complex)
    np.divide(1.0, inv, out=gamma, where=np.abs(inv) > 1.0e-14)
    a_pair = -np.imag(gamma) / np.pi
    return q, omega, a_pair, shift, re_pi, im_pi










