# =====================================================================
# SLIM copy of true_akw_pipeline/decompose_akw_qp_inc.py
#
# 9 top-level symbols (298 lines, 50% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   extract_dyson_qp_from_cube
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   _load_convention
#   _load_cube
#   _row_integral
#   _copy_npz_payload
#   _write_component_cube
#   _plot_diagnostics
#   decompose_one
#   parse_args
#   main
# =====================================================================
#!/usr/bin/env python3
"""Split A(k,omega) cubes into coherent QP and incoherent residual parts.

This is intentionally a conservative diagnostic/building-block script.  By
default it does not clip the residual:

    A_inc = A_full - A_qp

so that A_qp + A_inc reconstructs the original convention-normalized spectral
cube exactly up to roundoff.  Later stages can decide how to regularize small
negative residuals, but the first invariant we want is algebraic closure.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fflo.kramers_kronig import normalize_spectral_weight  # noqa: E402
from fflo.impi_table import (  # noqa: E402
    build_qp_lorentzian_cube,
    extract_lorentzian_qp_from_cube,
)






def _row_axis(w_axis: np.ndarray, ik: int) -> np.ndarray:
    w = np.asarray(w_axis, dtype=float)
    return np.asarray(w[ik] if w.ndim == 2 else w, dtype=float)




def _scalar_from_source(source: np.lib.npyio.NpzFile, keys: tuple[str, ...], default: float = np.nan) -> float:
    for key in keys:
        if key not in source.files:
            continue
        val = np.asarray(source[key]).reshape(-1)
        if val.size:
            try:
                return float(val[0])
            except Exception:
                return float(default)
    return float(default)


def _mu_for_label(source: np.lib.npyio.NpzFile, label: str) -> float:
    low = label.lower()
    if "down" in low or "dn" in low:
        return _scalar_from_source(source, ("mu_dn", "mu_down"))
    return _scalar_from_source(source, ("mu_up",))


def _interp_zero(x0: float, y0: float, x1: float, y1: float) -> float:
    den = float(y1) - float(y0)
    if abs(den) < 1.0e-30:
        return 0.5 * (float(x0) + float(x1))
    t = -float(y0) / den
    return float(x0) + float(np.clip(t, 0.0, 1.0)) * (float(x1) - float(x0))


def _lorentzian_row(w: np.ndarray, center: float, gamma: float, weight: float) -> np.ndarray:
    gamma = max(float(gamma), 1.0e-10)
    weight = max(float(weight), 0.0)
    with np.errstate(over="ignore", invalid="ignore", divide="ignore"):
        out = (weight / np.pi) * gamma / ((np.asarray(w, dtype=float) - float(center)) ** 2 + gamma**2)
    return np.nan_to_num(out, nan=0.0, posinf=0.0, neginf=0.0)


def _dyson_candidates(
    wi: np.ndarray,
    ai: np.ndarray,
    rei: np.ndarray,
    imi: np.ndarray,
    *,
    xi: float,
    sigma0: float,
    eta: float,
    z_min: float,
    z_max: float,
    max_gamma: float,
    min_peak: float,
) -> list[dict[str, float]]:
    finite = np.isfinite(wi) & np.isfinite(ai) & np.isfinite(rei) & np.isfinite(imi)
    if np.count_nonzero(finite) < 5:
        return []
    wv = np.asarray(wi[finite], dtype=float)
    av = np.asarray(ai[finite], dtype=float)
    rev = np.asarray(rei[finite], dtype=float)
    imv = np.asarray(imi[finite], dtype=float)
    order = np.argsort(wv)
    wv = wv[order]
    av = av[order]
    rev = rev[order]
    imv = imv[order]
    keep = np.concatenate(([True], np.diff(wv) > 1.0e-12))
    wv = wv[keep]
    av = av[keep]
    rev = rev[keep]
    imv = imv[keep]
    if wv.size < 5:
        return []

    residual = wv - float(xi) - (rev - float(sigma0))
    finite_res = np.isfinite(residual)
    if np.count_nonzero(finite_res) < 5:
        return []

    with np.errstate(invalid="ignore", divide="ignore"):
        dre = np.gradient(rev, wv, edge_order=2)

    brackets: list[int] = []
    for i in range(wv.size - 1):
        f0 = residual[i]
        f1 = residual[i + 1]
        if not (np.isfinite(f0) and np.isfinite(f1)):
            continue
        if f0 == 0.0 or f0 * f1 <= 0.0:
            brackets.append(i)

    out: list[dict[str, float]] = []
    for i in brackets:
        cen = _interp_zero(float(wv[i]), float(residual[i]), float(wv[i + 1]), float(residual[i + 1]))
        if not (float(wv[0]) <= cen <= float(wv[-1])):
            continue
        peak_at_pole = float(np.interp(cen, wv, av))
        if not np.isfinite(peak_at_pole) or peak_at_pole < float(min_peak):
            continue
        dre_val = float(np.interp(cen, wv, dre))
        den = 1.0 - dre_val
        if not np.isfinite(den) or den <= 1.0e-8:
            continue
        z_raw = 1.0 / den
        if not (float(z_min) <= z_raw <= float(z_max)):
            continue
        im_val = float(np.interp(cen, wv, imv))
        gamma0 = float(eta) + max(0.0, -im_val)
        gamma = max(float(z_raw) * gamma0, 1.0e-8)
        if not np.isfinite(gamma) or gamma <= 0.0 or gamma > float(max_gamma):
            continue
        out.append(
            {
                "center": float(cen),
                "peak": float(peak_at_pole),
                "slope_re": float(dre_val),
                "weight_raw": float(z_raw),
                "gamma0": float(gamma0),
                "gamma": float(gamma),
            }
        )
    return out


def extract_dyson_qp_from_cube(
    source: np.lib.npyio.NpzFile,
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    a_vals: np.ndarray,
    *,
    label: str,
    max_gamma: float,
    z_min: float,
    z_max: float,
    min_peak: float,
    peak_cap_factor: float,
    enforce_positive_inc: bool,
    positive_inc_qpcut: float,
) -> dict[str, np.ndarray]:
    if "ReS" not in source.files or "ImS" not in source.files:
        raise ValueError("Dyson extraction requires ReS and ImS in the input cube.")

    k = np.asarray(k_axis, dtype=float)
    a = np.asarray(a_vals, dtype=float)
    re_s = np.asarray(source["ReS"], dtype=float)
    im_s = np.asarray(source["ImS"], dtype=float)
    eta = _scalar_from_source(source, ("eta",), 1.0e-3)
    sigma0 = _scalar_from_source(source, ("sigma0",), 0.0)
    mass = _scalar_from_source(source, ("mass",), 1.0)
    mu = _mu_for_label(source, label)
    if not np.isfinite(mu):
        raise ValueError(f"Cannot infer spin chemical potential for {label}.")

    center = np.full(k.size, np.nan, dtype=float)
    gamma = np.full(k.size, np.nan, dtype=float)
    gamma0 = np.full(k.size, np.nan, dtype=float)
    weight = np.zeros(k.size, dtype=float)
    weight_raw = np.zeros(k.size, dtype=float)
    weight_scale = np.zeros(k.size, dtype=float)
    peak = np.zeros(k.size, dtype=float)
    slope_re = np.full(k.size, np.nan, dtype=float)
    valid = np.zeros(k.size, dtype=bool)

    for ik in range(k.size):
        wi = _row_axis(w_axis, ik)
        ai = np.asarray(a[ik], dtype=float)
        rei = np.asarray(re_s[ik], dtype=float)
        imi = np.asarray(im_s[ik], dtype=float)
        if wi.size != ai.size or rei.size != ai.size or imi.size != ai.size:
            continue
        xi = float(k[ik] * k[ik] / float(mass) - float(mu))
        candidates = _dyson_candidates(
            wi,
            ai,
            rei,
            imi,
            xi=xi,
            sigma0=sigma0,
            eta=eta,
            z_min=float(z_min),
            z_max=float(z_max),
            max_gamma=float(max_gamma),
            min_peak=float(min_peak),
        )
        if not candidates:
            continue
        cand = max(candidates, key=lambda c: c["peak"])
        cen = cand["center"]
        gam = cand["gamma"]
        z_raw = cand["weight_raw"]
        z_used = z_raw

        if np.isfinite(peak_cap_factor) and peak_cap_factor > 0.0:
            z_peak_cap = float(peak_cap_factor) * cand["peak"] * np.pi * gam
            if np.isfinite(z_peak_cap) and z_peak_cap > 0.0:
                z_used = min(z_used, z_peak_cap)

        if bool(enforce_positive_inc):
            qp_row_raw = _lorentzian_row(wi, cen, gam, z_used)
            qp_peak = float(np.nanmax(qp_row_raw)) if qp_row_raw.size else 0.0
            mask = np.isfinite(ai) & np.isfinite(qp_row_raw) & (qp_row_raw > qp_peak * float(positive_inc_qpcut))
            if np.any(mask):
                ratios = np.divide(ai[mask], qp_row_raw[mask], out=np.zeros(np.count_nonzero(mask)), where=qp_row_raw[mask] > 0.0)
                ratios = ratios[np.isfinite(ratios)]
                if ratios.size:
                    scale = min(1.0, 0.98 * max(0.0, float(np.nanmin(ratios))))
                    z_used *= scale

        if not np.isfinite(z_used) or z_used <= 0.0:
            continue

        center[ik] = cen
        gamma[ik] = gam
        gamma0[ik] = cand["gamma0"]
        weight[ik] = z_used
        weight_raw[ik] = z_raw
        weight_scale[ik] = z_used / z_raw if z_raw > 0.0 else 0.0
        peak[ik] = cand["peak"]
        slope_re[ik] = cand["slope_re"]
        valid[ik] = True

    return {
        "k": k,
        "center": center,
        "gamma": gamma,
        "gamma0": gamma0,
        "weight": weight,
        "weight_raw": weight_raw,
        "weight_scale": weight_scale,
        "peak": peak,
        "slope_re": slope_re,
        "valid": valid,
    }














