# =====================================================================
# SLIM copy of diagnostics/density_from_clean_pair_one_shot.py
#
# 0 top-level symbols (0 lines, 0% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   main
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
# =====================================================================
#!/usr/bin/env python3
"""One-shot density diagnostic for the clean vacuum-subtracted pair engine.

This does not modify a production pipeline.  It follows the production map:
pair-native ImSigma, stale support outside the safe update rectangle, global
KK on the complete base omega grid, Sigma mixing, Dyson rebuild, pole-aware
omega enrichment, and row-local density integration.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import os
from pathlib import Path
import sys

import numpy as np


PIPELINE = Path(__file__).resolve().parents[1]
ROOT = PIPELINE.parent
if str(PIPELINE) not in sys.path:
    sys.path.insert(0, str(PIPELINE))

from fflo.kramers_kronig import (
    kk_re_pv_linear,
    kk_sigma_gamma_asymptote,
)
from fflo.sigma_engine import (
    Physics,
    _im_sigma_row_pair_native,
    _internal_a_eval,
    _pn_qp_tables,
    bilinear_eval_with_support,
    find_qp_poles_dyson,
    interp_pchip,
    load_cube_sigma,
    pole_refind_half_widths_from_im_sigma,
    rebuild_a_from_mixed_sigma_1d,
    rebuild_a_from_saved_sigma_grid,
    rebuild_omega_per_k,
    select_sigma_k_indices,
)

from fflo.compare_motors import build_clean_smooth_pair
from fflo.sigma_from_pair import (
    build_sigma_p_grid,
    compute_im_sigma_scan_at_k_from_table,
)


DEFAULT_IMPI = (
    ROOT
    / "diagnostics/subtract_product_benchmark_p065/results"
    / "pair_strategy_production_inputs/impi_subtract_product.npz"
)
DEFAULT_SEEDS = ROOT / "X_FFLO_v2/seeds/P0p65"
DEFAULT_OUT = (
    ROOT
    / "X_FFLO_FULLGRID_PROD/diagnostics"
    / "density_from_clean_pair_p065"
)


def load_seed(path: Path) -> dict[str, np.ndarray | float | str]:
    with np.load(path) as data:
        w = np.asarray(data["w"], dtype=float)
        if "w_base" in data.files:
            w_base = np.asarray(data["w_base"], dtype=float)
        elif w.ndim == 1:
            # Legacy heatmap cubes used one common omega axis and did not save
            # the redundant w_base key.
            w_base = w.copy()
        elif w.ndim == 2 and np.allclose(w, w[0], rtol=0.0, atol=1.0e-12):
            w_base = np.asarray(w[0], dtype=float).copy()
        else:
            raise KeyError(
                f"{path}: missing w_base for a genuinely row-local omega grid"
            )
        return {
            "k": np.asarray(data["k"], dtype=float),
            "w": w,
            "w_base": w_base,
            "a": np.asarray(data["A"], dtype=float),
            "res": np.asarray(data["ReS"], dtype=float),
            "ims": np.asarray(data["ImS"], dtype=float),
            "sigma0": float(data["sigma0"]),
            "mass": float(data["mass"]),
            "eta": float(data["eta"]),
            "convention": str(data["a_convention"]),
            "mu_up": float(data["mu_up"]),
            "mu_dn": float(data["mu_dn"]) if "mu_dn" in data.files else float(data["mu_down"]),
        }


def occupied_nk(a: np.ndarray, w: np.ndarray) -> np.ndarray:
    a = np.asarray(a, dtype=float)
    w = np.asarray(w, dtype=float)
    if w.ndim == 1:
        mask = w <= 0.0
        return np.trapezoid(a[:, mask], w[mask], axis=1)
    return np.asarray(
        [
            np.trapezoid(a[i, w[i] <= 0.0], w[i, w[i] <= 0.0])
            for i in range(a.shape[0])
        ],
        dtype=float,
    )


def row_sum_rule(a: np.ndarray, w: np.ndarray) -> np.ndarray:
    a = np.asarray(a, dtype=float)
    w = np.asarray(w, dtype=float)
    if w.ndim == 1:
        return np.trapezoid(a, w, axis=1)
    return np.asarray(
        [np.trapezoid(a[i], w[i]) for i in range(a.shape[0])],
        dtype=float,
    )


def density(k: np.ndarray, nk: np.ndarray) -> float:
    return float(np.trapezoid(np.asarray(k) * np.asarray(nk), np.asarray(k)))


def _recon_linear() -> bool:
    """SIGMA_RECON_LINEAR: sostituisce PCHIP con interpolazione lineare nelle due
    ricostruzioni della Sigma sparsa (in omega da w_eval, in k da k_sparse).
    Diagnostico: se il risultato cambia, il campionamento non e' sufficiente;
    se non cambia, la ricostruzione e' adeguata e l'errore sta altrove.
    In k np.interp CLAMPA ai bordi invece di estrapolare come PchipInterpolator
    (extrapolate=True), il che e' anche piu' prudente oltre l'ultimo nodo."""
    return str(os.environ.get("SIGMA_RECON_LINEAR", "0")).strip().lower() not in {
        "", "0", "false", "no", "off"
    }


def density_with_contact_tail(
    k: np.ndarray,
    nk: np.ndarray,
    enabled: bool,
    fit_min: float = 10.0,
    fit_max_fraction: float = 0.92,
    contact_override: float = np.nan,
    contact_tail_start: float = np.nan,
) -> tuple[float, float, float, float]:
    """Return total, captured, extrapolated tail, and fitted contact.

    In the present two-dimensional normalization, n(k)=C/k^4 contributes
    C/(2*k_max^2) beyond the last momentum row. Nothing is rescaled.
    """
    k = np.asarray(k, dtype=float)
    nk = np.asarray(nk, dtype=float)
    captured = density(k, nk)
    if not enabled:
        return captured, captured, 0.0, float("nan")
    if np.isfinite(float(contact_override)):
        contact = float(contact_override)
    else:
        lo = max(float(fit_min), 0.70 * float(k[-1]))
        hi = float(fit_max_fraction) * float(k[-1])
        mask = (k >= lo) & (k <= hi) & np.isfinite(nk) & (nk >= 0.0)
        if np.count_nonzero(mask) < 3:
            raise RuntimeError(
                f"contact-tail fit has fewer than three rows in [{lo:g},{hi:g}]"
            )
        contact = float(np.median(k[mask] ** 4 * nk[mask]))
    if np.isfinite(float(contact_tail_start)):
        tail_start = float(contact_tail_start)
        if not (float(k[0]) < tail_start <= float(k[-1])):
            raise RuntimeError(
                f"contact tail start {tail_start:g} outside k support "
                f"[{k[0]:g},{k[-1]:g}]"
            )
        core_points = np.unique(
            np.concatenate((k[k < tail_start], np.asarray([tail_start])))
        )
        captured = float(
            np.trapezoid(
                core_points * np.interp(core_points, k, nk), core_points
            )
        )
        tail = contact / (2.0 * tail_start**2)
    else:
        tail = contact / (2.0 * float(k[-1]) ** 2)
    return captured + tail, captured, tail, contact


def pair_contact_from_shifted_table(
    q: np.ndarray, omega: np.ndarray, a_pair: np.ndarray
) -> tuple[float, float]:
    """Return Delta_inf^2 and the fermion C=Delta_inf^2/4."""
    q = np.asarray(q, dtype=float)
    omega = np.asarray(omega, dtype=float)
    a_pair = np.asarray(a_pair, dtype=float)
    occupied = omega <= 0.0
    if np.count_nonzero(occupied) < 2:
        raise RuntimeError("pair table has fewer than two occupied omega nodes")
    delta2 = -float(
        np.trapezoid(
            q * np.trapezoid(a_pair[:, occupied], omega[occupied], axis=1), q
        )
        / (2.0 * np.pi)
    )
    if not np.isfinite(delta2) or delta2 <= 0.0:
        raise RuntimeError(f"non-positive pair contact scale Delta_inf^2={delta2}")
    return delta2, 0.25 * delta2


def _two_pole_omega_row(
    w_base: np.ndarray,
    pole: float,
    pole_half_width: float,
    satellite: float,
    satellite_half_width: float,
    n_local: int,
) -> np.ndarray:
    """Budget-neutral omega row resolving both Dyson roots at high k."""
    w = np.unique(np.asarray(w_base, dtype=float))
    n_w = int(w.size)
    if n_w < 2:
        return w

    finite_centers = [value for value in (pole, satellite) if np.isfinite(value)]
    support_lo = min([float(w[0])] + [float(value) - 2.0 for value in finite_centers])
    support_hi = max([float(w[-1])] + [float(value) + 2.0 for value in finite_centers])

    def feature(center: float, half_width: float) -> np.ndarray:
        if not np.isfinite(center):
            return np.empty(0, dtype=float)
        # A narrow uniform feature followed by a large empty omega cell gives
        # the trapezoid rule a false triangular area.  Logarithmic shoulders
        # resolve the Lorentzian core and carry its decay continuously to both
        # global boundaries with the same fixed row budget.
        n_side = max(4, (int(n_local) - 1) // 2)
        # The physical/numerical Lorentzian width is O(1e-3).  Starting the
        # geometric shoulder at O(1e-3) leaves one oversized triangle across
        # the peak; start at 1e-4 or finer so the trapezoidal row measure is
        # genuinely converged without any post-hoc row normalization.
        core = max(min(float(half_width) / 256.0, 1.0e-5), 1.0e-7)
        span = max(center - support_lo, support_hi - center, float(half_width))
        offsets = np.geomspace(core, span, n_side)
        return np.unique(
            np.clip(
                np.concatenate((center - offsets, np.asarray([center]), center + offsets)),
                support_lo,
                support_hi,
            )
        )

    zero = w[np.abs(w) <= 0.20]
    primary = feature(float(pole), max(float(pole_half_width), 0.05))
    secondary = feature(float(satellite), max(float(satellite_half_width), 0.05))
    mandatory = np.unique(
        np.concatenate((np.asarray([support_lo, support_hi, 0.0]), primary, secondary))
    )
    budget = max(0, n_w - mandatory.size)
    if zero.size > budget:
        take = np.round(np.linspace(0, zero.size - 1, budget)).astype(int)
        zero = zero[take]
    anchors = np.unique(np.concatenate((mandatory, zero)))
    remaining = np.setdiff1d(w, anchors, assume_unique=False)
    budget = n_w - anchors.size
    if budget > 0 and remaining.size:
        take = np.round(np.linspace(0, remaining.size - 1, budget)).astype(int)
        anchors = np.unique(np.concatenate((anchors, remaining[take])))
    if anchors.size < n_w:
        remaining = np.setdiff1d(w, anchors, assume_unique=False)
        anchors = np.unique(np.concatenate((anchors, remaining[: n_w - anchors.size])))
    return np.asarray(np.sort(anchors)[:n_w], dtype=float)


_SIGMA_WORKER_CTX: dict = {}


def _sigma_worker_init(ctx: dict) -> None:
    """Runs once per worker PROCESS (real parallelism, unlike ThreadPoolExecutor,
    which was serialized by the GIL for this CPU-bound work -- see
    _sigma_compute_row_worker)."""
    _SIGMA_WORKER_CTX.update(ctx)


def _qp_tables_for_exact_all_roots(
    eps_tab: np.ndarray,
    *,
    kc: np.ndarray,
    wc: np.ndarray,
    res_c: np.ndarray,
    ims_c: np.ndarray,
    sigma0_c: float,
    mu_internal: float,
    eta_c: float,
    p_max: float,
    n_p_fine: int = 2400,
    max_poles: int = 3,
) -> dict:
    """Locate every regular Dyson crossing for exact-window integration.

    Unlike the historical ring control variate, exact-window integration uses
    the complete A inside each window.  It therefore must not discard a root
    merely because its width exceeds the control-variate sharpness threshold.
    """
    p_fine = np.linspace(1.0e-4, float(p_max), int(n_p_fine))
    re_i, _ = bilinear_eval_with_support(
        p_fine[:, None], eps_tab[None, :], kc, wc, res_c
    )
    im_i, _ = bilinear_eval_with_support(
        p_fine[:, None], eps_tab[None, :], kc, wc, ims_c
    )
    xi = (p_fine * p_fine - float(mu_internal))[:, None]
    residual = eps_tab[None, :] - xi - (re_i - float(sigma0_c))
    gamma = np.abs(im_i) + float(eta_c)
    flips = np.signbit(residual[1:, :]) != np.signbit(residual[:-1, :])
    p_star = np.full((max_poles, eps_tab.size), np.nan)
    gamma_p = np.full_like(p_star, np.nan)
    weight_p = np.zeros_like(p_star)
    dp = float(p_fine[1] - p_fine[0])
    for energy_index in range(eps_tab.size):
        for branch, lower in enumerate(np.flatnonzero(flips[:, energy_index])[:max_poles]):
            f0 = float(residual[lower, energy_index])
            f1 = float(residual[lower + 1, energy_index])
            fraction = f0 / (f0 - f1 + 1.0e-300)
            slope = abs((f1 - f0) / dp)
            if slope < 1.0e-6:
                continue
            width = (
                float(gamma[lower, energy_index]) * (1.0 - fraction)
                + float(gamma[lower + 1, energy_index]) * fraction
            ) / slope
            p_star[branch, energy_index] = p_fine[lower] + fraction * dp
            gamma_p[branch, energy_index] = max(width, 1.0e-3)
            weight_p[branch, energy_index] = 1.0 / slope
    return {
        "p_star": p_star,
        "gam_p": gamma_p,
        "wgt_p": weight_p,
    }


def _apply_im_sigma_sign_policy(
    row: np.ndarray, omega: np.ndarray
) -> tuple[np.ndarray, int, float, float, float]:
    row = np.asarray(row, dtype=float)
    omega = np.asarray(omega, dtype=float)
    positive = row > 0.0
    count = int(np.count_nonzero(positive))
    maximum = float(np.max(np.where(positive, row, 0.0)))
    positive_l1 = float(np.trapezoid(np.maximum(row, 0.0), omega))
    negative_l1 = float(np.trapezoid(np.maximum(-row, 0.0), omega))
    relative_l1 = positive_l1 / max(negative_l1, 1.0e-300)
    policy = str(os.environ.get("SIGMA_IM_SIGN_POLICY", "clamp")).strip().lower()
    tolerance = float(os.environ.get("SIGMA_IM_SIGN_TOL", "1e-10"))
    relative_tolerance = float(
        os.environ.get("SIGMA_IM_SIGN_REL_L1_TOL", "inf")
    )
    if policy not in {"clamp", "reject"}:
        raise ValueError(f"unknown SIGMA_IM_SIGN_POLICY={policy!r}")
    if policy == "reject" and (
        maximum > tolerance or relative_l1 > relative_tolerance
    ):
        raise RuntimeError(
            "raw ImSigma violates causality: "
            f"max_positive={maximum:.12e} (tol={tolerance:.12e}), "
            f"relative_positive_L1={relative_l1:.12e} "
            f"(tol={relative_tolerance:.12e})"
        )
    return np.minimum(row, 0.0), count, maximum, positive_l1, negative_l1


def _im_sigma_row_pair_native_quad_vec(
    w_axis_target: np.ndarray,
    *,
    kv: float,
    q_axis_pair: np.ndarray,
    omega_axis_pair: np.ndarray,
    a_pair: np.ndarray,
    eval_internal,
    n_theta: int,
    p_int_max: float,
    tail_cell_max: float,
) -> np.ndarray:
    """Gold diagnostic: adaptive fermion angle on the resonant Q core."""
    from scipy.integrate import quad_vec

    q = np.asarray(q_axis_pair, dtype=float)
    om = np.asarray(omega_axis_pair, dtype=float)
    ap = np.asarray(a_pair, dtype=float)
    w_target = np.asarray(w_axis_target, dtype=float)
    if np.any(w_target < om[0]) or np.any(w_target > om[-1]):
        raise ValueError("Sigma frequencies exceed pair support")
    # In each T=0 convolution window Omega lies between external omega and
    # zero, hence epsilon=Omega-omega never exceeds the pair support itself.
    eps_lo = -float(max(om[-1], 0.0))
    eps_hi = -float(min(om[0], 0.0))
    eps_core = np.arange(-0.5, 0.5 + 1.0e-12, 2.0e-3)
    n_stretched = 420
    eps_pos = 0.5 * np.exp(
        np.linspace(0.0, np.log(max(eps_hi, 1.0) / 0.5), n_stretched)
    )
    eps_neg = -0.5 * np.exp(
        np.linspace(0.0, np.log(max(-eps_lo, 1.0) / 0.5), n_stretched)
    )
    eps_tab = np.unique(np.concatenate((eps_neg[::-1], eps_core, eps_pos)))
    eps_tab = eps_tab[(eps_tab >= eps_lo - 1.0) & (eps_tab <= eps_hi + 1.0)]

    q_adaptive_max = float(os.environ.get("SIGMA_PN_QUADVEC_Q_MAX", "3.0"))
    epsabs = float(os.environ.get("SIGMA_PN_QUADVEC_EPSABS", "1e-7"))
    epsrel = float(os.environ.get("SIGMA_PN_QUADVEC_EPSREL", "2e-5"))
    limit = int(os.environ.get("SIGMA_PN_QUADVEC_LIMIT", "1000"))
    small_k_direct = float(
        os.environ.get("SIGMA_PN_QUADVEC_SMALL_K_DIRECT", "1e-3")
    )
    theta = (np.arange(int(n_theta)) + 0.5) * 2.0 * np.pi / float(n_theta)
    angular = np.empty((q.size, eps_tab.size), dtype=float)
    for q_index, q_value in enumerate(q):
        if abs(float(kv)) <= small_k_direct:
            # At k=0, |Q-k|=Q and the fermion factor has no angular
            # dependence.  Very small k is numerically indistinguishable on
            # the stored fermion grid, so an adaptive angular solve only
            # burns subdivisions without changing the integral.
            if q_value <= p_int_max:
                values = eval_internal(
                    np.asarray([[q_value]], dtype=float), eps_tab[None, :]
                )
                angular[q_index] = 2.0 * np.pi * np.asarray(values)[0]
            else:
                angular[q_index] = 0.0
        elif q_value <= q_adaptive_max + 1.0e-14:
            def integrand(theta_value: float) -> np.ndarray:
                p_value = np.sqrt(
                    max(
                        q_value * q_value
                        + kv * kv
                        - 2.0 * q_value * kv * np.cos(theta_value),
                        0.0,
                    )
                )
                if p_value > p_int_max:
                    return np.zeros(eps_tab.size, dtype=float)
                values = eval_internal(
                    np.asarray([[p_value]], dtype=float), eps_tab[None, :]
                )
                return np.asarray(values, dtype=float)[0]

            value, _ = quad_vec(
                integrand,
                0.0,
                np.pi,
                epsabs=epsabs,
                epsrel=epsrel,
                norm="max",
                limit=limit,
                quadrature="gk21",
            )
            angular[q_index] = 2.0 * np.asarray(value, dtype=float)
        else:
            p_theta = np.sqrt(
                np.maximum(
                    q_value * q_value
                    + kv * kv
                    - 2.0 * q_value * kv * np.cos(theta),
                    0.0,
                )
            )
            values = eval_internal(p_theta[:, None], eps_tab[None, :])
            values = np.where(p_theta[:, None] <= p_int_max, values, 0.0)
            angular[q_index] = 2.0 * np.pi * np.mean(values, axis=0)

    q_weights = np.empty_like(q)
    q_weights[1:-1] = 0.5 * (q[2:] - q[:-2])
    q_weights[0] = 0.5 * (q[1] - q[0])
    q_weights[-1] = 0.5 * (q[-1] - q[-2])
    q_weights *= q

    out = np.zeros(w_target.size, dtype=float)
    omega_mode = str(
        os.environ.get("SIGMA_PN_OMEGA_INTEGRATION_MODE", "tail_subdivide")
    ).strip().lower()
    omega_gl_n = max(2, int(os.environ.get("SIGMA_PN_OMEGA_GL_N", "4")))
    if omega_mode == "panel_gl":
        omega_gl_x, omega_gl_w = np.polynomial.legendre.leggauss(omega_gl_n)
    for omega_index, external_omega in enumerate(w_target):
        if external_omega == 0.0:
            continue
        lo, hi = (
            (0.0, float(external_omega))
            if external_omega > 0.0
            else (float(external_omega), 0.0)
        )
        sign = 1.0 if external_omega > 0.0 else -1.0
        inner = om[(om > lo + 1.0e-12) & (om < hi - 1.0e-12)]
        edges = np.concatenate(([lo], inner, [hi]))
        if omega_mode == "panel_gl":
            half = 0.5 * (edges[1:] - edges[:-1])
            mid = 0.5 * (edges[1:] + edges[:-1])
            segment = (mid[:, None] + half[:, None] * omega_gl_x).ravel()
            omega_weights = (half[:, None] * omega_gl_w).ravel()
        elif omega_mode == "tail_subdivide":
            pieces = [edges[:1]]
            for left, right in zip(edges[:-1], edges[1:]):
                if right - left > tail_cell_max:
                    count = int(np.ceil((right - left) / tail_cell_max))
                    pieces.append(np.linspace(left, right, count + 1)[1:])
                else:
                    pieces.append(np.asarray([right]))
            segment = np.concatenate(pieces)
            omega_weights = np.empty_like(segment)
            omega_weights[1:-1] = 0.5 * (segment[2:] - segment[:-2])
            omega_weights[0] = 0.5 * (segment[1] - segment[0])
            omega_weights[-1] = 0.5 * (segment[-1] - segment[-2])
        else:
            raise ValueError(
                "SIGMA_PN_OMEGA_INTEGRATION_MODE must be "
                "'tail_subdivide' or 'panel_gl'"
            )
        pair_segment = np.asarray(
            [np.interp(segment, om, row) for row in ap], dtype=float
        )
        eps_needed = segment - float(external_omega)
        lower = np.clip(
            np.searchsorted(eps_tab, eps_needed) - 1, 0, eps_tab.size - 2
        )
        fraction = (eps_needed - eps_tab[lower]) / np.maximum(
            eps_tab[lower + 1] - eps_tab[lower], 1.0e-14
        )
        fermion = (
            angular[:, lower] * (1.0 - fraction)[None, :]
            + angular[:, lower + 1] * fraction[None, :]
        )
        total = np.sum(
            q_weights[:, None]
            * pair_segment
            * fermion
            * (sign * omega_weights)[None, :]
        )
        out[omega_index] = -np.pi * float(total) / (2.0 * np.pi) ** 2
    return out


def _pair_native_row_dispatch(w_axis_target: np.ndarray, **kwargs) -> np.ndarray:
    mode = str(os.environ.get("SIGMA_PN_ANGLE_MODE", "legacy")).strip().lower()
    if mode == "quad_vec":
        kwargs.pop("qp_tab", None)
        return _im_sigma_row_pair_native_quad_vec(w_axis_target, **kwargs)
    return _im_sigma_row_pair_native(w_axis_target, **kwargs)


def _sigma_compute_row_worker(
    row_index: int,
) -> tuple[int, np.ndarray, int, float, float, float]:
    g = _SIGMA_WORKER_CTX
    k_sparse = g["k_sparse"]
    omega_target = g["omega_target"]
    chunk = g["chunk"]
    cube = g["cube"]
    mu_internal = g["mu_internal"]

    def eval_internal(pq: np.ndarray, eq: np.ndarray) -> np.ndarray:
        return _internal_a_eval(
            pq,
            eq,
            cube["k"],
            cube["w"],
            cube["a"],
            cube["res"],
            cube["ims"],
            cube["sigma0"],
            mu_internal,
            cube["eta"],
        )

    kval = float(k_sparse[row_index])
    row = np.empty(omega_target.size, dtype=float)
    use_reference = str(os.environ.get("SIGMA_REFERENCE_ENGINE", "0")).strip().lower() not in {"0", "false", "no", "off", ""}
    if use_reference:
        p_max = float(os.environ.get("SIGMA_REF_PMAX", "10.0"))
        n_p = int(os.environ.get("SIGMA_REF_NP", "121"))
        n_phi = int(os.environ.get("SIGMA_REF_NPHI", "128"))
        n_eps = int(os.environ.get("SIGMA_REF_NEPS", "1201"))
        p_grid, _ = build_sigma_p_grid(
            0.0, p_max, n_p, "linear",
            mu_internal=mu_internal, k_ext=kval, q_feature=float("nan"),
            feature_half_width=0.0, feature_n_local=1, feature_mode="none",
            tail_start=float("nan"), tail_n=0,
        )
        phi_grid = np.linspace(0.0, np.pi, n_phi, endpoint=False)
        eps_grid = np.linspace(-260.0, 260.0, n_eps)
        internal_a = eval_internal(p_grid[:, None], eps_grid[None, :])
        for start in range(0, omega_target.size, chunk):
            stop = min(start + chunk, omega_target.size)
            row[start:stop] = compute_im_sigma_scan_at_k_from_table(
                omega_target[start:stop],
                k_ext=float(kval),
                p_grid=p_grid,
                eps_grid=eps_grid,
                phi_grid=phi_grid,
                temperature=0.0,
                internal_a=internal_a,
                q_axis_pair=g["pair_q"],
                omega_axis_pair=g["pair_omega"],
                a_pair_table=g["pair_a"],
                qp_subtraction="none",
            )
        if not globals().get("_REF_ANNOUNCED", False):
            globals()["_REF_ANNOUNCED"] = True
            print(f"[sigma-engine] REFERENCE SCAN ON (n_p={n_p}, n_phi={n_phi}, n_eps={n_eps}, p_max={p_max:g})", flush=True)
        row, positive_count, positive_max, positive_l1, negative_l1 = (
            _apply_im_sigma_sign_policy(row, omega_target)
        )
        return (
            row_index, row, positive_count, positive_max,
            positive_l1, negative_l1,
        )
    for start in range(0, omega_target.size, chunk):
        stop = min(start + chunk, omega_target.size)
        row[start:stop] = _pair_native_row_dispatch(
            omega_target[start:stop],
            kv=float(kval),
            q_axis_pair=g["pair_q"],
            omega_axis_pair=g["pair_omega"],
            a_pair=g["pair_a"],
            eval_internal=eval_internal,
            n_theta=g["n_theta"],
            p_int_max=float(os.environ.get("SIGMA_PN_PINTMAX", "6.0")),
            tail_cell_max=float(os.environ.get("SIGMA_PN_TAILCELL", "0.02")),
            qp_tab=g["qp_tab"],
        )
    row, positive_count, positive_max, positive_l1, negative_l1 = (
        _apply_im_sigma_sign_policy(row, omega_target)
    )
    return (
        row_index, row, positive_count, positive_max,
        positive_l1, negative_l1,
    )


def memory_safe_im_sigma(
    *,
    spin: str,
    cube: dict[str, np.ndarray | float | str],
    pair_q: np.ndarray,
    pair_omega: np.ndarray,
    pair_a: np.ndarray,
    k_target: np.ndarray,
    omega_target: np.ndarray,
    physics: Physics,
    qff: float,
    sigma_nk: int,
    sigma_k_feature_fraction: float,
    n_theta: int,
    omega_chunk: int,
    workers: int,
    checkpoint: Path,
) -> np.ndarray:
    """Evaluate sparse Sigma rows serially and checkpoint after every row."""
    from scipy.interpolate import PchipInterpolator

    mu_internal = float(physics.mu_down if spin == "up" else physics.mu_up)
    spin_l = str(spin).strip().lower()
    mu_external = float(physics.mu_up if spin_l == "up" else physics.mu_down)
    kf_external = np.sqrt(max(float(physics.mass) * mu_external, 0.0))
    kf_internal = np.sqrt(max(float(physics.mass) * mu_internal, 0.0))
    anchors = [
        float(k_target[0]),
        float(k_target[-1]),
        float(qff),
        float(kf_external),
        0.5 * float(kf_external),  # Resolve Sigma inside the external Fermi sea.
        float(kf_internal),
        abs(float(qff) - float(kf_internal)),
        float(qff) + float(kf_internal),
        0.5 * (float(qff) + float(kf_internal)),
        float(kf_internal) + 0.5 * float(qff),
    ]
    selected_set = {
        int(np.argmin(np.abs(k_target - value)))
        for value in anchors
        if np.isfinite(value) and k_target[0] <= value <= k_target[-1]
    }
    # A global farthest-point fill spends every spare node in the very wide
    # high-k tail.  Reserve an explicit quota for the physically structured
    # interval before filling the remaining support globally.
    feature_max = min(
        float(k_target[-1]),
        float(qff) + max(float(kf_external), float(kf_internal)),
    )
    feature_candidates = np.flatnonzero(k_target <= feature_max + 1.0e-12)
    feature_quota = int(
        np.clip(
            np.ceil(float(sigma_k_feature_fraction) * int(sigma_nk)),
            0,
            int(sigma_nk),
        )
    )
    feature_quota = max(
        feature_quota,
        sum(index in set(feature_candidates.tolist()) for index in selected_set),
    )
    while (
        len(selected_set) < int(sigma_nk)
        and sum(index in set(feature_candidates.tolist()) for index in selected_set)
        < feature_quota
    ):
        selected_now = np.asarray(sorted(selected_set), dtype=int)
        distances = np.min(
            np.abs(
                k_target[feature_candidates, None]
                - k_target[selected_now][None, :]
            ),
            axis=1,
        )
        distances[np.isin(feature_candidates, selected_now)] = -np.inf
        selected_set.add(int(feature_candidates[int(np.argmax(distances))]))
    while len(selected_set) < int(sigma_nk):
        selected_now = np.asarray(sorted(selected_set), dtype=int)
        distances = np.min(
            np.abs(k_target[:, None] - k_target[selected_now][None, :]), axis=1
        )
        distances[selected_now] = -np.inf
        selected_set.add(int(np.argmax(distances)))
    selected = np.asarray(sorted(selected_set), dtype=int)
    if selected.size > int(sigma_nk):
        # Preserve both support endpoints and thin the remaining anchors.
        interior = selected[1:-1]
        need = max(0, int(sigma_nk) - 2)
        pick = np.round(np.linspace(0, interior.size - 1, need)).astype(int)
        selected = np.concatenate(([selected[0]], interior[pick], [selected[-1]]))
    k_sparse = np.asarray(k_target[selected], dtype=float)
    im_sparse = np.full((selected.size, omega_target.size), np.nan, dtype=float)
    done = np.zeros(selected.size, dtype=bool)
    positive_counts = np.zeros(selected.size, dtype=np.int64)
    positive_maxima = np.zeros(selected.size, dtype=float)
    positive_l1 = np.zeros(selected.size, dtype=float)
    negative_l1 = np.zeros(selected.size, dtype=float)

    if checkpoint.exists():
        with np.load(checkpoint) as saved:
            if (
                np.array_equal(saved["k_sparse"], k_sparse)
                and np.array_equal(saved["omega"], omega_target)
            ):
                im_sparse = np.asarray(saved["im_sparse"], dtype=float)
                done = np.asarray(saved["done"], dtype=bool)
                if "positive_counts" in saved.files:
                    positive_counts = np.asarray(saved["positive_counts"], dtype=np.int64)
                if "positive_maxima" in saved.files:
                    positive_maxima = np.asarray(saved["positive_maxima"], dtype=float)
                if "positive_l1" in saved.files:
                    positive_l1 = np.asarray(saved["positive_l1"], dtype=float)
                if "negative_l1" in saved.files:
                    negative_l1 = np.asarray(saved["negative_l1"], dtype=float)
                print(
                    f"[density-clean] resume Sigma_{spin}: "
                    f"{done.sum()}/{done.size} sparse k rows",
                    flush=True,
                )

    p_int_max = float(os.environ.get("SIGMA_PN_PINTMAX", "6.0"))
    qp_p_max = p_int_max + 1.0
    eps_src = np.linspace(
        -mu_internal - 2.0,
        qp_p_max**2 - mu_internal + 2.0,
        max(1800, int(240 * qp_p_max)),
    )
    qp_kwargs = dict(
        kc=np.asarray(cube["k"]),
        wc=np.asarray(cube["w"]),
        res_c=np.asarray(cube["res"]),
        ims_c=np.asarray(cube["ims"]),
        sigma0_c=float(cube["sigma0"]),
        mu_internal=mu_internal,
        eta_c=float(cube["eta"]),
        p_max=qp_p_max,
        max_poles=int(os.environ.get("PN_RING_MAX_POLES", "3")),
    )
    ring_disabled = str(os.environ.get("SIGMA_PN_RING", "1")).strip().lower() in {
        "0",
        "false",
        "no",
        "off",
    }
    if ring_disabled:
        qp_tab = None
    else:
        exact_all_roots = str(
            os.environ.get("SIGMA_PN_EXACT_ALL_ROOTS", "0")
        ).strip().lower() not in {"0", "false", "no", "off", ""}
        if exact_all_roots:
            qp_tab = _qp_tables_for_exact_all_roots(
                eps_src,
                n_p_fine=int(os.environ.get("SIGMA_PN_RING_NP_FINE", "2400")),
                **qp_kwargs,
            )
        else:
            qp_tab = _pn_qp_tables(eps_src, **qp_kwargs)
        qp_tab["eps_src"] = eps_src

    def eval_internal(pq: np.ndarray, eq: np.ndarray) -> np.ndarray:
        return _internal_a_eval(
            pq,
            eq,
            np.asarray(cube["k"]),
            np.asarray(cube["w"]),
            np.asarray(cube["a"]),
            np.asarray(cube["res"]),
            np.asarray(cube["ims"]),
            float(cube["sigma0"]),
            mu_internal,
            float(cube["eta"]),
        )

    chunk = max(1, int(omega_chunk))
    def compute_row(
        row_index: int,
    ) -> tuple[int, np.ndarray, int, float, float, float]:
        kval = float(k_sparse[row_index])
        row = np.empty(omega_target.size, dtype=float)
        use_reference = str(os.environ.get("SIGMA_REFERENCE_ENGINE", "0")).strip().lower() not in {"0", "false", "no", "off", ""}
        if use_reference:
            p_max = float(os.environ.get("SIGMA_REF_PMAX", "10.0"))
            n_p = int(os.environ.get("SIGMA_REF_NP", "121"))
            n_phi = int(os.environ.get("SIGMA_REF_NPHI", "128"))
            n_eps = int(os.environ.get("SIGMA_REF_NEPS", "1201"))
            p_grid, _ = build_sigma_p_grid(
                0.0, p_max, n_p, "linear",
                mu_internal=mu_internal, k_ext=kval, q_feature=float("nan"),
                feature_half_width=0.0, feature_n_local=1, feature_mode="none",
                tail_start=float("nan"), tail_n=0,
            )
            phi_grid = np.linspace(0.0, np.pi, n_phi, endpoint=False)
            eps_grid = np.linspace(-260.0, 260.0, n_eps)
            internal_a = eval_internal(p_grid[:, None], eps_grid[None, :])
            for start in range(0, omega_target.size, chunk):
                stop = min(start + chunk, omega_target.size)
                row[start:stop] = compute_im_sigma_scan_at_k_from_table(
                    omega_target[start:stop],
                    k_ext=float(kval),
                    p_grid=p_grid,
                    eps_grid=eps_grid,
                    phi_grid=phi_grid,
                    temperature=0.0,
                    internal_a=internal_a,
                    q_axis_pair=pair_q,
                    omega_axis_pair=pair_omega,
                    a_pair_table=pair_a,
                    qp_subtraction="none",
                )
            row, positive_count, positive_max, pos_l1, neg_l1 = (
                _apply_im_sigma_sign_policy(row, omega_target)
            )
            return row_index, row, positive_count, positive_max, pos_l1, neg_l1
        for start in range(0, omega_target.size, chunk):
            stop = min(start + chunk, omega_target.size)
            row[start:stop] = _pair_native_row_dispatch(
                omega_target[start:stop],
                kv=float(kval),
                q_axis_pair=pair_q,
                omega_axis_pair=pair_omega,
                a_pair=pair_a,
                eval_internal=eval_internal,
                n_theta=int(n_theta),
                p_int_max=p_int_max,
                tail_cell_max=float(os.environ.get("SIGMA_PN_TAILCELL", "0.02")),
                qp_tab=qp_tab,
            )
        row, positive_count, positive_max, pos_l1, neg_l1 = (
            _apply_im_sigma_sign_policy(row, omega_target)
        )
        return row_index, row, positive_count, positive_max, pos_l1, neg_l1

    pending = [index for index in range(selected.size) if not done[index]]
    n_workers = max(1, min(int(workers), len(pending))) if pending else 1
    if n_workers > 1:
        print(
            f"[density-clean] Sigma_{spin}: {n_workers} concurrent k workers "
            "(processes)",
            flush=True,
        )
        worker_ctx = {
            "k_sparse": k_sparse,
            "omega_target": omega_target,
            "chunk": chunk,
            "cube": {
                "k": np.asarray(cube["k"]),
                "w": np.asarray(cube["w"]),
                "a": np.asarray(cube["a"]),
                "res": np.asarray(cube["res"]),
                "ims": np.asarray(cube["ims"]),
                "sigma0": float(cube["sigma0"]),
                "eta": float(cube["eta"]),
            },
            "mu_internal": mu_internal,
            "pair_q": pair_q,
            "pair_omega": pair_omega,
            "pair_a": pair_a,
            "n_theta": int(n_theta),
            "qp_tab": qp_tab,
        }
        with ProcessPoolExecutor(
            max_workers=n_workers,
            initializer=_sigma_worker_init,
            initargs=(worker_ctx,),
        ) as pool:
            futures = {
                pool.submit(_sigma_compute_row_worker, index): index
                for index in pending
            }
            for future in as_completed(futures):
                (
                    row_index, row, positive_count, positive_max,
                    pos_l1, neg_l1,
                ) = future.result()
                im_sparse[row_index] = row
                positive_counts[row_index] = positive_count
                positive_maxima[row_index] = positive_max
                positive_l1[row_index] = pos_l1
                negative_l1[row_index] = neg_l1
                done[row_index] = True
                print(
                    f"[density-clean] Sigma_{spin} completed sparse k "
                    f"{row_index + 1}/{selected.size}: k={k_sparse[row_index]:.6g}",
                    flush=True,
                )
                np.savez_compressed(
                    checkpoint,
                    k_sparse=k_sparse,
                    omega=omega_target,
                    im_sparse=im_sparse,
                    done=done,
                    positive_counts=positive_counts,
                    positive_maxima=positive_maxima,
                    positive_l1=positive_l1,
                    negative_l1=negative_l1,
                )
    else:
        for row_index in pending:
            print(
                f"[density-clean] Sigma_{spin} sparse k "
                f"{row_index + 1}/{selected.size}: k={k_sparse[row_index]:.6g}",
                flush=True,
            )
            (
                row_index, row, positive_count, positive_max,
                pos_l1, neg_l1,
            ) = compute_row(row_index)
            im_sparse[row_index] = row
            positive_counts[row_index] = positive_count
            positive_maxima[row_index] = positive_max
            positive_l1[row_index] = pos_l1
            negative_l1[row_index] = neg_l1
            done[row_index] = True
            np.savez_compressed(
                checkpoint,
                k_sparse=k_sparse,
                omega=omega_target,
                im_sparse=im_sparse,
                done=done,
                positive_counts=positive_counts,
                positive_maxima=positive_maxima,
                positive_l1=positive_l1,
                negative_l1=negative_l1,
            )

    sign_report = checkpoint.with_name(checkpoint.stem + "_sign_audit.txt")
    sign_report.write_text(
        f"policy {os.environ.get('SIGMA_IM_SIGN_POLICY', 'clamp')}\n"
        f"tolerance {float(os.environ.get('SIGMA_IM_SIGN_TOL', '1e-10')):.12e}\n"
        f"raw_positive_points {int(np.sum(positive_counts))}\n"
        f"raw_positive_max {float(np.max(positive_maxima)):.12e}\n"
        f"raw_positive_L1 {float(np.sum(positive_l1)):.12e}\n"
        f"raw_negative_L1 {float(np.sum(negative_l1)):.12e}\n"
        f"raw_positive_relative_L1 "
        f"{float(np.sum(positive_l1))/max(float(np.sum(negative_l1)), 1.0e-300):.12e}\n",
        encoding="ascii",
    )

    im_full = np.empty((k_target.size, omega_target.size), dtype=float)
    _lin = _recon_linear()
    for iw in range(omega_target.size):
        if _lin:
            im_full[:, iw] = np.interp(k_target, k_sparse, im_sparse[:, iw])
        else:
            im_full[:, iw] = PchipInterpolator(
                k_sparse, im_sparse[:, iw], extrapolate=True
            )(k_target)
    return np.minimum(im_full, 0.0)


def pole_aware_rebuild(
    *,
    k: np.ndarray,
    w_base: np.ndarray,
    re_sigma: np.ndarray,
    im_sigma: np.ndarray,
    mu: float,
    mass: float,
    eta: float,
    convention: str,
    occupied_protect_min: float,
    sigma0_mode: str,
    sigma0_density_kmax: float,
    pole_refind_n_local: int,
    density_target: float = np.nan,
    density_contact_tail: bool = False,
    density_contact_override: float = np.nan,
    high_k_contact_start: float = np.nan,
    high_k_contact_delta2: float = np.nan,
    high_k_contact_mu_internal: float = np.nan,
    high_k_contact_eta: float = 1.0e-3,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float]:
    initial_sigma0_mode = str(sigma0_mode)
    if initial_sigma0_mode.strip().lower() == "density" and np.isfinite(
        float(density_target)
    ):
        # The row-local solve below owns the explicit number target.  The
        # legacy base-grid helper assumes target=m*mu/2, which is invalid once
        # the physical chemical potential is allowed to become negative.
        initial_sigma0_mode = "fermi"
    a_base, _, _, sigma0, _ = rebuild_a_from_mixed_sigma_1d(
        k_axis=k,
        w_axis=w_base,
        re_mix=re_sigma,
        im_mix=im_sigma,
        mu_sigma=mu,
        mass=mass,
        eta_g=eta,
        convention=convention,
        sigma0_mode=initial_sigma0_mode,
        sigma0_density_kmax=sigma0_density_kmax,
    )
    poles = find_qp_poles_dyson(
        a_base, re_sigma, w_base, k, mu, mass, sigma0=sigma0
    )
    widths = pole_refind_half_widths_from_im_sigma(
        w_axis=w_base,
        im_sigma=im_sigma,
        poles=poles,
        eta_g=eta,
        min_half_width=0.05,
        width_factor=16.0,
    )
    w_rows = rebuild_omega_per_k(
        w_base,
        poles,
        widths,
        int(pole_refind_n_local),
        zero_protect_half_width=0.20,
        occupied_protect_min=occupied_protect_min,
    )
    has_contact_model = (
        np.isfinite(float(high_k_contact_delta2))
        and np.isfinite(float(high_k_contact_mu_internal))
    )
    if has_contact_model:
        xi_internal_all = np.asarray(k, dtype=float) ** 2 / float(mass) - float(
            high_k_contact_mu_internal
        )
        # The numerical Sigma rows already contain the contact satellite, but
        # the dominant-pole grid does not resolve it.  Add it as a quadrature
        # feature without replacing the numerical Sigma itself.
        for ik in np.flatnonzero(
            (np.asarray(k, dtype=float) >= 3.0)
            & (np.asarray(k, dtype=float) < float(high_k_contact_start) - 1.0e-12)
        ):
            w_rows[ik] = _two_pole_omega_row(
                w_base,
                float(poles[ik]),
                float(widths[ik]),
                -float(xi_internal_all[ik]),
                0.10,
                max(121, int(pole_refind_n_local)),
            )
    contact_rows = (
        np.isfinite(float(high_k_contact_start))
        & np.isfinite(float(high_k_contact_delta2))
        & (np.asarray(k, dtype=float) >= float(high_k_contact_start) - 1.0e-12)
    )
    if np.ndim(contact_rows) and np.any(contact_rows):
        xi_external = np.asarray(k, dtype=float) ** 2 / float(mass) - float(mu)
        xi_internal = np.asarray(k, dtype=float) ** 2 / float(mass) - float(
            high_k_contact_mu_internal
        )
        for ik in np.flatnonzero(contact_rows):
            # eta->0 roots of Dyson with Sigma=Delta2/(omega+xi_internal).
            # They are much more accurate feature centers than an argmax on
            # the sparse shared omega grid.
            b = float(xi_internal[ik] + xi_external[ik] - sigma0)
            discriminant = np.sqrt(b * b + 4.0 * float(high_k_contact_delta2))
            root_positive = 0.5 * (b + discriminant) - float(xi_internal[ik])
            root_occupied = 0.5 * (b - discriminant) - float(xi_internal[ik])
            w_rows[ik] = _two_pole_omega_row(
                w_base,
                root_positive,
                float(widths[ik]),
                root_occupied,
                16.0 * float(high_k_contact_eta),
                max(241, int(pole_refind_n_local)),
            )
    re_rows = interp_pchip(re_sigma, w_base, w_rows)
    im_rows = np.minimum(interp_pchip(im_sigma, w_base, w_rows), 0.0)
    if np.ndim(contact_rows) and np.any(contact_rows):
        for ik in np.flatnonzero(contact_rows):
            x = w_rows[ik] + k[ik] ** 2 / float(mass) - float(
                high_k_contact_mu_internal
            )
            denominator = x * x + float(high_k_contact_eta) ** 2
            re_rows[ik] = float(high_k_contact_delta2) * x / denominator
            im_rows[ik] = (
                -float(high_k_contact_delta2)
                * float(high_k_contact_eta)
                / denominator
            )
    if str(sigma0_mode).strip().lower() == "density":
        # The first density solve happens on w_base inside the production
        # helper.  Sharp occupied poles are integrated on the row-local grid
        # below, so refine the scalar shift against that same final measure.
        target = (
            float(mass) * float(mu) / 2.0
            if not np.isfinite(float(density_target))
            else float(density_target)
        )
        kmax = float(sigma0_density_kmax)
        kmask = np.asarray(k, dtype=float) <= kmax
        if np.count_nonzero(kmask) < 2:
            raise RuntimeError(
                f"row-local sigma0 density closure has fewer than two k nodes below {kmax:g}"
            )

        def row_local_density(shift: float) -> float:
            trial = rebuild_a_from_saved_sigma_grid(
                k_axis=k,
                w_grid=w_rows,
                re_sigma=re_rows,
                im_sigma=im_rows,
                mu_sigma=mu,
                mass=mass,
                eta_g=eta,
                convention=convention,
                sigma0=float(shift),
            )
            nk_trial = occupied_nk(trial, w_rows)
            total, _, _, _ = density_with_contact_tail(
                np.asarray(k)[kmask], nk_trial[kmask], density_contact_tail,
                contact_override=density_contact_override,
                contact_tail_start=(
                    high_k_contact_start
                    if np.isfinite(float(high_k_contact_start))
                    else np.nan
                ),
            )
            return total

        step = 0.02
        lo = float(sigma0) - step
        hi = float(sigma0) + step
        n_lo = row_local_density(lo)
        n_hi = row_local_density(hi)
        for _ in range(30):
            if n_lo <= target:
                break
            step *= 2.0
            lo = float(sigma0) - step
            n_lo = row_local_density(lo)
        step = 0.02
        for _ in range(30):
            if n_hi >= target:
                break
            step *= 2.0
            hi = float(sigma0) + step
            n_hi = row_local_density(hi)
        if not (n_lo <= target <= n_hi):
            raise RuntimeError(
                "row-local sigma0 density closure could not bracket "
                f"target={target:.9g}: n({lo:.9g})={n_lo:.9g}, "
                f"n({hi:.9g})={n_hi:.9g}"
            )
        for _ in range(60):
            mid = 0.5 * (lo + hi)
            n_mid = row_local_density(mid)
            if abs(n_mid - target) <= 1.0e-9:
                lo = hi = mid
                break
            if n_mid < target:
                lo = mid
            else:
                hi = mid
        sigma0 = 0.5 * (lo + hi)
        print(
            f"[density-clean] row-local sigma0 closure: sigma0={sigma0:+.9f} "
            f"density={row_local_density(sigma0):.9f} target={target:.9f}",
            flush=True,
        )
    a_rows = rebuild_a_from_saved_sigma_grid(
        k_axis=k,
        w_grid=w_rows,
        re_sigma=re_rows,
        im_sigma=im_rows,
        mu_sigma=mu,
        mass=mass,
        eta_g=eta,
        convention=convention,
        sigma0=sigma0,
    )
    return a_rows, w_rows, re_rows, im_rows, float(sigma0)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--impi", type=Path, default=DEFAULT_IMPI)
    parser.add_argument(
        "--pair-table",
        type=Path,
        help=(
            "Use an existing proxy-residual pair table instead of rebuilding "
            "the experimental clean smooth-KK pair from --impi."
        ),
    )
    parser.add_argument(
        "--shifted-pair-table",
        type=Path,
        help=(
            "Diagnostic-only input already containing the shifted A_pair. "
            "It is consumed verbatim, without another Thouless shift."
        ),
    )
    parser.add_argument("--seed-root", type=Path, default=DEFAULT_SEEDS)
    parser.add_argument("--seed-up", type=Path)
    parser.add_argument("--seed-down", type=Path)
    parser.add_argument("--pair-sign-guard", choices=("on", "off"), default="on")
    parser.add_argument("--subcritical-delta", type=float, default=0.0)
    parser.add_argument(
        "--thouless-q-mode",
        choices=("qff", "global-max"),
        default="qff",
        help="Choose the raw omega=0 pair row used for the Thouless shift.",
    )
    parser.add_argument(
        "--eta-floor-mode",
        choices=("broad", "exact_zero"),
        default="broad",
        help="Regularization applied when rebuilding the shifted pair table.",
    )
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument(
        "--compute-spins",
        nargs="+",
        choices=("up", "down"),
        default=("up", "down"),
        help=(
            "Sigma channels to recompute. Omitted channels retain their seed "
            "Sigma; useful for spin-resolved convergence audits."
        ),
    )
    parser.add_argument("--sigma-nk", type=int, default=16)
    parser.add_argument(
        "--sigma-k-feature-fraction",
        type=float,
        default=0.0,
        help=(
            "Minimum fraction of sparse Sigma k nodes reserved below "
            "qFF+max(kF_up,kF_down); zero preserves the legacy selector."
        ),
    )
    parser.add_argument("--sigma-nomega", type=int, default=97)
    parser.add_argument("--n-theta", type=int, default=64)
    parser.add_argument("--omega-chunk", type=int, default=16)
    parser.add_argument("--pole-refind-n-local", type=int, default=61)
    parser.add_argument("--k-update-max", type=float, default=np.nan)
    parser.add_argument(
        "--allow-partial-q-support",
        action="store_true",
        help=(
            "Permit Sigma updates beyond q_max-p_int_max using only the available "
            "Q domain. The output reports the internal momentum through which the "
            "domain remains complete; this is an audited diagnostic, not extrapolation."
        ),
    )
    parser.add_argument("--w-update-min", type=float, default=-216.0)
    parser.add_argument("--w-update-max", type=float, default=144.0)
    parser.add_argument("--mix", type=float, nargs="+", default=[0.3, 1.0])
    parser.add_argument(
        "--emit-cube-dir",
        type=Path,
        default=None,
        help="If set, write next-iteration A_komega_{spinup,spindown}_iterNNN.npz cubes here.",
    )
    parser.add_argument(
        "--emit-cube-alpha",
        type=float,
        default=0.2,
        help="Which --mix value's rebuilt cube to emit (must be present in --mix).",
    )
    parser.add_argument("--iteration-index", type=int, default=0)
    parser.add_argument(
        "--sigma0-mode-up", choices=("fermi", "density", "none"), default="fermi"
    )
    parser.add_argument(
        "--sigma0-mode-down", choices=("fermi", "density", "none"), default="fermi"
    )
    parser.add_argument("--target-density-up", type=float, default=np.nan)
    parser.add_argument("--target-density-down", type=float, default=np.nan)
    parser.add_argument(
        "--promote-density-shift-to-mu",
        action="store_true",
        help=(
            "When emitting density-mode cubes, store mu_new=mu_old+shift and "
            "sigma0=0. This preserves the rebuilt A exactly while propagating "
            "the number-equation chemical potential to every next-stage reader."
        ),
    )
    parser.add_argument(
        "--audit-unclosed",
        action="store_true",
        help="Also rebuild each mixed Sigma with sigma0=0 and report its raw number error.",
    )
    parser.add_argument(
        "--sigma0-density-kmax",
        type=float,
        default=np.nan,
        help="k cap for density-mode number closure; default uses the full cube.",
    )
    parser.add_argument(
        "--density-contact-tail",
        action="store_true",
        help=(
            "Include the audited median C/k^4 continuation beyond the last k "
            "row in density closure and reporting. No spectral row is rescaled."
        ),
    )
    parser.add_argument(
        "--high-k-sigma-mode",
        choices=("stale", "pair-contact"),
        default="stale",
        help=(
            "Boundary condition beyond --k-update-max. pair-contact uses the "
            "causal leading UV Sigma from the shifted pair table."
        ),
    )
    parser.add_argument("--high-k-contact-eta", type=float, default=1.0e-3)
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    paths = {
        "up": args.seed_up or args.seed_root / "A_komega_spinup_seed.npz",
        "down": args.seed_down or args.seed_root / "A_komega_spindown_seed.npz",
    }
    seeds = {spin: load_seed(path) for spin, path in paths.items()}
    mu_up_cube = float(seeds["up"]["mu_up"])
    mu_dn_cube = float(seeds["up"]["mu_dn"])
    qff = float(
        np.sqrt(max(mu_up_cube, 0.0)) - np.sqrt(max(mu_dn_cube, 0.0))
    )
    if args.pair_table is not None and args.shifted_pair_table is not None:
        raise ValueError("use only one of --pair-table and --shifted-pair-table")
    if args.shifted_pair_table is not None:
        with np.load(args.shifted_pair_table.resolve()) as saved_pair:
            q = np.asarray(saved_pair["q"], dtype=float)
            omega_pair = np.asarray(saved_pair["omega"], dtype=float)
            a_pair = np.asarray(saved_pair["A_pair"], dtype=float)
            re_pi = np.asarray(saved_pair["RePi"], dtype=float)
            im_pi = np.asarray(saved_pair["ImPi"], dtype=float)
            pair_shift = float(saved_pair["pair_shift"])
            if "pair_q_selected" in saved_pair.files:
                pair_q_selected = float(saved_pair["pair_q_selected"])
            else:
                # A retarded bosonic spectral function is exactly zero at
                # omega=0.  argmax(A_pair[:, 0]) therefore returns q[0], not
                # the channel used to shift this table.  Legacy shifted files
                # did not save that metadata; their physically meaningful
                # fallback is the fixed-mu kF mismatch.
                pair_q_selected = float(qff)
        pair_kind = "pre_shifted_diagnostic"
        clean_pair_path = args.out_dir / "pre_shifted_pair_used.npz"
    elif args.pair_table is not None:
        from fflo.pair_shifted import (
            apply_shift_to_pair_table,
            load_pair_table,
        )

        pair_native = load_pair_table(args.pair_table.resolve())
        q_native = np.asarray(pair_native["q"], dtype=float)
        omega_native = np.asarray(pair_native["omega"], dtype=float)
        re_inv_native = np.asarray(pair_native["ReInvGamma"], dtype=float)
        iw = int(np.argmin(np.abs(omega_native)))
        if args.thouless_q_mode == "global-max":
            iq = int(np.nanargmax(re_inv_native[:, iw]))
        else:
            iq = int(np.argmin(np.abs(q_native - qff)))
        pair_q_selected = float(q_native[iq])
        # PAIR_SHIFT_FIXED: congela l'accoppiamento al valore dato invece di
        # ritararlo a ogni iterazione. Serve a girare il loop a g fisso: vedi
        # il commento in critical_line/pair_shifted.py. Vuoto/assente = schema
        # normale (shift ricalcolato dalla tabella corrente).
        _shift_env = str(os.environ.get("PAIR_SHIFT_FIXED", "")).strip()
        _shift_override = float(_shift_env) if _shift_env else None
        pair_shift = (
            _shift_override
            if _shift_override is not None
            else float(re_inv_native[iq, iw])
        )
        shifted = apply_shift_to_pair_table(
            pair_native,
            pair_q_selected,
            subcritical_delta=float(args.subcritical_delta),
            eta_floor_mode=str(args.eta_floor_mode),
            base_shift_override=_shift_override,
        )
        q = np.asarray(shifted["q"], dtype=float)
        omega_pair = np.asarray(shifted["omega"], dtype=float)
        a_pair = np.asarray(shifted["A_pair"], dtype=float)
        re_pi = np.asarray(shifted.get("RePi", pair_native["RePi"]), dtype=float)
        im_pi = np.asarray(shifted.get("ImPi", pair_native["ImPi"]), dtype=float)
        pair_kind = "proxy_residual"
        clean_pair_path = args.out_dir / "proxy_pair_pinned.npz"
    else:
        q, omega_pair, a_pair, pair_shift, re_pi, im_pi = build_clean_smooth_pair(
            args.impi,
            qff,
            2.0e-3,
            sign_guard=args.pair_sign_guard == "on",
            subcritical_delta=float(args.subcritical_delta),
        )
        pair_kind = "clean_smooth_kk"
        clean_pair_path = args.out_dir / "clean_smooth_pair_pinned.npz"
        pair_q_selected = float(qff)
    np.savez_compressed(
        clean_pair_path,
        q=q,
        omega=omega_pair,
        A_pair=a_pair,
        RePi=re_pi,
        ImPi=im_pi,
        pair_shift=np.array(pair_shift),
        pair_q_selected=np.array(pair_q_selected),
    )
    pair_delta2, pair_contact = pair_contact_from_shifted_table(q, omega_pair, a_pair)
    print(
        f"[density-clean] shifted-pair contact: Delta_inf^2={pair_delta2:.12g} "
        f"C={pair_contact:.12g}",
        flush=True,
    )

    k = np.asarray(seeds["up"]["k"], dtype=float)
    w_base = np.asarray(seeds["up"]["w_base"], dtype=float)
    mass = float(seeds["up"]["mass"])
    eta = float(seeds["up"]["eta"])
    convention = str(seeds["up"]["convention"])
    sigma0_density_kmax = (
        float(k[-1])
        if not np.isfinite(args.sigma0_density_kmax)
        else float(args.sigma0_density_kmax)
    )
    physics = Physics(eps0=1.0, mu_up=mu_up_cube, mu_down=mu_dn_cube, mass=mass, pmf_scale=0.0)
    target = {
        "up": (
            0.5 * mu_up_cube
            if not np.isfinite(args.target_density_up)
            else float(args.target_density_up)
        ),
        "down": (
            0.5 * mu_dn_cube
            if not np.isfinite(args.target_density_down)
            else float(args.target_density_down)
        ),
    }

    sigma_p_int_max = float(os.environ.get("SIGMA_PN_PINTMAX", "6.0"))
    q_safe = float(q[-1] - sigma_p_int_max)
    if args.allow_partial_q_support:
        requested_k_max = float(k[-1]) if not np.isfinite(args.k_update_max) else float(args.k_update_max)
        k_update_max = min(requested_k_max, float(k[-1]))
    else:
        k_update_max = q_safe if not np.isfinite(args.k_update_max) else min(
            float(args.k_update_max), q_safe
        )
    complete_internal_p = max(0.0, float(q[-1]) - k_update_max)
    k_mask = k <= k_update_max + 1.0e-12
    w_mask = (
        (w_base >= float(args.w_update_min) - 1.0e-12)
        & (w_base <= float(args.w_update_max) + 1.0e-12)
    )
    print(
        f"[density-clean] safe update k<= {k_update_max:.6g} "
        f"({k_mask.sum()}/{k.size}), omega=[{w_base[w_mask][0]:.6g},"
        f"{w_base[w_mask][-1]:.6g}] ({w_mask.sum()}/{w_base.size})",
        flush=True,
    )
    if args.allow_partial_q_support and k_update_max > q_safe + 1.0e-12:
        print(
            "[density-clean] PARTIAL Q SUPPORT: "
            f"at k={k_update_max:.6g}, all angular configurations are represented "
            f"only through internal p={complete_internal_p:.6g}; "
            "larger-p configurations are partially clipped by q_max",
            flush=True,
        )

    old_sigma = {spin: load_cube_sigma(path) for spin, path in paths.items()}
    fresh = {}
    mu_external = {"up": mu_up_cube, "down": mu_dn_cube}
    internal_path = {"up": paths["down"], "down": paths["up"]}
    w_update = w_base[w_mask]
    n_sigma_omega = min(int(args.sigma_nomega), w_update.size)
    w_eval_indices = np.unique(
        np.round(np.linspace(0, w_update.size - 1, n_sigma_omega)).astype(int)
    )
    w_eval = w_update[w_eval_indices]
    print(
        f"[density-clean] adaptive Sigma omega grid: {w_eval.size}/{w_update.size} nodes",
        flush=True,
    )
    for spin in args.compute_spins:
        print(f"[density-clean] computing Sigma_{spin}", flush=True)
        im_eval = memory_safe_im_sigma(
            spin=spin,
            cube=seeds["down" if spin == "up" else "up"],
            pair_q=q,
            pair_omega=omega_pair,
            pair_a=a_pair,
            k_target=k[k_mask],
            omega_target=w_eval,
            physics=physics,
            qff=pair_q_selected,
            sigma_nk=int(args.sigma_nk),
            sigma_k_feature_fraction=float(args.sigma_k_feature_fraction),
            n_theta=int(args.n_theta),
            omega_chunk=int(args.omega_chunk),
            workers=int(args.workers),
            checkpoint=args.out_dir / f"imsigma_{spin}_checkpoint.npz",
        )
        from scipy.interpolate import PchipInterpolator

        im_sub = np.empty((im_eval.shape[0], w_update.size), dtype=float)
        _lin = _recon_linear()
        for ik in range(im_eval.shape[0]):
            if _lin:
                im_sub[ik] = np.interp(w_update, w_eval, im_eval[ik])
            else:
                im_sub[ik] = PchipInterpolator(
                    w_eval, im_eval[ik], extrapolate=False
                )(w_update)
        im_sub = np.minimum(im_sub, 0.0)
        old_re, old_im = old_sigma[spin]
        full_im = np.array(old_im, copy=True)
        full_im[np.ix_(k_mask, w_mask)] = im_sub
        mu_internal = mu_dn_cube if spin == "up" else mu_up_cube
        if args.high_k_sigma_mode == "pair-contact":
            high_k_mask = k >= k_update_max - 1.0e-12
            x = w_base[None, :] + k[high_k_mask, None] ** 2 / mass - mu_internal
            full_im[high_k_mask] = (
                -pair_delta2 * float(args.high_k_contact_eta)
                / (x * x + float(args.high_k_contact_eta) ** 2)
            )
        full_im = np.minimum(full_im, 0.0)
        # 2026-09-17: ImSigma has a slow ~1/ln^2(omega) pair-continuum UV tail
        # (documented in project memory `project_sigma_kk_tail.md`) that a plain
        # KK on a FINITE window handles poorly -- confirmed directly on a clean
        # Lorentzian-seed run: ImSigma_down at the omega-window edge (|w|=110)
        # was still ~20-45% of its peak value, and every row's sum rule
        # int A(k,w) domega sat at a small but uniform ~+0.5% excess across
        # nearly all k (not localized to any one k), consistent with a
        # systematically mishandled slow tail rather than a k-local bug.
        # `kk_sigma_gamma_asymptote` (already implemented and validated
        # elsewhere in this codebase, in
        # true_akw_pipeline/run_lorentzian_self_consistency_fixed_mu.py, but
        # never wired into this script) removes the analytic
        # n_internal*Gamma(k,omega) high-frequency asymptote before the KK
        # step, leaving only a fast-decaying (~omega^-1.6) residual to
        # transform numerically. n_internal ("opposite-spin occupation") is
        # the coefficient of the leading UV term of the Sigma diagram's own
        # high-frequency expansion -- a fixed, standard-normalization
        # quantity from that specific diagram (mu_internal/(4*pi)), NOT the
        # same thing as this script's own OUTPUT density convention
        # (mu/2). Tried substituting mu_internal/2 here on the (wrong)
        # assumption the two should match this script's density convention:
        # catastrophic (n_down blew up to +586%, per-row sum rules ranged
        # 0.005-1.87) -- confirms mu_internal/(4*pi) is the correct
        # diagrammatic coefficient for THIS asymptote, independent of the
        # separate reporting convention used elsewhere. Reverted to
        # mu_internal/(4*pi), matching the validated reference
        # implementation exactly.
        # 2026-09-17: default kept OFF ("legacy") -- both attempted
        # n_internal normalizations (mu/2 and the "correct" mu/(4*pi))
        # produced CATASTROPHIC per-row breakage (n_down +586% and +111%
        # respectively, individual row sum rules ranging 0.02-4.12) from a
        # genuine pole in the analytic Gamma(k,omega) asymptote at
        # omega* = k^2/2 - mu_up - mu_dn - eps0, which falls inside the data
        # window and hits specific external k rows hard. The reference
        # implementation in run_lorentzian_self_consistency_fixed_mu.py
        # presumably handles this some way not yet understood/replicated
        # here -- do NOT enable by default until that is understood; only
        # opt in explicitly (SIGMA_KK_MODE=gamma_asymptote) for further
        # isolated investigation, never for a real Picard run.
        sigma_kk_mode = str(os.environ.get("SIGMA_KK_MODE", "legacy")).strip().lower()
        if sigma_kk_mode == "gamma_asymptote":
            eps0_row = float(physics.eps0)
            eta_gamma_row = float(os.environ.get("SIGMA_KK_ETA_GAMMA", "0.002"))
            n_internal_row = float(mu_internal) / (4.0 * np.pi)
            full_re = np.empty_like(full_im)
            for irow, kv in enumerate(k):
                full_re[irow] = kk_sigma_gamma_asymptote(
                    w_base, full_im[irow],
                    k_ext=float(kv), eps0=eps0_row,
                    mu_up=float(mu_up_cube), mu_dn=float(mu_dn_cube),
                    eta_gamma=eta_gamma_row, n_internal=n_internal_row,
                    kk_pad=0.0, kk_oversample=1.0, kk_n_max=None,
                )
        elif sigma_kk_mode == "log_tail":
            # 2026-09-17: SAFE alternative to gamma_asymptote.  Confirmed on
            # real checkpoint data that ImSigma's ~1/ln^2 UV tail lives
            # EXCLUSIVELY on the omega>0 side (Im at the omega=-110 edge is
            # exactly 0.0 on every row; only the omega=+110 edge carries the
            # slow tail) -- consistent with the branch-cut structure of
            # g0_inverse(w)=-(1/8pi)ln((k^2/2-mu_up-mu_dn-w-i*eta)/eps0),
            # whose Im part is a finite constant as w->+inf (giving the
            # Im(Gamma)~-8*pi^2*n_internal/ln^2((w-B)/eps0) tail) but ->0 as
            # w->-inf (no branch-cut crossing on that side).
            #
            # Rather than subtracting this analytic asymptote POINTWISE
            # before the KK (the gamma_asymptote approach, which failed:
            # the resonance in Gamma at omega*=B+eps0 is narrower than the
            # sparse omega grid and aliases catastrophically when
            # point-sampled), this adds a POST-HOC closed-form correction to
            # the already-computed "legacy" Re(w) for the missing
            # int_{Omega}^{inf} contribution of the tail beyond the data
            # window.  This never touches any interior grid point or
            # evaluates Gamma near its pole -- it only needs the tail's
            # amplitude, read off from the real measured boundary value
            # im_sigma(k, w=+Omega), and integrates the model tail
            # -A/ln^2((w-B)/eps0) from Omega to infinity exactly (quad, no
            # small-nu/Omega Taylor truncation). Validated on a synthetic
            # two-sided log-tail model against a brute-force reference KK:
            # closed-form leading-order version matched to 0.6%, 99.4% error
            # reduction vs doing nothing; this uses the full quad integral
            # (strictly more accurate, no B/Omega truncation at all).
            from scipy import integrate as _sp_integrate

            eps0_row = float(os.environ.get("SIGMA_KK_EPS0", physics.eps0))
            full_re = np.asarray(
                [kk_re_pv_linear(w_base, row) for row in full_im], dtype=float
            )
            omega_hi = float(w_base[-1])
            omega_lo = float(w_base[0])
            tiny = 1.0e-10

            def _tail_delta(im_edge: float, omega_edge: float, sign: float, b_row: float) -> float:
                if abs(im_edge) < tiny:
                    return 0.0
                shifted_edge = sign * omega_edge - b_row
                if shifted_edge <= eps0_row * (1.0 + tiny):
                    return 0.0
                ln_edge = np.log(shifted_edge / eps0_row)
                if ln_edge <= tiny:
                    return 0.0
                amp = -im_edge * ln_edge * ln_edge  # calibrate A from boundary

                def integrand(w: float) -> float:
                    shifted = sign * w - b_row
                    return (-amp / np.log(shifted / eps0_row) ** 2) / (sign * w)

                val, _ = _sp_integrate.quad(integrand, omega_edge, np.inf, limit=500)
                return val / np.pi

            # 2026-09-17 (later): a HARD on/off exclusion near kF (skip the
            # correction entirely for rows within a radius of kF) was tried
            # and made things dramatically WORSE (alpha_0.3 gap_down +1.33%
            # -> +17.8%, alpha_1 -12.8% -> +24.9%) -- the delta(k) correction
            # already varies smoothly with k (through B(k)=k^2/2-mu_up-mu_dn),
            # so suddenly zeroing it at one row while neighbors keep their
            # full value introduces a genuine k-DISCONTINUITY in Re(Sigma(k))
            # right at kF, which is far worse than the uniform correction it
            # replaced (same "razor-blade near a sparse node" disease class
            # as every other bug this session). A smooth cubic-smoothstep
            # taper (SIGMA_KK_LOGTAIL_KF_TAPER) was tried too and STILL made
            # things worse (alpha_0.3 +5.68%, alpha_1 +13.27%, crossing zero)
            # -- a per-row-varying correction of ANY shape near kF perturbs
            # the local pole structure there, and the downstream
            # pole-refind/density-integral machinery is not tolerant of that.
            #
            # Root-cause reframing (user's insight, 2026-09-17): sigma0 =
            # Re(Sigma(kF_bare, 0)) is subtracted UNIFORMLY from every k-row
            # (see rebuild_a_from_mixed_sigma_1d's fermi/density branches).
            # The pipeline's OWN existing comment there documents that a bias
            # in sigma0 feeds the density DIRECTLY and uniformly
            # (dn ~ -delta_sigma0/2 per spin). Since a GLOBAL constant shift
            # of the WHOLE re_mix array (same value at every k, every omega)
            # changes sigma0 by exactly that constant while leaving the
            # RELATIVE k,omega structure of Re(Sigma) completely untouched,
            # applying ONE tail correction (evaluated at k=kF_bare only) to
            # EVERY row equally is a pure sigma0 correction -- no k-dependent
            # pole perturbation at all, unlike every variant above.
            log_tail_global = str(
                os.environ.get("SIGMA_KK_LOGTAIL_GLOBAL", "0")
            ).strip().lower() not in {"0", "false", "no", "off"}
            if log_tail_global:
                kf_bare = float(
                    np.sqrt(max(mu_dn_cube if spin == "down" else mu_up_cube, 0.0))
                )
                b_bare = kf_bare * kf_bare / 2.0 - float(mu_up_cube) - float(mu_dn_cube)
                im_edge_pos_bare = float(np.interp(kf_bare, k, full_im[:, -1]))
                im_edge_neg_bare = float(np.interp(kf_bare, k, full_im[:, 0]))
                delta_sigma0 = _tail_delta(im_edge_pos_bare, omega_hi, 1.0, b_bare)
                delta_sigma0 += _tail_delta(im_edge_neg_bare, -omega_lo, -1.0, b_bare)
                print(
                    f"[density-clean] log_tail_global spin={spin} kf_bare={kf_bare:.6f} "
                    f"delta_sigma0={delta_sigma0:+.6f}",
                    flush=True,
                )
                full_re += delta_sigma0
            else:
                kf_taper_width = float(os.environ.get("SIGMA_KK_LOGTAIL_KF_TAPER", "0.0"))
                kf_down_row = float(np.sqrt(max(mu_dn_cube, 0.0)))
                kf_up_row = float(np.sqrt(max(mu_up_cube, 0.0)))

                def _kf_weight(kv: float) -> float:
                    if kf_taper_width <= 0.0:
                        return 1.0
                    dist = min(abs(kv - kf_down_row), abs(kv - kf_up_row))
                    if dist >= kf_taper_width:
                        return 1.0
                    if dist <= 0.0:
                        return 0.0
                    t = dist / kf_taper_width
                    return float(3.0 * t * t - 2.0 * t * t * t)

                for irow, kv in enumerate(k):
                    kf_weight = _kf_weight(float(kv))
                    if kf_weight <= 0.0:
                        continue
                    b_row = float(kv) * float(kv) / 2.0 - float(mu_up_cube) - float(mu_dn_cube)
                    delta = _tail_delta(float(full_im[irow, -1]), omega_hi, 1.0, b_row)
                    delta += _tail_delta(float(full_im[irow, 0]), -omega_lo, -1.0, b_row)
                    full_re[irow, :] += kf_weight * delta
        elif sigma_kk_mode == "log_tail_extend":
            # 2026-09-17 (later still): every variant above PATCHES the
            # already-computed "legacy" Re(w) after the fact (a constant or
            # near-constant additive correction). None of them gave a clean
            # improvement -- worst case they introduce a k-discontinuity
            # (hard exclusion) or are a provable no-op (uniform/global,
            # exactly cancelled by the sigma0 Fermi pin: sigma0 shifted by
            # -0.28 to -0.92 in testing yet the density gap did not move
            # past the 4th decimal, confirming Re(Sigma)-sigma0 is invariant
            # under any k,omega-UNIFORM shift by construction).
            #
            # Different mechanism: instead of patching the OUTPUT, extend
            # the INPUT array handed to kk_re_pv_linear with real
            # geometrically-spaced sample points of the calibrated analytic
            # tail model, from the data edge (+-Omega) out to a large but
            # finite cutoff. The ordinary PV-KK machinery then produces a
            # genuinely omega-DEPENDENT Re(Sigma) correction (decaying away
            # from omega=0 like any real KK contribution, not a flat
            # offset), and feeds it through sigma0/pole-refind exactly like
            # any other Re(Sigma) -- no special-casing, no k-discontinuity,
            # because every row is extended by the same recipe and the
            # result is just a normal (if slightly more accurate) Re(Sigma).
            # Does NOT claim to capture the exact infinite-window integral
            # (the log-tail converges too slowly for any finite cutoff to be
            # exact -- log(1e4)/log(110) is only ~2x, not >>1) -- this tests
            # whether getting the near-field OMEGA-SHAPE right (rather than
            # the far-field exact total) is enough to behave well.
            eps0_row = float(os.environ.get("SIGMA_KK_EPS0", physics.eps0))
            w_max_extend = float(os.environ.get("SIGMA_KK_LOGTAIL_WMAX", "1.0e4"))
            n_extend = int(os.environ.get("SIGMA_KK_LOGTAIL_NEXT", "60"))
            omega_hi = float(w_base[-1])
            omega_lo = float(w_base[0])
            tiny = 1.0e-10
            full_re = np.empty_like(full_im)
            for irow, kv in enumerate(k):
                b_row = float(kv) * float(kv) / 2.0 - float(mu_up_cube) - float(mu_dn_cube)
                pieces_w = [w_base]
                pieces_im = [full_im[irow]]

                im_edge_pos = float(full_im[irow, -1])
                shifted_edge_pos = omega_hi - b_row
                if abs(im_edge_pos) >= tiny and shifted_edge_pos > eps0_row * (1.0 + tiny):
                    ln_edge = np.log(shifted_edge_pos / eps0_row)
                    if ln_edge > tiny:
                        amp = -im_edge_pos * ln_edge * ln_edge
                        w_ext = np.geomspace(omega_hi * 1.001, w_max_extend + b_row, n_extend)
                        shifted = w_ext - b_row
                        im_ext = -amp / np.log(shifted / eps0_row) ** 2
                        pieces_w.append(w_ext)
                        pieces_im.append(im_ext)

                im_edge_neg = float(full_im[irow, 0])
                shifted_edge_neg = -omega_lo - b_row
                if abs(im_edge_neg) >= tiny and shifted_edge_neg > eps0_row * (1.0 + tiny):
                    ln_edge = np.log(shifted_edge_neg / eps0_row)
                    if ln_edge > tiny:
                        amp = -im_edge_neg * ln_edge * ln_edge
                        w_ext = -np.geomspace(-omega_lo * 1.001, w_max_extend + b_row, n_extend)
                        shifted = -w_ext - b_row
                        im_ext = -amp / np.log(shifted / eps0_row) ** 2
                        pieces_w.insert(0, w_ext[::-1])
                        pieces_im.insert(0, im_ext[::-1])

                if len(pieces_w) == 1:
                    full_re[irow] = kk_re_pv_linear(w_base, full_im[irow])
                    continue
                ext_w = np.concatenate(pieces_w)
                ext_im = np.concatenate(pieces_im)
                order = np.argsort(ext_w)
                ext_w = ext_w[order]
                ext_im = ext_im[order]
                ext_re = kk_re_pv_linear(ext_w, ext_im)
                base_start = np.searchsorted(ext_w, w_base[0])
                full_re[irow] = ext_re[base_start:base_start + w_base.size]
        else:
            full_re = np.asarray(
                [kk_re_pv_linear(w_base, row) for row in full_im], dtype=float
            )
        fresh[spin] = (full_re, full_im)

    for spin in ("up", "down"):
        if spin not in fresh:
            fresh[spin] = old_sigma[spin]

    results: dict[str, dict[str, np.ndarray | float]] = {}
    raw_rebuild: dict[str, dict[str, tuple]] = {}
    unclosed_results: dict[str, dict[str, np.ndarray | float]] = {}
    for label, alpha in [("seed", None)] + [
        (f"alpha_{value:g}", float(value)) for value in args.mix
    ]:
        results[label] = {}
        raw_rebuild[label] = {}
        for spin in ("up", "down"):
            if alpha is None:
                a = np.asarray(seeds[spin]["a"], dtype=float)
                w = np.asarray(seeds[spin]["w"], dtype=float)
                re_rows = np.empty_like(a)
                im_rows = np.empty_like(a)
                sigma0 = np.nan
            else:
                old_re, old_im = old_sigma[spin]
                fresh_re, fresh_im = fresh[spin]
                re_mix = (1.0 - alpha) * old_re + alpha * fresh_re
                im_mix = np.minimum(
                    (1.0 - alpha) * old_im + alpha * fresh_im, 0.0
                )
                a, w, re_rows, im_rows, sigma0 = pole_aware_rebuild(
                    k=k,
                    w_base=w_base,
                    re_sigma=re_mix,
                    im_sigma=im_mix,
                    mu=mu_external[spin],
                    mass=mass,
                    eta=eta,
                    convention=convention,
                    occupied_protect_min=-102.0,
                    sigma0_mode=(
                        args.sigma0_mode_up if spin == "up" else args.sigma0_mode_down
                    ),
                    sigma0_density_kmax=sigma0_density_kmax,
                    density_target=target[spin],
                    pole_refind_n_local=int(args.pole_refind_n_local),
                    density_contact_tail=bool(args.density_contact_tail),
                    density_contact_override=pair_contact,
                    high_k_contact_start=(
                        k_update_max if args.high_k_sigma_mode == "pair-contact" else np.nan
                    ),
                    high_k_contact_delta2=(
                        pair_delta2 if args.high_k_sigma_mode == "pair-contact" else np.nan
                    ),
                    high_k_contact_mu_internal=(
                        mu_dn_cube if spin == "up" else mu_up_cube
                    ),
                    high_k_contact_eta=float(args.high_k_contact_eta),
                )
            nk = occupied_nk(a, w)
            sums = row_sum_rule(a, w)
            density_total, density_captured, density_tail, contact = density_with_contact_tail(
                k, nk, bool(args.density_contact_tail),
                contact_override=pair_contact,
                contact_tail_start=(
                    k_update_max if args.high_k_sigma_mode == "pair-contact" else np.nan
                ),
            )
            results[label][f"nk_{spin}"] = nk
            results[label][f"sum_{spin}"] = sums
            results[label][f"density_{spin}"] = density_total
            results[label][f"density_captured_{spin}"] = density_captured
            results[label][f"density_tail_{spin}"] = density_tail
            results[label][f"contact_{spin}"] = contact
            results[label][f"sigma0_{spin}"] = sigma0
            raw_rebuild[label][spin] = (a, w, re_rows, im_rows, sigma0)
            if args.audit_unclosed and alpha is not None:
                unclosed_label = f"{label}_unclosed"
                unclosed_results.setdefault(unclosed_label, {})
                a_u, w_u, *_ = pole_aware_rebuild(
                    k=k,
                    w_base=w_base,
                    re_sigma=re_mix,
                    im_sigma=im_mix,
                    mu=mu_external[spin],
                    mass=mass,
                    eta=eta,
                    convention=convention,
                    occupied_protect_min=-102.0,
                    sigma0_mode="none",
                    sigma0_density_kmax=sigma0_density_kmax,
                    pole_refind_n_local=int(args.pole_refind_n_local),
                    density_contact_tail=bool(args.density_contact_tail),
                    density_contact_override=pair_contact,
                )
                nk_u = occupied_nk(a_u, w_u)
                density_total, density_captured, density_tail, contact = density_with_contact_tail(
                    k, nk_u, bool(args.density_contact_tail),
                    contact_override=pair_contact,
                    contact_tail_start=(
                        k_update_max if args.high_k_sigma_mode == "pair-contact" else np.nan
                    ),
                )
                unclosed_results[unclosed_label][f"nk_{spin}"] = nk_u
                unclosed_results[unclosed_label][f"sum_{spin}"] = row_sum_rule(a_u, w_u)
                unclosed_results[unclosed_label][f"density_{spin}"] = density_total
                unclosed_results[unclosed_label][f"density_captured_{spin}"] = density_captured
                unclosed_results[unclosed_label][f"density_tail_{spin}"] = density_tail
                unclosed_results[unclosed_label][f"contact_{spin}"] = contact
                unclosed_results[unclosed_label][f"sigma0_{spin}"] = 0.0

    results.update(unclosed_results)

    if args.emit_cube_dir is not None:
        emit_label = f"alpha_{args.emit_cube_alpha:g}"
        if emit_label not in raw_rebuild:
            raise ValueError(
                f"--emit-cube-alpha {args.emit_cube_alpha} was not among --mix {args.mix}"
            )
        args.emit_cube_dir.mkdir(parents=True, exist_ok=True)
        promoted_mu = None
        if args.promote_density_shift_to_mu:
            if (args.sigma0_mode_up, args.sigma0_mode_down) != ("density", "density"):
                raise ValueError(
                    "--promote-density-shift-to-mu requires density mode for both spins"
                )
            promoted_mu = {
                "up": mu_up_cube + float(raw_rebuild[emit_label]["up"][4]),
                "down": mu_dn_cube + float(raw_rebuild[emit_label]["down"][4]),
            }
        for spin in ("up", "down"):
            a_new, w_new, re_new, im_new, sigma0_new = raw_rebuild[emit_label][spin]
            src_path = paths[spin]
            cube = dict(np.load(src_path))
            cube["A"] = np.asarray(a_new, dtype=float)
            cube["w"] = np.asarray(w_new, dtype=float)
            cube["w_base"] = np.asarray(w_base, dtype=float)
            cube["ReS"] = np.asarray(re_new, dtype=float)
            cube["ImS"] = np.asarray(im_new, dtype=float)
            if promoted_mu is None:
                cube["sigma0"] = np.array(float(sigma0_new), dtype=np.float64)
            else:
                cube["mu_up"] = np.array(promoted_mu["up"], dtype=np.float64)
                cube["mu_dn"] = np.array(promoted_mu["down"], dtype=np.float64)
                cube["mu_down"] = np.array(promoted_mu["down"], dtype=np.float64)
                cube["sigma0"] = np.array(0.0, dtype=np.float64)
                cube["number_mu_shift_up"] = np.array(
                    promoted_mu["up"] - mu_up_cube, dtype=np.float64
                )
                cube["number_mu_shift_down"] = np.array(
                    promoted_mu["down"] - mu_dn_cube, dtype=np.float64
                )
            cube["mix_alpha"] = np.array(float(args.emit_cube_alpha), dtype=np.float64)
            cube["iteration"] = np.array(int(args.iteration_index), dtype=np.int64)
            cube["pair_delta_inf_squared"] = np.array(pair_delta2, dtype=np.float64)
            cube["pair_contact"] = np.array(pair_contact, dtype=np.float64)
            cube["high_k_sigma_mode"] = np.array(str(args.high_k_sigma_mode))
            cube["high_k_contact_start"] = np.array(k_update_max, dtype=np.float64)
            tag = "spinup" if spin == "up" else "spindown"
            out_path = (
                args.emit_cube_dir
                / f"A_komega_{tag}_iter{int(args.iteration_index):03d}.npz"
            )
            np.savez(out_path, **cube)
            print(f"[density-clean] emitted next-iteration cube: {out_path}", flush=True)

    target_polarization = (target["up"] - target["down"]) / (
        target["up"] + target["down"]
    )
    lines = [
        f"Pair one-shot density diagnostic, P={target_polarization:.6g}, pair={pair_kind}",
        "No row normalization. Row-local pole-refind and row-local omega integration.",
        (
            "Fresh numerical ImSigma inside the safe support rectangle; "
            + (
                "causal pair-contact Sigma outside."
                if args.high_k_sigma_mode == "pair-contact"
                else "stale seed ImSigma outside."
            )
        ),
        "ReSigma is global KK[full ImSigma] before mixing.",
        f"pair_sign_guard {args.pair_sign_guard}",
        f"subcritical_delta {args.subcritical_delta:.12e}",
        f"thouless_q_mode {args.thouless_q_mode}",
        f"eta_floor_mode {args.eta_floor_mode}",
        f"pair_q_selected {pair_q_selected:.12e}",
        f"pair_raw_thouless_shift {pair_shift:+.12e}",
        f"k_update_max {k_update_max:.12g}",
        f"allow_partial_q_support {int(args.allow_partial_q_support)}",
        f"complete_internal_p_at_kmax {complete_internal_p:.12g}",
        f"omega_update {w_base[w_mask][0]:.12g} {w_base[w_mask][-1]:.12g}",
        f"sigma_nk {args.sigma_nk}",
        f"sigma_k_feature_fraction {args.sigma_k_feature_fraction:.12g}",
        f"pole_refind_n_local {args.pole_refind_n_local}",
        f"sigma_p_int_max {sigma_p_int_max:.12g}",
        f"n_theta {args.n_theta}",
        f"compute_spins {' '.join(args.compute_spins)}",
        f"sigma0_mode_up {args.sigma0_mode_up}",
        f"sigma0_mode_down {args.sigma0_mode_down}",
        f"mu_input_up {mu_up_cube:.12g}",
        f"mu_input_down {mu_dn_cube:.12g}",
        f"promote_density_shift_to_mu {int(args.promote_density_shift_to_mu)}",
        f"audit_unclosed {int(args.audit_unclosed)}",
        f"sigma0_density_kmax {sigma0_density_kmax:.12g}",
        f"density_contact_tail {int(args.density_contact_tail)}",
        f"high_k_sigma_mode {args.high_k_sigma_mode}",
        f"high_k_contact_eta {args.high_k_contact_eta:.12e}",
        f"pair_delta_inf_squared {pair_delta2:.12e}",
        f"pair_contact {pair_contact:.12e}",
        f"target_density_up {target['up']:.12g}",
        f"target_density_down {target['down']:.12g}",
    ]

    # Every SIGMA_PN_* / PN_* knob that steers the Sigma engine, with the value
    # actually in force (env override or built-in default). Without this block a
    # run is not reproducible: on 2026-09-21 an identical re-run of
    # gammafix_loop/iter019 -- same pair table, same seed cubes, empty diff on
    # every parameter recorded above -- produced an ImSigma differing by 18% at
    # large k, and the cause could not be identified because none of these was
    # written down anywhere.
    _sigma_env_defaults = {
        "SIGMA_PN_PINTMAX": "6.0",
        "SIGMA_PN_RING": "1",
        "SIGMA_PN_RING_MODE": "legacy",
        "SIGMA_PN_RING_NP_FINE": "2400",
        "SIGMA_PN_ANGLE_MODE": "legacy",
        "SIGMA_RECON_LINEAR": "0",
        "PAIR_SHIFT_FIXED": "",
        "SIGMA_PN_ANGLE_EXACT_CUT": "0",
        "SIGMA_PN_EXACT_ALL_ROOTS": "0",
        "SIGMA_PN_TAILCELL": "0.02",
        "SIGMA_PN_OMEGA_INTEGRATION_MODE": "tail_subdivide",
        "SIGMA_PN_OMEGA_GL_N": "4",
        "SIGMA_PN_Q_INTEGRATION_MODE": "panel_gl",
        "SIGMA_PN_Q_GL_N": "8",
        "SIGMA_PN_Q_REFINE_LEVELS": "0",
        "SIGMA_PN_Q_REFINE_MAX": "inf",
        "SIGMA_PN_Q_GL_LOWK_MAX": "-1",
        "SIGMA_PN_QUADVEC_Q_MAX": "3.0",
        "SIGMA_PN_QUADVEC_EPSABS": "1e-7",
        "SIGMA_PN_QUADVEC_EPSREL": "2e-5",
        "SIGMA_PN_QUADVEC_LIMIT": "1000",
        "SIGMA_PN_QUADVEC_SMALL_K_DIRECT": "1e-3",
        "SIGMA_PN_NTHETA": "96",
        "SIGMA_PN_EXACT_WINDOW_GAMMA": "16",
        "SIGMA_IM_SIGN_POLICY": "clamp",
        "SIGMA_IM_SIGN_TOL": "1e-10",
        "PN_RING_MAX_POLES": "3",
        "IMPI_INTERNAL_REBUILD": "0",
    }
    for _key, _default in _sigma_env_defaults.items():
        _set = _key in os.environ
        lines.append(
            f"env {_key} {os.environ.get(_key, _default)}"
            f" {'(env)' if _set else '(default)'}"
        )
    for _key in sorted(os.environ):
        if (_key.startswith("SIGMA_") or _key.startswith("PN_") or _key.startswith("IMPI_")) \
                and _key not in _sigma_env_defaults:
            lines.append(f"env {_key} {os.environ[_key]} (env,unlisted)")

    lines += [
        "",
        "case n_up gap_up rel_up n_down gap_down rel_down n_total P",
    ]
    for label, values in results.items():
        n_up = float(values["density_up"])
        n_down = float(values["density_down"])
        total = n_up + n_down
        pol = (n_up - n_down) / total
        lines.append(
            f"{label} {n_up:.12f} {n_up-target['up']:+.12f} "
            f"{(n_up-target['up'])/target['up']:+.6%} "
            f"{n_down:.12f} {n_down-target['down']:+.12f} "
            f"{(n_down-target['down'])/target['down']:+.6%} "
            f"{total:.12f} {pol:.9f}"
        )
        for spin in ("up", "down"):
            sums = np.asarray(values[f"sum_{spin}"])
            lines.append(
                f"  tail {label} {spin} "
                f"captured={float(values[f'density_captured_{spin}']):.9f} "
                f"beyond_kmax={float(values[f'density_tail_{spin}']):.9f} "
                f"contact={float(values[f'contact_{spin}']):.9f}"
            )
            lines.append(
                f"  sumrule {label} {spin} median={np.median(sums):.9f} "
                f"mean={np.mean(sums):.9f} min={np.min(sums):.9f} "
                f"max={np.max(sums):.9f}"
            )

    (args.out_dir / "density_summary.txt").write_text(
        "\n".join(lines) + "\n", encoding="ascii"
    )
    save = {"k": k}
    for label, values in results.items():
        for key, value in values.items():
            save[f"{label}_{key}"] = value
    np.savez_compressed(args.out_dir / "density_results.npz", **save)

    try:
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(1, 2, figsize=(12, 4.5), constrained_layout=True)
        colors = {"seed": "0.25", "alpha_0.3": "#d55e00", "alpha_1": "#0072b2"}
        for spin, ax in zip(("up", "down"), axes):
            for label, values in results.items():
                ax.plot(
                    k,
                    values[f"nk_{spin}"],
                    lw=1.5,
                    label=label,
                    color=colors.get(label),
                )
            ax.set_xlim(0.0, 6.0)
            ax.set_ylim(bottom=0.0)
            ax.set_xlabel("k")
            ax.set_ylabel(f"n_{spin}(k)")
            ax.grid(alpha=0.25)
            ax.legend()
        fig.savefig(args.out_dir / "nk_clean_pair_one_shot.png", dpi=180)
        plt.close(fig)
    except ImportError:
        print("[warn] matplotlib not available, skipping nk_clean_pair_one_shot.png", flush=True)

    print("\n".join(lines))
    print(f"saved {args.out_dir}")


if __name__ == "__main__":
    main()
