# =====================================================================
# SLIM copy of true_akw_pipeline/make_true_akw_cubes_feature_grid_poleaware.py
#
# 28 top-level symbols (2039 lines, 92% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   compute_z_at_kf_row, find_dyson_poles_per_k
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   parse_args
#   resolve_mu
#   build_split_axis
#   enrich_with_zero_feature_window
#   merge_omega_log_nodes
#   append_outer_omega_tails
#   append_outer_k_tails
#   allocate_positive_counts
#   build_hybrid_omega_grid
#   build_spin_k_grid_from_xi
#   build_spin_resolved_axes
#   spectral_from_g
#   enforce_retarded_im_sigma
#   configure_backends
#   compute_sigma0_rand
#   build_true_cube_for_spin
#   pole_feature_nodes_from_sigma
#   enrich_omega_grid_with_sigma_poles
#   compute_mstar_ratio_from_poles
#   build_qp_lorentzian_cube
#   build_qp_lorentzian_cube_per_k
#   check_qp_decomposition
#   apply_qp_subtraction
#   _apply_option_c
#   save_cube
#   latest_run_dir
#   newest_matching
#   main
# =====================================================================
#!/usr/bin/env python3
"""Generate spin-up and spin-down true A(k,omega) cubes on feature-aware grids.

Main change versus the Nomega-style builder:
- one common hybrid omega grid, dense near omega=0
- two spin-dependent k grids, each built from xi_sigma = k^2/m - mu_sigma
  so resolution is automatically concentrated near k_F,sigma

The spectral construction stays the same:
  A(k,w) = -C * Im[ 1 / (w - xi_k - Sigma^R(k,w) + i*eta_g) ]
with ImSigma from ``simga_test.imsigma_ret`` and ReSigma from KK reconstruction.

This file follows the simpler grid philosophy requested by the user, but it is
adapted to the current repo backend. The older ``Akw.*`` / ``FFLO_legacy``
modules are not present in this workspace, so we keep the grid logic and wire
it into the existing ``simga_test`` machinery that the rest of the pipeline
already uses.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
import os
from pathlib import Path
import sys

import numpy as np

HERE = Path(__file__).resolve()
REPO = HERE.parent.parent

if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from fflo import sigma_test as st


PRODUCTION = True
OUT_BASE = REPO / "true_akw_pipeline" / "true_akw_cubes_feature_grid"






































def find_dyson_poles_per_k(
    k: np.ndarray,
    w: np.ndarray,
    re_s: np.ndarray,
    *,
    mu_sigma: float,
    mass: float,
    newton_steps: int = 3,
) -> np.ndarray:
    """Return E_qp[ik] = Dyson pole energy per k row (nan if not found).

    Uses linear interpolation for the initial root estimate, then refines
    with Newton steps using a finite-difference estimate of df/domega.
    On the pole-aware omega grid (dense around the pole) this converges fast.
    """
    k_arr = np.asarray(k, dtype=float).reshape(-1)
    w_arr = np.asarray(w, dtype=float).reshape(-1)
    re = np.asarray(re_s, dtype=float)
    nk = k_arr.size
    pole_e = np.full(nk, float("nan"))
    wmin, wmax = float(w_arr[0]), float(w_arr[-1])

    for ik in range(nk):
        xi_k = float(k_arr[ik] ** 2) / float(mass) - float(mu_sigma)
        f = w_arr - xi_k - re[ik]
        finite = np.isfinite(f)
        candidates: list[float] = []
        for j in np.where(finite[:-1] & finite[1:] & (f[:-1] * f[1:] <= 0.0))[0]:
            f0, f1 = float(f[j]), float(f[j + 1])
            w0, w1 = float(w_arr[j]), float(w_arr[j + 1])
            denom = f1 - f0
            root = 0.5 * (w0 + w1) if abs(denom) <= 1.0e-15 else w0 - f0 * (w1 - w0) / denom
            # Newton refinement — uses the dense pole-aware grid for accurate interp
            local_dw = max(float(w_arr[1] - w_arr[0]), 1.0e-10)
            for _ in range(int(newton_steps)):
                re_root = float(np.interp(root, w_arr, re[ik]))
                f_root = root - xi_k - re_root
                re_p = float(np.interp(root + local_dw, w_arr, re[ik]))
                re_m = float(np.interp(root - local_dw, w_arr, re[ik]))
                df = 1.0 - (re_p - re_m) / (2.0 * local_dw)
                if abs(df) < 1.0e-12:
                    break
                root = root - f_root / df
                if not (wmin <= root <= wmax):
                    root = 0.5 * (w0 + w1)
                    break
            if np.isfinite(root) and wmin <= root <= wmax:
                candidates.append(float(root))
        if candidates:
            pole_e[ik] = min(candidates, key=lambda x: abs(float(x) - xi_k))

    return pole_e


def compute_z_at_kf_row(re_s_kf: np.ndarray, w: np.ndarray, pole_e_kf: float) -> float:
    """Z = 1/(1 - dReSigma/domega) evaluated at the k_F QP pole energy."""
    w_arr = np.asarray(w, dtype=float)
    re = np.asarray(re_s_kf, dtype=float)
    target = float(pole_e_kf) if np.isfinite(float(pole_e_kf)) else 0.0
    i0 = int(np.argmin(np.abs(w_arr - target)))
    if 0 < i0 < w_arr.size - 1:
        dw = float(w_arr[i0 + 1] - w_arr[i0 - 1])
        dre = float(re[i0 + 1] - re[i0 - 1])
    elif i0 == 0:
        dw = float(w_arr[1] - w_arr[0])
        dre = float(re[1] - re[0])
    else:
        dw = float(w_arr[-1] - w_arr[-2])
        dre = float(re[-1] - re[-2])
    slope = dre / dw if abs(dw) > 1.0e-15 else 0.0
    denom = 1.0 - slope
    if abs(denom) < 1.0e-6:
        return 0.5
    return float(np.clip(1.0 / denom, 0.05, 1.0))






















