# =====================================================================
# SLIM copy of true_akw_pipeline/make_impi_analytic_cv.py
#
# 10 top-level symbols (647 lines, 82% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   _canonical_qp_fields, _cv_init, _cv_work, _kf
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   _cx_init
#   _cx_work
#   _get
#   _replace
#   _extend_with_decay
#   _qp_fields
#   _residual_cube_audit
#   _load_cube_arrays
#   _run_grid
#   main
# =====================================================================
#!/usr/bin/env python3
"""Two-spin analytic-QP pair bubble (drop-in for make_impi_table.py).

Full decomposition:
    A_up = A_QP_up + A_inc_up       (QP Lorentzian + incoherent remainder)
    A_dn = A_QP_dn + A_inc_dn

    A_up × A_dn = QP×QP  +  QP_up×inc_dn  +  inc_up×QP_dn  +  inc×inc

    ImPi = ImPi_grid(A_inc × A_inc)          [smooth → grid OK]
         + ImPi_analytic(QP_up × QP_dn)      [coherent_impi, closed-form]
         + ImPi_cross(QP_up × A_inc_dn)      [residue: Z_u Φ A_inc_dn(ω-E_u)]
         + ImPi_cross(QP_dn × A_inc_up)      [residue: Z_d Φ A_inc_up(ω-E_d)]

The inc×inc integrand has no razor → the shared eps grid resolves it.
The two cross terms are evaluated analytically via the Lorentzian residue:
    ∫_0^ω dε L_u(ε) A_inc_dn(ω-ε) ≈ Z_u Φ(E_u,Γ_u,ω) A_inc_dn(ω-E_u)
where Φ = [arctan((ω-E)/Γ) + arctan(E/Γ)]/π is the exact Lorentzian fraction.

Same CLI as make_impi_table.py.
"""
from __future__ import annotations
import os, sys, subprocess, tempfile, shutil
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor
import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from fflo.qp_dyson import extract_qp_dyson
from fflo.analytic_bubble import (
    coherent_impi, coherent_impi_kjac, coherent_impi_phipanel,
    _build_a_inc_interpolator, build_row_local_cube_interpolator,
    cross_impi_term,
)
from fflo.qp_cube import build_qp_cube, build_inc_cube, qp_model_from_cube

MAKE_IMPI = str(HERE / "make_impi_table.py")

_CV: dict = {}


def _cv_init(omg, ku, Eu, Zu, Gu, kd, Ed, Zd, Gd, feats, opts):
    _CV.update(dict(omg=omg, ku=ku, Eu=Eu, Zu=Zu, Gu=Gu, kd=kd, Ed=Ed, Zd=Zd, Gd=Gd, feats=feats))
    _CV.update(dict(opts))


def _cv_work(qv):
    g = _CV
    if len(g["ku"]) == 0 or len(g["kd"]) == 0:
        # No valid coherent QP pole anywhere for one spin this iteration
        # (Z/Gamma thresholds rejected every k) -> no coherent x coherent piece.
        return np.zeros(np.asarray(g["omg"], float).size, float)
    mode = str(g.get("angle_mode", "uniform")).strip().lower()
    if mode == "phipanel":
        return coherent_impi_phipanel(
            float(qv), g["omg"], g["ku"], g["Eu"], g["Zu"], g["Gu"],
            g["kd"], g["Ed"], g["Zd"], g["Gd"],
            nk=int(g.get("nk", 700)),
            n_phi_panel=int(g.get("n_phi_panel", 24)),
            phi_panel_chunk_size=int(g.get("phi_panel_chunk_size", 8)),
            phi_feature_half_width=float(g.get("phi_feature_half_width", 0.08)),
            phi_feature_n_local=int(g.get("phi_feature_n_local", 81)),
            kmax=g.get("kmax"),
            gamma_floor=float(g.get("gamma_floor", 1e-3)),
            kf_features=g["feats"],
        )
    if mode == "kjac":
        return coherent_impi_kjac(
            float(qv), g["omg"], g["ku"], g["Eu"], g["Zu"], g["Gu"],
            g["kd"], g["Ed"], g["Zd"], g["Gd"],
            nk=int(g.get("nk", 700)),
            n_kquad=int(g.get("n_kquad", 160)),
            kquad_chunk_size=int(g.get("kquad_chunk_size", 16)),
            kmax=g.get("kmax"),
            gamma_floor=float(g.get("gamma_floor", 1e-3)),
            kf_features=g["feats"],
        )
    return coherent_impi(
        float(qv), g["omg"], g["ku"], g["Eu"], g["Zu"], g["Gu"],
        g["kd"], g["Ed"], g["Zd"], g["Gd"],
        nk=int(g.get("nk", 700)),
        nphi=int(g.get("nphi", 160)), kmax=g.get("kmax"),
        gamma_floor=float(g.get("gamma_floor", 1e-3)),
        kf_features=g["feats"],
    )


# ---------- cross-term parallelism (one (q, cross_id) pair per worker) ----------
_CX: dict = {}














def _canonical_qp_fields(cube_path, model):
    """Return the canonical full-k model shared by every clean term."""
    return (
        np.asarray(model["k"], float),
        np.asarray(model["E"], float),
        np.asarray(model["Z"], float),
        np.asarray(model["G"], float),
        float(model["mu"]),
    )




def _kf(k, E, mu_free=0.0):
    if len(E) == 0:
        # No k passed the (now stricter) validity thresholds at all for this
        # spin/iteration -- fall back to the free-theory kF instead of
        # indexing an empty array. This is only a quadrature feature-placement
        # hint, not core physics, so a coarse fallback here is safe.
        return float(np.sqrt(max(mu_free, 0.0)))
    s = np.where(np.diff(np.sign(E)) != 0)[0]
    if not len(s):
        return float(np.sqrt(np.abs(E[0])))
    j = s[0]
    return float(k[j] - E[j] * (k[j + 1] - k[j]) / (E[j + 1] - E[j]))








