# =====================================================================
# SLIM copy of true_akw_pipeline/compute_convolution_from_adn_table.py
#
# 9 top-level symbols (682 lines, 40% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   _trapz, _trapz_axis, bilinear_eval_with_support, compute_impi_raw_totals_for_slice, compute_impi_scan_from_slice_provider, compute_impi_scan_from_table_vectorized, finalize_impi_scan, g0_constant_from_cutoff, g0_inverse, kk_re_pv_linear, kk_re_with_optional_powerlaw_tail, kk_sigma_gamma_asymptote, load_cube_a_convention, load_cube_physics, normalize_spectral_rows, normalize_spectral_weight, proxy_full_pi_from_gamma, proxy_medium_pi_from_gamma, vacuum_pi_from_cutoff
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   load_akw_cube
#   load_table_source_a_convention
#   collapse_duplicate_omega_slices
#   proxy_pi_from_gamma
#   kk_re_proxy_subtracted
#   kk_re_bare_vacuum_plus_proxy_medium
#   compute_impi_scan_from_table
#   parse_args
#   main
# =====================================================================
#!/usr/bin/env python3
r"""Compute convolution integrals using a precomputed translated A_down table.

Uses:
- precomputed table: A_down_phi_integral(omega, p, eps) = ∫ dphi A_down(...)
- spin-up cube: A_up(k, omega)

At fixed external omega, computes
  I_p_raw(p) = ∫ d eps (f(eps) + f(omega-eps)) A_up(p,eps) A_down_phi_integral(omega,p,eps)

and total radial integral
  I_total_raw = ∫ p dp I_p_raw(p).

Also reports normalized versions:
  I_p_scaled   = I_p_raw / (2pi)^2
  I_total_scaled = I_total_raw / (2pi)^2
  ImPi_est = +pi * I_total_scaled

Additionally splits epsilon contributions:
  I_pos_raw = ∫ p dp ∫_{eps>0}   A_up * A_down_phi_int
  I_neg_raw = ∫ p dp ∫_{eps<0}   A_up * A_down_phi_int
so that (for the thermal integrand):
  I_thermal_raw = I_pos_raw + I_neg_raw
"""

from __future__ import annotations

import argparse
from datetime import datetime
from collections.abc import Callable
from pathlib import Path
import sys

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fflo.proxy import Gamma as analytical_gamma
from fflo.proxy import configuration as analytical_configuration

# --------------------------
# Editable settings
# --------------------------
OMEGA_TARGET = 0.0

P_SAMPLES = [0.5, 0.8, 1.0, 1.2, 1.4]
OUT_BASE = REPO_ROOT / "true_akw_pipeline" / "convolution_from_table_runs"

# Additional output: save the Enss-style inverse-pair reconstruction over omega.
RUN_OMEGA_SCAN = True
OMEGA_SCAN_MIN: float | None = -10.0
OMEGA_SCAN_MAX: float | None = 10.0
ETA_GAMMA = 1.0e-2
KK_PAD = 0.0
KK_OVERSAMPLE = 1.0
KK_MODE = "linear"  # "linear", "proxy_subtracted", or "bare_vacuum_plus_proxy_medium"
KK_USE_FULL_SOURCE = True  # True -> use full available ImPi(omega) as KK source, then crop to scan window
KK_TAIL = "zero"  # "zero" or "hold" extrapolation outside available ImPi support
EPS_INTEGRATION_MODE = "panel_kinks"  # "plain" or "panel_kinks"
ENFORCE_SAFE_SUPPORT = False




def _scalar_from_npz(data: np.lib.npyio.NpzFile, keys: list[str], default: float = np.nan) -> float:
    for k in keys:
        if k in data.files:
            v = np.asarray(data[k]).reshape(-1)
            if v.size > 0:
                return float(v[0])
    return float(default)


def load_cube_physics(path: Path) -> tuple[float, float, float]:
    with np.load(path) as data:
        eps0 = _scalar_from_npz(data, ["eps0", "epsilon_0"], default=np.nan)
        mu_up = _scalar_from_npz(data, ["mu_up"], default=np.nan)
        mu_dn = _scalar_from_npz(data, ["mu_dn", "mu_down"], default=np.nan)
    return float(eps0), float(mu_up), float(mu_dn)


def load_cube_a_convention(path: Path) -> str:
    with np.load(path) as data:
        if "a_convention" not in data.files:
            return "minus2_im"
        val = np.asarray(data["a_convention"]).reshape(-1)
        if val.size == 0:
            return "minus2_im"
        raw = val[0]
        if isinstance(raw, bytes):
            return raw.decode("utf-8", errors="replace")
        return str(raw)


def normalize_spectral_weight(a_vals: np.ndarray, convention: str) -> tuple[np.ndarray, str]:
    conv = str(convention).strip()
    if conv == "minus2_im":
        return np.asarray(a_vals, dtype=float) / (2.0 * np.pi), "minus2_im -> divided by 2pi"
    if conv == "minus1_over_pi_im":
        return np.asarray(a_vals, dtype=float), "minus1_over_pi_im -> unchanged"
    return np.asarray(a_vals, dtype=float), f"{conv or 'unknown'} -> assumed unchanged"


def normalize_spectral_rows(
    a_vals: np.ndarray,
    omega_axis: np.ndarray,
    convention: str,
    *,
    enabled: bool = True,
    row_norm_floor: float = 5.0e-2,
) -> tuple[np.ndarray, str]:
    """Convert A convention and enforce the row sum rule on usable k rows.

    The floor prevents rows with almost no captured spectral support from being
    blown up into fake spectra when the quasiparticle peak lies outside the
    finite omega box. Rows below the floor are left convention-normalized only.
    """
    arr, desc = normalize_spectral_weight(a_vals, convention)
    if not bool(enabled):
        return arr, f"{desc}; row normalization disabled"

    w = np.asarray(omega_axis, dtype=float)
    if arr.ndim != 2 or w.ndim not in (1, 2) or arr.shape[1] != w.shape[-1]:
        raise ValueError(
            "normalize_spectral_rows expects A shape (n_k,n_omega) and matching omega axis; "
            f"got A{arr.shape}, omega{w.shape}"
        )

    if w.ndim == 2:
        row_weight = np.array([np.trapezoid(arr[ik], w[ik]) for ik in range(arr.shape[0])])
    else:
        row_weight = np.trapezoid(arr, w, axis=1)
    floor = float(max(row_norm_floor, 0.0))
    good = np.isfinite(row_weight) & (row_weight > floor)
    out = np.array(arr, dtype=float, copy=True)
    out[good] = out[good] / row_weight[good, None]
    return (
        out,
        f"{desc}; row-normalized {int(np.count_nonzero(good))}/{row_weight.size} rows "
        f"(floor={floor:.3g}, weight min/max={float(np.nanmin(row_weight)):.6g}/{float(np.nanmax(row_weight)):.6g})",
    )




def bilinear_eval_with_support(
    k_query: np.ndarray | float,
    w_query: np.ndarray | float,
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    akw: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Evaluate A(k,ω) at query points via interpolation.

    w_axis may be 1D (shared grid, classic bilinear) or 2D (n_k, n_w) for
    per-k omega grids.  In the 2D case the call pattern is assumed to be
    k_query shape (n_p, 1) and w_query shape (1, n_eps) — i.e. each row of
    k_query uses a single k value for all ε — so we vectorise over ε per row.
    """
    k_ax = np.asarray(k_axis, dtype=float)
    w_ax = np.asarray(w_axis, dtype=float)
    kq = np.asarray(k_query, dtype=float)
    wq = np.asarray(w_query, dtype=float)

    if w_ax.ndim == 1:
        # --- original shared-grid bilinear path ---
        kqb, wqb = np.broadcast_arrays(kq, wq)
        shp = kqb.shape
        kf = kqb.ravel()
        wf = wqb.ravel()

        in_k = (kf >= float(k_ax[0])) & (kf <= float(k_ax[-1]))
        in_w = (wf >= float(w_ax[0])) & (wf <= float(w_ax[-1]))
        inside = in_k & in_w

        out = np.zeros_like(kf, dtype=float)
        if np.any(inside):
            ki = np.searchsorted(k_ax, kf[inside], side="right") - 1
            wi = np.searchsorted(w_ax, wf[inside], side="right") - 1
            ki = np.clip(ki, 0, k_ax.size - 2)
            wi = np.clip(wi, 0, w_ax.size - 2)
            k0 = k_ax[ki]; k1 = k_ax[ki + 1]
            w0 = w_ax[wi]; w1 = w_ax[wi + 1]
            tk = (kf[inside] - k0) / np.maximum(k1 - k0, 1.0e-14)
            tw = (wf[inside] - w0) / np.maximum(w1 - w0, 1.0e-14)
            a00 = akw[ki, wi]; a10 = akw[ki + 1, wi]
            a01 = akw[ki, wi + 1]; a11 = akw[ki + 1, wi + 1]
            out[inside] = (
                (1.0 - tk) * (1.0 - tw) * a00
                + tk * (1.0 - tw) * a10
                + (1.0 - tk) * tw * a01
                + tk * tw * a11
            )
        return out.reshape(shp), inside.reshape(shp)

    # --- per-k omega grid path (w_ax is 2D, shape n_k x n_w) ---
    # Expected call: kq shape (n_p, 1), wq shape (1, n_eps)
    kqb, wqb = np.broadcast_arrays(kq, wq)
    shp = kqb.shape
    n_p, n_eps = shp

    w_lo = w_ax[:, 0]   # per-row lower bound
    w_hi = w_ax[:, -1]  # per-row upper bound

    k_lo, k_hi = float(k_ax[0]), float(k_ax[-1])

    out = np.zeros((n_p, n_eps), dtype=float)
    inside = np.zeros((n_p, n_eps), dtype=bool)

    kf = kqb[:, 0]   # (n_p,)
    wf = wqb[0, :]   # (n_eps,)

    in_k = (kf >= k_lo) & (kf <= k_hi)

    ki = np.searchsorted(k_ax, kf, side="right") - 1
    ki = np.clip(ki, 0, k_ax.size - 2)
    tk = (kf - k_ax[ki]) / np.maximum(k_ax[ki + 1] - k_ax[ki], 1.0e-14)

    # Vectorized (2026-09-20): group query rows by shared k-bucket index
    # instead of looping per row (mirrors the bucketing already used in
    # _rowlocal_bilinear_pairs). Bit-for-bit identical to the previous
    # per-row Python loop, verified on captured production call arguments
    # (see scratchpad gammafix_candidate/verify_fast_bilinear.py); ~3.3-3.6x
    # faster since np.interp is called once per unique bucket instead of
    # once per query point.
    valid_ip = np.flatnonzero(in_k)
    if valid_ip.size:
        ki_valid = ki[valid_ip]
        for index in np.unique(ki_valid):
            rows = valid_ip[ki_valid == index]
            w0 = w_ax[index]
            w1 = w_ax[index + 1]
            in_w = (wf >= max(float(w0[0]), float(w1[0]))) & (wf <= min(float(w0[-1]), float(w1[-1])))
            inside[rows] = in_w
            if not np.any(in_w):
                continue
            cols = np.flatnonzero(in_w)
            a0 = np.interp(wf[cols], w0, akw[index])
            a1 = np.interp(wf[cols], w1, akw[index + 1])
            tk0 = tk[rows][:, None]
            out[np.ix_(rows, cols)] = (1.0 - tk0) * a0[None, :] + tk0 * a1[None, :]

    return out.reshape(shp), inside.reshape(shp)


def fermi_zero_temp(x: np.ndarray | float) -> np.ndarray:
    return (np.asarray(x, dtype=float) < 0.0).astype(float)


def _kernel_kink_tol(eps: np.ndarray | float, omega: float) -> float:
    eps_arr = np.asarray(eps, dtype=float).reshape(-1)
    finite = eps_arr[np.isfinite(eps_arr)]
    if finite.size >= 2:
        diffs = np.diff(np.unique(np.sort(finite)))
        diffs = diffs[diffs > 0.0]
        if diffs.size > 0:
            return max(1.0e-12, 0.25 * float(np.min(diffs)))
    return max(1.0e-12, 1.0e-10 * (1.0 + abs(float(omega))))


def _medium_kernel_scalar_midpoint_zero_temp(eps: float, omega: float) -> float:
    eps_val = float(eps)
    omega_val = float(omega)
    delta = max(1.0e-12, 1.0e-10 * (1.0 + abs(omega_val)))

    def _raw_med(x: float) -> float:
        return float(fermi_zero_temp(x) + fermi_zero_temp(omega_val - x))

    is_zero_kink = np.isclose(eps_val, 0.0, atol=delta, rtol=0.0)
    is_omega_kink = np.isclose(eps_val, omega_val, atol=delta, rtol=0.0)
    if is_zero_kink or is_omega_kink:
        left = _raw_med(eps_val - delta)
        right = _raw_med(eps_val + delta)
        return 0.5 * (left + right)
    return _raw_med(eps_val)


def thermal_kernel_zero_temp(eps: np.ndarray, omega: float) -> np.ndarray:
    eps_arr = np.asarray(eps, dtype=float)
    fe = fermi_zero_temp(eps_arr)
    fwe = fermi_zero_temp(float(omega) - eps_arr)
    med = fe + fwe
    tol = _kernel_kink_tol(eps_arr, float(omega))
    kink_mask = np.isclose(eps_arr, 0.0, atol=tol, rtol=0.0) | np.isclose(
        eps_arr, float(omega), atol=tol, rtol=0.0
    )
    if np.any(kink_mask):
        med = np.asarray(med, dtype=float).copy()
        for idx in np.where(kink_mask)[0]:
            med[idx] = _medium_kernel_scalar_midpoint_zero_temp(float(eps_arr[idx]), float(omega))
    return med - 1.0


def medium_kernel_zero_temp(eps: np.ndarray, omega: float) -> np.ndarray:
    eps_arr = np.asarray(eps, dtype=float)
    fe = fermi_zero_temp(eps_arr)
    fwe = fermi_zero_temp(float(omega) - eps_arr)
    med = fe + fwe
    tol = _kernel_kink_tol(eps_arr, float(omega))
    kink_mask = np.isclose(eps_arr, 0.0, atol=tol, rtol=0.0) | np.isclose(
        eps_arr, float(omega), atol=tol, rtol=0.0
    )
    if np.any(kink_mask):
        med = np.asarray(med, dtype=float).copy()
        for idx in np.where(kink_mask)[0]:
            med[idx] = _medium_kernel_scalar_midpoint_zero_temp(float(eps_arr[idx]), float(omega))
    return med


def impi_prefactor_sign() -> float:
    """Prefactor multiplying I_total_scaled to get ImPi on real frequencies."""
    return +np.pi


def _trapz_axis(y: np.ndarray, x: np.ndarray, axis: int) -> np.ndarray:
    if hasattr(np, "trapezoid"):
        return np.trapezoid(y, x, axis=axis)
    return np.trapz(y, x, axis=axis)  # pragma: no cover


def _trapz(y: np.ndarray, x: np.ndarray) -> float:
    if hasattr(np, "trapezoid"):
        return float(np.trapezoid(y, x))
    return float(np.trapz(y, x))  # pragma: no cover


def _p_gl_panel_integrate(
    p_grid: np.ndarray,
    f_p: np.ndarray,
    split_points: np.ndarray,
    n_gl: int = 8,
) -> float:
    """GL panel quadrature for ∫ f(p) dp, splitting at kink positions.

    f_p is known on the dense p_grid (feature-enriched near the split points).
    GL nodes within each panel are evaluated via linear interpolation on p_grid.
    Splitting at the nesting momentum p*=kF_up-Q and at kF_dn removes the
    Q-dependent discretisation error that causes ReΓ⁻¹(Q,0) jitter.
    """
    p = np.asarray(p_grid, dtype=float)
    f = np.asarray(f_p, dtype=float)
    pts = np.asarray(split_points, dtype=float)
    pts = pts[(pts > p[0]) & (pts < p[-1])]
    # Keep the existing p-grid knots as panel boundaries.  The previous version
    # used only the requested split points, so a low-order GL rule could stride
    # across many sharp p-grid features and miss spectral weight.  Adding the
    # split points to the native knots preserves the ordinary trapezoid result
    # when no extra kink is present, while still allowing exact panel cuts at
    # p*=kF_up-Q or kF_dn when they fall between grid nodes.
    bds = np.unique(np.concatenate([p, pts]))
    xg, wg = np.polynomial.legendre.leggauss(max(2, int(n_gl)))
    total = 0.0
    for i in range(len(bds) - 1):
        a, b = float(bds[i]), float(bds[i + 1])
        if b <= a:
            continue
        mid = 0.5 * (a + b)
        half = 0.5 * (b - a)
        total += half * float(np.dot(wg, np.interp(mid + half * xg, p, f)))
    return total


def compute_impi_raw_totals_for_slice(
    omega_value: float,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    adn_phi_slice: np.ndarray,
    aup_grid: np.ndarray,
    *,
    eps_integration_mode: str = "plain",
    p_integration_mode: str = "plain",
    p_split_points: np.ndarray | None = None,
    p_gl_n: int = 8,
) -> tuple[float, float, float]:
    """Compute raw radial totals for one omega slice."""
    integ_mode = str(eps_integration_mode).strip().lower()
    if integ_mode not in {"plain", "panel_kinks"}:
        raise ValueError("eps_integration_mode must be 'plain' or 'panel_kinks'.")

    prod = aup_grid * adn_phi_slice
    if integ_mode == "panel_kinks":
        i_p_thermal_raw = _trapz_axis_panel_kernel(
            prod,
            eps_grid,
            float(omega_value),
            _thermal_kernel_scalar_zero_temp,
        )
        i_p_med_raw = _trapz_axis_panel_kernel(
            prod,
            eps_grid,
            float(omega_value),
            _medium_kernel_scalar_zero_temp,
        )
    else:
        thermal = thermal_kernel_zero_temp(eps_grid, float(omega_value))
        medium = medium_kernel_zero_temp(eps_grid, float(omega_value))
        i_p_thermal_raw = _trapz_axis((thermal[None, :] * aup_grid) * adn_phi_slice, eps_grid, axis=1)
        i_p_med_raw = _trapz_axis((medium[None, :] * aup_grid) * adn_phi_slice, eps_grid, axis=1)
    i_p_no_thermal_raw = _trapz_axis(prod, eps_grid, axis=1)

    use_gl = (str(p_integration_mode).strip().lower() == "panel_kinks"
              and p_split_points is not None
              and len(np.asarray(p_split_points)) > 0)
    if use_gl:
        _sp = np.asarray(p_split_points, dtype=float)
        return (
            _p_gl_panel_integrate(p_grid, p_grid * i_p_thermal_raw, _sp, p_gl_n),
            _p_gl_panel_integrate(p_grid, p_grid * i_p_no_thermal_raw, _sp, p_gl_n),
            _p_gl_panel_integrate(p_grid, p_grid * i_p_med_raw, _sp, p_gl_n),
        )
    return (
        _trapz(p_grid * i_p_thermal_raw, p_grid),
        _trapz(p_grid * i_p_no_thermal_raw, p_grid),
        _trapz(p_grid * i_p_med_raw, p_grid),
    )


def finalize_impi_scan(
    omega_grid: np.ndarray,
    i_total_thermal_raw: np.ndarray,
    i_total_no_thermal_raw: np.ndarray,
    i_total_med_raw: np.ndarray,
) -> dict[str, np.ndarray]:
    """Convert raw totals into scaled totals and ImPi arrays."""
    i_total_thermal_scaled = np.asarray(i_total_thermal_raw, dtype=float) / ((2.0 * np.pi) ** 2)
    i_total_no_thermal_scaled = np.asarray(i_total_no_thermal_raw, dtype=float) / ((2.0 * np.pi) ** 2)
    i_total_med_scaled = np.asarray(i_total_med_raw, dtype=float) / ((2.0 * np.pi) ** 2)
    im_pi_thermal = impi_prefactor_sign() * i_total_thermal_scaled
    im_pi_no_thermal = -np.pi * i_total_no_thermal_scaled
    im_pi_med = impi_prefactor_sign() * i_total_med_scaled

    return {
        "omega": np.asarray(omega_grid, dtype=float),
        "i_total_thermal_raw": np.asarray(i_total_thermal_raw, dtype=float),
        "i_total_no_thermal_raw": np.asarray(i_total_no_thermal_raw, dtype=float),
        "i_total_med_raw": np.asarray(i_total_med_raw, dtype=float),
        "i_total_thermal_scaled": i_total_thermal_scaled,
        "i_total_no_thermal_scaled": i_total_no_thermal_scaled,
        "i_total_med_scaled": i_total_med_scaled,
        "im_pi_thermal": im_pi_thermal,
        "im_pi_no_thermal": im_pi_no_thermal,
        "im_pi_med": im_pi_med,
    }


def compute_impi_scan_from_slice_provider(
    omega_grid: np.ndarray,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    aup_grid: np.ndarray,
    slice_provider,
    *,
    eps_integration_mode: str = "plain",
    p_integration_mode: str = "plain",
    p_split_points: np.ndarray | None = None,
    p_gl_n: int = 8,
    progress: bool = False,
) -> tuple[dict[str, np.ndarray], float]:
    """Compute ImPi(omega) by streaming translated slices one omega at a time."""
    n_omega = omega_grid.size
    i_total_thermal_raw = np.zeros(n_omega, dtype=float)
    i_total_no_thermal_raw = np.zeros(n_omega, dtype=float)
    i_total_med_raw = np.zeros(n_omega, dtype=float)
    support_mean_accum = 0.0

    for io, omega_value in enumerate(np.asarray(omega_grid, dtype=float)):
        slice_dn, support_frac = slice_provider(int(io), float(omega_value))
        support_mean_accum += float(np.mean(np.asarray(support_frac, dtype=float)))
        thermal_raw, no_thermal_raw, med_raw = compute_impi_raw_totals_for_slice(
            float(omega_value),
            p_grid,
            eps_grid,
            np.asarray(slice_dn, dtype=float),
            aup_grid,
            eps_integration_mode=eps_integration_mode,
            p_integration_mode=p_integration_mode,
            p_split_points=p_split_points,
            p_gl_n=int(p_gl_n),
        )
        i_total_thermal_raw[io] = thermal_raw
        i_total_no_thermal_raw[io] = no_thermal_raw
        i_total_med_raw[io] = med_raw
        if progress and ((io + 1) % max(1, n_omega // 10) == 0 or (io + 1) == n_omega):
            print(f"[info] omega slice {io + 1}/{n_omega} done (omega={float(omega_value):+.3f})")

    return finalize_impi_scan(
        omega_grid,
        i_total_thermal_raw,
        i_total_no_thermal_raw,
        i_total_med_raw,
    ), support_mean_accum / max(1, n_omega)


def compute_impi_scan_from_table_vectorized(
    omega_grid: np.ndarray,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    aup_grid: np.ndarray,
    adn_phi_table: np.ndarray,
    support_frac_table: np.ndarray,
) -> tuple[dict[str, np.ndarray], float]:
    """Vectorized ImPi scan over all omega at once from a pre-built adn_phi table.

    Eliminates the per-omega Python loop. Uses plain-mode T=0 step-function kernels.

    Args:
        adn_phi_table: shape (n_omega, n_p, n_eps) — phi-integrated A_dn slices
        support_frac_table: shape (n_omega, n_p, n_eps) — support fractions
    """
    omega = np.asarray(omega_grid, dtype=float)
    eps = np.asarray(eps_grid, dtype=float)
    p = np.asarray(p_grid, dtype=float)
    aup = np.asarray(aup_grid, dtype=float)         # (n_p, n_eps)
    table = np.asarray(adn_phi_table, dtype=float)  # (n_omega, n_p, n_eps)

    prod = aup[None, :, :] * table  # (n_omega, n_p, n_eps)

    # T=0 medium kernel: Θ(-ε) + Θ(ε-ω), vectorized: (n_omega, n_eps)
    fe = (eps[None, :] < 0.0).astype(float)
    fwe = (eps[None, :] > omega[:, None]).astype(float)
    medium_k = fe + fwe  # (n_omega, n_eps)
    thermal_k = medium_k - 1.0

    # Integrate over eps (axis 2)
    i_p_thermal = _trapz_axis(thermal_k[:, None, :] * prod, eps, axis=2)    # (n_omega, n_p)
    i_p_no_thermal = _trapz_axis(prod, eps, axis=2)                          # (n_omega, n_p)
    i_p_med = _trapz_axis(medium_k[:, None, :] * prod, eps, axis=2)         # (n_omega, n_p)

    # Integrate over p (axis 1)
    if hasattr(np, "trapezoid"):
        i_total_thermal_raw = np.trapezoid(p[None, :] * i_p_thermal, p, axis=1)
        i_total_no_thermal_raw = np.trapezoid(p[None, :] * i_p_no_thermal, p, axis=1)
        i_total_med_raw = np.trapezoid(p[None, :] * i_p_med, p, axis=1)
    else:  # pragma: no cover
        i_total_thermal_raw = np.trapz(p[None, :] * i_p_thermal, p, axis=1)
        i_total_no_thermal_raw = np.trapz(p[None, :] * i_p_no_thermal, p, axis=1)
        i_total_med_raw = np.trapz(p[None, :] * i_p_med, p, axis=1)

    support_mean = float(np.mean(support_frac_table))
    return finalize_impi_scan(
        omega_grid,
        i_total_thermal_raw,
        i_total_no_thermal_raw,
        i_total_med_raw,
    ), support_mean




def _insert_axis_anchors_rows(
    x: np.ndarray,
    y_rows: np.ndarray,
    anchors: np.ndarray | list[float] | tuple[float, ...],
) -> tuple[np.ndarray, np.ndarray]:
    x_aug = np.asarray(x, dtype=float).reshape(-1)
    y_aug = np.asarray(y_rows, dtype=float)
    if y_aug.ndim != 2 or y_aug.shape[1] != x_aug.size:
        raise ValueError("y_rows must be 2D with shape (n_rows, x.size).")

    if x_aug.size < 2:
        return x_aug, y_aug

    dx_min = np.min(np.diff(x_aug))
    tol = max(1.0e-12, 1.0e-8 * float(dx_min))
    anchors_arr = np.asarray(anchors, dtype=float).reshape(-1)
    anchors_arr = anchors_arr[np.isfinite(anchors_arr)]
    if anchors_arr.size == 0:
        return x_aug, y_aug

    anchors_arr = np.unique(anchors_arr)
    anchors_arr = anchors_arr[(anchors_arr > float(x_aug[0]) + tol) & (anchors_arr < float(x_aug[-1]) - tol)]
    for aval in anchors_arr.tolist():
        if np.any(np.abs(x_aug - float(aval)) <= tol):
            continue
        j = int(np.searchsorted(x_aug, float(aval), side="left"))
        if not (0 < j < x_aug.size):
            continue
        x0 = float(x_aug[j - 1])
        x1 = float(x_aug[j])
        t = (float(aval) - x0) / max(x1 - x0, 1.0e-14)
        new_col = (1.0 - t) * y_aug[:, j - 1] + t * y_aug[:, j]
        x_aug = np.insert(x_aug, j, float(aval))
        y_aug = np.insert(y_aug, j, new_col, axis=1)
    return x_aug, y_aug


def _thermal_kernel_scalar_zero_temp(eps_mid: float, omega: float) -> float:
    return _medium_kernel_scalar_midpoint_zero_temp(float(eps_mid), float(omega)) - 1.0


def _medium_kernel_scalar_zero_temp(eps_mid: float, omega: float) -> float:
    return _medium_kernel_scalar_midpoint_zero_temp(float(eps_mid), float(omega))


def _trapz_axis_panel_kernel(
    y_prod: np.ndarray,
    x: np.ndarray,
    omega: float,
    kernel_scalar_fn,
) -> np.ndarray:
    x_aug, y_aug = _insert_axis_anchors_rows(x, y_prod, [0.0, float(omega)])
    if x_aug.size < 2:
        return np.zeros(y_aug.shape[0], dtype=float)

    out = np.zeros(y_aug.shape[0], dtype=float)
    break_vals = [0.0, float(omega)]
    break_idx: list[int] = [0]
    for aval in sorted(set(float(v) for v in break_vals if np.isfinite(v))):
        matches = np.where(np.isclose(x_aug, float(aval), atol=1.0e-12, rtol=0.0))[0]
        if matches.size > 0:
            idx = int(matches[0])
            if 0 < idx < x_aug.size - 1:
                break_idx.append(idx)
    break_idx.append(x_aug.size - 1)
    break_idx = sorted(set(break_idx))

    for i in range(len(break_idx) - 1):
        lo = int(break_idx[i])
        hi = int(break_idx[i + 1])
        if hi <= lo:
            continue
        x_seg = x_aug[lo : hi + 1]
        y_seg = y_aug[:, lo : hi + 1]
        eps_mid = 0.5 * (float(x_seg[0]) + float(x_seg[-1]))
        kval = float(kernel_scalar_fn(eps_mid, float(omega)))
        if kval == 0.0:
            continue
        out += kval * _trapz_axis(y_seg, x_seg, axis=1)
    return out


def kk_re_pv_linear(omega_grid: np.ndarray, im_vals: np.ndarray) -> np.ndarray:
    """Piecewise-linear principal-value KK on a strictly increasing omega grid."""
    x = np.asarray(omega_grid, dtype=float)
    y = np.asarray(im_vals, dtype=float)
    if x.ndim != 1 or y.ndim != 1 or x.size != y.size:
        raise ValueError("omega_grid and im_vals must be 1D arrays of equal size.")
    if x.size < 3:
        raise ValueError("Need at least 3 omega points for KK transform.")
    if np.any(np.diff(x) <= 0.0):
        raise ValueError("omega_grid must be strictly increasing.")

    n = x.size
    m = (y[1:] - y[:-1]) / (x[1:] - x[:-1])
    c = y[:-1] - m * x[:-1]
    out = np.full(n, np.nan, dtype=float)

    x0 = x[:-1][None, :]
    x1 = x[1:][None, :]
    mm = m[None, :]
    cc = c[None, :]
    w = x[1:-1][:, None]

    with np.errstate(divide="ignore", invalid="ignore"):
        seg = mm * (x1 - x0) + (mm * w + cc) * np.log(np.abs((x1 - w) / (x0 - w)))

    ridx = np.arange(n - 2)
    seg[ridx, ridx] = 0.0
    seg[ridx, ridx + 1] = 0.0
    total = np.sum(seg, axis=1)

    xl = x[:-2]
    xm = x[1:-1]
    xr = x[2:]
    yl = y[:-2]
    ym = y[1:-1]
    yr = y[2:]
    m_left = (ym - yl) / (xm - xl)
    m_right = (yr - ym) / (xr - xm)
    local = m_left * (xm - xl) + m_right * (xr - xm) + ym * np.log((xr - xm) / (xm - xl))
    out[1:-1] = (total + local) / np.pi
    out[0] = out[1]
    out[-1] = out[-2]
    return out


def kk_with_powerlaw_tail(
    omega_grid: np.ndarray,
    im_vals: np.ndarray,
    *,
    alpha: float,
    n_boundary: int = 3,
) -> np.ndarray:
    """KK transform with analytic tail correction for Im ~ -C/omega^alpha.

    alpha must be supplied by the caller from the known proxy asymptotics —
    it is a physics input, not fitted from data.  C is read off the boundary:
      C_pos = -Im(omega_max) * omega_max^alpha   (positive tail)
      C_neg = -Im(omega_min) * |omega_min|^alpha  (negative tail)
    averaged over n_boundary edge points for noise robustness.

    For alpha <= 1 (log-divergent tail) no correction is applied.

    Correction formula (to next order in nu/omega_max):
      delta_Re(nu) ~ C / (pi*(alpha-1)*omega_max^(alpha-1))
                     * (1 + alpha/(alpha-1) * nu/omega_max)
    """
    if alpha <= 1.0:
        return kk_re_pv_linear(omega_grid, im_vals)

    x = np.asarray(omega_grid, dtype=float)
    y = np.asarray(im_vals, dtype=float)
    re = kk_re_pv_linear(x, y)

    nb = max(1, int(n_boundary))
    omega_max = float(x[-1])
    omega_min = float(np.abs(x[0]))

    c_pos = float(np.mean(-y[-nb:] * x[-nb:] ** alpha))
    c_neg = float(np.mean(-y[:nb] * np.abs(x[:nb]) ** alpha))

    nu = x.copy()
    denom = (alpha - 1.0) * omega_max ** (alpha - 1.0)

    corr_pos = c_pos / (np.pi * denom)
    re += corr_pos * (1.0 + (alpha / (alpha - 1.0)) * nu / omega_max)

    corr_neg = c_neg / (np.pi * denom)
    re -= corr_neg * (1.0 - (alpha / (alpha - 1.0)) * nu / omega_min)

    return re


def kk_re_with_optional_powerlaw_tail(
    omega_source: np.ndarray,
    im_source: np.ndarray,
    omega_output: np.ndarray,
    *,
    kk_pad: float,
    kk_oversample: float,
    tail_mode: str,
    kk_n_max: int | None = None,
    tail_alpha: float | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Build a KK grid and reconstruct Re with an optional two-sided power tail.

    If ``tail_alpha`` is supplied, the exterior contribution is evaluated from
    the actual source-window boundaries.  In that mode ``kk_pad`` and
    ``tail_mode`` are deliberately ignored for the exterior region: padding with
    zeros or held boundary values would corrupt the coefficients of the
    analytic left/right tails.
    """
    alpha = None if tail_alpha is None else float(tail_alpha)
    if alpha is None or not np.isfinite(alpha):
        omega_kk, im_kk = build_kk_input_grid(
            omega_source,
            im_source,
            omega_output,
            kk_pad=float(kk_pad),
            kk_oversample=float(kk_oversample),
            tail_mode=str(tail_mode),
            kk_n_max=kk_n_max,
        )
        re_kk = kk_re_pv_linear(omega_kk, im_kk)
        return omega_kk, im_kk, re_kk

    # Oversample inside the computed source window only.  The exterior is
    # supplied analytically by kk_with_powerlaw_tail using the two boundaries.
    omega_kk, im_kk = build_kk_input_grid(
        omega_source,
        im_source,
        omega_source,
        kk_pad=0.0,
        kk_oversample=float(kk_oversample),
        tail_mode="zero",
        kk_n_max=kk_n_max,
    )
    re_kk = kk_with_powerlaw_tail(omega_kk, im_kk, alpha=alpha)
    return omega_kk, im_kk, re_kk


def _uniform_step(x: np.ndarray) -> float:
    dx = np.diff(np.asarray(x, dtype=float))
    dx = dx[dx > 0.0]
    if dx.size == 0:
        return 1.0
    return float(np.median(dx))


def build_kk_input_grid(
    omega_source: np.ndarray,
    im_source: np.ndarray,
    omega_output: np.ndarray,
    *,
    kk_pad: float,
    kk_oversample: float,
    tail_mode: str,
    kk_n_max: int | None = None,
    tail_eval: Callable[[np.ndarray], np.ndarray] | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Build the omega/im arrays used for KK, optionally padded and oversampled.

    `tail_mode="analytic"` or `tail_mode="analytic_proxy"` uses `tail_eval`
    to supply the exterior omega tails instead of a constant extrapolation.
    """
    x_src = np.asarray(omega_source, dtype=float)
    y_src = np.asarray(im_source, dtype=float)
    x_out = np.asarray(omega_output, dtype=float)
    if x_src.ndim != 1 or y_src.ndim != 1 or x_src.size != y_src.size:
        raise ValueError("omega_source and im_source must be 1D arrays with equal size.")
    if x_out.ndim != 1 or x_out.size < 2:
        raise ValueError("omega_output must be 1D with at least 2 points.")
    if np.any(np.diff(x_src) <= 0.0):
        order = np.argsort(x_src)
        x_src = x_src[order]
        y_src = y_src[order]

    pad = max(float(kk_pad), 0.0)
    ov = max(float(kk_oversample), 1.0)
    x_min_target = float(x_out[0]) - pad
    x_max_target = float(x_out[-1]) + pad
    x_min = min(float(x_src[0]), x_min_target)
    x_max = max(float(x_src[-1]), x_max_target)

    dx = max(_uniform_step(x_src) / ov, 1.0e-12)
    n = max(3, int(round((x_max - x_min) / dx)) + 1)
    if kk_n_max is not None:
        kk_n_cap = max(int(kk_n_max), 3)
        if n > kk_n_cap:
            n = kk_n_cap
    x_kk = np.linspace(x_min, x_max, n, dtype=float)

    tail = str(tail_mode).strip().lower()
    if tail == "hold":
        y_left = float(y_src[0])
        y_right = float(y_src[-1])
    elif tail == "zero":
        y_left = 0.0
        y_right = 0.0
    elif tail in {"analytic", "analytic_proxy"}:
        if tail_eval is None:
            raise ValueError("tail_mode='analytic' requires tail_eval.")
        y_kk = np.interp(x_kk, x_src, y_src)
        left_mask = x_kk < float(x_src[0])
        right_mask = x_kk > float(x_src[-1])
        if np.any(left_mask):
            y_kk[left_mask] = np.asarray(tail_eval(x_kk[left_mask]), dtype=float)
        if np.any(right_mask):
            y_kk[right_mask] = np.asarray(tail_eval(x_kk[right_mask]), dtype=float)
        return x_kk, y_kk
    else:
        raise ValueError("tail_mode must be 'zero', 'hold', or 'analytic'.")

    y_kk = np.interp(x_kk, x_src, y_src, left=y_left, right=y_right)
    return x_kk, y_kk


def g0_inverse(omega: np.ndarray, q: float, eps0: float, mu_up: float, mu_dn: float, eta_gamma: float) -> np.ndarray:
    w_c = np.asarray(omega, dtype=float) + 1j * float(eta_gamma)
    return -(1.0 / (8.0 * np.pi)) * np.log((float(q) * float(q) / 2.0 - float(mu_up) - float(mu_dn) -w_c) / float(eps0))


def kk_sigma_gamma_asymptote(
    omega: np.ndarray,
    im_sigma: np.ndarray,
    *,
    k_ext: float,
    eps0: float,
    mu_up: float,
    mu_dn: float,
    eta_gamma: float,
    n_internal: float,
    kk_pad: float,
    kk_oversample: float,
    kk_n_max: int | None = None,
) -> np.ndarray:
    """ReSigma via KK with the analytic n_internal*Gamma(k,omega) asymptote removed.

    The pair-fluctuation ImSigma has a slow ~1/ln^2(omega) UV tail (the pair
    continuum / contact tail) that makes a plain KK non-convergent and the
    powerlaw exterior wrong.  The high-frequency expansion of the convolution
    gives Sigma(k,omega) -> n_internal * Gamma(k,omega) (Gamma the vacuum pair
    propagator at the external momentum, n_internal = mu_internal/4pi the
    opposite-spin occupation).  Gamma is causal so Re(Gamma) is the exact KK of
    Im(Gamma), known in closed form (= Re(1/g0_inverse)).  Subtract
    n_internal*Im(Gamma), KK the fast-decaying residual numerically (zero tail),
    add back n_internal*Re(Gamma).  Validated: residual ~ omega^-1.6 and
    KK[residual](0) plateaus for window >= 24 while plain KK keeps drifting.
    """
    w = np.asarray(omega, dtype=float)
    gamma = 1.0 / g0_inverse(w, float(k_ext), float(eps0), float(mu_up), float(mu_dn), float(eta_gamma))
    im_asy = float(n_internal) * np.imag(gamma)
    re_asy = float(n_internal) * np.real(gamma)
    residual = np.asarray(im_sigma, dtype=float) - im_asy
    # KK the residual on the NATIVE (split, dense-near-0) grid with the exact
    # piecewise-linear principal value.  Do NOT re-grid to uniform (oversample):
    # that coarsens the dense near-omega=0 region and smears the sharp QP peak,
    # breaking the window-independence.  The residual decays fast (~omega^-1.6)
    # so the implicit zero exterior of kk_re_pv_linear is harmless.
    return re_asy + kk_re_pv_linear(w, residual)


def proxy_medium_pi_from_gamma(
    omega: np.ndarray,
    *,
    q: float,
    eps0: float,
    mu_up: float,
    mu_dn: float,
    eta_gamma: float,
) -> np.ndarray:
    """Return the analytic proxy medium piece Pi_med = g0^{-1} - Gamma_proxy^{-1}.

    Important:
    This is not the full pair bubble including the vacuum contribution. In the
    notation of the 2D FFLO paper, the proxy Gamma^{-1} already contains the
    vacuum term, so subtracting it from g0^{-1} leaves only the Fermi-surface
    / medium contribution.
    """
    analytical_configuration.update(
        epsilon_0=float(eps0),
        mu_up=float(mu_up),
        mu_down=float(mu_dn),
    )
    w = np.asarray(omega, dtype=float)
    gamma_vals = np.asarray(
        analytical_gamma(float(q), w + 1j * float(eta_gamma)),
        dtype=complex,
    )
    g0_inv = g0_inverse(
        w,
        q=float(q),
        eps0=float(eps0),
        mu_up=float(mu_up),
        mu_dn=float(mu_dn),
        eta_gamma=float(eta_gamma),
    )
    with np.errstate(divide="ignore", invalid="ignore"):
        inv_gamma = 1.0 / gamma_vals
    return np.asarray(g0_inv - inv_gamma, dtype=complex)




def proxy_full_pi_from_gamma(
    omega: np.ndarray,
    *,
    q: float,
    eps0: float,
    mu_up: float,
    mu_dn: float,
    eta_gamma: float,
    cutoff: float,
) -> np.ndarray:
    """Return the full proxy-consistent pair bubble at finite cutoff.

    This combines the finite-cutoff bare vacuum piece with the proxy medium
    contribution:

        Pi_proxy_full = Pi_vac,cutoff + Pi_proxy_medium

    which is the correct object to compare against a full numerical Pi.
    """
    return np.asarray(
        vacuum_pi_from_cutoff(
            omega,
            q=float(q),
            eps0=float(eps0),
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
            eta_gamma=float(eta_gamma),
            cutoff=float(cutoff),
        )
        + proxy_medium_pi_from_gamma(
            omega,
            q=float(q),
            eps0=float(eps0),
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
            eta_gamma=float(eta_gamma),
        ),
        dtype=complex,
    )


def vacuum_pi_from_cutoff(
    omega: np.ndarray,
    *,
    q: float,
    eps0: float,
    mu_up: float,
    mu_dn: float,
    eta_gamma: float,
    cutoff: float,
) -> np.ndarray:
    """Bare vacuum bubble at finite cutoff, defined so g0_const - Pi_vac = g0_inverse."""
    g0_const = g0_constant_from_cutoff(float(cutoff), float(eps0))
    g0_inv = g0_inverse(
        np.asarray(omega, dtype=float),
        q=float(q),
        eps0=float(eps0),
        mu_up=float(mu_up),
        mu_dn=float(mu_dn),
        eta_gamma=float(eta_gamma),
    )
    return np.asarray(float(g0_const) - g0_inv, dtype=complex)






def g0_constant_from_cutoff(cutoff: float, eps0: float) -> float:
    cutoff_val = float(cutoff)
    eps0_val = float(eps0)
    if not np.isfinite(cutoff_val) or cutoff_val <= 0.0:
        raise ValueError(f"Need positive finite cutoff to define bare g0, got {cutoff_val!r}.")
    if not np.isfinite(eps0_val) or eps0_val <= 0.0:
        raise ValueError(f"Need positive finite eps0 to define bare g0, got {eps0_val!r}.")
    return float(-(1.0 / (8.0 * np.pi)) * np.log((cutoff_val * cutoff_val + eps0_val) / eps0_val))







        # Cluster-minimal copy: omega-scan plotting is intentionally omitted.


