# =====================================================================
# SLIM copy of true_akw_pipeline/lattice_grids.py
#
# 3 top-level symbols (113 lines, 49% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   build_omega_lattice, build_q_michele_lattice
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   eps_union_nodes
#   build_k_three_block
#   build_k_three_block_xi
# =====================================================================
"""Static commensurate grids (Michele's design) for FFLO convolutions.

Three builders:

1. build_omega_lattice: frequency lattice whose nodes are ALL integer
   multiples of a micro-spacing dw (the int() trick).  A linear block of
   n_linear nodes per side around 0 at spacing dw resolves the critical pair
   pole / QP scale; int-sinh tails reach +-w_max.  Because every node sits on
   the micro-lattice, frequency sums omega+eps land ON the lattice: no
   interpolation aliasing, and the razor blade at Omega=omega+eps=0 falls on
   nodes for every on-lattice omega.

2. build_q_michele_lattice: positive momentum lattice with a uniform infrared
   block and an int-sinh ultraviolet tail. Every node is an integer multiple
   of dq, so the active Q region is evenly resolved without feature packets.

3. build_k_three_block: momentum grid with tanh blocks [0,kf1] and [kf1,kf2]
   (dense at 0, kf1, kf2) and a sinh tail [kf2,kmax] (dense at kf2), one grid
   shared by both spins.

Validated 2026-07-04 against dense references on the P=0.20 CVDENSE state:
bubble ImPi(q~qF, Omega<=0.1) error -6% (production split grid) -> -0.03%
(lattice) at equal node budget; Sigma eps-blade handled by the union
lattice ∪ (lattice - omega) node set (see eps_union_nodes).
"""

from __future__ import annotations

import numpy as np
from scipy.optimize import brentq


def _int_sinh_tail(n_steps: int, target_units: int) -> np.ndarray:
    """Strictly increasing integer offsets int(sinh(g j)/g), j=1..n_steps,
    with the largest equal to target_units. Duplicates from the int() are
    removed; g is solved so the tail spans exactly target_units."""
    if target_units <= n_steps:
        return np.arange(1, target_units + 1, dtype=int)

    def f(g: float) -> float:
        x = g * n_steps
        s = np.sinh(x) if x < 700.0 else np.exp(min(x, 700.0)) / 2.0
        return s / g - float(target_units)

    g = brentq(f, 1e-6, 5.0)
    nu = np.array([int(np.sinh(g * j) / g) for j in range(1, n_steps + 1)], dtype=int)
    nu = np.unique(nu[nu >= 1])
    nu[-1] = target_units
    return nu


def build_omega_lattice(
    dw: float,
    n_linear: int,
    w_max_pos: float,
    w_max_neg: float,
    n_tail_pos: int,
    n_tail_neg: int,
) -> np.ndarray:
    """Frequency lattice: nodes k*dw, linear |k|<=n_linear, int-sinh tails to
    +-w_max. Returns strictly increasing float nodes including 0."""
    upos = int(round(w_max_pos / dw))
    uneg = int(round(abs(w_max_neg) / dw))
    if upos <= n_linear or uneg <= n_linear:
        raise ValueError("w_max must exceed the linear block n_linear*dw")
    tail_p = n_linear + _int_sinh_tail(n_tail_pos, upos - n_linear)
    tail_m = n_linear + _int_sinh_tail(n_tail_neg, uneg - n_linear)
    units = np.concatenate([-tail_m[::-1], np.arange(-n_linear, n_linear + 1), tail_p])
    return np.unique(units) * float(dw)


def build_q_michele_lattice(
    dq: float,
    q_linear_max: float,
    q_max: float,
    n_tail: int,
) -> np.ndarray:
    """Positive Q lattice with a uniform core and an int-sinh tail.

    The core contains every micro-lattice node from 0 through q_linear_max.
    The tail uses ``n_tail`` increasingly spaced lattice offsets and lands
    exactly on q_max. Both boundaries must be integer multiples of ``dq``.
    """
    dq = float(dq)
    q_linear_max = float(q_linear_max)
    q_max = float(q_max)
    n_tail = int(n_tail)
    if not (np.isfinite(dq) and dq > 0.0):
        raise ValueError("q lattice dq must be finite and positive")
    if not (0.0 < q_linear_max < q_max):
        raise ValueError("need 0 < q_linear_max < q_max")
    if n_tail < 1:
        raise ValueError("q lattice n_tail must be positive")

    n_linear = int(round(q_linear_max / dq))
    n_max = int(round(q_max / dq))
    if not np.isclose(n_linear * dq, q_linear_max, rtol=0.0, atol=1e-12):
        raise ValueError("q_linear_max must be an integer multiple of dq")
    if not np.isclose(n_max * dq, q_max, rtol=0.0, atol=1e-12):
        raise ValueError("q_max must be an integer multiple of dq")

    tail = n_linear + _int_sinh_tail(n_tail, n_max - n_linear)
    units = np.concatenate([np.arange(n_linear + 1, dtype=int), tail])
    grid = np.unique(units).astype(float) * dq
    if grid[0] != 0.0 or not np.isclose(grid[-1], q_max):
        raise RuntimeError("Q lattice does not span the requested interval")
    return grid








