# =====================================================================
# SLIM copy of true_akw_pipeline/make_lorentzian_akw_cubes.py
#
# 6 top-level symbols (210 lines, 76% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   build_lorentzian_cube, resolve_mu
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   parse_args
#   build_axes
#   save_cube
#   latest_run_dir
#   newest_matching
#   main
# =====================================================================
#!/usr/bin/env python3
"""Generate spin-up and spin-down Lorentzian A(k,omega) cubes.

The output .npz files are shaped and named to be compatible with:
- true_akw_pipeline/precompute_adn_phi_table.py
- true_akw_pipeline/compute_convolution_from_adn_table.py
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_BASE = REPO_ROOT / "true_akw_pipeline" / "lorentzian_cubes"
PRODUCTION = True




def resolve_mu(eps0: float, pmf_scale: float, mu_up_arg: float, mu_dn_arg: float) -> tuple[float, float, float]:
    if not (np.isfinite(eps0) and 0.0 < eps0 <= 2.0):
        raise ValueError("eps0 must satisfy 0 < eps0 <= 2.")
    pmf = float(eps0 * np.sqrt(2.0 / eps0 - 1.0))
    mu_up = float(mu_up_arg) if np.isfinite(mu_up_arg) else float(1.0 + pmf_scale * pmf)
    mu_dn = float(mu_dn_arg) if np.isfinite(mu_dn_arg) else float(1.0 - pmf_scale * pmf)
    if mu_up <= 0.0 or mu_dn <= 0.0:
        raise ValueError(f"Require mu_up>0 and mu_dn>0, got mu_up={mu_up}, mu_dn={mu_dn}.")
    return mu_up, mu_dn, pmf




def build_lorentzian_cube(
    k: np.ndarray,
    w: np.ndarray,
    *,
    mu_sigma: float,
    mass: float,
    eta: float,
    convention: str,
) -> np.ndarray:
    xi = (k[:, None] * k[:, None]) / float(mass) - float(mu_sigma)
    dw = w[None, :] - xi
    g2 = float(eta) * float(eta)
    if str(convention) == "minus2_im":
        # A = -2 Im[1/(w-xi+i eta)] = 2 eta / ((w-xi)^2 + eta^2)
        return (2.0 * float(eta)) / (dw * dw + g2)
    # A = -(1/pi) Im G = eta/pi / ((w-xi)^2 + eta^2)
    return (float(eta) / np.pi) / (dw * dw + g2)










