# =====================================================================
# SLIM copy of true_akw_pipeline/make_pair_gamma_table_proxy_residual.py
#
# 0 top-level symbols (0 lines, 0% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   main
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
# =====================================================================
#!/usr/bin/env python3
"""Build a proxy-residual pair table from a numerical ImPi source.

Theory:

    Pi_num = Pi_ref + DeltaPi_res
    Pi_ref = Pi_vac,cutoff + Pi_proxy,medium   (original proxy_residual mode)
    Pi_ref = Pi_QP-QP                          (qp_subtracted mode — UV-safe)
    Pi_ref = Pi_vac,cutoff                     (direct_vacuum_kk mode)
    Gamma_num^{-1} = Gamma_ref^{-1} - DeltaPi_res

The key point is that the KK reconstruction is applied only to the residual
DeltaPi_res, which must decay at large |omega|.

In the original proxy_residual mode Im(Pi_ref) → -1/8 at large Omega (vacuum
log with k→∞), while Im(Pi_SC) → 0 at Omega > 2*k_cut^2/m - mu_up - mu_dn,
leaving a permanent +1/8 offset in ImDeltaPi that breaks the KK.

The qp_subtracted mode avoids this: Im(Pi_QP-QP) is computed analytically from
per-k Dyson poles extracted from the SC cubes and decays as ~1/Omega^2 (finite
k_cut Lorentzian tails), so ImDeltaPi = Im(Pi_SC) - Im(Pi_QP-QP) → 0 by
construction for all q.

The direct_vacuum_kk mode is the minimal finite-cutoff reconstruction used by
the validated high-polarization candidate.  It Kramers-Kronig transforms only
Im(Pi_num-Pi_vac,cutoff) on the native omega grid and adds the exact complex
finite-cutoff vacuum bubble back.  It applies no residual taper and no proxy
or QP reference.
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import sys

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fflo.kramers_kronig import (
    g0_constant_from_cutoff,
    g0_inverse,
    kk_re_pv_linear,
    kk_re_with_optional_powerlaw_tail,
    proxy_full_pi_from_gamma,
    proxy_medium_pi_from_gamma,
    vacuum_pi_from_cutoff,
)


OUT_BASE = REPO_ROOT / "true_akw_pipeline" / "pair_gamma_tables_proxy_residual"

# ---------------------------------------------------------------------------
# QP-QP analytic pair bubble (for qp_subtracted reference mode)
# ---------------------------------------------------------------------------

_PREF_QPQP = np.pi / (2.0 * np.pi) ** 2


def _cheb_nodes(n: int) -> tuple[np.ndarray, np.ndarray]:
    j = np.arange(1, n + 1)
    return np.cos(np.pi * (2 * j - 1) / (2 * n)), np.full(n, 2.0 * np.pi / n)


def _interp0(x_q: np.ndarray, x: np.ndarray, y: np.ndarray) -> np.ndarray:
    return np.interp(x_q, x, y, left=0.0, right=0.0)


def _compute_impi_qpqp(
    q: float,
    omega: np.ndarray,
    up_k: np.ndarray, up_e: np.ndarray, up_z: np.ndarray, up_gamma: np.ndarray,
    up_mu: float, up_mass: float,
    dn_k: np.ndarray, dn_e: np.ndarray, dn_z: np.ndarray, dn_gamma: np.ndarray,
    dn_mu: float, dn_mass: float,
    p_grid: np.ndarray, n_phi: int,
) -> np.ndarray:
    """Analytic QP-QP Im Pi.  Uses free dispersion for step-function kernel,
    extracted Z and gamma for Lorentzian weight.  Decays as 1/Omega^2 at large
    Omega since both Lorentzians have finite k_cut support."""
    u_cheb, w_cheb = _cheb_nodes(n_phi)
    dp  = np.gradient(p_grid)
    zu  = _interp0(p_grid, up_k, up_z)
    gu  = _interp0(p_grid, up_k, up_gamma)
    eu  = _interp0(p_grid, up_k, up_e)
    vup = (zu > 0) & (gu > 0)

    kern_up = (                                   # (n_p, n_omega)
        (eu[:, None] < 0.0).astype(float)
        + (eu[:, None] > omega[None, :]).astype(float)
        - 1.0
    )
    kern_up[~vup] = 0.0
    w_base = p_grid * dp * zu                     # (n_p,)

    out = np.zeros(omega.size)
    for ui, wpi in zip(u_cheb, w_cheb):
        k2 = np.sqrt(np.maximum(q * q + p_grid * p_grid - 2.0 * q * p_grid * ui, 0.0))
        ed = _interp0(k2, dn_k, dn_e)
        zd = _interp0(k2, dn_k, dn_z)
        gd = _interp0(k2, dn_k, dn_gamma)
        v  = vup & (zd > 0) & (gd > 0)

        width  = (gu + gd)[v]
        center = (eu + ed)[v]
        lor = (
            width[:, None] / np.pi
            / ((omega[None, :] - center[:, None]) ** 2 + width[:, None] ** 2)
        )
        weight = (w_base * zd)[v]
        out += wpi * np.einsum("p,pw,pw->w", weight, kern_up[v], lor)

    return _PREF_QPQP * out


def _load_sc_cube_for_qp(cube_path_str: str) -> tuple:
    """Load an SC cube and return (k, w_1d, re_s_1d, im_s_1d, mu_sigma, mass, mu_up, mu_dn)."""
    from fflo.feature_grid import (
        find_dyson_poles_per_k,
        compute_z_at_kf_row,
    )

    path = Path(str(cube_path_str).strip()).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"SC cube not found: {path}")

    with np.load(path, allow_pickle=True) as d:
        k      = np.asarray(d["k"],   dtype=float)
        w_raw  = np.asarray(d["w"],   dtype=float)
        re_s   = np.asarray(d["ReS"], dtype=float)
        im_s   = np.asarray(d["ImS"], dtype=float)
        w_base = np.asarray(d["w_base"], dtype=float) if "w_base" in d.files else None
        mu_up  = float(np.asarray(d["mu_up"]).reshape(-1)[0])
        mu_dn_raw = d["mu_dn"] if "mu_dn" in d.files else d.get("mu_down", None)
        mu_dn  = float(np.asarray(mu_dn_raw).reshape(-1)[0]) if mu_dn_raw is not None else np.nan
        mass   = float(np.asarray(d.get("mass", [1.0])).reshape(-1)[0])
        spin_r = np.asarray(d.get("spin", ["up"])).reshape(-1)[0]
        spin   = str(spin_r.decode() if isinstance(spin_r, bytes) else spin_r).lower()

    mu_sigma = mu_up if "up" in spin else mu_dn

    # Determine shared 1D omega grid
    if w_base is not None and w_base.ndim == 1:
        w_1d = w_base
    elif w_raw.ndim == 1:
        w_1d = w_raw
    else:
        w_1d = w_raw[0]

    # Interpolate ReS / ImS rows to w_1d if they live on per-k grids
    if re_s.ndim == 2 and w_raw.ndim == 2 and w_raw.shape[0] == k.size:
        re_s_1d = np.zeros((k.size, w_1d.size), dtype=float)
        im_s_1d = np.zeros((k.size, w_1d.size), dtype=float)
        for ik in range(k.size):
            re_s_1d[ik] = np.interp(w_1d, w_raw[ik], re_s[ik])
            im_s_1d[ik] = np.interp(w_1d, w_raw[ik], im_s[ik])
    else:
        re_s_1d = re_s
        im_s_1d = im_s

    return k, w_1d, re_s_1d, im_s_1d, mu_sigma, mass, mu_up, mu_dn, spin, find_dyson_poles_per_k, compute_z_at_kf_row


def _extract_qp_poles(
    k: np.ndarray, w: np.ndarray, re_s: np.ndarray, im_s: np.ndarray,
    mu_sigma: float, mass: float, xi_cutoff: float,
    find_dyson_poles_per_k, compute_z_at_kf_row,
    gamma_floor: float = 1.0e-3,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return (pole_e, z_arr, gamma_arr, valid) per k-row.

    gamma_floor: minimum QP width — used when ImS≈0 (e.g., free-gas seed
    iteration).  The floor ensures that even the seed Lorentzians contribute
    to Im Pi_QP-QP, so the residual stays UV-safe from the very first iter.
    """
    pole_e    = find_dyson_poles_per_k(k, w, re_s, mu_sigma=mu_sigma, mass=mass)
    z_arr     = np.full(k.size, np.nan)
    gamma_arr = np.full(k.size, np.nan)
    valid     = np.zeros(k.size, dtype=bool)

    for ik, kv in enumerate(k):
        xi_k = float(kv) ** 2 / float(mass) - float(mu_sigma)
        if abs(xi_k) >= float(xi_cutoff) or not np.isfinite(pole_e[ik]):
            continue
        z = compute_z_at_kf_row(re_s[ik], w, pole_e[ik])
        if z <= 0.0:
            continue
        im_at_pole = float(np.interp(pole_e[ik], w, im_s[ik]))
        gam = -z * im_at_pole
        if gam <= 0.0:
            gam = float(gamma_floor)   # free-gas seed fallback
        z_arr[ik]     = z
        gamma_arr[ik] = gam
        valid[ik]     = True

    n_valid = int(np.sum(valid))
    print(f"[qpqp] mu_sigma={mu_sigma:.6f}, xi_cut={xi_cutoff:.4g}, "
          f"valid_poles={n_valid}/{k.size}", flush=True)
    return pole_e, z_arr, gamma_arr, valid


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build a proxy-residual pair table from a numerical ImPi source.")
    p.add_argument("--impi-table-path", required=True, help="Path to impi_table.npz or impi_uv_matched_table.npz")
    p.add_argument(
        "--im-source",
        choices=("auto", "full_dress", "uv_matched", "plain"),
        default="auto",
        help="Which ImPi field to use from the input table.",
    )
    p.add_argument(
        "--kk-tail",
        choices=("zero", "hold", "analytic_proxy"),
        default="zero",
        help=(
            "Exterior omega tail for the residual KK. In this proxy-residual builder "
            "the correct analytic asymptotic tail is zero, so analytic_proxy is treated as zero."
        ),
    )
    p.add_argument(
        "--kk-tail-alpha",
        type=float,
        default=None,
        help=(
            "Power-law exponent alpha for the analytic KK tail correction on the residual "
            "(Im ~ -C/omega^alpha). C is read from the grid boundary — no fitting. "
            "Supply from the known proxy asymptotics (e.g. 2.0 for a Lorentzian proxy). "
            "None (default) disables the correction."
        ),
    )
    p.add_argument("--kk-pad", type=float, default=4.0)
    p.add_argument("--kk-oversample", type=float, default=2.0)
    p.add_argument(
        "--kk-max-n",
        type=int,
        default=4096,
        help=(
            "Maximum number of points in the internal uniform KK grid. "
            "Keeps enriched omega grids from creating a memory-heavy O(N^2) KK matrix. "
            "Set <=0 to disable the cap."
        ),
    )
    p.add_argument("--eta-gamma", type=float, default=1.0e-3)
    p.add_argument(
        "--im-inv-sign-guard",
        choices=("on", "off"),
        default="on",
        help=(
            "Clamp wrong-signed Im Gamma^{-1} cells to zero before inverting "
            "(bosonic positivity: sign(Im Gamma^{-1}) = sign(omega)).  The clamped "
            "cells are sub-1e-3 quadrature residuals in Pauli-blocked windows; near "
            "the critical ridge they otherwise become wrong-signed A_pair of order "
            "1/eta.  Raw values are kept in ImInvGammaRaw."
        ),
    )
    p.add_argument(
        "--reference-mode",
        choices=(
            "auto",
            "proxy_residual",
            "lorentzian_fixed_point",
            "qp_subtracted",
            "direct_vacuum_kk",
        ),
        default="auto",
        help=(
            "auto uses an exact Lorentzian fixed point when the input ImPi table carries "
            "consistent Lorentzian cube metadata; otherwise it uses the proxy-residual path. "
            "qp_subtracted: uses Im(Pi_QP-QP) as the UV-safe KK reference — ImDeltaPi → 0 "
            "by construction for all q. direct_vacuum_kk: subtracts the exact finite-cutoff "
            "vacuum bubble, KKs the native residual without tapering, and adds the vacuum back."
        ),
    )
    p.add_argument(
        "--qp-residual-mode",
        choices=("cross_inc", "incinc_only", "full_minus_qpqp"),
        default="cross_inc",
        help=(
            "Residual used in qp_subtracted mode when QP decomposition fields exist. "
            "cross_inc uses QPInc+IncQP+IncInc (physical full-QPQP residual); "
            "incinc_only uses only (A_up-A_up^QP)(A_dn-A_dn^QP), a diagnostic strong subtraction; "
            "full_minus_qpqp falls back to subtracting QPQP from the full table."
        ),
    )
    p.add_argument(
        "--qpqp-source",
        choices=("auto", "table", "analytic"),
        default="auto",
        help=(
            "QPQP reference/add-back source in qp_subtracted mode. auto prefers the table; "
            "analytic recomputes the QPQP bubble from extracted poles."
        ),
    )
    p.add_argument(
        "--qpqp-xi-cutoff",
        type=float,
        default=0.015,
        help="QP window cutoff |xi_k| < cutoff for QP-QP reference (qp_subtracted mode).",
    )
    p.add_argument(
        "--qpqp-n-p",
        type=int,
        default=5000,
        help="p-grid points for analytic QP-QP integration.",
    )
    p.add_argument(
        "--qpqp-n-phi",
        type=int,
        default=24,
        help="Chebyshev angular points for QP-QP integration.",
    )
    p.add_argument(
        "--residual-omega-taper-start",
        type=float,
        default=np.nan,
        help=(
            "If finite with --residual-omega-taper-stop, leave DeltaImPi_res untouched for "
            "|omega| <= start and taper it toward the analytic reference tail beyond this point."
        ),
    )
    p.add_argument(
        "--residual-omega-taper-stop",
        type=float,
        default=np.nan,
        help="If finite with --residual-omega-taper-start, force DeltaImPi_res to zero for |omega| >= stop.",
    )
    p.add_argument(
        "--residual-omega-taper-mode",
        choices=("cosine", "hard", "none", "qkin_cosine", "qkin_hard"),
        default="cosine",
        help=(
            "Residual tail taper shape. none disables tapering. qkin_* tapers only positive omega "
            "above omega=(q+kF_up)^2-mu_down+start, reaching zero over width=stop."
        ),
    )
    p.add_argument("--out-dir", default="", help="Optional output dir.")
    p.add_argument(
        "--no-plots",
        action="store_true",
        help="Skip PNG heatmaps and q-scan plots. Useful for headless or unstable IDE sessions.",
    )
    return p.parse_args()


def load_im_source(
    path: Path,
    source_mode: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float, float, float, float, str, dict[str, str | float]]:
    with np.load(path) as d:
        q = np.asarray(d["q"], dtype=float)
        omega = np.asarray(d["omega"], dtype=float)
        support_mean = np.asarray(d["support_mean"], dtype=float) if "support_mean" in d.files else np.zeros(q.size, dtype=float)
        eps0 = float(np.asarray(d["eps0"]).reshape(-1)[0])
        mu_up = float(np.asarray(d["mu_up"]).reshape(-1)[0])
        mu_dn = float(np.asarray(d["mu_dn"]).reshape(-1)[0])
        p_int_max = float(np.asarray(d["p_int_max"]).reshape(-1)[0])

        mode = str(source_mode).strip().lower()
        if mode == "auto":
            if "ImPiFullDress" in d.files:
                im_pi = np.asarray(d["ImPiFullDress"], dtype=float)
                mode_used = "full_dress"
            elif "ImPiFull" in d.files:
                im_pi = np.asarray(d["ImPiFull"], dtype=float)
                mode_used = "plain"
            elif "ImPi" in d.files:
                im_pi = np.asarray(d["ImPi"], dtype=float)
                mode_used = "plain"
            else:
                raise ValueError(f"Could not auto-detect ImPi source field in {path}")
        elif mode == "full_dress":
            im_pi = np.asarray(d["ImPiFullDress"], dtype=float)
            mode_used = "full_dress"
        elif mode == "uv_matched":
            im_pi = np.asarray(d["ImPiUVMatched"], dtype=float)
            mode_used = "uv_matched"
        elif mode == "plain":
            if "ImPiFull" in d.files:
                im_pi = np.asarray(d["ImPiFull"], dtype=float)
            else:
                im_pi = np.asarray(d["ImPi"], dtype=float)
            mode_used = "plain"
        else:
            raise ValueError(f"Unsupported im-source mode: {source_mode!r}")

        meta: dict[str, str | float] = {
            "cube_source": str(np.asarray(d["cube_source"]).reshape(-1)[0]) if "cube_source" in d.files else "",
            "up_cube_model": str(np.asarray(d["up_cube_model"]).reshape(-1)[0]) if "up_cube_model" in d.files else "",
            "down_cube_model": str(np.asarray(d["down_cube_model"]).reshape(-1)[0]) if "down_cube_model" in d.files else "",
            "up_cube_eta": float(np.asarray(d["up_cube_eta"]).reshape(-1)[0]) if "up_cube_eta" in d.files else np.nan,
            "down_cube_eta": float(np.asarray(d["down_cube_eta"]).reshape(-1)[0]) if "down_cube_eta" in d.files else np.nan,
            "up_cube_path": str(np.asarray(d["up_cube_path"]).reshape(-1)[0]) if "up_cube_path" in d.files else "",
            "down_cube_path": str(np.asarray(d["down_cube_path"]).reshape(-1)[0]) if "down_cube_path" in d.files else "",
        }

    if q.ndim != 1 or omega.ndim != 1 or im_pi.ndim != 2 or im_pi.shape != (q.size, omega.size):
        raise ValueError(f"Invalid ImPi table shapes in {path}")
    return q, omega, im_pi, support_mean, eps0, mu_up, mu_dn, p_int_max, mode_used, meta


def choose_reference_mode(requested_mode: str, meta: dict[str, str | float]) -> tuple[str, float]:
    mode = str(requested_mode).strip().lower()

    if mode in {"qp_subtracted", "direct_vacuum_kk"}:
        return mode, np.nan

    up_model = str(meta.get("up_cube_model", "")).strip().lower()
    down_model = str(meta.get("down_cube_model", "")).strip().lower()
    up_eta = float(meta.get("up_cube_eta", np.nan))
    down_eta = float(meta.get("down_cube_eta", np.nan))

    lorentzian_ok = (
        up_model == "lorentzian"
        and down_model == "lorentzian"
        and np.isfinite(up_eta)
        and np.isfinite(down_eta)
        and abs(up_eta - down_eta) <= 1.0e-12 * max(1.0, abs(up_eta), abs(down_eta))
    )

    if mode == "lorentzian_fixed_point":
        if not lorentzian_ok:
            raise ValueError("lorentzian_fixed_point requested, but the ImPi table does not carry consistent Lorentzian cube metadata.")
        return "lorentzian_fixed_point", float(up_eta)

    if mode == "auto" and lorentzian_ok:
        return "lorentzian_fixed_point", float(up_eta)

    return "proxy_residual", np.nan


def kk_on_residual(
    omega_grid: np.ndarray,
    delta_im: np.ndarray,
    *,
    kk_pad: float,
    kk_oversample: float,
    kk_tail: str,
    kk_max_n: int | None,
    kk_tail_alpha: float | None = None,
) -> np.ndarray:
    """KK transform of the residual ImΠ.

    kk_tail_alpha: power-law exponent alpha for the analytic tail correction
      (Im ~ -C/omega^alpha).  Must be supplied from the known proxy asymptotics;
      C is read off the grid boundary — no fitting is performed.
      None disables the correction (default, original behaviour).
    """
    tail_mode = str(kk_tail).strip().lower()
    if tail_mode == "analytic_proxy":
        # residual KK does not have access to the proxy form here;
        # fall back to zero and let kk_tail_alpha handle the correction
        tail_mode = "zero"

    # Source-of-truth R25 production behavior: --kk-tail-alpha nan means no
    # analytic exterior tail, so the residual KK is evaluated directly on the
    # native feature-refined omega grid.  In that branch the padded/capped
    # auxiliary KK grid is intentionally bypassed even if kk_pad/kk_max_n were
    # passed on the command line.
    if kk_tail_alpha is None:
        return kk_re_pv_linear(np.asarray(omega_grid, dtype=float), np.asarray(delta_im, dtype=float))

    omega_kk, delta_im_kk, delta_re_kk = kk_re_with_optional_powerlaw_tail(
        omega_grid,
        delta_im,
        omega_grid,
        kk_pad=float(kk_pad),
        kk_oversample=float(kk_oversample),
        tail_mode=tail_mode,
        kk_n_max=kk_max_n,
        tail_alpha=kk_tail_alpha,
    )

    return np.interp(omega_grid, omega_kk, delta_re_kk)


def build_residual_omega_taper(
    omega_grid: np.ndarray,
    *,
    start: float,
    stop: float,
    mode: str,
) -> tuple[np.ndarray, str, float, float]:
    """Weight for the numerical residual: 1 in the core, 0 in the asymptotic tail."""
    w = np.asarray(omega_grid, dtype=float)
    weights = np.ones_like(w, dtype=float)
    mode_l = str(mode).strip().lower()

    if mode_l == "none" or not (np.isfinite(float(start)) and np.isfinite(float(stop))):
        return weights, "none", np.nan, np.nan

    start_abs = float(abs(start))
    stop_abs = float(abs(stop))
    if stop_abs <= start_abs:
        raise ValueError(
            "Require residual omega taper stop > start after taking absolute values "
            f"(got start={start_abs:.6g}, stop={stop_abs:.6g})."
        )

    x = np.abs(w)
    if mode_l == "hard":
        weights = np.where(x < start_abs, 1.0, 0.0)
    elif mode_l == "cosine":
        weights = np.ones_like(w, dtype=float)
        weights[x >= stop_abs] = 0.0
        mask = (x > start_abs) & (x < stop_abs)
        t = (x[mask] - start_abs) / (stop_abs - start_abs)
        weights[mask] = 0.5 * (1.0 + np.cos(np.pi * t))
    else:
        raise ValueError(f"Unsupported residual omega taper mode: {mode!r}")

    return weights, mode_l, start_abs, stop_abs


def build_residual_qkin_taper(
    q_grid: np.ndarray,
    omega_grid: np.ndarray,
    *,
    mu_up: float,
    mu_dn: float,
    start_offset: float,
    width: float,
    mode: str,
) -> tuple[np.ndarray, str, float, float]:
    """q-dependent positive-omega taper above (q + kF_up)^2 - mu_down.

    The scalar start/stop CLI arguments are interpreted as an offset added to
    the kinematic threshold and a taper width, respectively.
    """
    q = np.asarray(q_grid, dtype=float)
    w = np.asarray(omega_grid, dtype=float)
    mode_l = str(mode).strip().lower()
    if not mode_l.startswith("qkin_"):
        raise ValueError(f"Unsupported q-kinematic taper mode: {mode!r}")

    offset = 0.0 if not np.isfinite(float(start_offset)) else float(start_offset)
    taper_width = 20.0 if not np.isfinite(float(width)) else float(width)
    if taper_width <= 0.0:
        raise ValueError(f"qkin taper width must be positive, got {taper_width:.6g}.")

    kf_up = float(np.sqrt(max(float(mu_up), 0.0)))
    threshold = (q[:, None] + kf_up) ** 2 - float(mu_dn) + offset
    x = (w[None, :] - threshold) / taper_width
    weights = np.ones((q.size, w.size), dtype=float)

    if mode_l == "qkin_hard":
        weights = np.where(x > 0.0, 0.0, 1.0)
    elif mode_l == "qkin_cosine":
        weights[x >= 1.0] = 0.0
        mask = (x > 0.0) & (x < 1.0)
        weights[mask] = 0.5 * (1.0 + np.cos(np.pi * x[mask]))
    else:
        raise ValueError(f"Unsupported residual omega taper mode: {mode!r}")

    return weights, mode_l, offset, taper_width


def _taper_weight_on_grid(
    q_value: float,
    omega_values: np.ndarray,
    *,
    mode: str,
    start: float,
    stop: float,
    mu_up: float,
    mu_dn: float,
) -> np.ndarray:
    """Evaluate the configured residual taper on an arbitrary omega grid."""
    w = np.asarray(omega_values, dtype=float)
    mode_l = str(mode).strip().lower()
    if mode_l == "none":
        return np.ones_like(w, dtype=float)

    if mode_l.startswith("qkin_"):
        kf_up = float(np.sqrt(max(float(mu_up), 0.0)))
        threshold = (float(q_value) + kf_up) ** 2 - float(mu_dn) + float(start)
        width = float(stop)
        x = (w - threshold) / width
        if mode_l == "qkin_hard":
            return np.where(x > 0.0, 0.0, 1.0)
        if mode_l == "qkin_cosine":
            out = np.ones_like(w, dtype=float)
            out[x >= 1.0] = 0.0
            mask = (x > 0.0) & (x < 1.0)
            out[mask] = 0.5 * (1.0 + np.cos(np.pi * x[mask]))
            return out

    if np.isfinite(float(start)) and np.isfinite(float(stop)):
        start_abs = float(abs(start))
        stop_abs = float(abs(stop))
        x = np.abs(w)
        if mode_l == "hard":
            return np.where(x < start_abs, 1.0, 0.0)
        if mode_l == "cosine":
            out = np.ones_like(w, dtype=float)
            out[x >= stop_abs] = 0.0
            mask = (x > start_abs) & (x < stop_abs)
            t = (x[mask] - start_abs) / (stop_abs - start_abs)
            out[mask] = 0.5 * (1.0 + np.cos(np.pi * t))
            return out

    raise ValueError(f"Unsupported residual omega taper mode: {mode!r}")


def _taper_breakpoints(
    q_value: float,
    *,
    mode: str,
    start: float,
    stop: float,
    mu_up: float,
    mu_dn: float,
) -> list[float]:
    mode_l = str(mode).strip().lower()
    if mode_l == "none":
        return []
    if mode_l.startswith("qkin_"):
        kf_up = float(np.sqrt(max(float(mu_up), 0.0)))
        threshold = (float(q_value) + kf_up) ** 2 - float(mu_dn) + float(start)
        return [threshold, threshold + float(stop)]
    if np.isfinite(float(start)) and np.isfinite(float(stop)):
        start_abs = float(abs(start))
        stop_abs = float(abs(stop))
        return [-stop_abs, -start_abs, start_abs, stop_abs]
    return []


def kk_on_tapered_residual_native(
    omega_grid: np.ndarray,
    delta_im_raw: np.ndarray,
    *,
    q_value: float,
    taper_mode: str,
    taper_start: float,
    taper_stop: float,
    mu_up: float,
    mu_dn: float,
) -> np.ndarray:
    """Native-grid PV KK of a tapered residual, with taper kinks inserted."""
    omega = np.asarray(omega_grid, dtype=float)
    raw = np.asarray(delta_im_raw, dtype=float)
    extra = [
        float(x)
        for x in _taper_breakpoints(
            float(q_value),
            mode=taper_mode,
            start=float(taper_start),
            stop=float(taper_stop),
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
        )
        if float(omega[0]) < float(x) < float(omega[-1])
    ]
    omega_ext = np.unique(np.concatenate([omega, np.asarray(extra, dtype=float)]))
    raw_ext = np.interp(omega_ext, omega, raw)
    weight_ext = _taper_weight_on_grid(
        float(q_value),
        omega_ext,
        mode=taper_mode,
        start=float(taper_start),
        stop=float(taper_stop),
        mu_up=float(mu_up),
        mu_dn=float(mu_dn),
    )
    re_ext = kk_re_pv_linear(omega_ext, raw_ext * weight_ext)
    return np.interp(omega, omega_ext, re_ext)


def main() -> None:
    args = parse_args()
    impi_table_path = Path(args.impi_table_path).expanduser().resolve()
    if not impi_table_path.exists():
        raise FileNotFoundError(f"ImPi table not found: {impi_table_path}")

    q_grid, omega_grid, im_pi_num, support_mean, eps0, mu_up, mu_dn, p_cutoff, im_source_used, meta = load_im_source(
        impi_table_path,
        str(args.im_source),
    )

    re_pi = np.zeros_like(im_pi_num)
    im_pi = np.zeros_like(im_pi_num)
    re_pi_vac = np.zeros_like(im_pi_num)
    im_pi_vac = np.zeros_like(im_pi_num)
    re_pi_proxy_med = np.zeros_like(im_pi_num)
    im_pi_proxy_med = np.zeros_like(im_pi_num)
    re_pi_ref = np.zeros_like(im_pi_num)
    im_pi_ref = np.zeros_like(im_pi_num)
    re_delta_pi_res = np.zeros_like(im_pi_num)
    im_delta_pi_res = np.zeros_like(im_pi_num)
    im_delta_pi_res_raw = np.zeros_like(im_pi_num)
    re_inv_gamma_ref = np.zeros_like(im_pi_num)
    im_inv_gamma_ref = np.zeros_like(im_pi_num)
    re_inv_gamma = np.zeros_like(im_pi_num)
    im_inv_gamma = np.zeros_like(im_pi_num)
    im_inv_gamma_raw = np.zeros_like(im_pi_num)
    re_gamma = np.zeros_like(im_pi_num)
    im_gamma = np.zeros_like(im_pi_num)
    a_pair = np.zeros_like(im_pi_num)

    # Im Gamma^{-1} sign guard: bosonic positivity requires
    # sign(Im Gamma^{-1}(omega)) = sign(omega)  (A_pair(omega<0) <= 0).
    # Quadrature residuals of order <=1e-3 can violate this inside
    # Pauli-blocked windows where the true Im Pi is ~0; near the critical
    # ridge 1/|Gamma^{-1}|^2 amplifies them into wrong-signed spectral
    # weight.  The guard clamps wrong-signed cells to zero (raw kept in
    # ImInvGammaRaw).
    sign_guard_on = str(getattr(args, "im_inv_sign_guard", "on")).strip().lower() in {"on", "1", "true", "yes"}
    sign_guard_total = 0
    omega_sign = np.sign(omega_grid)

    g0_const = g0_constant_from_cutoff(float(p_cutoff), float(eps0))

    out_dir = Path(args.out_dir).expanduser().resolve() if str(args.out_dir).strip() else (
        OUT_BASE / f"run_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    reference_mode_used, eta_reference = choose_reference_mode(str(args.reference_mode), meta)
    eta_gamma_used = float(eta_reference) if reference_mode_used == "lorentzian_fixed_point" else float(args.eta_gamma)
    qp_residual_mode_used = str(args.qp_residual_mode).strip().lower()
    qpqp_source_used = str(args.qpqp_source).strip().lower()
    im_pi_qpqp_from_table: np.ndarray | None = None
    im_pi_qp_residual_from_table: np.ndarray | None = None
    if reference_mode_used == "qp_subtracted":
        with np.load(impi_table_path) as d:
            if "ImPiQPQP" in d.files and qpqp_source_used != "analytic":
                candidate = np.asarray(d["ImPiQPQP"], dtype=float)
                if candidate.shape != im_pi_num.shape:
                    raise ValueError(
                        "ImPiQPQP in the ImPi table has shape "
                        f"{candidate.shape}, expected {im_pi_num.shape}."
                    )
                im_pi_qpqp_from_table = candidate
            if qp_residual_mode_used == "incinc_only" and "ImPiIncInc" in d.files:
                residual_candidate = np.asarray(d["ImPiIncInc"], dtype=float)
                if residual_candidate.shape != im_pi_num.shape:
                    raise ValueError(
                        "ImPiIncInc in the ImPi table has shape "
                        f"{residual_candidate.shape}, expected {im_pi_num.shape}."
                    )
                im_pi_qp_residual_from_table = residual_candidate
            elif qp_residual_mode_used == "cross_inc" and all(k in d.files for k in ("ImPiQPInc", "ImPiIncQP", "ImPiIncInc")):
                residual_candidate = (
                    np.asarray(d["ImPiQPInc"], dtype=float)
                    + np.asarray(d["ImPiIncQP"], dtype=float)
                    + np.asarray(d["ImPiIncInc"], dtype=float)
                )
                if residual_candidate.shape != im_pi_num.shape:
                    raise ValueError(
                        "QP residual components in the ImPi table have shape "
                        f"{residual_candidate.shape}, expected {im_pi_num.shape}."
                    )
                im_pi_qp_residual_from_table = residual_candidate
            elif qp_residual_mode_used not in {"cross_inc", "incinc_only", "full_minus_qpqp"}:
                raise ValueError(f"Unsupported qp_residual_mode: {qp_residual_mode_used!r}")

    tail_mode = str(args.kk_tail).strip().lower()
    tail_mode_used = "zero" if tail_mode == "analytic_proxy" else tail_mode
    kk_max_n = int(args.kk_max_n) if int(args.kk_max_n) > 0 else None
    kk_tail_alpha_used = (
        float(args.kk_tail_alpha)
        if args.kk_tail_alpha is not None and np.isfinite(float(args.kk_tail_alpha))
        else None
    )
    kk_effective_mode = "native_pv" if kk_tail_alpha_used is None else "padded_optional_tail"
    taper_mode_req = str(args.residual_omega_taper_mode).strip().lower()
    if taper_mode_req.startswith("qkin_"):
        residual_taper_weight, residual_taper_mode_used, residual_taper_start, residual_taper_stop = build_residual_qkin_taper(
            q_grid,
            omega_grid,
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
            start_offset=float(args.residual_omega_taper_start),
            width=float(args.residual_omega_taper_stop),
            mode=taper_mode_req,
        )
    else:
        residual_taper_weight, residual_taper_mode_used, residual_taper_start, residual_taper_stop = build_residual_omega_taper(
            omega_grid,
            start=float(args.residual_omega_taper_start),
            stop=float(args.residual_omega_taper_stop),
            mode=taper_mode_req,
        )

    # ------------------------------------------------------------------
    # qp_subtracted: load SC cubes and extract QP poles before the loop
    # ------------------------------------------------------------------
    qp_up_k = qp_up_e = qp_up_z = qp_up_gamma = qp_up_mu = qp_up_mass = None
    qp_dn_k = qp_dn_e = qp_dn_z = qp_dn_gamma = qp_dn_mu = qp_dn_mass = None
    p_grid_qpqp: np.ndarray | None = None

    if reference_mode_used == "qp_subtracted" and (im_pi_qpqp_from_table is None or qpqp_source_used == "analytic"):
        up_cube_path = str(meta.get("up_cube_path", "")).strip()
        dn_cube_path = str(meta.get("down_cube_path", "")).strip()
        if not up_cube_path or not dn_cube_path:
            raise ValueError(
                "qp_subtracted mode requires up_cube_path and down_cube_path in the ImPi "
                "table metadata. Run make_impi_table.py with SC cubes that store these fields."
            )
        print(f"[qpqp] loading up  cube: {up_cube_path}", flush=True)
        (qp_up_k, qp_up_w, qp_up_re_s, qp_up_im_s,
         qp_up_mu, qp_up_mass, _up_mu_up, _up_mu_dn, _up_spin,
         _find_dyson, _compute_z) = _load_sc_cube_for_qp(up_cube_path)
        print(f"[qpqp] loading dn  cube: {dn_cube_path}", flush=True)
        (qp_dn_k, qp_dn_w, qp_dn_re_s, qp_dn_im_s,
         qp_dn_mu, qp_dn_mass, _dn_mu_up, _dn_mu_dn, _dn_spin,
         _, _) = _load_sc_cube_for_qp(dn_cube_path)

        xi_cut = float(args.qpqp_xi_cutoff)
        print(f"[qpqp] extracting up QP poles ...", flush=True)
        qp_up_e, qp_up_z, qp_up_gamma, _up_valid = _extract_qp_poles(
            qp_up_k, qp_up_w, qp_up_re_s, qp_up_im_s,
            qp_up_mu, qp_up_mass, xi_cut, _find_dyson, _compute_z,
        )
        print(f"[qpqp] extracting dn QP poles ...", flush=True)
        qp_dn_e, qp_dn_z, qp_dn_gamma, _dn_valid = _extract_qp_poles(
            qp_dn_k, qp_dn_w, qp_dn_re_s, qp_dn_im_s,
            qp_dn_mu, qp_dn_mass, xi_cut, _find_dyson, _compute_z,
        )

        p_min_qp = max(float(qp_up_k[0]), float(qp_dn_k[0]))
        p_max_qp = min(float(qp_up_k[-1]), float(qp_dn_k[-1]))
        p_grid_qpqp = np.linspace(p_min_qp, p_max_qp, int(args.qpqp_n_p))
        print(
            f"[qpqp] p_grid [{p_min_qp:.4f},{p_max_qp:.4f}] n={int(args.qpqp_n_p)}, "
            f"n_phi={int(args.qpqp_n_phi)}", flush=True,
        )
    elif reference_mode_used == "qp_subtracted":
        print(
            "[qpqp] using ImPiQPQP from the ImPi table; "
            "residual is full minus QP-QP on the same quadrature.",
            flush=True,
        )
        if im_pi_qp_residual_from_table is not None:
            print(
                f"[qpqp] using saved {qp_residual_mode_used} residual; "
                "no post-hoc Full-QPQP subtraction.",
                flush=True,
            )

    print(f"[info] ImPi table : {impi_table_path}")
    print(f"[info] out dir    : {out_dir}")
    print(f"[info] q grid     : [{q_grid[0]:+.3f},{q_grid[-1]:+.3f}] n={q_grid.size}")
    print(f"[info] omega grid : [{omega_grid[0]:+.3f},{omega_grid[-1]:+.3f}] n={omega_grid.size}")
    print(f"[info] source     : {im_source_used}")
    print(f"[info] p cutoff   : {float(p_cutoff):+.6f}")
    print(f"[info] g0 const   : {float(g0_const):+.12e}")
    print(
        f"[info] kk         : tail={tail_mode_used}, pad={float(args.kk_pad):.3g}, "
        f"oversample={float(args.kk_oversample):.3g}, max_n={kk_max_n if kk_max_n is not None else 'uncapped'}, "
        f"effective={kk_effective_mode}"
    )
    print(
        f"[info] res taper  : mode={residual_taper_mode_used}, "
        f"|omega|=[{residual_taper_start:+.6g},{residual_taper_stop:+.6g}], "
        f"min_weight={float(np.min(residual_taper_weight)):.3g}"
    )
    print(f"[info] reference  : {reference_mode_used} (eta_gamma={eta_gamma_used:.6g})")
    if reference_mode_used == "qp_subtracted":
        print(f"[info] qp residual: mode={qp_residual_mode_used}, qpqp_source={qpqp_source_used}")

    im_pi_qpqp_table = np.zeros_like(im_pi_num)  # filled only in qp_subtracted mode

    for iq, qv in enumerate(q_grid):
        residual_taper_weight_i = (
            residual_taper_weight[iq]
            if np.ndim(residual_taper_weight) == 2
            else residual_taper_weight
        )
        pi_vac_i = vacuum_pi_from_cutoff(
            omega_grid,
            q=float(qv),
            eps0=float(eps0),
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
            eta_gamma=float(eta_gamma_used),
            cutoff=float(p_cutoff),
        )
        pi_proxy_med_i = proxy_medium_pi_from_gamma(
            omega_grid,
            q=float(qv),
            eps0=float(eps0),
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
            eta_gamma=float(eta_gamma_used),
        )
        pi_ref_i = proxy_full_pi_from_gamma(
            omega_grid,
            q=float(qv),
            eps0=float(eps0),
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
            eta_gamma=float(eta_gamma_used),
            cutoff=float(p_cutoff),
        )
        inv_gamma_ref_proxy_i = g0_inverse(
            omega_grid,
            q=float(qv),
            eps0=float(eps0),
            mu_up=float(mu_up),
            mu_dn=float(mu_dn),
            eta_gamma=float(eta_gamma_used),
        ) - pi_proxy_med_i

        if reference_mode_used == "lorentzian_fixed_point":
            inv_gamma_ref_i = inv_gamma_ref_proxy_i
            delta_im_i_raw = np.zeros_like(omega_grid, dtype=float)
            delta_im_i = np.zeros_like(omega_grid, dtype=float)
            delta_re_i = np.zeros_like(omega_grid, dtype=float)
            delta_pi_i = np.zeros_like(pi_ref_i, dtype=complex)
            pi_num_i = np.asarray(pi_ref_i, dtype=complex)
            inv_gamma_i = np.asarray(inv_gamma_ref_i, dtype=complex)
            pi_ref_save_i = np.asarray(pi_ref_i, dtype=complex)

        elif reference_mode_used == "direct_vacuum_kk":
            # Exact finite-cutoff decomposition:
            #   Pi_num = Pi_vac,Lambda + KK[Im(Pi_num-Pi_vac,Lambda)]
            # No proxy, QP reference, taper, padding, or analytic exterior is
            # introduced.  This is intentionally identical to the frozen
            # build_clean_smooth_pair validation path.
            inv_gamma_ref_i = float(g0_const) - np.asarray(pi_vac_i, dtype=complex)
            delta_im_i_raw = np.asarray(im_pi_num[iq], dtype=float) - np.imag(pi_vac_i)
            delta_im_i = np.asarray(delta_im_i_raw, dtype=float)
            delta_re_i = kk_re_pv_linear(omega_grid, delta_im_i_raw)
            delta_pi_i = delta_re_i + 1j * delta_im_i
            pi_num_i = np.asarray(pi_vac_i, dtype=complex) + delta_pi_i
            inv_gamma_i = float(g0_const) - pi_num_i
            pi_ref_save_i = np.asarray(pi_vac_i, dtype=complex)

        elif reference_mode_used == "qp_subtracted":
            # Prefer the QP-QP component saved by make_impi_table.py: it was
            # integrated on the same (p, eps, omega) quadrature as ImPiNum, so
            # Delta ImPi = ImPiFull - ImPiQPQP performs the UV cancellation at
            # the integrand/quadrature level.  Fall back to the older analytic
            # QP-QP rebuild only for legacy ImPi tables without ImPiQPQP.
            if im_pi_qpqp_from_table is not None and qpqp_source_used != "analytic":
                im_pi_qpqp_i = np.asarray(im_pi_qpqp_from_table[iq], dtype=float)
            else:
                # Im(Pi_QP-QP) → 0 at large Omega (finite k_cut Lorentzian tails) — UV safe
                im_pi_qpqp_i = _compute_impi_qpqp(
                    float(qv), omega_grid,
                    qp_up_k, qp_up_e, qp_up_z, qp_up_gamma, qp_up_mu, qp_up_mass,
                    qp_dn_k, qp_dn_e, qp_dn_z, qp_dn_gamma, qp_dn_mu, qp_dn_mass,
                    p_grid_qpqp, int(args.qpqp_n_phi),
                )
            im_pi_qpqp_table[iq] = im_pi_qpqp_i
            # Re(Pi_QP-QP) via UV-safe KK (tail → 0)
            re_pi_qpqp_i = kk_on_residual(
                omega_grid, im_pi_qpqp_i,
                kk_pad=float(args.kk_pad),
                kk_oversample=float(args.kk_oversample),
                kk_tail="zero",
                kk_max_n=kk_max_n,
            )
            pi_qpqp_i = re_pi_qpqp_i + 1j * im_pi_qpqp_i
            # Standard finite-cutoff convention: Gamma^{-1}=g0_Lambda^{-1}-Pi.
            inv_gamma_ref_i = float(g0_const) - pi_qpqp_i
            # residual = SC - QP-QP → 0 at large Omega.  Prefer the saved
            # QPInc+IncQP+IncInc components because they were integrated as
            # subtracted terms, avoiding a post-hoc cancellation of two larger
            # tables.
            if im_pi_qp_residual_from_table is not None:
                delta_im_i_raw = np.asarray(im_pi_qp_residual_from_table[iq], dtype=float)
            else:
                delta_im_i_raw = np.asarray(im_pi_num[iq], dtype=float) - im_pi_qpqp_i
            delta_im_i = delta_im_i_raw * residual_taper_weight_i
            if kk_max_n is None and float(args.kk_pad) == 0.0 and kk_tail_alpha_used is None:
                delta_re_i = kk_on_tapered_residual_native(
                    omega_grid,
                    delta_im_i_raw,
                    q_value=float(qv),
                    taper_mode=residual_taper_mode_used,
                    taper_start=float(residual_taper_start),
                    taper_stop=float(residual_taper_stop),
                    mu_up=float(mu_up),
                    mu_dn=float(mu_dn),
                )
            else:
                delta_re_i = kk_on_residual(
                    omega_grid, delta_im_i,
                    kk_pad=float(args.kk_pad),
                    kk_oversample=float(args.kk_oversample),
                    kk_tail=str(args.kk_tail),
                    kk_max_n=kk_max_n,
                    kk_tail_alpha=kk_tail_alpha_used,
                )
            delta_pi_i = delta_re_i + 1j * delta_im_i
            pi_num_i = pi_qpqp_i + delta_pi_i
            inv_gamma_i = inv_gamma_ref_i - delta_pi_i
            pi_ref_save_i = pi_qpqp_i

        else:  # proxy_residual
            inv_gamma_ref_i = inv_gamma_ref_proxy_i
            delta_im_i_raw = np.asarray(im_pi_num[iq], dtype=float) - np.imag(pi_ref_i)
            delta_im_i = delta_im_i_raw * residual_taper_weight_i
            if kk_max_n is None and float(args.kk_pad) == 0.0 and kk_tail_alpha_used is None:
                delta_re_i = kk_on_tapered_residual_native(
                    omega_grid,
                    delta_im_i_raw,
                    q_value=float(qv),
                    taper_mode=residual_taper_mode_used,
                    taper_start=float(residual_taper_start),
                    taper_stop=float(residual_taper_stop),
                    mu_up=float(mu_up),
                    mu_dn=float(mu_dn),
                )
            else:
                delta_re_i = kk_on_residual(
                    omega_grid,
                    delta_im_i,
                    kk_pad=float(args.kk_pad),
                    kk_oversample=float(args.kk_oversample),
                    kk_tail=str(args.kk_tail),
                    kk_max_n=kk_max_n,
                    kk_tail_alpha=kk_tail_alpha_used,
                )
            delta_pi_i = delta_re_i + 1j * delta_im_i
            pi_num_i = pi_ref_i + delta_pi_i
            inv_gamma_i = inv_gamma_ref_proxy_i - delta_pi_i
            pi_ref_save_i = np.asarray(pi_ref_i, dtype=complex)

        im_inv_gamma_raw[iq] = np.imag(inv_gamma_i)
        n_guard_i = 0
        if sign_guard_on:
            im_i = np.imag(inv_gamma_i)
            wrong = np.where(omega_sign != 0.0, im_i * omega_sign < 0.0, im_i != 0.0)
            n_guard_i = int(np.count_nonzero(wrong))
            if n_guard_i:
                inv_gamma_i = np.real(inv_gamma_i) + 1j * np.where(wrong, 0.0, im_i)
                sign_guard_total += n_guard_i

        gamma_i = 1.0 / inv_gamma_i

        re_pi_vac[iq] = np.real(pi_vac_i)
        im_pi_vac[iq] = np.imag(pi_vac_i)
        re_pi_proxy_med[iq] = np.real(pi_proxy_med_i)
        im_pi_proxy_med[iq] = np.imag(pi_proxy_med_i)
        re_pi_ref[iq] = np.real(pi_ref_save_i)
        im_pi_ref[iq] = np.imag(pi_ref_save_i)
        re_delta_pi_res[iq] = delta_re_i
        im_delta_pi_res_raw[iq] = delta_im_i_raw
        im_delta_pi_res[iq] = delta_im_i
        re_pi[iq] = np.real(pi_num_i)
        im_pi[iq] = np.imag(pi_num_i)
        re_inv_gamma_ref[iq] = np.real(inv_gamma_ref_i)
        im_inv_gamma_ref[iq] = np.imag(inv_gamma_ref_i)
        re_inv_gamma[iq] = np.real(inv_gamma_i)
        im_inv_gamma[iq] = np.imag(inv_gamma_i)
        re_gamma[iq] = np.real(gamma_i)
        im_gamma[iq] = np.imag(gamma_i)
        a_pair[iq] = -(1.0 / np.pi) * np.imag(gamma_i)

        io0 = int(np.argmin(np.abs(omega_grid)))
        tail_im = float(delta_im_i[-1]) if delta_im_i.size > 0 else float("nan")
        print(
            f"[info] ({iq + 1}/{q_grid.size}) q={qv:+.6f} support_mean={support_mean[iq]:.4f} "
            f"ImDeltaPi_res(0~)={delta_im_i[io0]:+.6e} ImDeltaPi_res(tail)={tail_im:+.6e} "
            f"ReInvGamma(0~)={np.real(inv_gamma_i[io0]):+.6e} im_guard={n_guard_i}"
        )

    if sign_guard_on:
        print(
            f"[info] ImInvGamma sign guard: clamped {sign_guard_total} wrong-signed cells "
            f"({100.0 * sign_guard_total / max(im_inv_gamma_raw.size, 1):.2f}% of table)"
        )

    out_npz = out_dir / "pair_gamma_table.npz"
    np.savez_compressed(
        out_npz,
        q=q_grid.astype(np.float64),
        omega=omega_grid.astype(np.float64),
        ImPiNum=im_pi_num.astype(np.float64),
        ImPiQPQP=im_pi_qpqp_table.astype(np.float64),
        RePi=re_pi.astype(np.float64),
        ImPi=im_pi.astype(np.float64),
        RePiVacuum=re_pi_vac.astype(np.float64),
        ImPiVacuum=im_pi_vac.astype(np.float64),
        RePiProxyMedium=re_pi_proxy_med.astype(np.float64),
        ImPiProxyMedium=im_pi_proxy_med.astype(np.float64),
        RePiReference=re_pi_ref.astype(np.float64),
        ImPiReference=im_pi_ref.astype(np.float64),
        ReDeltaPiResidual=re_delta_pi_res.astype(np.float64),
        ImDeltaPiResidual=im_delta_pi_res.astype(np.float64),
        ImDeltaPiResidualRaw=im_delta_pi_res_raw.astype(np.float64),
        ReInvGammaReference=re_inv_gamma_ref.astype(np.float64),
        ImInvGammaReference=im_inv_gamma_ref.astype(np.float64),
        ReInvGamma=re_inv_gamma.astype(np.float64),
        ImInvGamma=im_inv_gamma.astype(np.float64),
        ImInvGammaRaw=im_inv_gamma_raw.astype(np.float64),
        im_inv_sign_guard=np.array("on" if sign_guard_on else "off"),
        im_inv_sign_guard_points=np.array(int(sign_guard_total), dtype=np.int64),
        ReGamma=re_gamma.astype(np.float64),
        ImGamma=im_gamma.astype(np.float64),
        A_pair=a_pair.astype(np.float64),
        support_mean=support_mean.astype(np.float64),
        eps0=np.array(float(eps0), dtype=np.float64),
        mu_up=np.array(float(mu_up), dtype=np.float64),
        mu_dn=np.array(float(mu_dn), dtype=np.float64),
        g0_const=np.array(float(g0_const), dtype=np.float64),
        p_int_max=np.array(float(p_cutoff), dtype=np.float64),
        eta_gamma=np.array(float(eta_gamma_used), dtype=np.float64),
        kernel=np.array("direct_vacuum_kk" if reference_mode_used == "direct_vacuum_kk" else "proxy_residual"),
        reference=np.array("finite_cutoff_vacuum" if reference_mode_used == "direct_vacuum_kk" else "proxy_full_cutoff_matched"),
        reference_mode=np.array(str(reference_mode_used)),
        reconstruction=np.array(
            "finite_cutoff_vacuum_plus_native_residual_kk"
            if reference_mode_used == "direct_vacuum_kk"
            else "gamma_proxy_minus_delta_pi_res"
        ),
        im_source=np.array(str(im_source_used)),
        kk_tail=np.array(str(tail_mode_used)),
        kk_effective_mode=np.array(str(kk_effective_mode)),
        kk_pad=np.array(float(args.kk_pad), dtype=np.float64),
        kk_oversample=np.array(float(args.kk_oversample), dtype=np.float64),
        kk_max_n=np.array(-1 if kk_max_n is None else int(kk_max_n), dtype=np.int64),
        residual_omega_taper_weight=residual_taper_weight.astype(np.float64),
        residual_omega_taper_mode=np.array(str(residual_taper_mode_used)),
        residual_omega_taper_start=np.array(float(residual_taper_start), dtype=np.float64),
        residual_omega_taper_stop=np.array(float(residual_taper_stop), dtype=np.float64),
        qpqp_xi_cutoff=np.array(float(args.qpqp_xi_cutoff), dtype=np.float64),
        qpqp_n_p=np.array(int(args.qpqp_n_p), dtype=np.int64),
        qpqp_n_phi=np.array(int(args.qpqp_n_phi), dtype=np.int64),
    )
    print(f"[info] saved: {out_npz}")

    # Cluster-minimal copy: diagnostics and plotting are intentionally omitted.


if __name__ == "__main__":
    main()
