# =====================================================================
# SLIM copy of critical_line/pair_shifted.py
#
# 9 top-level symbols (311 lines, 61% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   apply_shift_to_pair_table, load_pair_table
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   g0_inv_shifted
#   inv_gamma_shifted
#   find_q_fflo
#   default_q_fflo_window
#   q_fflo_from_luttinger_mu
#   extract_eps0
#   extract_eps0_from_re_inv_gamma
#   find_q_best_channel
#   critical_eps0_from_pair_table
# =====================================================================
"""Coupling-independent shifted pair propagator and Thouless ε₀ extraction.

Theory (fflo_cluster_description.tex, §Computation of the critical line):

    Γ⁻¹_shifted(Q,Ω) ≡ Γ⁻¹(Q,Ω) - Γ⁻¹(Q_FFLO, 0⁺)

The coupling ε₀ enters Γ⁻¹ only through the reference piece [Γ₀^ref]⁻¹ = g₀⁻¹:

    g₀⁻¹(Q,Ω) = -(1/8π) log[(Q²/2 − μ_↑ − μ_↓ − Ω − iη) / ε₀]

Its difference at two points cancels ε₀:

    g₀⁻¹(Q,Ω) − g₀⁻¹(Q_FFLO,0) = (1/8π) log[(Q_FFLO²/2 − μ − Ω_thr) /
                                                 (Q²/2 − μ − Ω − iη)]

where μ = μ_↑ + μ_↓ and Ω_thr = 0 at the FFLO point.

The full shifted Γ⁻¹ is therefore ε₀-independent:

    Γ⁻¹_shifted(Q,Ω) = [g₀⁻¹(Q,Ω) − g₀⁻¹(Q_FFLO,0)] − ΔΠ(Q,Ω) + ΔΠ(Q_FFLO,0)

where ΔΠ = Π_num_medium − Π_proxy_medium is the coupling-independent residual.

After a self-consistent run with the shifted propagator (§sc_critical.py) the physical
coupling is extracted from the Thouless condition Γ⁻¹(Q_FFLO,0) = 0:

    g₀⁻¹(Q_FFLO, 0) = Π_num_medium(Q_FFLO, 0)
    ε₀ = |Q_FFLO²/2 − μ_↑ − μ_↓| · exp(8π · Re[Π_num_medium(Q_FFLO, 0)])

Note: applied to a run NOT at the critical point this gives an approximation;
the exact ε₀ requires Green's functions from the critical-point SC (§sc_critical.py).
"""

from __future__ import annotations

import numpy as np
from pathlib import Path
















def load_pair_table(path: Path | str) -> dict:
    """Load a pair_gamma_table.npz and return a plain dict with float/array entries."""
    d = np.load(str(path))
    out = {}
    for k in d.keys():
        v = d[k]
        if v.ndim == 0:
            out[k] = float(v) if v.dtype.kind in "fiu" else str(v)
        else:
            out[k] = np.asarray(v)
    return out






def apply_shift_to_pair_table(
    pair_table: dict,
    Q_fflo: float,
    *,
    inplace: bool = False,
    subcritical_delta: float = 0.0,
    eta_floor_mode: str = "broad",
    base_shift_override: float | None = None,
) -> dict:
    """Return a pair table where Gamma is replaced by the Thouless-shifted Gamma.

    The shift is

        Gamma_shifted^{-1}(Q, omega)
          = Gamma^{-1}(Q, omega) - Re Gamma^{-1}(Q_fflo, 0) - subcritical_delta

    so that Re Gamma_shifted^{-1}(Q_fflo, 0) = -subcritical_delta.  With
    ``subcritical_delta=0`` (default) the system sits exactly at the Thouless
    point; a small positive delta parks it just on the stable side, which
    regularizes the undamped pinned mode when the winning channel lies inside
    the Pauli-blocked window (q~0 channel at high polarization).  Since the
    shift is equivalent to a coupling change, observables can be extrapolated
    delta -> 0 across runs.

    The sigma code only consumes ``A_pair``, but we recompute ``ReGamma``,
    ``ImGamma``, and ``A_pair`` together so the saved shifted table remains
    internally consistent.
    """
    t = pair_table if inplace else {
        key: value.copy() if isinstance(value, np.ndarray) else value
        for key, value in pair_table.items()
    }

    q = np.asarray(t["q"], dtype=float)
    omega = np.asarray(t["omega"], dtype=float)
    re_inv = np.asarray(t["ReInvGamma"], dtype=float)
    im_inv = np.asarray(t["ImInvGamma"], dtype=float)
    if q.ndim != 1 or omega.ndim != 1 or re_inv.shape != (q.size, omega.size):
        raise ValueError(
            f"Invalid pair table shapes for Thouless shift: "
            f"q{q.shape}, omega{omega.shape}, ReInvGamma{re_inv.shape}"
        )
    if im_inv.shape != re_inv.shape:
        raise ValueError(
            f"Invalid ImInvGamma shape for Thouless shift: expected {re_inv.shape}, got {im_inv.shape}"
        )

    iw0 = int(np.argmin(np.abs(omega)))
    delta = float(subcritical_delta)
    if not np.isfinite(delta):
        delta = 0.0
    # base_shift_override: congela l'accoppiamento invece di ritararlo.
    # Lo schema normale ricalcola ReGamma^-1(Q_fflo,0) a ogni iterazione e lo
    # sottrae, il che equivale a cambiare g a ogni giro. Il vincolo pero' fissa
    # UN PUNTO mentre il contact e' un integrale su tutta la superficie (Q,Omega):
    # misurato il 2026-09-22, riapplicando sempre lo shift della prima iterazione
    # il contact converge a 0.2745, mentre ricalcolandolo cresce senza limite
    # (0.576 -> 1.081 in 13 iterazioni). Con l'override si gira a g fisso.
    if base_shift_override is not None and np.isfinite(float(base_shift_override)):
        base_shift = float(base_shift_override)
    else:
        base_shift = float(np.interp(float(Q_fflo), q, re_inv[:, iw0]))
    shift = base_shift + delta
    re_shifted = re_inv - shift

    eta_floor = abs(float(t.get("eta_gamma", 1.0e-3)))
    if not np.isfinite(eta_floor) or eta_floor <= 0.0:
        eta_floor = 1.0e-3

    im_shifted = np.array(im_inv, dtype=float, copy=True)
    floor_mode = str(eta_floor_mode).strip().lower()
    if floor_mode not in {"broad", "exact_zero"}:
        raise ValueError(f"Unsupported eta_floor_mode: {eta_floor_mode!r}")
    if floor_mode == "broad":
        zero_denom = (np.abs(re_shifted) < eta_floor) & (np.abs(im_shifted) < eta_floor)
    else:
        # The validated direct-vacuum cycle leaves every nonzero causal cell
        # untouched and removes only the sampled zero-measure Thouless point.
        # Broadly replacing Im Gamma^-1 after its KK reconstruction breaks the
        # causal pair and changes the Sigma functional.
        zero_denom = np.hypot(re_shifted, im_shifted) <= 1.0e-14
    if floor_mode == "broad" and np.any(zero_denom):
        # The Thouless shift intentionally makes Re Gamma^{-1}(Q_FFLO, 0)=0.
        # Keep the retarded regulator in the saved table so Sigma never sees
        # an exact 1/0 pole at a sampled grid point — but keep it ODD in
        # omega: Im Gamma^{-1} carries sign(omega) (bosonic positivity,
        # A_pair(omega<0) <= 0).  A constant +eta here would inject
        # wrong-signed A_pair = +1/(pi*eta) on the occupied side of every
        # near-critical point; that is fatal once the winning channel sits
        # inside the Pauli-blocked window (q~0 at high P), where the whole
        # soft region satisfies |Im Gamma^{-1}| < eta.
        odd_eta = eta_floor * np.where(omega < 0.0, -1.0, 1.0)[None, :]
        im_shifted = np.where(zero_denom, np.broadcast_to(odd_eta, im_shifted.shape), im_shifted)

    denom = re_shifted + 1j * im_shifted
    gamma = np.zeros(denom.shape, dtype=complex)
    with np.errstate(divide="ignore", invalid="ignore"):
        np.divide(1.0, denom, out=gamma, where=~zero_denom)

    a_pair = -(1.0 / np.pi) * np.imag(gamma)
    if float(omega[iw0]) == 0.0:
        # A_pair(q, omega=0) is exactly zero (odd spectral function).  Without
        # this, the floored pinned nodes carry a +1/(pi*eta) spike at omega=0
        # that linear interpolation in the sigma step smears into the occupied
        # side.
        pinned0 = zero_denom[:, iw0]
        gamma[pinned0, iw0] = np.real(gamma[pinned0, iw0])
        a_pair[pinned0, iw0] = 0.0

    t["ReInvGamma"] = re_shifted.astype(np.float64)
    t["ImInvGamma"] = im_shifted.astype(np.float64)
    t["ReGamma"] = np.real(gamma).astype(np.float64)
    t["ImGamma"] = np.imag(gamma).astype(np.float64)
    t["A_pair"] = a_pair.astype(np.float64)
    # Compatibility metadata consumed by the pre-Sigma gamma gate and by
    # older diagnostics.  This is the complete inverse-propagator shift,
    # including the optional normal-side subcritical delta.
    t["pair_shift"] = np.array(float(shift), dtype=np.float64)
    t["thouless_shift_q_fflo"] = np.array(float(Q_fflo), dtype=np.float64)
    t["thouless_shift_re_inv_gamma_q0"] = np.array(float(base_shift), dtype=np.float64)
    t["thouless_shift_subcritical_delta"] = np.array(float(delta), dtype=np.float64)
    t["thouless_shift_eta_floor"] = np.array(float(eta_floor), dtype=np.float64)
    t["thouless_shift_eta_floor_mode"] = np.array(str(floor_mode))
    t["thouless_shift_eta_floor_points"] = np.array(int(np.count_nonzero(zero_denom)), dtype=np.int64)
    return t
