# =====================================================================
# SLIM copy of diagnostics/run_inline_qp_product_p065.py
#
# 0 top-level symbols (0 lines, 0% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   main
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
# =====================================================================
#!/usr/bin/env python3
"""Frozen-cube ImPi builder for matched and direct-product diagnostics."""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor
import os
from pathlib import Path
import subprocess
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
PIPELINE = ROOT
sys.path.insert(0, str(ROOT))

from fflo.qp_cube import build_qp_cube, qp_model_from_cube  # noqa: E402
from fflo.impi_cv import (  # noqa: E402
    _canonical_qp_fields,
    _cv_init,
    _cv_work,
    _kf,
)


DEFAULT_RUN = (
    ROOT
    / "cluster_pull/proxy_product_fast80_fix_live/manual_P0p65_20260803_094811"
    / "proxy_product_P0p65_fast80_a0p20_it8/sc"
)
DEFAULT_UP = DEFAULT_RUN / "iter_002/cubes/A_komega_spinup_iter002.npz"
DEFAULT_DOWN = DEFAULT_RUN / "iter_002/cubes/A_komega_spindown_iter002.npz"
DEFAULT_OLD_PAIR = DEFAULT_RUN / "iter_003/pair/pair_gamma_table.npz"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--up", type=Path, default=DEFAULT_UP)
    parser.add_argument("--down", type=Path, default=DEFAULT_DOWN)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=ROOT / "diagnostics/inline_qp_product_p065",
    )
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--profile", choices=("turbo", "quick", "gold"), default="quick")
    parser.add_argument(
        "--impi-scheme",
        choices=("matched", "direct"),
        default="matched",
        help="Use the matched control variate or integrate the full A*A product directly.",
    )
    parser.add_argument("--lattice-n-linear", type=int, default=0)
    parser.add_argument("--lattice-n-tail", type=int, default=0)
    parser.add_argument("--p-nodes", type=int, default=0)
    parser.add_argument("--p-feature-width", type=float, default=float("nan"))
    parser.add_argument("--p-feature-nodes", type=int, default=-1)
    parser.add_argument("--angular-nodes", type=int, default=0)
    parser.add_argument("--angular-feature-nodes", type=int, default=-1)
    parser.add_argument("--coherent-nk", type=int, default=0)
    parser.add_argument("--coherent-nquad", type=int, default=0)
    parser.add_argument(
        "--q-core-dq",
        type=float,
        default=0.0,
        help="If positive, replace the profile Q points with a uniform [0,q-core-max] grid.",
    )
    parser.add_argument("--q-core-max", type=float, default=2.0)
    parser.add_argument("--q-table-max", type=float, default=11.5)
    parser.add_argument(
        "--q-tail-points",
        default="4.0,6.0,8.0",
        help="Comma-separated Q points appended to a uniform Q core.",
    )
    parser.add_argument(
        "--q-points",
        default="",
        help="Explicit comma-separated Q audit points; overrides the profile/core Q list.",
    )
    parser.add_argument("--q-local-center", type=float, default=float("nan"))
    parser.add_argument("--q-local-half-width", type=float, default=0.0)
    parser.add_argument("--q-local-dq", type=float, default=0.0)
    parser.add_argument("--omega-feature-half-width", type=float, default=0.0)
    parser.add_argument("--omega-feature-nodes", type=int, default=0)
    parser.add_argument(
        "--omega-feature-mode",
        choices=("zero", "zero_and_thresholds", "paper_thresholds"),
        default="zero",
    )
    parser.add_argument("--omega-feature-q-min", type=float, default=float("nan"))
    parser.add_argument("--omega-feature-q-max", type=float, default=float("nan"))
    parser.add_argument("--omega-feature-q-max-points", type=int, default=0)
    parser.add_argument(
        "--kf-feature-source",
        choices=("occupation", "free"),
        default="free",
        help="Choose the kF used only for ImPi quadrature feature placement.",
    )
    parser.add_argument("--old-pair", type=Path, default=DEFAULT_OLD_PAIR)
    parser.add_argument("--skip-pair", action="store_true")
    parser.add_argument(
        "--reference-mode",
        choices=("auto", "proxy_residual", "lorentzian_fixed_point",
                 "qp_subtracted", "direct_vacuum_kk"),
        default="proxy_residual",
        help=(
            "KK reference passed through to make_pair_gamma_table_proxy_residual.py. "
            "qp_subtracted uses the dressed QP-QP bubble, whose kernel "
            "(e<0)+(e>Omega)-1 carries the Pauli kinematics, so the hole-hole "
            "(Omega<0) side is referenced consistently with the particle-particle "
            "side. proxy_residual (the historical default) leaves ImPiQPQP=0."
        ),
    )
    parser.add_argument(
        "--qpqp-xi-cutoff",
        type=float,
        default=0.015,
        help=(
            "Half-width in |xi_k| of the shell where QP poles are extracted for "
            "the QP-QP bubble. The 0.015 default only covers a sliver at kF, which "
            "is enough for a Z measurement but not for building a global QP-QP "
            "reference; widen it when using --reference-mode qp_subtracted."
        ),
    )
    return parser.parse_args()


def run(command: list[str], *, env: dict[str, str] | None = None, log: Path) -> None:
    log.parent.mkdir(parents=True, exist_ok=True)
    with log.open("w", encoding="ascii") as stream:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            env=env,
            stdout=stream,
            stderr=subprocess.STDOUT,
            check=False,
            text=True,
        )
    if completed.returncode:
        raise RuntimeError(f"command failed ({completed.returncode}); see {log}")


def pair_q_zero_cut(path: Path) -> tuple[np.ndarray, np.ndarray]:
    with np.load(path, allow_pickle=True) as data:
        q = np.asarray(data["q"], dtype=float)
        omega = np.asarray(data["omega"], dtype=float)
        values = np.asarray(data["ReInvGamma"], dtype=float)
    return q, np.asarray(
        [np.interp(0.0, omega, row) for row in values],
        dtype=float,
    )


def main() -> None:
    args = parse_args()
    up = args.up.resolve()
    down = args.down.resolve()
    out = args.out_dir.resolve()
    out.mkdir(parents=True, exist_ok=True)
    workers = max(1, int(args.workers))
    for path in (up, down):
        if not path.exists():
            raise FileNotFoundError(path)

    control_dir = out / "control"
    impi_dir = out / "impi"
    pair_dir = out / "pair"
    impi_dir.mkdir(exist_ok=True)
    qp_up = control_dir / "A0_up.npz"
    qp_down = control_dir / "A0_down.npz"
    model_up = None
    model_down = None
    if args.impi_scheme == "matched":
        control_dir.mkdir(exist_ok=True)
        model_up = qp_model_from_cube(up)
        model_down = qp_model_from_cube(down)
        build_qp_cube(up, qp_up, model=model_up)
        build_qp_cube(down, qp_down, model=model_down)

    with np.load(up) as z:
        mu_up_cube = float(z["mu_up"])
        mass_cube = float(z["mass"]) if "mass" in z.files else 1.0
    with np.load(down) as z:
        mu_dn_cube = float(z["mu_dn"]) if "mu_dn" in z.files else float(z["mu_down"])
    qff = float(np.sqrt(mass_cube * mu_up_cube) - np.sqrt(mass_cube * mu_dn_cube))
    q_table_max = float(args.q_table_max)
    if not np.isfinite(q_table_max) or q_table_max <= 0.0:
        raise ValueError("--q-table-max must be finite and positive")

    if args.profile == "turbo":
        q_extra = f"{qff:.15g},1.0,4.0,8.0"
        lattice_linear = "40"
        lattice_tail = "20"
        p_nodes = "31"
        p_feature_width = "0"
        p_feature_nodes = "0"
        angular_nodes = "10"
        angular_feature_nodes = "7"
        coherent_nk = 96
        coherent_nquad = 48
    elif args.profile == "quick":
        q_extra = f"0.6,{qff:.15g},0.75,1.0,2.0,4.0,6.0,8.0"
        lattice_linear = "80"
        lattice_tail = "45"
        p_nodes = "61"
        p_feature_width = "0"
        p_feature_nodes = "0"
        angular_nodes = "16"
        angular_feature_nodes = "11"
        coherent_nk = 224
        coherent_nquad = 96
    else:
        q_extra = (
            f"0.3,0.5,0.6,0.65,0.675,{qff:.15g},0.7,0.725,0.75,"
            "0.8,0.9,1.0,1.25,1.5,2.0,3.0"
        )
        lattice_linear = "120"
        lattice_tail = "70"
        p_nodes = "31"
        p_feature_width = "0.05"
        p_feature_nodes = "7"
        angular_nodes = "20"
        angular_feature_nodes = "21"
        coherent_nk = 448
        coherent_nquad = 160
    if args.lattice_n_linear > 0:
        lattice_linear = str(args.lattice_n_linear)
    if args.lattice_n_tail > 0:
        lattice_tail = str(args.lattice_n_tail)
    if args.p_nodes > 0:
        p_nodes = str(args.p_nodes)
    if np.isfinite(args.p_feature_width):
        p_feature_width = f"{args.p_feature_width:.15g}"
    if args.p_feature_nodes >= 0:
        p_feature_nodes = str(args.p_feature_nodes)
    if args.angular_nodes > 0:
        angular_nodes = str(args.angular_nodes)
    if args.angular_feature_nodes >= 0:
        angular_feature_nodes = str(args.angular_feature_nodes)
    if args.coherent_nk > 0:
        coherent_nk = args.coherent_nk
    if args.coherent_nquad > 0:
        coherent_nquad = args.coherent_nquad
    if float(args.q_core_dq) > 0.0:
        dq = float(args.q_core_dq)
        q_core_max = float(args.q_core_max)
        if not np.isfinite(dq) or not np.isfinite(q_core_max) or q_core_max <= 0.0:
            raise ValueError("--q-core-dq and --q-core-max must be finite and positive")
        core = np.arange(0.0, q_core_max + 0.5 * dq, dq, dtype=float)
        tails = [
            float(value)
            for value in str(args.q_tail_points).split(",")
            if value.strip()
        ]
        q_values = np.unique(np.concatenate((core, [qff], np.asarray(tails))))
        q_extra = ",".join(f"{value:.15g}" for value in q_values)
    if str(args.q_points).strip():
        explicit = [
            float(value)
            for value in str(args.q_points).split(",")
            if value.strip()
        ]
        q_values = np.unique(np.concatenate(([0.0, qff, q_table_max], explicit)))
        q_extra = ",".join(f"{value:.15g}" for value in q_values)
    if float(args.q_local_half_width) > 0.0 or float(args.q_local_dq) > 0.0:
        half = float(args.q_local_half_width)
        dq_local = float(args.q_local_dq)
        if not np.isfinite(half) or not np.isfinite(dq_local) or half <= 0.0 or dq_local <= 0.0:
            raise ValueError("local Q refinement requires positive finite half-width and dq")
        center = (
            float(args.q_local_center)
            if np.isfinite(float(args.q_local_center))
            else qff
        )
        local = np.arange(center - half, center + half + 0.5 * dq_local, dq_local)
        local = local[(local >= 0.0) & (local <= q_table_max)]
        existing = np.asarray(
            [float(value) for value in q_extra.split(",") if value.strip()],
            dtype=float,
        )
        q_values = np.unique(np.concatenate((existing, local, [center, qff])))
        q_extra = ",".join(f"{value:.15g}" for value in q_values)
    grid_table = impi_dir / "impi_residual_grid.npz"
    if not grid_table.exists():
        command = [
            sys.executable,
            "-m", "fflo.impi_table",
            "--up-cube-path", str(up),
            "--down-cube-path", str(down),
            "--q-min", "0", "--q-max", f"{q_table_max:.15g}", "--n-q", "2",
            "--q-grid-mode", "linear_features",
            "--q-feature-half-width", "0", "--q-feature-n-local", "0",
            "--q-extra-points", q_extra, "--q-pre-feature-n", "0",
            "--omega-min", "-12", "--omega-max", "12", "--n-omega", "101",
            "--omega-tail-max", "240", "--omega-tail-n", "10",
            "--omega-tail-side", "symmetric", "--omega-grid-mode", "lattice",
            "--lattice-dw", "0.001", "--lattice-n-linear", lattice_linear,
            "--lattice-n-tail", lattice_tail,
            "--omega-feature-half-width", f"{float(args.omega_feature_half_width):.15g}",
            "--omega-feature-n-local", str(int(args.omega_feature_nodes)),
            "--omega-feature-mode", str(args.omega_feature_mode),
            "--omega-feature-q-min", f"{float(args.omega_feature_q_min):.15g}",
            "--omega-feature-q-max", f"{float(args.omega_feature_q_max):.15g}",
            "--omega-feature-q-max-points", str(int(args.omega_feature_q_max_points)),
            "--p-int-min", "0", "--p-int-max", "4", "--n-p-int", p_nodes,
            "--p-grid-mode", "linear", "--p-feature-half-width", p_feature_width,
            "--p-feature-n-local", p_feature_nodes, "--p-feature-mode", "kf_and_shells",
            "--kf-feature-source", str(args.kf_feature_source),
            "--p-feature-q-min", "0.2", "--p-feature-q-max", "2.1",
            "--p-feature-q-max-points", "3",
            "--eps-min", "-24", "--eps-max", "160", "--n-eps", "241",
            "--eps-grid-mode", "lattice", "--eps-integration-mode", "panel_kinks",
            "--p-integration-mode", "plain", "--p-gl-n", "8",
            "--n-phi", "20", "--phi-chunk-size", "16",
            "--angular-mode", "phipanel", "--n-kquad", angular_nodes,
            "--kquad-chunk-size", "4", "--kquad-kf-feature",
            "--kquad-feature-n-local", angular_feature_nodes,
            "--kquad-feature-half-width", "0.05",
            "--qp-lorentzian-cv", "none", "--routing", "difference",
            "--parallel-mode", "processes", "--max-workers", str(workers),
            "--no-row-normalize-cubes", "--out-dir", str(impi_dir / "residual"),
        ]
        if args.impi_scheme == "matched":
            command[6:6] = [
                "--subtract-up-cube-path", str(qp_up),
                "--subtract-down-cube-path", str(qp_down),
            ]
        env = dict(os.environ)
        env.update(
            IMPI_INTERNAL_REBUILD="1",
            OMP_NUM_THREADS="1",
            OPENBLAS_NUM_THREADS="1",
            MKL_NUM_THREADS="1",
            NUMEXPR_NUM_THREADS="1",
        )
        run(command, env=env, log=out / "grid_residual.log")
        source = impi_dir / "residual/impi_table.npz"
        source.replace(grid_table)

    with np.load(grid_table, allow_pickle=True) as data:
        result = {key: np.asarray(data[key]) for key in data.files}
    q = np.asarray(result["q"], dtype=float)
    omega = np.asarray(result["omega"], dtype=float)
    if args.impi_scheme == "matched":
        assert model_up is not None and model_down is not None
        ku, eu, zu, gu, mu_up = _canonical_qp_fields(up, model_up)
        kd, ed, zd, gd, mu_down = _canonical_qp_fields(down, model_down)
        features = [_kf(ku, eu, mu_up), _kf(kd, ed, mu_down)]
        options = dict(
            angle_mode="kjac",
            nk=coherent_nk,
            nphi=64,
            n_kquad=coherent_nquad,
            kquad_chunk_size=8,
            kmax=float(result["p_int_max"]),
            gamma_floor=1.0e-3,
        )
        with ProcessPoolExecutor(
            max_workers=min(workers, q.size),
            initializer=_cv_init,
            initargs=(
                omega,
                ku, eu, zu, gu,
                kd, ed, zd, gd,
                features,
                options,
            ),
        ) as pool:
            analytic = np.asarray(list(pool.map(_cv_work, q.tolist(), chunksize=1)))

        residual = np.asarray(result["ImPi"], dtype=float)
        total = residual + analytic
        result["ImPiGridResidual"] = residual
        result["ImPiQPQP"] = analytic
        result["ImPi"] = total
        result["ImPiFull"] = total
        result["ImPi_scheme"] = np.array("subtract_product_inline")
        result["ImPi_analytic_cv"] = np.array(True)
    else:
        total = np.asarray(result["ImPi"], dtype=float)
        result["ImPiFull"] = total
        result["ImPi_scheme"] = np.array("direct_product")
        result["ImPi_analytic_cv"] = np.array(False)
    final_table = impi_dir / "impi_table.npz"
    np.savez_compressed(final_table, **result)

    if not args.skip_pair:
        command = [
            sys.executable,
            "-m", "fflo.pair_gamma",
            "--no-plots", "--impi-table-path", str(final_table),
            "--kk-pad", "0", "--kk-oversample", "1", "--kk-tail", "zero",
            "--kk-tail-alpha", "nan", "--kk-max-n", "0",
            "--eta-gamma", "0.002", "--im-inv-sign-guard", "on",
            "--reference-mode", str(args.reference_mode),
            "--qp-residual-mode", "cross_inc", "--qpqp-source", "auto",
            "--qpqp-xi-cutoff", f"{float(args.qpqp_xi_cutoff):.15g}", "--qpqp-n-p", "5000",
            "--qpqp-n-phi", "24", "--residual-omega-taper-start", "0",
            "--residual-omega-taper-stop", "20",
            "--residual-omega-taper-mode", "qkin_cosine",
            "--out-dir", str(pair_dir),
        ]
        run(command, log=out / "pair.log")

    formula = (
        "Grid[A*A-A0*A0] + SemiAnalytic[A0*A0]"
        if args.impi_scheme == "matched"
        else "Grid[A*A]"
    )
    report = [
        f"ImPi product test: {args.impi_scheme}",
        f"up={up}",
        f"down={down}",
        f"q_nodes={q.size} omega_nodes={omega.size}",
        f"q_table_max={q_table_max:.12g}",
        f"workers={workers}",
        f"profile={args.profile}",
        f"kf_feature_source={args.kf_feature_source}",
        f"formula={formula}",
        "full_line=internal rebuild from ReS/ImS",
    ]
    if args.impi_scheme == "matched":
        report.append("control_line=canonical QP A0 evaluated directly")
    else:
        report.append("control_line=none")
    old_pair = args.old_pair.resolve()
    new_pair = pair_dir / "pair_gamma_table.npz"
    if new_pair.exists():
        q_new, y_new = pair_q_zero_cut(new_pair)
        i_new = int(np.argmax(y_new))
        report.append(
            f"new ReInvGamma_max={y_new[i_new]:+.12e} q={q_new[i_new]:.12g}"
        )
        old_y_for_plot = None
        if old_pair.exists():
            q_old, y_old = pair_q_zero_cut(old_pair)
            i_old = int(np.argmax(y_old))
            report.append(
                f"old ReInvGamma_max={y_old[i_old]:+.12e} q={q_old[i_old]:.12g}"
            )
            old_y_for_plot = (q_old, y_old)
        try:
            import matplotlib

            matplotlib.use("Agg")
            import matplotlib.pyplot as plt

            fig, axis = plt.subplots(figsize=(7.2, 4.8))
            axis.plot(q_new, y_new, "o-", label=f"{args.impi_scheme} product")
            if old_y_for_plot is not None:
                axis.plot(*old_y_for_plot, "-", alpha=0.8, label="current subtract_product")
            axis.axvline(qff, color="black", linestyle="--", linewidth=1)
            axis.set_xlabel("Q")
            axis.set_ylabel(r"Re $\Gamma^{-1}(Q,0)$")
            axis.grid(alpha=0.25)
            axis.legend()
            fig.tight_layout()
            fig.savefig(out / "regammainv_q_omega0.png", dpi=180)
            plt.close(fig)
        except ImportError:
            print("[warn] matplotlib not available, skipping regammainv_q_omega0.png", flush=True)

    report_path = out / "summary.txt"
    report_path.write_text("\n".join(report) + "\n", encoding="ascii")
    print(report_path.read_text(encoding="ascii"))


if __name__ == "__main__":
    main()
