# =====================================================================
# SLIM copy of FFLO_exec/proxy.py
#
# 51 top-level symbols (1323 lines, 72% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   Gamma, configuration
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   _map_legendre
#   gl_integrate_1d
#   Omega_th
#   Oth_min
#   P_min_and_max
#   Delta_inf_squared
#   Sigma_f_down_vectorized
#   Sigma_b_down_split
#   Sigma_f_down_asympt
#   Sigma_b_down_asympt
#   Sigma_down_asympt
#   Sigma_f_up_vectorized
#   Sigma_b_up_split
#   Sigma_f_up_asympt
#   Sigma_b_up_asympt
#   Sigma_up_asympt
#   Sigma_down
#   Sigma_up
#   _omega_panels
#   _sigma0_for
#   _alpha_sigma
#   _resigL_sigma
#   _n_sigma_komega
#   _n_sigma_komega_asympt
#   prepare_nsigma_context
#   evaluate_nsigma_with_context
#   _n_sigma_vectorized
#   ndown_vectorized
#   nup_vectorized
#   totaldensity_sigma
#   _safe_sqrt
#   _mu_down_from_mu_up
#   _total_density_given_muup
#   _res_total
#   _bracket_root
#   _bisect_scalar
#   _secant_fallback
#   _scan_min_abs
#   solve_mu_up_1d_total_density
#   find_kjump
#   _log
#   _fmt_vec
#   _ensure_targets_from_P
#   _density_residual_mu
#   _residual_inf
#   _solve_mu_least_squares
#   _solve_mu_newton_krylov
#   solve_for_fixed_P
#   thouless_check
#   find_critical_polarization
#   run_nk_full
# =====================================================================
#!/usr/bin/env python3
"""
psc_kernel.py

Minimal, cluster-ready PSC kernel.

Contains EXACTLY what the Slurm driver needs:

- configuration
- solve_for_fixed_P(...)
- thouless_check(...)

and the physics chain they depend on.

No plotting, no demo run, no overlay, no unused helpers.
"""

import os
import numpy as np
from numpy.lib.scimath import sqrt as csqrt
from numpy.polynomial.legendre import leggauss
from scipy.optimize import least_squares, newton_krylov
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime

# ---------------------------------------------------------------------
# optional site-specific parameters
# ---------------------------------------------------------------------
# try:
#     from parameters import *  # noqa: F401,F403
# except ImportError:
#     pass

# ---------------------------------------------------------------------
# global HPC knobs
# ---------------------------------------------------------------------
MAX_WORKERS = int(os.environ.get("PSC_MAX_WORKERS", "10"))
_EPS = np.finfo(float).eps

LOG_LEVELS = {"ERROR": 0, "WARN": 1, "INFO": 2, "DEBUG": 3}
LOG_LEVEL = LOG_LEVELS.get("INFO", 2)


def _log(level: str, msg: str):
    if LOG_LEVELS[level] <= LOG_LEVEL:
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"[{ts}] [{level}] {msg}")


def _fmt_vec(v):
    v = np.asarray(v, float).ravel()
    return "(" + ", ".join(f"{x:+.6e}" for x in v) + ")"


# ---------------------------------------------------------------------
# masses / basic constants
# ---------------------------------------------------------------------
m_r = 0.5
r = 1.0
m_up = 2 * m_r          # 1.0
m_down = 2 * m_r * r    # 1.0
M = m_up + m_down       # 2.0

# quadrature / integration parameters

omega_min = 1e-4
k_min=1e-9
k_max = 3
epsilon = 1e-10
n_phi = 50
n_Omega = 100
n_P = 100
n_k = 10
eta_small = 1e-10

# OMEGA_MIN_OVERRIDE = None


# ---------------------------------------------------------------------
# config object
# ---------------------------------------------------------------------
class BaseConfig:
    def __init__(self, Polar=np.nan, epsilon_0=np.nan, mu_up=np.nan, mu_down=np.nan):

        self.m_r = 0.5
        self.r = 1.0
        self.m_up = 2 * self.m_r
        self.m_dn = 2 * self.m_r * self.r
        self.M = self.m_up + self.m_dn

        # inputs
        self.Polar = Polar
        self.epsilon_0 = epsilon_0
        self.mu_up = mu_up
        self.mu_down = mu_down

        # total density
        self.ntarget = 1.0

        # MF polarization
        self.Polar_c_mf = self.epsilon_0 * np.sqrt(2 / self.epsilon_0 - 1)

        # density targets
        if np.isfinite(self.Polar):
            self.nuptarget = 0.5 * self.ntarget * (1 + self.Polar)
            self.ndntarget = 0.5 * self.ntarget * (1 - self.Polar)
        else:
            self.nuptarget = 0.5
            self.ndntarget = 0.5

        self.kF_up = np.sqrt(2 * self.nuptarget)
        self.kF_dn = np.sqrt(2 * self.ndntarget)

        # derived placeholders
        self.g = np.nan
        self.h = np.nan
        self.qFFLO = np.nan
        self.k_mu_down = np.nan
        self.k_mu_up = np.nan
        self.k_jump_up = np.nan
        self.k_jump_down = np.nan

        self.update_computed()

    def update_computed(self):
        self.g = 0.5 * np.log(self.epsilon_0 / 2) if self.epsilon_0 > 0 else np.nan

        if (self.mu_up is not None) and (self.mu_down is not None):
            self.h = (self.mu_up - self.mu_down) / 2
            self.qFFLO = np.sqrt(max(self.mu_up, 0)) - np.sqrt(max(self.mu_down, 0))
        else:
            self.h = np.nan
            self.qFFLO = np.nan

        self.k_mu_down = np.sqrt(self.m_dn * self.mu_down) if (self.mu_down is not None and self.mu_down > 0) else 0.0
        self.k_mu_up = np.sqrt(self.m_up * self.mu_up) if (self.mu_up is not None and self.mu_up > 0) else 0.0

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

        if ("Polar" in kwargs) or ("ntarget" in kwargs):
            P = float(self.Polar) if np.isfinite(self.Polar) else 0.0
            nt = float(self.ntarget)
            self.nuptarget = 0.5 * nt * (1.0 + P)
            self.ndntarget = 0.5 * nt * (1.0 - P)
            self.kF_up = np.sqrt(2 * self.nuptarget)
            self.kF_dn = np.sqrt(2 * self.ndntarget)

        self.update_computed()


# # # global configuration
configuration = BaseConfig()

# eps0=0.1
# configuration.update(epsilon_0= eps0)
# Polar_c_f = configuration.epsilon_0*np.sqrt(2/configuration.epsilon_0-1)
# configuration.update(epsilon_0=0.1, Polar=0.5)
# configuration.update(mu_up=1.501160, mu_down=0.514126)
# eps=5.2450864576e-01
# mu_u=2
# mu_d=0.02
# configuration.update(epsilon_0= eps, mu_up = mu_u, mu_down = mu_d)
# ---------------------------------------------------------------------
# quadrature helpers
# ---------------------------------------------------------------------





# ---------------------------------------------------------------------
# Gamma and its ingredients
# ---------------------------------------------------------------------
def calculate_z_down(P, w):
    mu_down = configuration.mu_down
    mu_up = configuration.mu_up
    return mu_down - (mu_up / r) - (P ** 2 / m_down) + w


def calculate_z_up(P, w):
    mu_down = configuration.mu_down
    mu_up = configuration.mu_up
    return mu_up - (mu_down / r) - (P ** 2 / m_up) + w


def calculate_A_down(P, w):
    mu_up = configuration.mu_up
    z = calculate_z_down(P, w)
    term1 = z / 2
    term2 = ((P ** 2) / (M * r))
    term3 = np.sign(np.real(z)) * np.sqrt((z / 2) ** 2 - (P ** 2 / (m_down * r)) * mu_up)
    return term1 + term2 + term3


def calculate_A_up(P, w):
    mu_down = configuration.mu_down
    z = calculate_z_up(P, w)
    term1 = z / 2
    term2 = ((P ** 2) / (M * r))
    term3 = np.sign(np.real(z)) * np.sqrt((z / 2) ** 2 - (P ** 2 / (m_up * r)) * mu_down)
    return term1 + term2 + term3


def Gamma(P, w):
    mu_down = configuration.mu_down
    mu_up = configuration.mu_up
    epsilon_0 = configuration.epsilon_0

    term = (P ** 2 / M) - mu_up - mu_down - w
    T2_minus1 = -1 / (8 * np.pi) * np.log(term / (epsilon_0))

    I_F_down = 1 / (8 * np.pi) * (np.log(calculate_A_up(P, w)) - np.log(term) - 1j * np.pi * np.sign(np.imag(w)))
    I_F_up = 1 / (8 * np.pi) * (np.log(calculate_A_down(P, w)) - np.log(term) - 1j * np.pi * np.sign(np.imag(w)))

    if mu_down < 0 and mu_up > 0:
        return 1 / (T2_minus1 - I_F_up)
    elif mu_down >= 0 and mu_up < 0:
        return 1 / (T2_minus1 - I_F_down)
    elif mu_down < 0 and mu_up < 0:
        return 1 / (T2_minus1)
    elif mu_down > 0 and mu_up > 0:
        return 1 / (T2_minus1 - I_F_up - I_F_down)


# ---------------------------------------------------------------------
# thresholds
# ---------------------------------------------------------------------






# ---------------------------------------------------------------------
# contact scale Δ∞²
# ---------------------------------------------------------------------


# ---------------------------------------------------------------------
# self-energies (down)
# ---------------------------------------------------------------------









# ---------------------------------------------------------------------
# self-energies (up)
# ---------------------------------------------------------------------










# ---------------------------------------------------------------------
# total self-energies
# ---------------------------------------------------------------------




# ---------------------------------------------------------------------
# ω-panels for nσ(k)
# ---------------------------------------------------------------------








# def _resigL_sigma(spin, mode, *, kref=None, omega_ref=1e-3):
#     """
#     resigL_σ = Re Σ_σ(kref, ω_ref).
#     """
#     Σfun = Sigma_down if spin == "down" else Sigma_up
#     if kref is None:
#         kref = float(configuration.k_mu_down if spin == "down" else configuration.k_mu_up)
#     w = float(omega_ref) if (np.isfinite(omega_ref) and omega_ref > 0.0) else 1e-5
#     Sig = np.asarray(Σfun(float(kref), w)).reshape(-1)[0]
#     return float(np.real(Sig))
# ---------------------------------------------------------------------
# subtraction helpers
# ---------------------------------------------------------------------
# ---------------------------------------------------------------------
# integrands and nσ(k)
# ---------------------------------------------------------------------














# ---------------------------------------------------------------------
# total density ∫ k nσ(k)
# ---------------------------------------------------------------------

# =========================
# Stable 1D (s) density solver + Pc march
# =========================
# ===== 1D criticality-constrained μ-solver ==========================F=====
# Requires: configuration, totaldensity_sigma(...), Gamma(...) already imported.
import numpy as np
from datetime import datetime
from math import isfinite
from concurrent.futures import ThreadPoolExecutor

# ===== knobs =====
ABS_RES_TOL   = 5e-3            # target on | n_up + n_dn - ntarget |
MAX_WORKERS   = 10              # totaldensity_sigma threads
BRACKET_INIT  = 0.02            # ± fraction around the seed to try first
BRACKET_GROW  = 2.0             # multiply half-width when expanding
BRACKET_MAXIT = 18              # max expansions
SECANT_MAXIT  = 20              # safety for secant fallback
GRID_MIN      = 6               # min grid points for scan fallback
GRID_MAX      = 30              # max grid points for scan fallback

# ===== logging =====
LOG_LEVELS = {"ERROR": 0, "WARN": 1, "INFO": 2, "DEBUG": 3}
LOG_LEVEL  = LOG_LEVELS.get("INFO", 2)

def _log(level: str, msg: str):
    if LOG_LEVELS[level] <= LOG_LEVEL:
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"[{ts}] [{level}] {msg}")



def _ensure_targets_from_P(P: float):
    """Set (ν_up^t, ν_dn^t) from ntarget, P if not already present."""
    if hasattr(configuration, "nuptarget") and hasattr(configuration, "ndntarget"):
        return
    nt = float(getattr(configuration, "ntarget", 1.0))
    configuration.update(
        nuptarget=0.5 * nt * (1.0 + float(P)),
        ndntarget=0.5 * nt * (1.0 - float(P)),
    )











from scipy.optimize import root

    
# k_l_down, k_l_up = find_kjump('down', 'norm'), find_kjump('up', 'norm') 
# print(k_l_down, k_l_up)
# configuration.update(k_jump_down = k_l_down, k_jump_up = k_l_up)

# print(totaldensity_sigma('up', 'norm'))

# print(totaldensity_sigma('down', 'norm'))


##### 2D SOLVER



import numpy as np
from scipy.optimize import least_squares, newton_krylov
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime

# ---------- knobs ----------
_EPS = np.finfo(float).eps         # ~2.22e-16, used to silence SciPy warnings for ftol/xtol
MAX_WORKERS = 10                   # threads for density integrals

# ---------- logging ----------
LOG_LEVELS = {"ERROR": 0, "WARN": 1, "INFO": 2, "DEBUG": 3}
LOG_LEVEL = LOG_LEVELS.get("INFO", 2)  # set to "DEBUG" for more detail



# ---------- targets from polarization ----------

# ---------- residual in μ-space ----------




# ---------- inner μ–solvers ----------


# ---------- public wrapper for a fixed polarization ----------

# ---------- Thouless line check (unchanged physics; add a tiny bit of logging) ----------

# ---------- polarization sweep with warm starts and logs ----------

# configuration.update(epsilon_0 =2, Polar = 0.15)
# configuration.update(mu_up=+1.150090e+00,mu_down= -1.670790e+00)
# k_l_down, k_l_up = find_kjump('down', 'norm'), find_kjump('up', 'norm') 
# configuration.update(k_jump_up=k_l_up, k_jump_down=k_l_down)
# Each panel: its own figure
FIGSIZE_SINGLE = (7 * 1.3, 5 * 1.3)  # ≈ (9.1, 6.5)

# Common axes rectangle: [left, bottom, width, height] in figure coords
AXES_RECT = [0.18, 0.16, 0.78, 0.78] 




# 75  -1.4750000000e+00  1.4390985989e+00-9.624534e-01

# configuration.update(epsilon_0=2, Polar=0.15)
# configuration.update(mu_up=  1.3 , mu_down =-2)

# print(solve_for_fixed_P(0.15, mu_guess=np.array([configuration.mu_up, configuration.mu_down]), mode='norm', use_parallel=True)
# )

# #####
# configuration.update(epsilon_0 =1.0246014443e-01   )
# # Polar_c = configuration.epsilon_0* np.sqrt(2/configuration.epsilon_0 -1)
# configuration.update(mu_up = 9.8750000000e-01, mu_down = 2.9273415415e-01)
# 41 -1.4857142857e+00  0.000000e+00 0.000000e+00

# ######NSCT
# configuration.update(epsilon_0=3.6631277777e-02, Polar=9.8119691962e-02)
# configuration.update(mu_up=9.2187500000e-01, mu_down=4.7537253787e-01)

# # Update k_jumps
# k_l_down, k_l_up = find_kjump('down', 'norm'), find_kjump('up', 'norm')
# configuration.update(k_jump_up=k_l_up, k_jump_down=k_l_down)

# # Use k_jump_down
# k = configuration.k_jump_down

# configuration.update(epsilon_0=5.1744459652e-01, Polar=8.5990388573e-01)
# configuration.update(mu_up= 1.8565205853e+00, mu_down = 1.1919543571e-01)



##### CHECK SALTO
# configuration.update(epsilon_0 = 2)
# configuration.update(mu_up= 1.15008923, mu_down =-1.67077277)
# configuration.update(epsilon_0=0.286588, mu_up=1.03125, mu_down = 0.0667814, Polar =  0.0491976)



# new_run idx=0 eps0=0.0049575 g=-3 pcrit=0.0565068 mu_up=0.857812 mu_down=0.68328 qFFLO=0.0995741
# new_run idx=43 eps0=0.144363 g=-1.31429 pcrit=0.0954777 mu_up=1.00937 mu_down=0.218411 qFFLO=0.537332
#   down: k_jump=1.00848, window=[0.467344,1.54201], defined=True, contains=True
#   up  : k_jump=1.0409, window=[0.0699881,1.00468], defined=True, contains=False

# configuration.update(epsilon_0 = 0.144363 , Polar = 0.0954777)
# configuration.update(mu_up= 1.00937, mu_down =0.218411 )
# configuration.update(epsilon_0=0.286588, mu_up=1.03125, mu_down = 0.0667814, Polar =  0.0491976)


# k_l_down, k_l_up = find_kjump('down', 'norm'), find_kjump('up', 'norm')
# configuration.update(k_jump_up = k_l_up, k_jump_down = k_l_down)
# run_nk_full(
#     mode="norm",
#     k_center_dn=configuration.k_jump_down,
#     k_center_up=configuration.k_jump_up,
#     n_before_dn=35,
#     n_after_dn=35,
#     n_before_up=35,
#     n_after_up=35,
#     delta_dn=0.5,
#     txt_prefix="density_data_nk_NSCT",
#     make_plot=True,
# )

# configuration.update(epsilon_0=5.1744459652e-01, Polar=8.5990388573e-01)
# configuration.update(mu_up= 1.8565205853e+00, mu_down = 1.1919543571e-01)
# k_l_down, k_l_up = find_kjump('down', 'rand'), find_kjump('up', 'rand')
# configuration.update(k_jump_up = k_l_up, k_jump_down = k_l_down)
# print(f'k_jump_up: {configuration.k_jump_up}, k_jump_down: {configuration.k_jump_down}')
# omega_range = np.linspace(0.1, 1, 4)


