# =====================================================================
# SLIM copy of true_akw_pipeline/build_qp_cube.py
#
# 1 top-level symbols (48 lines, 24% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   build_inc_cube, build_qp_cube, qp_model_from_cube
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   _bridge_invalid
# =====================================================================
"""Build a QP-Lorentzian cube A_QP(k,omega) = Z_k/pi * Gamma_k/((w-E_k)^2+Gamma_k^2)
from the SMOOTH Dyson QP (qp_dyson_extract), saved as a cube-like npz so the
existing bubble (make_impi) can be run on it -> ImPi_grid(QP x QP).

Control variate for the two-spin QP bubble:
    ImPi = ImPi_grid(full) - ImPi_grid(QP) + ImPi_analytic(QP)   [coherent_impi]
The (analytic - grid)(QP) term removes the razor mis-sampling (172x at kF).
"""
from __future__ import annotations
import sys
import numpy as np
sys.path.insert(0, "true_akw_pipeline")
from fflo.qp_dyson import extract_qp_dyson




def _dense_bridged_model(k, E, Z, G, valid, *, decay_len=0.3):
    """Build the canonical continuous QP model, including dense edge decay.

    Sampling an exponential only at the last native k row and at a distant
    k_max makes subsequent linear interpolation follow the chord, which can
    exceed the intended decay by orders of magnitude.  Insert several anchors
    per decay length and use this same representation everywhere.
    """
    k = np.asarray(k, float)
    valid = np.asarray(valid, bool)
    if not np.any(valid):
        return k.copy(), np.zeros_like(k), np.zeros_like(k), np.ones_like(k)

    kd = k[valid].copy()
    ed = np.asarray(E, float)[valid].copy()
    zd = np.asarray(Z, float)[valid].copy()
    gd = np.asarray(G, float)[valid].copy()
    reach = 8.0 * float(decay_len)
    points_per_len = 6

    if kd[0] > 1.0e-9:
        span = min(float(kd[0]), reach)
        n = max(8, int(np.ceil(span / decay_len * points_per_len)))
        klo = kd[0] - np.linspace(span, 0.0, n, endpoint=False)
        klo = klo[klo > 1.0e-9]
        zlo = zd[0] * np.exp(-(kd[0] - klo) / decay_len)
        kd = np.concatenate((klo, kd))
        ed = np.concatenate((np.full(klo.size, ed[0]), ed))
        zd = np.concatenate((zlo, zd))
        gd = np.concatenate((np.full(klo.size, gd[0]), gd))

    if kd[-1] < k[-1] - 1.0e-12:
        anchor_k = float(kd[-1])
        anchor_e = float(ed[-1])
        anchor_z = float(zd[-1])
        anchor_g = float(gd[-1])
        span = min(float(k[-1] - anchor_k), reach)
        n = max(8, int(np.ceil(span / decay_len * points_per_len)))
        khi = anchor_k + np.linspace(0.0, span, n + 1)[1:]
        if khi[-1] < k[-1] - 1.0e-12:
            khi = np.concatenate((khi, [k[-1]]))
        zhi = anchor_z * np.exp(-(khi - anchor_k) / decay_len)
        kd = np.concatenate((kd, khi))
        ed = np.concatenate((ed, np.full(khi.size, anchor_e)))
        zd = np.concatenate((zd, zhi))
        gd = np.concatenate((gd, np.full(khi.size, anchor_g)))

    return kd, ed, zd, gd


def qp_model_from_cube(src_path):
    """Extract one canonical QP model for every use in a decomposition.

    The old pipeline independently extracted and extrapolated the QP fields
    when it built ``A_QP``, ``A_inc``, and the analytic add-back.  Tiny
    differences between those models do not cancel: they are amplified by the
    pair KK transform.  Returning the bridged full-k model here lets callers
    pass the exact same arrays to every term.
    """
    c = dict(np.load(src_path))
    k = np.asarray(c["k"], float)
    w2 = c["w"].astype(float) if c["w"].ndim == 2 else None
    wb = np.asarray(c["w_base"] if "w_base" in c else c["w"], float)
    spin_dn = "spindown" in str(src_path).lower()
    mu = float(c["mu_dn"]) if spin_dn else float(c["mu_up"])
    eta = float(c["eta"])
    E, Z, G, valid = extract_qp_dyson(
        k, w2, wb, c["ReS"], c["ImS"], mu, float(c["sigma0"]),
        eta, float(c["mass"]),
    )
    kd, Ed, Zd, Gd = _dense_bridged_model(k, E, Z, G, valid)
    return {
        "k": np.asarray(kd, float),
        "E": np.asarray(Ed, float),
        "Z": np.asarray(Zd, float),
        "G": np.asarray(Gd, float),
        "native_k": k,
        "valid_native": np.asarray(valid, bool),
        "eta": eta,
        "mu": mu,
    }


def _qp_rows(c, model):
    """Evaluate the canonical QP Lorentzian on a cube's row-local axes."""
    k = np.asarray(c["k"], float)
    if not np.array_equal(k, np.asarray(model["native_k"], float)):
        raise ValueError("QP model and cube k grids differ")
    w2 = c["w"].astype(float) if c["w"].ndim == 2 else None
    wb = np.asarray(c["w_base"] if "w_base" in c else c["w"], float)
    km = np.asarray(model["k"], float)
    E = np.interp(k, km, np.asarray(model["E"], float))
    Z = np.interp(k, km, np.asarray(model["Z"], float))
    G = np.maximum(np.interp(k, km, np.asarray(model["G"], float)), float(model["eta"]))
    out = np.zeros_like(np.asarray(c["A"], float))
    for ik in range(k.size):
        w = w2[ik] if w2 is not None else wb
        out[ik] = (Z[ik] / np.pi) * G[ik] / ((w - E[ik]) ** 2 + G[ik] ** 2)
    return out


def build_qp_cube(src_path, dst_path, *, model=None):
    c = dict(np.load(src_path))
    model = qp_model_from_cube(src_path) if model is None else model
    c["A"] = _qp_rows(c, model)
    np.savez(dst_path, **c)
    return (
        int(np.count_nonzero(model["valid_native"])),
        int(np.asarray(model["native_k"]).size),
    )


def build_inc_cube(src_path, dst_path, *, model=None):
    """Build A_inc cube: A_inc(k,w) = A_full(k,w) - A_QP_Lorentzian(k,w).

    A_inc is smooth (QP razor removed) so the eps-grid bubble integrates it
    accurately.  A_inc + A_QP = A_full exactly, so
        ImPi_inc_grid + ImPi_QP_analytic + cross1 + cross2 = ImPi_total
    """
    c = dict(np.load(src_path))
    model = qp_model_from_cube(src_path) if model is None else model
    c["A"] = np.asarray(c["A"], float) - _qp_rows(c, model)
    np.savez(dst_path, **c)
    return (
        int(np.count_nonzero(model["valid_native"])),
        int(np.asarray(model["native_k"]).size),
    )


