# =====================================================================
# SLIM copy of true_akw_pipeline/qp_dyson_extract.py
#
# 0 top-level symbols (0 lines, 0% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   extract_qp_dyson
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
# =====================================================================
"""Smooth Dyson QP extraction for the analytic-QP bubble (route 2).

The argmax(A) extractor quantizes the QP center to the omega-grid and is biased
(the spectral peak is pulled off the Dyson pole by the omega-dependence of ImSigma).
That grid noise, amplified x8pi by the Thouless gain, is what scatters g_c.

Here the QP is the *Dyson pole*: the root of  omega - xi_k - (ReSigma(k,omega) - sigma0) = 0,
found by linear interpolation of the (smooth) ReSigma row -> smooth in k and P.
  Z_k     = 1 / (1 - dReSigma/domega|_{E_k})      (residue)
  Gamma_k = Z_k * (|ImSigma(k,E_k)| + eta)         (Dyson width)
"""
from __future__ import annotations
import os
import numpy as np


def _row(w2, wb, ik):
    return w2[ik] if (w2 is not None and np.ndim(w2) == 2) else wb


def extract_qp_dyson(k, w2, wb, ReS, ImS, mu, sigma0, eta, mass, win_w=0.05, max_gamma=None, max_z=None):
    """Return E[k], Z[k], Gamma[k], valid[k] (the dominant Dyson QP per k).

    2026-08-01: BOTH hard magnitude caps (max_z, max_gamma) are removed as
    rejection criteria. Both showed the identical failure mode when traced:
    a smooth, modest change in Sigma between iterations pushes many crossings
    clustered near a binary threshold over it SIMULTANEOUSLY, converting a
    continuous physical change into a discrete rejection avalanche (max_z:
    Z-boundary ratchet, 27%->9% valid over 13 iters; max_gamma: measured
    Gamma 0.280->0.526 for one k between iterations, from ImSigma nearly
    doubling, wiping out 95 low-k up-spin points at once at P=0.65 iter3).
    Fixing max_gamma alone only moved the collapse to a different iteration
    and a different spin (down-spin iter6), confirming the cap itself -- not
    its specific value -- is the destabilizing agent. The only remaining
    rejection criteria are physical/mathematical, not arbitrary magnitude
    thresholds: slope<=0 (unphysical negative-residue branch) and, when
    QP_STABILITY_CHECK is set, window-size instability (a shape/consistency
    test, not a cap on the crossing's magnitude). Z is still clipped to the
    sum-rule bound (<=1), which is enforcing a hard physical constraint, not
    discarding a pole.

    QP_MAX_Z / QP_MAX_GAMMA are kept as opt-in overrides (None -> disabled)
    for comparison against the old capped behavior, not used by default."""
    if max_z is None:
        max_z = os.environ.get("QP_MAX_Z")
        max_z = float(max_z) if max_z else None
    if max_gamma is None:
        max_gamma = os.environ.get("QP_MAX_GAMMA")
        max_gamma = float(max_gamma) if max_gamma else None
    # QP_STABILITY_CHECK (diagnostic, 2026-08-01): if the subtraction were
    # self-consistent, whether a k is called "valid" should barely matter --
    # Grid[QP] and the analytic QP counterterm use the SAME (E,Z,Gamma), so
    # relabeling shouldn't move the answer much. It moves it a LOT (measured:
    # +0.0255 in one iteration switching max_z 0.85->1.0) because "invalid"
    # k are forced to Z=0 (no coherent weight) via the decay fix above, while
    # their TRUE Z can be close to 1 (real weak-coupling far-kF physics, not
    # noise) -- a real crossing gets thrown to zero instead of used. Test a
    # different discriminant: accept any crossing whose Z estimate is STABLE
    # under a change of the local fit window (genuine poles don't care how
    # wide you fit; marginal/noisy crossings do -- see k=1.215 case, Z swung
    # 0.61->0.88 across win=0.05->0.10), clipping Z to the sum-rule bound
    # instead of rejecting outright for being close to/above 1.
    use_stability = str(os.environ.get("QP_STABILITY_CHECK", "0")).strip().lower() not in {"0", "false", "no", "off", ""}
    stability_tol = float(os.environ.get("QP_STABILITY_TOL", "0.15"))
    k = np.asarray(k, float)
    nk = k.size
    E = np.full(nk, np.nan)
    Z = np.full(nk, np.nan)
    G = np.full(nk, np.nan)
    valid = np.zeros(nk, bool)
    for ik in range(nk):
        w = np.asarray(_row(w2, wb, ik), float)
        re = np.asarray(ReS[ik], float)
        im = np.asarray(ImS[ik], float)
        xi = k[ik] ** 2 / mass - mu
        f = w - xi - (re - sigma0)              # f(E_k) = 0 at the Dyson pole
        sc = np.where(np.diff(np.sign(f)) != 0)[0]
        best = None
        for j in sc:
            df = f[j + 1] - f[j]
            if df == 0.0:
                continue
            t = -f[j] / df
            wr = w[j] + t * (w[j + 1] - w[j])
            # dReSigma/domega from a LOCAL LINEAR FIT over a window around E_k
            # (single-interval finite diff is noisy -> Z spikes when slope->1).
            win = max(win_w, 4.0 * float(w[j + 1] - w[j]))
            sel = np.abs(w - wr) <= win
            if np.count_nonzero(sel) >= 4:
                dre = float(np.polyfit(w[sel] - wr, re[sel], 1)[0])
            else:
                dre = (re[j + 1] - re[j]) / (w[j + 1] - w[j])
            slope = 1.0 - dre                   # df/dw at the root
            if slope <= 0.0:                    # not a QP (negative residue branch)
                continue
            z = 1.0 / slope
            if use_stability:
                win_wide = win * 2.5
                sel_wide = np.abs(w - wr) <= win_wide
                if np.count_nonzero(sel_wide) >= 4:
                    dre_wide = float(np.polyfit(w[sel_wide] - wr, re[sel_wide], 1)[0])
                else:
                    dre_wide = dre
                slope_wide = 1.0 - dre_wide
                if slope_wide <= 0.0:
                    continue
                z_wide = 1.0 / slope_wide
                rel_diff = abs(z - z_wide) / max(abs(z), abs(z_wide), 1.0e-6)
                if rel_diff > stability_tol:    # Z estimate is window-sensitive ->
                    continue                    # marginal/noisy crossing, not a real pole
                z = min(z, 1.0)                 # clip to the sum-rule bound; a stable
                                                 # crossing near/at Z=1 is the physical
                                                 # weak-coupling limit, not spurious
            else:
                z = min(z, 1.0)                  # sum-rule clip always applies; no
                if max_z is not None and z > max_z:  # magnitude-based REJECTION unless
                    continue                         # an opt-in cap was explicitly set
            imr = float(np.interp(wr, w, im))
            g = z * (abs(imr) + eta)
            if max_gamma is not None and g > max_gamma:  # opt-in only (see docstring)
                continue
            # dominant pole = the one closest to omega=0: the coherent QP branch must
            # continuously track the Fermi level, so among valid (Z<=1) crossings the
            # nearest-to-0 one is the physical band, not whichever has the largest Z.
            if best is None or abs(wr) < abs(best[0]):
                best = (wr, z, g)
        if best is not None:
            E[ik], Z[ik], G[ik] = best
            valid[ik] = True
    return E, Z, G, valid
