# =====================================================================
# SLIM copy of true_akw_pipeline/run_lorentzian_self_consistency_fixed_mu.py
#
# 39 top-level symbols (3735 lines, 75% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   Physics, _im_sigma_row_pair_native, _internal_a_eval, _pn_qp_tables, bilinear_eval_with_support, find_qp_poles_dyson, interp_pchip, load_cube_sigma, pole_refind_half_widths_from_im_sigma, rebuild_a_from_mixed_sigma_1d, rebuild_a_from_saved_sigma_grid, rebuild_omega_per_k, select_sigma_k_indices
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   LocalJumpRefinement
#   parse_args
#   scalar_or_default
#   load_cube_base_omega
#   save_selfcons_cube
#   load_cube_sigma_complex
#   load_cube_pmf_scale
#   copy_seed_cube_with_physics
#   build_seed_cubes
#   run_step
#   pair_grid_defaults
#   run_pair_pipeline_for_iteration
#   _im_gamma0_asympt
#   _im_sigma_qp_subtract
#   _im_sigma_asym_tail
#   re_sigma_log_tail_correction
#   _sigma_re_from_kk
#   _load_internal_sigma_for_rebuild
#   _union_inloop_enabled
#   _pair_native_enabled
#   _im_sigma_row_union_fast
#   _sigma_process_row
#   compute_sigma_cube_for_spin
#   mix_sigma_arrays
#   _clamp_im_restore_re_kk
#   trapezoid_weights_1d
#   build_aitken_weights
#   aitken_delta2_global
#   mix_sigma_and_rebuild_a
#   find_kstar_from_sigma
#   interp_sigma_row_at_k
#   refine_local_kjump_from_sigma
#   save_local_kjump_refinement
#   find_qp_poles_per_k
#   interp_a_to_omega
#   rebuild_a_from_mixed_sigma
#   compute_nk_lorentzian
#   write_history
#   main
# =====================================================================
#!/usr/bin/env python3
"""Run a fixed-mu self-consistency loop with a Lorentzian or cube seed.

The loop is

    A^(n) -> ImPi_full^(n) -> Gamma^(n) -> Sigma^(n+1) -> A^(n+1)

with fixed ``mu_up`` and ``mu_down``. The pair sector uses the stabilized
residual KK route already present in the current pipeline:

    Pi_num = Pi_ref + DeltaPi_res
    1/Gamma_num = 1/Gamma_ref - DeltaPi_res

Iteration 0 starts from spin-resolved Lorentzian cubes unless explicit seed
cubes are supplied. Subsequent iterations save updated cubes with the mixed
pair-convolution self-energy.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from datetime import datetime
import multiprocessing as _mp
import os
from pathlib import Path
import subprocess
import sys
import time

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fflo.kramers_kronig import (
    bilinear_eval_with_support,
    kk_re_with_optional_powerlaw_tail,
    kk_re_pv_linear,
    kk_sigma_gamma_asymptote,
    load_cube_physics,
    normalize_spectral_rows,
)
from fflo.sigma_from_pair import (
    analytical_configuration,
    build_dyson_qp_table_for_sigma,
    build_sigma_p_grid,
    compute_im_sigma_at_omega,
    compute_im_sigma_scan_at_k,
    compute_im_sigma_scan_at_k_from_table,
    detect_core_range,
    estimate_pair_q_feature,
    load_cube_a_convention,
    load_pair_table,
    pair_spectral_function,
    pair_spectral_function_from_table,
)
from fflo.lorentzian_cube import build_lorentzian_cube, resolve_mu
from fflo.spectral import build_axes, spectral_from_g
from fflo.adn_phi import build_eps_grid, load_akw_cube


OUT_BASE = REPO_ROOT / "true_akw_pipeline" / "self_consistency_runs"


@dataclass(frozen=True)
class Physics:
    eps0: float
    mu_up: float
    mu_down: float
    mass: float
    pmf_scale: float












def load_cube_sigma(path: Path) -> tuple[np.ndarray, np.ndarray]:
    with np.load(path) as d:
        if "ReS" in d.files and "ImS" in d.files:
            re_s = np.asarray(d["ReS"], dtype=float)
            im_s = np.asarray(d["ImS"], dtype=float)
            w = np.asarray(d["w"], dtype=float) if "w" in d.files else None
            w_base = np.asarray(d["w_base"], dtype=float) if "w_base" in d.files else None
            if w is not None and w.ndim == 2:
                # Saved pole-aware cubes store Sigma on a row-local omega grid.
                # The self-consistency driver mixes Sigma on the fixed base grid,
                # so old rows must be remapped before reuse.
                target_w = w_base if (w_base is not None and w_base.ndim == 1) else w[0]
                re_out = np.empty((re_s.shape[0], target_w.size), dtype=float)
                im_out = np.empty((im_s.shape[0], target_w.size), dtype=float)
                use_pchip = str(os.environ.get("LOAD_CUBE_SIGMA_PCHIP", "0")).strip().lower() not in {"0", "false", "no", "off", ""}
                for ik in range(re_s.shape[0]):
                    if use_pchip:
                        order = np.argsort(w[ik])
                        wk = w[ik][order]
                        from scipy.interpolate import PchipInterpolator
                        re_out[ik] = PchipInterpolator(wk, re_s[ik][order], extrapolate=False)(target_w)
                        im_out[ik] = PchipInterpolator(wk, im_s[ik][order], extrapolate=False)(target_w)
                        re_out[ik] = np.where(np.isnan(re_out[ik]), np.interp(target_w, wk, re_s[ik][order]), re_out[ik])
                        im_out[ik] = np.where(np.isnan(im_out[ik]), np.interp(target_w, wk, im_s[ik][order]), im_out[ik])
                    else:
                        re_out[ik] = np.interp(target_w, w[ik], re_s[ik], left=re_s[ik, 0], right=re_s[ik, -1])
                        im_out[ik] = np.interp(target_w, w[ik], im_s[ik], left=im_s[ik, 0], right=im_s[ik, -1])
                return re_out, im_out
            return re_s, im_s
        k = np.asarray(d["k"], dtype=float)
        w = np.asarray(d["w"], dtype=float)
    return np.zeros((k.size, w.shape[-1]), dtype=float), np.zeros((k.size, w.shape[-1]), dtype=float)


























def _rowlocal_bilinear_pairs(kq, wq, k_axis, w_grid, values):
    """Bilinear evaluation for arbitrary paired queries on row-local w grids."""
    kb, wb = np.broadcast_arrays(np.asarray(kq, dtype=float), np.asarray(wq, dtype=float))
    shape = kb.shape
    kf = kb.ravel()
    wf = wb.ravel()
    ka = np.asarray(k_axis, dtype=float)
    wg = np.asarray(w_grid, dtype=float)
    tab = np.asarray(values, dtype=float)
    out = np.zeros_like(kf)
    inside_k = (kf >= ka[0]) & (kf <= ka[-1])
    if not np.any(inside_k):
        return out.reshape(shape), inside_k.reshape(shape)
    lower = np.searchsorted(ka, kf[inside_k], side="right") - 1
    lower = np.clip(lower, 0, ka.size - 2)
    source_indices = np.flatnonzero(inside_k)
    inside = np.zeros_like(kf, dtype=bool)
    for index in np.unique(lower):
        select_local = lower == index
        select = source_indices[select_local]
        ww = wf[select]
        v0 = np.interp(ww, wg[index], tab[index], left=0.0, right=0.0)
        v1 = np.interp(ww, wg[index + 1], tab[index + 1], left=0.0, right=0.0)
        tk = (kf[select] - ka[index]) / max(ka[index + 1] - ka[index], 1.0e-14)
        out[select] = (1.0 - tk) * v0 + tk * v1
        inside[select] = (
            ((ww >= wg[index, 0]) & (ww <= wg[index, -1]))
            | ((ww >= wg[index + 1, 0]) & (ww <= wg[index + 1, -1]))
        )
    return out.reshape(shape), inside.reshape(shape)


def _internal_a_eval(pq, eq, kc, wc, ac, res_c, ims_c, sigma0_c, mu_internal, eta_c):
    """Internal-fermion A at (p, eps) integration nodes.

    Default path: bilinear interpolation of the stored (peaked) A — measured
    to over/mis-count near sharp QP peaks (bias ∝ C).  With
    SIGMA_INTERNAL_REBUILD=1 (res_c/ims_c provided): bilinear-interpolate the
    SMOOTH ReSigma/ImSigma instead and rebuild the Dyson A exactly at the
    evaluation point (peak position/width analytic, no peak interpolation).
    """
    if res_c is None:
        v, ins = bilinear_eval_with_support(pq, eq, kc, wc, ac)
        return np.where(ins, v, 0.0)
    query_ndim = np.broadcast(np.asarray(pq), np.asarray(eq)).ndim
    if np.asarray(wc).ndim == 2 and query_ndim > 2:
        re_i, _ = _rowlocal_bilinear_pairs(pq, eq, kc, wc, res_c)
        im_i, ins = _rowlocal_bilinear_pairs(pq, eq, kc, wc, ims_c)
    else:
        re_i, _ = bilinear_eval_with_support(pq, eq, kc, wc, res_c)
        im_i, ins = bilinear_eval_with_support(pq, eq, kc, wc, ims_c)
    xi = pq * pq - float(mu_internal)
    g = np.abs(im_i) + float(eta_c)
    a = (1.0 / np.pi) * g / ((eq - xi - (re_i - float(sigma0_c))) ** 2 + g * g)
    return np.where(ins, a, 0.0)








def _pn_qp_tables(
    eps_tab: np.ndarray,
    *,
    kc: np.ndarray,
    wc: np.ndarray,
    res_c: np.ndarray,
    ims_c: np.ndarray,
    sigma0_c: float,
    mu_internal: float,
    eta_c: float,
    p_max: float,
    n_p_fine: int = 600,
    max_poles: int = 3,
) -> dict:
    """r34 kjac-ring: internal-fermion QP pole tables p*(eps), width gamma_p and
    p-integrated weight, K-INDEPENDENT (once per spin per iteration).
    Poles = sign changes of F(p,eps) = eps - xi_p - (ReS - sigma0) along p."""
    ring_mode = str(os.environ.get("SIGMA_PN_RING_MODE", "legacy")).strip().lower()
    robust_ring = ring_mode in {"robust", "smooth", "v2", "exact", "exact_window"}
    if robust_ring:
        n_p_fine = int(
            os.environ.get("SIGMA_PN_RING_NP_FINE", str(max(int(n_p_fine), 2400)))
        )
    p_fine = np.linspace(1e-4, float(p_max), int(n_p_fine))
    re_i, _ = bilinear_eval_with_support(p_fine[:, None], eps_tab[None, :], kc, wc, res_c)
    im_i, _ = bilinear_eval_with_support(p_fine[:, None], eps_tab[None, :], kc, wc, ims_c)
    xi = (p_fine * p_fine - float(mu_internal))[:, None]
    F = eps_tab[None, :] - xi - (re_i - float(sigma0_c))
    g = np.abs(im_i) + float(eta_c)
    n_e = eps_tab.size
    p_star = np.full((max_poles, n_e), np.nan)
    gam_p = np.full((max_poles, n_e), np.nan)
    wgt_p = np.zeros((max_poles, n_e))
    sgnb = np.signbit(F)
    flips = sgnb[1:, :] != sgnb[:-1, :]
    dp = p_fine[1] - p_fine[0]
    for je in range(n_e):
        rows = np.nonzero(flips[:, je])[0]
        for m, i0 in enumerate(rows[:max_poles]):
            f0, f1 = F[i0, je], F[i0 + 1, je]
            t = float(f0 / (f0 - f1 + 1e-300))
            dFdp = (f1 - f0) / dp
            if abs(dFdp) < 1e-8:
                continue
            slope = abs(float(dFdp))
            gm = float((g[i0, je] * (1 - t) + g[i0 + 1, je] * t) / slope)
            # ring treatment ONLY for sharp, well-defined poles: broad ones
            # (gm large) are resolved by the uniform theta grid; weak-slope
            # crossings (|dF/dp| small, band edges) have unbounded residue
            # and MUST be left to the quadrature.
            if robust_ring:
                # Blend the control variate out continuously where the pole
                # becomes broad or tangent.  The residual keeps the omitted
                # fraction, so this changes only the quadrature, not A_f.
                sharp_x = np.clip((0.05 - gm) / 0.03, 0.0, 1.0)
                sharp_act = sharp_x * sharp_x * (3.0 - 2.0 * sharp_x)
                slope_x = np.clip((slope - 0.5) / 0.5, 0.0, 1.0)
                slope_act = slope_x * slope_x * (3.0 - 2.0 * slope_x)
                activation = float(sharp_act * slope_act)
                if activation <= 1.0e-12:
                    continue
            else:
                if gm > 0.03 or slope < 0.8:
                    continue
                activation = 1.0
            p_star[m, je] = p_fine[i0] + t * dp
            # 2026-08-02: floor was 1e-6, 1000x below the gamma_floor=1e-3
            # convention used everywhere else in the pipeline (build_qp_cube,
            # analytic_qp_bubble). The ring Lorentzian's peak height ~wg/(pi*gm)
            # then reaches ~3e5 whenever the angular window samples close to
            # p_star, vs a worst case of ~318 with the 1e-3 floor used
            # elsewhere -- this matches the order of magnitude of the ReSigma
            # blowup traced to k=3.92 in the clean_decomposition scheme
            # (ReSigma reaching 1e4-1e7 from iteration 1). Same bug class as
            # the near-degenerate-pole fix in analytic_qp_bubble.py earlier
            # today (narrow Lorentzian, too-small width floor, evaluated near
            # its own singularity), different location.
            gam_p[m, je] = max(gm, 1e-3)
            wgt_p[m, je] = activation / slope
    return dict(p_star=p_star, gam_p=gam_p, wgt_p=wgt_p)


def _im_sigma_row_pair_native(
    w_axis_target: np.ndarray,
    *,
    kv: float,
    q_axis_pair: np.ndarray,
    omega_axis_pair: np.ndarray,
    a_pair: np.ndarray,
    eval_internal,          # callable (pq, eq) -> A_f  (Dyson rebuild / bilinear)
    n_theta: int = 96,
    p_int_max: float = 6.0,
    tail_cell_max: float = 0.05,
    qp_tab: dict | None = None,   # r34 kjac-ring: analytic QP angle (from _pn_qp_tables)
) -> np.ndarray:
    """PAIR-NATIVE Sigma engine (r33): Im Sigma(k,w) = -pi/(2pi)^2 *
    int Q dQ dtheta dOmega A_pair(Q,Omega) A_f(|Q-k|, Omega-w) * K(w,Omega),
    T=0 kernel K = +1 on Omega in (0,w), -1 on (w,0).

    - A_pair consumed ONLY on its native (q,Omega) nodes (never interpolated
      where it is dangerous); tail cells wider than tail_cell_max are
      subdivided with linear interp (harmless: smooth continuum there).
    - The angle lives on the FERMION: T(q,eps) = <A_f(|Q-k|,eps)>_theta is
      precomputed per row on the eps lattice (smooth -> vectorized, then
      linear interp in eps at Omega-w).
    - Validated standalone: smooth on BOTH omega sides, backbone within ~2%
      of the reference; kills the staircase by construction.
    """
    q = np.asarray(q_axis_pair, dtype=float)
    om = np.asarray(omega_axis_pair, dtype=float)
    ap = np.asarray(a_pair, dtype=float)
    w_tgt = np.asarray(w_axis_target, dtype=float)
    q_quad_w = None

    # Default changed from native_trapezoid to panel_gl (2026-09-16): see
    # the twin copy of this function in
    # weekend_validation_20260911/pair_native_candidate.py for the full
    # explanation (spurious Dyson root from under-resolved sparse tail
    # Q-cells, verified fixed by GL8 across the full k range).
    q_integration_mode = str(
        os.environ.get("SIGMA_PN_Q_INTEGRATION_MODE", "panel_gl")
    ).strip().lower()
    q_gl_n = 0
    if q_integration_mode in {"panel_gl", "gl", "gauss", "gauss_legendre"}:
        q_gl_n = max(1, int(os.environ.get("SIGMA_PN_Q_GL_N", "8")))
        q_gl_lowk_max = float(os.environ.get("SIGMA_PN_Q_GL_LOWK_MAX", "-1"))
        if float(kv) <= q_gl_lowk_max:
            q_gl_n = max(
                q_gl_n,
                int(os.environ.get("SIGMA_PN_Q_GL_N_LOWK", str(q_gl_n))),
            )
        x_gl, w_gl = np.polynomial.legendre.leggauss(q_gl_n)
        q_lo = q[:-1, None]
        q_hi = q[1:, None]
        q_mid = 0.5 * (q_lo + q_hi)
        q_half = 0.5 * (q_hi - q_lo)
        q_panel = q_mid + q_half * x_gl[None, :]
        frac = (q_panel - q_lo) / np.maximum(q_hi - q_lo, 1.0e-14)
        ap_panel = (
            (1.0 - frac)[:, :, None] * ap[:-1, None, :]
            + frac[:, :, None] * ap[1:, None, :]
        )
        q = q_panel.ravel()
        ap = ap_panel.reshape(-1, ap.shape[1])
        q_quad_w = (q_half * w_gl[None, :]).ravel()

    # The pair table is piecewise linear in Q, but the remaining fermion
    # factor can vary appreciably inside a wide Q cell.  Optional midpoint
    # subdivision improves only that quadrature: it neither smooths A_pair
    # nor invents additional pair information.  Keep it opt-in so legacy
    # production behavior is bit-for-bit unchanged.
    q_refine_levels = (
        0
        if q_quad_w is not None
        else max(0, int(os.environ.get("SIGMA_PN_Q_REFINE_LEVELS", "0")))
    )
    q_refine_max = float(os.environ.get("SIGMA_PN_Q_REFINE_MAX", "inf"))
    for _ in range(q_refine_levels):
        refine = q[:-1] < q_refine_max - 1.0e-14
        if not np.any(refine):
            break
        q_mid = 0.5 * (q[:-1] + q[1:])
        ap_mid = 0.5 * (ap[:-1] + ap[1:])
        q = np.concatenate((q, q_mid[refine]))
        ap = np.concatenate((ap, ap_mid[refine]), axis=0)
        order = np.argsort(q, kind="stable")
        q = q[order]
        ap = ap[order]

    ring_mode = str(os.environ.get("SIGMA_PN_RING_MODE", "legacy")).strip().lower()
    exact_ring = ring_mode in {"exact", "exact_window"}
    robust_ring = ring_mode in {"robust", "smooth", "v2", "exact", "exact_window"}
    # SIGMA_PN_ANGLE_EXACT_CUT (2026-09-22): il taglio p<=p_int_max era imposto
    # come MASCHERA su una griglia theta uniforme, cioe' si integrava un
    # integrando con un gradino usando una media a n_theta punti fissi. La
    # posizione del gradino rispetto ai nodi cambia con (q,k), quindi l'errore
    # non e' un bias ma rumore che oscilla di segno: misurato fino a 4.7% a
    # p_int_max=3 e 9.1% a p_int_max=6 sulla geometria esatta del kernel.
    # Peggiora alzando p_int_max perche' il guscio in cui il taglio morde,
    # q in (p_int_max-k, p_int_max+k), si sposta dove la griglia q e' piu' rada
    # e i pesi trapezoidali piu' grandi.
    # p(theta) cresce monotonamente da |q-k| a q+k, quindi p<=p_int_max equivale
    # a theta<=theta* con cos(theta*) = (q^2+k^2-p_int_max^2)/(2qk): basta
    # campionare su [0,theta*] invece di mascherare. Errore -> 0, stesso costo.
    _exact_cut = str(
        os.environ.get("SIGMA_PN_ANGLE_EXACT_CUT", "0")
    ).strip().lower() not in {"", "0", "false", "no", "off"}
    if _exact_cut:
        _pm = float(p_int_max)
        _arc_lo = np.abs(q - kv)
        _arc_hi = q + kv
        _cosstar = (q ** 2 + kv * kv - _pm * _pm) / np.maximum(2.0 * q * kv, 1.0e-300)
        theta_star = np.where(
            _arc_hi <= _pm,
            np.pi,
            np.where(_arc_lo >= _pm, 0.0, np.arccos(np.clip(_cosstar, -1.0, 1.0))),
        )
        theta = (np.arange(int(n_theta)) + 0.5)[None, :] * theta_star[:, None] / float(n_theta)
        p_th = np.sqrt(np.maximum(q[:, None] ** 2 + kv * kv - 2.0 * q[:, None] * kv * np.cos(theta), 0.0))
        p_ok = np.ones(p_th.shape, dtype=bool)
        theta_weight = 2.0 * theta_star[:, None]   # int su [0,theta*], poi specchiato
    else:
        theta_star = None
        theta = (np.arange(int(n_theta)) + 0.5) * 2.0 * np.pi / float(n_theta)
        p_th = np.sqrt(np.maximum(q[:, None] ** 2 + kv * kv - 2.0 * q[:, None] * kv * np.cos(theta)[None, :], 0.0))
        p_ok = p_th <= float(p_int_max)
        theta_weight = 2.0 * np.pi

    # eps support needed: Omega - w for all windows
    eps_lo = float(om[0]) - float(max(w_tgt[-1], 0.0))
    eps_hi = float(om[-1]) - float(min(w_tgt[0], 0.0))
    # smooth theta-averaged fermion table on a dense-core + stretched grid
    eps_core = np.arange(-0.5, 0.5 + 1e-12, 2.0e-3)
    n_str = 420
    eps_pos = 0.5 * np.exp(np.linspace(0.0, np.log(max(eps_hi, 1.0) / 0.5), n_str))
    eps_neg = -0.5 * np.exp(np.linspace(0.0, np.log(max(-eps_lo, 1.0) / 0.5), n_str))
    eps_tab = np.unique(np.concatenate([eps_neg[::-1], eps_core, eps_pos]))
    eps_tab = eps_tab[(eps_tab >= eps_lo - 1.0) & (eps_tab <= eps_hi + 1.0)]

    # r34 kjac-ring: interpolate the k-independent pole tables onto eps_tab
    ring = None
    if qp_tab is not None:
        eps_src = np.asarray(qp_tab["eps_src"], dtype=float)
        ring = []
        for m in range(qp_tab["p_star"].shape[0]):
            ps = np.interp(eps_tab, eps_src, qp_tab["p_star"][m], left=np.nan, right=np.nan)
            gm = np.interp(eps_tab, eps_src, qp_tab["gam_p"][m], left=np.nan, right=np.nan)
            wg = np.interp(eps_tab, eps_src, qp_tab["wgt_p"][m], left=0.0, right=0.0)
            ok_m = np.isfinite(np.asarray(qp_tab["p_star"][m], dtype=float))
            frac = np.interp(eps_tab, eps_src, ok_m.astype(float))
            if robust_ring:
                wg = wg * np.clip(frac, 0.0, 1.0)
            else:
                wg = np.where(frac > 0.99, wg, 0.0)   # only where the pole branch exists cleanly
            ring.append((ps, gm, wg))

    T = np.empty((q.size, eps_tab.size), dtype=float)
    chunk = 64
    flat_p = p_th.ravel()
    p_lo = np.abs(q - kv); p_hi = q + kv       # theta-arc endpoints per q
    for j0 in range(0, eps_tab.size, chunk):
        j1 = min(j0 + chunk, eps_tab.size)
        vals = eval_internal(flat_p[:, None], eps_tab[None, j0:j1])
        vals = vals.reshape(q.size, int(n_theta), j1 - j0)
        vals = np.where(p_ok[:, :, None], vals, 0.0)
        if ring is not None and not exact_ring:
            # subtract the QP Lorentzians at the theta nodes...
            for ps_a, gm_a, wg_a in ring:
                ps = ps_a[j0:j1]; gm = gm_a[j0:j1]; wg = wg_a[j0:j1]
                use = np.isfinite(ps) & (wg > 0.0)
                if not np.any(use):
                    continue
                dpp = p_th[:, :, None] - ps[None, None, :]
                L = (wg / np.pi) * gm / (dpp ** 2 + gm[None, None, :] ** 2)
                if robust_ring:
                    scaled = np.abs(dpp) / np.maximum(gm[None, None, :], 1.0e-12)
                    taper = np.where(
                        scaled <= 6.0,
                        1.0,
                        np.where(
                            scaled < 10.0,
                            0.5 * (1.0 + np.cos(np.pi * (scaled - 6.0) / 4.0)),
                            0.0,
                        ),
                    )
                    L = np.where(use[None, None, :] & p_ok[:, :, None], L * taper, 0.0)
                else:
                    L = np.where(use[None, None, :] & p_ok[:, :, None] & (np.abs(dpp) <= 8.0 * gm[None, None, :]), L, 0.0)
                vals = vals - L
        T[:, j0:j1] = vals.mean(axis=1) * theta_weight   # smooth remainder: short theta is enough
        if ring is not None:
            # ...and add int dtheta L(p(theta)) via a dedicated fine theta-window
            # around each ring crossing (L is analytic: pure arithmetic, no
            # eval_internal; robust at arc tangency where closed forms diverge).
            n_win = int(os.environ.get("SIGMA_PN_RING_NWIN", "48"))
            if robust_ring:
                su, sw = np.polynomial.legendre.leggauss(n_win)
            else:
                su = np.linspace(-1.0, 1.0, n_win)
            for ps_a, gm_a, wg_a in ring:
                ps = ps_a[j0:j1]; gm = gm_a[j0:j1]; wg = wg_a[j0:j1]
                use2 = np.isfinite(ps) & (wg > 0.0) & (ps <= float(p_int_max) + 0.5)
                if not np.any(use2):
                    continue
                pss = np.where(use2, ps, 1.0); gms = np.where(use2, gm, 1.0)
                if robust_ring:
                    # Exact support of the smooth p-window mapped to theta.
                    # This remains continuous when the pole enters an angular
                    # arc and is well behaved at theta=0,pi tangencies.
                    p_arc_lo = np.abs(q[:, None] - float(kv))
                    p_arc_hi = q[:, None] + float(kv)
                    window_gamma = (
                        float(os.environ.get("SIGMA_PN_EXACT_WINDOW_GAMMA", "16"))
                        if exact_ring
                        else 10.0
                    )
                    p_sup_lo = np.maximum(p_arc_lo, pss[None, :] - window_gamma * gms[None, :])
                    p_sup_hi = np.minimum(p_arc_hi, pss[None, :] + window_gamma * gms[None, :])
                    p_sup_hi = np.minimum(p_sup_hi, float(p_int_max))
                    denom = 2.0 * q[:, None] * float(kv)
                    overlap = (
                        use2[None, :]
                        & (denom > 1.0e-12)
                        & (p_sup_hi > p_sup_lo + 1.0e-14)
                    )
                    x_lo = (q[:, None] ** 2 + kv * kv - p_sup_lo ** 2) / np.maximum(denom, 1.0e-12)
                    x_hi = (q[:, None] ** 2 + kv * kv - p_sup_hi ** 2) / np.maximum(denom, 1.0e-12)
                    th_lo = np.arccos(np.clip(x_lo, -1.0, 1.0))
                    th_hi = np.arccos(np.clip(x_hi, -1.0, 1.0))
                    th_mid = 0.5 * (th_lo + th_hi)
                    th_half = 0.5 * (th_hi - th_lo)
                    th_w = th_mid[:, :, None] + th_half[:, :, None] * su[None, None, :]
                else:
                    x_star = (q[:, None] ** 2 + kv * kv - pss[None, :] ** 2) / np.maximum(2.0 * q[:, None] * kv, 1e-12)
                    overlap = (x_star > -1.0 + 1e-9) & (x_star < 1.0 - 1e-9) & use2[None, :]
                    th_star = np.arccos(np.clip(x_star, -1.0 + 1e-12, 1.0 - 1e-12))
                    dpdth = np.maximum(q[:, None] * kv * np.sin(th_star) / np.maximum(pss[None, :], 1e-9), 1e-9)
                    th_half = np.clip(8.0 * gms[None, :] / dpdth, 5e-4, 0.5 * np.pi)
                    th_w = th_star[:, :, None] + th_half[:, :, None] * su[None, None, :]
                    th_w = np.clip(th_w, 0.0, np.pi)
                p_w = np.sqrt(np.maximum(q[:, None, None] ** 2 + kv * kv - 2.0 * q[:, None, None] * kv * np.cos(th_w), 0.0))
                if exact_ring:
                    eps_w = np.broadcast_to(
                        eps_tab[None, j0:j1, None], p_w.shape
                    )
                    a_window = eval_internal(p_w, eps_w)
                    vals_qe = np.transpose(vals, (0, 2, 1))
                    if _exact_cut:
                        # griglia theta per-q su [0,theta*]: indice frazionario
                        # senza wrap (th_w <= theta* per costruzione, p_sup_hi
                        # e' gia' clippato a p_int_max piu' sopra).
                        _dth = np.maximum(theta_star, 1.0e-300) / float(n_theta)
                        u = np.clip(
                            th_w / _dth[:, None, None] - 0.5,
                            0.0,
                            float(int(n_theta) - 1) - 1.0e-9,
                        )
                        i0 = np.floor(u).astype(int)
                        frac_theta = u - i0
                        i1 = np.minimum(i0 + 1, int(n_theta) - 1)
                    else:
                        dtheta = 2.0 * np.pi / float(theta.size)
                        u = np.mod(th_w / dtheta - 0.5, float(theta.size))
                        i0 = np.floor(u).astype(int)
                        frac_theta = u - i0
                        i1 = (i0 + 1) % theta.size
                    base0 = np.take_along_axis(vals_qe, i0, axis=2)
                    base1 = np.take_along_axis(vals_qe, i1, axis=2)
                    a_base_window = (1.0 - frac_theta) * base0 + frac_theta * base1
                    correction = th_half * np.sum(
                        (a_window - a_base_window) * sw[None, None, :], axis=2
                    )
                    T[:, j0:j1] = T[:, j0:j1] + 2.0 * np.where(
                        overlap, correction, 0.0
                    )
                    continue
                dpw = p_w - pss[None, :, None]
                Lw = (wg[None, :, None] / np.pi) * gms[None, :, None] / (dpw ** 2 + gms[None, :, None] ** 2)
                if robust_ring:
                    scaled_w = np.abs(dpw) / np.maximum(gms[None, :, None], 1.0e-12)
                    taper_w = np.where(
                        scaled_w <= 6.0,
                        1.0,
                        np.where(
                            scaled_w < 10.0,
                            0.5 * (1.0 + np.cos(np.pi * (scaled_w - 6.0) / 4.0)),
                            0.0,
                        ),
                    )
                    Lw = np.where(
                        (p_w <= float(p_int_max)) & overlap[:, :, None],
                        Lw * taper_w,
                        0.0,
                    )
                    integ = th_half * np.sum(Lw * sw[None, None, :], axis=2)
                else:
                    Lw = np.where((p_w <= float(p_int_max)) & overlap[:, :, None] & (np.abs(dpw) <= 8.0 * gms[None, :, None]), Lw, 0.0)
                    dth = (th_w[:, :, 2:] - th_w[:, :, :-2]) * 0.5
                    integ = np.sum(Lw[:, :, 1:-1] * dth, axis=2) + 0.5 * (Lw[:, :, 0] * (th_w[:, :, 1] - th_w[:, :, 0]) + Lw[:, :, -1] * (th_w[:, :, -1] - th_w[:, :, -2]))
                T[:, j0:j1] = T[:, j0:j1] + 2.0 * integ   # mirror window (2pi - theta*)

    if q_quad_w is None:
        wq = np.empty_like(q)
        wq[1:-1] = 0.5 * (q[2:] - q[:-2]); wq[0] = 0.5 * (q[1] - q[0]); wq[-1] = 0.5 * (q[-1] - q[-2])
    else:
        wq = q_quad_w
    q_weight = q * wq

    out = np.zeros(w_tgt.size, dtype=float)
    for io, w_ext in enumerate(w_tgt):
        if w_ext == 0.0:
            continue
        lo, hi = (0.0, float(w_ext)) if w_ext > 0.0 else (float(w_ext), 0.0)
        sgn = 1.0 if w_ext > 0.0 else -1.0
        # Omega=omega is generally inside a native pair-table cell.  Keep the
        # moving endpoints explicitly so the last partial cell is integrated
        # continuously instead of entering as a staircase at the next node.
        seg_inner = om[(om > lo + 1e-12) & (om < hi - 1e-12)]
        seg = np.concatenate(([lo], seg_inner, [hi]))
        # subdivide wide tail cells (pair is smooth there; interp is safe)
        pieces = [seg[:1]]
        for a0, b0 in zip(seg[:-1], seg[1:]):
            if (b0 - a0) > tail_cell_max:
                n_sub = int(np.ceil((b0 - a0) / tail_cell_max))
                pieces.append(np.linspace(a0, b0, n_sub + 1)[1:])
            else:
                pieces.append(np.array([b0]))
        seg_f = np.concatenate(pieces)
        ap_seg = np.empty((q.size, seg_f.size), dtype=float)
        for iq in range(q.size):
            ap_seg[iq] = np.interp(seg_f, om, ap[iq])
        ws = np.empty_like(seg_f)
        ws[1:-1] = 0.5 * (seg_f[2:] - seg_f[:-2]); ws[0] = 0.5 * (seg_f[1] - seg_f[0]); ws[-1] = 0.5 * (seg_f[-1] - seg_f[-2])
        # fermion factor at eps = Omega - w  (interp columns of smooth T)
        eps_need = seg_f - float(w_ext)
        idx = np.clip(np.searchsorted(eps_tab, eps_need) - 1, 0, eps_tab.size - 2)
        t = (eps_need - eps_tab[idx]) / np.maximum(eps_tab[idx + 1] - eps_tab[idx], 1e-14)
        Tf = T[:, idx] * (1.0 - t)[None, :] + T[:, idx + 1] * t[None, :]
        total = float(np.sum(q_weight[:, None] * ap_seg * Tf * (sgn * ws)[None, :]))
        out[io] = -np.pi * total / ((2.0 * np.pi) ** 2)
    if not globals().get("_PN_ANNOUNCED", False):
        globals()["_PN_ANNOUNCED"] = True
        print(
            f"[sigma-engine] PAIR-NATIVE ON (n_theta={int(n_theta)}, "
            f"eps_tab={eps_tab.size}, q_nodes={q.size}, "
            f"q_mode={q_integration_mode}, q_gl_n={q_gl_n}, "
            f"q_refine_levels={q_refine_levels}, "
            f"tail_cell_max={tail_cell_max:g})",
            flush=True,
        )
    return out




# ── Fork-based process-parallel sigma worker ─────────────────────────────────
# Populated in compute_sigma_cube_for_spin before spawning the Pool.
# Fork semantics on Linux mean child processes inherit all arrays via COW
# without any pickling overhead.  Only (ik, kv) args and result arrays cross
# the pipe.
_WORKER_CTX: dict = {}


# ─────────────────────────────────────────────────────────────────────────────














def rebuild_a_from_mixed_sigma_1d(
    *,
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    re_mix: np.ndarray,
    im_mix: np.ndarray,
    mu_sigma: float,
    mass: float,
    eta_g: float,
    convention: str,
    sigma0_mode: str = "fermi",
    sigma0_density_kmax: float = 5.53,
    sigma0_density_tol: float = 1.0e-5,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float, float]:
    k = np.asarray(k_axis, dtype=float)
    w = np.asarray(w_axis, dtype=float)
    re_mix = np.asarray(re_mix, dtype=float)
    im_mix = np.minimum(np.asarray(im_mix, dtype=float), 0.0)
    w_ref_idx = int(np.argmin(np.abs(w)))
    sigma0_w = float(w[w_ref_idx])
    sigma0_mode_l = str(sigma0_mode).strip().lower()
    if sigma0_mode_l == "density":
        # High-P closure: do NOT pin a quasiparticle at (kF, 0).  Solve the
        # scalar shift s so that the occupied density of the rebuilt A matches
        # the Luttinger target N = m*mu/2 (n(k) integrated to kmax, i.e. the
        # contact-repair window).  n(s) is monotone increasing in s (raising s
        # lowers every pole), so bisection is safe.  This is the polaron-to-
        # molecule-safe replacement of the Fermi-surface pin: at high P the
        # minority physical mu sits far below the band bottom and pinning
        # ReSigma(kF,0) manufactures a Fermi surface the state does not have.
        target = float(mass) * float(mu_sigma) / 2.0
        kmax = float(sigma0_density_kmax)
        kw = np.where(k <= kmax, k, 0.0)
        occ = w <= 0.0
        xi = k[:, None] ** 2 / float(mass) - float(mu_sigma)

        def occupied_density(s: float) -> float:
            g = 1.0 / (w[None, :] - xi - (re_mix - s) - 1j * im_mix + 1j * float(eta_g))
            a = spectral_from_g(g, str(convention))
            nk = np.trapezoid(a[:, occ], w[occ], axis=1)
            return float(np.trapezoid(nk * kw, k))

        # Start from the fermi-pin value as the initial guess and bracket.
        k_fermi = float(np.sqrt(max(float(mass) * float(mu_sigma), 0.0)))
        re_at_kF = np.array(
            [float(np.interp(k_fermi, k, re_mix[:, j])) for j in range(re_mix.shape[1])]
        )
        s_guess = float(np.interp(0.0, w, re_at_kF))
        lo, hi = s_guess - 1.0, s_guess + 1.0
        n_lo, n_hi = occupied_density(lo), occupied_density(hi)
        for _ in range(60):
            if n_lo <= target:
                break
            lo -= 2.0
            n_lo = occupied_density(lo)
        for _ in range(60):
            if n_hi >= target:
                break
            hi += 2.0
            n_hi = occupied_density(hi)
        if not (n_lo <= target <= n_hi):
            raise RuntimeError(
                f"sigma0 density mode: could not bracket target {target:.6f} "
                f"(n({lo:.2f})={n_lo:.6f}, n({hi:.2f})={n_hi:.6f})"
            )
        tol = float(sigma0_density_tol)
        sigma0 = 0.5 * (lo + hi)
        for _ in range(80):
            sigma0 = 0.5 * (lo + hi)
            n_mid = occupied_density(sigma0)
            if abs(n_mid - target) <= tol:
                break
            if n_mid < target:
                lo = sigma0
            else:
                hi = sigma0
        re_shifted = re_mix - sigma0
        sigma_mix = re_shifted + 1j * im_mix
        g = 1.0 / (w[None, :] - xi - sigma_mix + 1j * float(eta_g))
        a_mix = spectral_from_g(g, str(convention))
        return a_mix, re_mix, im_mix, float(sigma0), sigma0_w
    if sigma0_mode_l in {"fermi", "fermi_exact"}:
        # Pin the real-part shift EXACTLY at (kF, omega=0): sigma0 = ReSigma(kF, 0),
        # evaluated by interpolation (smooth ReSigma -> stable across iterations,
        # no single-index jumps, AND no bias). This makes the Luttinger kF coincide
        # with the free kF, so the density (and the polarization P_meas) come out
        # right by themselves. A +-10% k-average biased sigma0 by ~0.013, shifting
        # kF_L and inflating P_meas by ~5% (P=0.30 -> 0.316; exact -> 0.303).
        k_fermi = float(np.sqrt(max(float(mass) * float(mu_sigma), 0.0)))
        # ReSigma(kF, w): interpolate each omega-column at k_fermi, then at omega=0.
        re_at_kF = np.array(
            [float(np.interp(k_fermi, k, re_mix[:, j])) for j in range(re_mix.shape[1])]
        )
        sigma0 = float(np.interp(0.0, w, re_at_kF))
        # sigma0 AUDIT: an error delta on sigma0 feeds the density DIRECTLY
        # (unpinned kF: dn_sigma ~ -delta/2 per spin). Estimate the k-interp
        # error as |quadratic - linear| on the omega~0 column and report it.
        try:
            j0 = int(np.argmin(np.abs(np.asarray(w, dtype=float))))
            col = np.asarray(re_mix[:, j0], dtype=float)
            i0 = int(np.clip(np.searchsorted(k, k_fermi), 1, k.size - 2))
            kk3 = np.asarray(k[i0 - 1:i0 + 2], dtype=float)
            c3 = col[i0 - 1:i0 + 2]
            quad = float(np.polyval(np.polyfit(kk3, c3, 2), k_fermi))
            lin = float(np.interp(k_fermi, k, col))
            print(f"[sigma0-audit] mu={float(mu_sigma):.3f} sigma0={sigma0:+.6f} "
                  f"k-interp err~{abs(quad - lin):.2e} (dn budget ~ same order)", flush=True)
        except Exception:
            pass
    elif sigma0_mode_l == "fermi_window":
        # r24 compatibility/audit mode: average ReSigma(k,0) over a broad
        # neighbourhood of the free kF.  This is deliberately kept as an
        # explicit switch so we can separate the sigma0 change from the rest
        # of the r25 fixes without editing the pipeline again.
        k_fermi = float(np.sqrt(max(float(mass) * float(mu_sigma), 0.0)))
        dk = float(np.median(np.diff(k))) if k.size > 1 else 0.0
        kF_tol = max(0.10 * k_fermi, 3.0 * dk)
        near_kF = np.abs(k - k_fermi) <= kF_tol
        if not np.any(near_kF):
            near_kF[int(np.argmin(np.abs(k - k_fermi)))] = True
        sigma0 = float(np.mean(re_mix[near_kF, w_ref_idx]))
    elif sigma0_mode_l == "none":
        sigma0 = 0.0
    else:
        raise ValueError(f"Unsupported sigma0_mode '{sigma0_mode}'.")

    re_shifted = re_mix - sigma0
    sigma_mix = re_shifted + 1j * im_mix
    xi = k[:, None] ** 2 / float(mass) - float(mu_sigma)
    g = 1.0 / (w[None, :] - xi - sigma_mix + 1j * float(eta_g))
    a_mix = spectral_from_g(g, str(convention))
    return a_mix, re_mix, im_mix, sigma0, sigma0_w




def rebuild_a_from_saved_sigma_grid(
    *,
    k_axis: np.ndarray,
    w_grid: np.ndarray,
    re_sigma: np.ndarray,
    im_sigma: np.ndarray,
    mu_sigma: float,
    mass: float,
    eta_g: float,
    convention: str,
    sigma0: float,
) -> np.ndarray:
    """Rebuild A on the exact omega grid where ReSigma/ImSigma are saved."""
    k = np.asarray(k_axis, dtype=float)
    w = np.asarray(w_grid, dtype=float)
    re_s = np.asarray(re_sigma, dtype=float)
    im_s = np.asarray(im_sigma, dtype=float)
    if w.ndim == 1:
        xi = k[:, None] ** 2 / float(mass) - float(mu_sigma)
        g = 1.0 / (
            w[None, :]
            - xi
            - (re_s - float(sigma0))
            - 1j * im_s
            + 1j * float(eta_g)
        )
        return spectral_from_g(g, str(convention))
    if w.ndim != 2 or w.shape != re_s.shape or w.shape != im_s.shape:
        raise ValueError(
            "row-local omega rebuild expects w/ReS/ImS with matching 2D shapes; "
            f"got w{w.shape}, ReS{re_s.shape}, ImS{im_s.shape}"
        )
    xi = k[:, None] ** 2 / float(mass) - float(mu_sigma)
    g = 1.0 / (
        w
        - xi
        - (re_s - float(sigma0))
        - 1j * im_s
        + 1j * float(eta_g)
    )
    return spectral_from_g(g, str(convention))






def select_sigma_k_indices(
    k_axis: np.ndarray,
    n_target: int,
    *,
    spin: str,
    physics: Physics,
    mu_internal: float,
    q_feature: float,
) -> np.ndarray:
    """Choose reduced Sigma k-rows while preserving physical feature locations."""
    k = np.asarray(k_axis, dtype=float)
    nk = int(k.size)
    n = int(n_target)
    if n <= 0 or n >= nk:
        return np.arange(nk, dtype=int)

    base = set(np.round(np.linspace(0, nk - 1, max(2, n))).astype(int).tolist())

    spin_l = str(spin).strip().lower()
    mu_external = float(physics.mu_up if spin_l == "up" else physics.mu_down)
    kf_external = float(np.sqrt(max(float(physics.mass) * mu_external, 0.0)))
    kf_internal = float(np.sqrt(max(float(physics.mass) * float(mu_internal), 0.0)))

    features = [float(k[0]), 0.0, kf_external, kf_internal, float(k[-1])]
    if np.isfinite(float(q_feature)):
        q = abs(float(q_feature))
        features.extend(
            [
                q,
                abs(q - kf_internal),
                q + kf_internal,
                abs(q - kf_external),
                q + kf_external,
            ]
        )

    feature_idx: set[int] = set()
    for feat in features:
        if not np.isfinite(feat):
            continue
        idx = int(np.argmin(np.abs(k - float(feat))))
        for j in (idx - 1, idx, idx + 1):
            if 0 <= j < nk:
                base.add(j)
                feature_idx.add(j)

    idx_all = np.array(sorted(base), dtype=int)
    if idx_all.size <= n:
        return idx_all

    # Keep feature anchors first; thin the uniform background if the requested
    # reduced grid is very small.  In production, use sigma_nk ~ 40-80.
    keep = sorted(feature_idx)
    if len(keep) >= n:
        return np.array(sorted(keep)[:n], dtype=int)

    remaining = [i for i in idx_all.tolist() if i not in feature_idx]
    need = n - len(keep)
    if remaining:
        pick = np.round(np.linspace(0, len(remaining) - 1, min(need, len(remaining)))).astype(int)
        keep.extend([remaining[int(i)] for i in pick])
    return np.array(sorted(set(keep)), dtype=int)








def find_qp_poles_dyson(
    A: np.ndarray,
    re_sigma: np.ndarray,
    w: np.ndarray,
    k: np.ndarray,
    mu: float,
    mass: float,
    sigma0: float = 0.0,
) -> np.ndarray:
    """QP pole per k via the shifted Dyson zero-crossing.

    The saved/rebuilt spectral function uses

        G^-1 = omega - xi_k - (ReSigma(k,omega) - sigma0) + i(...)

    so the pole-refind grid must use the same shifted denominator.  Otherwise
    the enrichment can be centered on a pole of a different Green's function.

    w must be 1D (shared base grid). Falls back to argmax when no zero is found
    (deep incoherent tail or numerical issues).
    """
    w = np.asarray(w, dtype=float)
    A = np.asarray(A, dtype=float)
    re_sigma = np.asarray(re_sigma, dtype=float)
    k = np.asarray(k, dtype=float)
    xi = k * k / float(mass) - float(mu)   # bare dispersion ξ_k = k²/m − μ
    re_shifted = re_sigma - float(sigma0)

    poles = np.empty(len(k), dtype=float)
    for ik in range(len(k)):
        f = w - xi[ik] - re_shifted[ik]    # shifted Dyson residual on base grid
        # Find all sign-change intervals
        signs = np.sign(f)
        crossings = np.where(np.diff(signs) != 0)[0]  # left index of each bracket
        if len(crossings) == 0:
            # No zero found — fall back to argmax of A
            poles[ik] = float(w[int(np.argmax(A[ik]))])
            continue
        # Linear interpolation to refine each zero
        zeros = []
        for ic in crossings:
            f0, f1 = f[ic], f[ic + 1]
            w0, w1 = w[ic], w[ic + 1]
            denom = f1 - f0
            if abs(denom) < 1e-30:
                zeros.append(0.5 * (w0 + w1))
            else:
                zeros.append(float(w0 - f0 * (w1 - w0) / denom))
        # Among all zeros, pick the one with largest A (QP peak)
        best = max(zeros, key=lambda wz: float(np.interp(wz, w, A[ik])))
        poles[ik] = best
    return poles


def _build_w_row(
    w_base: np.ndarray,
    pole: float,
    half_width: float,
    n_local: int,
    *,
    zero_protect_half_width: float | None = None,
    occupied_protect_min: float | None = None,
) -> np.ndarray:
    """Build a single per-k omega row: protected zero grid + local pole grid.

    The dangerous rows are precisely those whose quasiparticle pole is near
    omega=0.  Therefore we must *not* skip pole enrichment inside the protected
    zero window.  Instead, keep the original base nodes around zero and add the
    local shifted-Dyson pole nodes on top, removing only far-tail/background
    nodes to keep the row length equal to len(w_base).

    At large k the occupation is controlled by a small broad shoulder at
    negative omega, not by the positive QP pole. If pole enrichment steals too
    many occupied-side base nodes, k^4 n(k) develops an artificial post-cut
    kink. occupied_protect_min keeps that shoulder resolved without increasing
    the saved row length.
    """
    w = np.unique(np.asarray(w_base, dtype=float))
    n_w = int(w.size)
    if n_w == 0:
        return w

    hw = float(max(half_width, 1.0e-10))
    n_loc = int(max(n_local, 2))
    if zero_protect_half_width is None:
        zero_protect_half_width = 4.0 * hw
    zero_protect_half_width = float(max(zero_protect_half_width, 0.0))

    if not np.isfinite(float(pole)) or not (float(w[0]) <= float(pole) <= float(w[-1])):
        return w.copy()

    protected_mask = np.abs(w) < zero_protect_half_width
    if occupied_protect_min is not None and np.isfinite(float(occupied_protect_min)):
        occ_min = float(min(occupied_protect_min, 0.0))
        protected_mask = protected_mask | ((w >= occ_min) & (w <= 0.0))
    w_protected = w[protected_mask]
    enrichment = np.linspace(
        max(float(pole) - hw, float(w[0])),
        min(float(pole) + hw, float(w[-1])),
        n_loc,
        dtype=float,
    )
    # r33: with POLE_REFIND_SNAP_DW>0 quantize enrichment nodes to integer
    # multiples of dw so refined rows stay on the commensurate micro-lattice
    # (dw=1e-3 is far below any physical width in play).
    _snap_dw = float(os.environ.get("POLE_REFIND_SNAP_DW", "0") or 0.0)
    if _snap_dw > 0.0:
        enrichment = np.unique(
            np.clip(np.round(enrichment / _snap_dw) * _snap_dw, float(w[0]), float(w[-1]))
        )

    # Keep the original zero grid and the local pole window.  Tail/background
    # nodes are the only budget that can be thinned away.
    anchors = np.unique(np.concatenate([w_protected, enrichment]))
    if anchors.size >= n_w:
        idx = np.round(np.linspace(0, anchors.size - 1, n_w)).astype(int)
        return np.asarray(anchors[idx], dtype=float)

    # Exclude protected occupied/zero nodes from the thinnable base pool. Exact
    # duplicates with enrichment are harmless because the final unique removes
    # them; if that leaves the row short, we add the nearest remaining base
    # nodes below.
    w_thinnable = w[~protected_mask]
    n_keep = max(0, n_w - anchors.size)
    if w_thinnable.size > n_keep:
        if n_keep > 0:
            idx = np.round(np.linspace(0, w_thinnable.size - 1, n_keep)).astype(int)
            w_thinnable = w_thinnable[idx]
        else:
            w_thinnable = np.array([], dtype=float)

    row = np.unique(np.concatenate([anchors, w_thinnable]))
    if row.size < n_w:
        # Duplicates between enrichment and retained base points can make the
        # row slightly short.  Fill from the remaining base nodes, preferring
        # points closest to omega=0 because they matter most for n(k).
        missing = n_w - row.size
        remaining = np.setdiff1d(w, row, assume_unique=False)
        if remaining.size:
            order = np.argsort(np.abs(remaining))
            row = np.unique(np.concatenate([row, remaining[order[:missing]]]))

    if row.size >= n_w:
        return np.asarray(row[:n_w], dtype=float)

    # Extremely defensive fallback: preserve monotonic shape if the base grid
    # itself was pathological.
    out = np.empty(n_w, dtype=float)
    out[:row.size] = row
    out[row.size:] = row[-1]
    return out


def rebuild_omega_per_k(
    w_base: np.ndarray,
    poles_per_k: np.ndarray,
    half_width: float | np.ndarray,
    n_local: int,
    *,
    zero_protect_half_width: float | None = None,
    occupied_protect_min: float | None = None,
) -> np.ndarray:
    """Build a per-k omega grid (2D, shape n_k x n_w).

    Each row is the shared base grid enriched locally around that k's QP pole.
    All rows have the same length (len(w_base)); budget is neutral per row.
    """
    w_base = np.asarray(w_base, dtype=float)
    poles = np.asarray(poles_per_k, dtype=float)
    if np.ndim(half_width) == 0:
        widths = np.full(poles.shape, float(half_width), dtype=float)
    else:
        widths = np.asarray(half_width, dtype=float)
        if widths.shape != poles.shape:
            raise ValueError(f"pole half-width shape {widths.shape} does not match poles {poles.shape}")
    rows = [
        _build_w_row(
            w_base,
            float(p),
            float(hw),
            n_local,
            zero_protect_half_width=zero_protect_half_width,
            occupied_protect_min=occupied_protect_min,
        )
        for p, hw in zip(poles, widths)
    ]
    n_w = len(w_base)
    # All rows should be length n_w after budget-neutral construction; pad/trim
    # with edge-repeat if deduplication made a row slightly shorter.
    out = np.empty((len(rows), n_w), dtype=float)
    for i, row in enumerate(rows):
        if len(row) >= n_w:
            out[i] = row[:n_w]
        else:
            out[i, :len(row)] = row
            out[i, len(row):] = row[-1]
    return out


def pole_refind_half_widths_from_im_sigma(
    *,
    w_axis: np.ndarray,
    im_sigma: np.ndarray,
    poles: np.ndarray,
    eta_g: float,
    min_half_width: float,
    width_factor: float,
) -> np.ndarray:
    """Choose per-row pole windows wide enough to include the spectral decay."""
    w = np.asarray(w_axis, dtype=float)
    im_s = np.asarray(im_sigma, dtype=float)
    poles = np.asarray(poles, dtype=float)
    widths = np.full(poles.shape, float(max(min_half_width, 1.0e-10)), dtype=float)
    factor = float(max(width_factor, 0.0))
    if factor <= 0.0:
        return widths
    for ik, pole in enumerate(poles):
        if not np.isfinite(float(pole)):
            continue
        gamma_eff = float(eta_g) + max(0.0, -float(np.interp(float(pole), w, im_s[ik])))
        if np.isfinite(gamma_eff):
            widths[ik] = max(widths[ik], factor * gamma_eff)
    return widths


def interp_pchip(
    arr: np.ndarray,
    w_old: np.ndarray,
    w_new: np.ndarray,
) -> np.ndarray:
    """Per-k PCHIP interpolation (nk, nw_old) → (nk, nw_new).

    w_old and w_new may each be 1D (shared) or 2D (per-k, shape nk x nw).
    PCHIP is shape-preserving (no overshoot), safe for sigma and A near QP poles.
    """
    from scipy.interpolate import PchipInterpolator
    arr = np.asarray(arr, dtype=float)
    w_old = np.asarray(w_old, dtype=float)
    w_new = np.asarray(w_new, dtype=float)
    nk = arr.shape[0]
    nw_new = w_new.shape[-1]
    out = np.empty((nk, nw_new), dtype=float)
    for ik in range(nk):
        wo = w_old[ik] if w_old.ndim == 2 else w_old
        wn = w_new[ik] if w_new.ndim == 2 else w_new
        y = np.asarray(arr[ik], dtype=float)
        finite = np.isfinite(y) & np.isfinite(wo)
        if not bool(np.all(finite)):
            if int(np.count_nonzero(finite)) >= 2:
                y = np.interp(wo, wo[finite], y[finite])
            elif int(np.count_nonzero(finite)) == 1:
                y = np.full_like(wo, float(y[finite][0]), dtype=float)
            else:
                y = np.zeros_like(wo, dtype=float)
        out[ik] = PchipInterpolator(wo, y, extrapolate=True)(wn)
    return out










    # ------------------------------------------------------------------


