# =====================================================================
# SLIM copy of simga_test.py
#
# 29 top-level symbols (1008 lines, 86% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   (module-level only)
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   _parse_args
#   gl_nodes_weights
#   gl_nodes_on_interval
#   gl_integrate
#   im_gamma_value
#   im_gamma_values
#   xi_bar
#   shell_bounds
#   qfflo_code_units
#   q_crossing_phi
#   build_p_panels
#   build_phi_panels
#   init_diag
#   diag_update
#   radial_integrand_value
#   imsigma_ret
#   fmt_float
#   should_trace
#   save_integrand_slices
#   _ImGamma0_asympt_large_Omega
#   _ImSigma_tail_asympt
#   _merge_nodes
#   _merge_nodes_weights
#   _build_symmetric_log_block
#   _trapezoid_weights
#   _build_kk_nodes_weights
#   build_omega_grid
#   kk_re_from_im_subtracted_tail
#   main
# =====================================================================
import argparse
import os
from pathlib import Path
import sys
from datetime import datetime

import numpy as np
try:
    from tqdm import tqdm
except ImportError:  # fallback if tqdm is not installed
    def tqdm(x, **kwargs):
        return x


# ------------------------------------------------------------------
# Minimal fixed Sigma test for the specific run:
# eps0=0.1, spin=down (override via --spin or SPIN env var), wmax=4, single-k Sigma vs omega
# Deterministic grid with integrand diagnostics (Appendix expression).
# ------------------------------------------------------------------
HERE = Path(__file__).resolve()
REPO = HERE.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from fflo.proxy import Gamma, configuration  # noqa: E402


# Fixed settings (no CLI/options)
def _default_spin() -> str:
    val = os.environ.get("SPIN", "down")
    val = val.strip().lower()
    return val if val in {"up", "down"} else "down"


EPS0 = 0.1
SPIN = _default_spin()
WMAX = 100
NW = 601
NP = 40
NPHI = 24
TAG = f"mild_gl0split_dense_minimal_NP_{NP}_NPHI_{NPHI}_crit"
MASS = 1.0
# Sigma mode: "norm" (no shift) or "rand" (MF shift)
MODE = "norm"
SIGMA0_OMEGA_REF = 1e-3
# Set a fixed test k. If None, uses kF_sigma.
K_TEST = None

# NOTE: Code uses xi = p^2/MASS - mu (no 1/2).
# The paper uses xi = p^2/(2m) - mu. To compare, interpret MASS here as m_paper/2.

# Deterministic grid / diagnostics
ETA = 1e-8
USE_QFFLO_SPLIT = True
USE_P_SPLITS = True
P_SPLIT_REL = 0.06
P_SPLIT_ABS = 1e-3
PHI_SPLIT_DELTA = 0.03
NP_BASE = NP
NP_PEAK = max(NP * 2, NP + 1)
NPHI_BASE = NPHI
NPHI_PEAK = max(NPHI * 3, NPHI + 1)
IM_GAMMA_ALERT = 1e3

TRACK_DIAGNOSTICS = True
TRACE_OMEGA_INDEXES = [NW // 2]  # omega ~ 0
TRACE_OMEGA_VALUES = None
TRACE_OMEGA_TOL = 1e-9
SAVE_INTEGRAND_PLOTS = True
RADIAL_PLOT_N = 400
PHI_PLOT_N = 2000
PLOT_WLIM = 1  # plot window for sigma (|omega| <= PLOT_WLIM)

# KK tail / PV settings
KK_TAIL_ENABLED = True
KK_TAIL_CALIBRATE = True
KK_TAIL_WMAX = 1.0e6
KK_TAIL_NT = 240
KK_TAIL_FIT_WMIN = None
KK_TAIL_FIT_WMAX = None
KK_ANCHOR_MODE = "infty_zero"  # None, "high_omega", or "infty_zero"
KK_GRID_MODE = "from_w_grid"  # "uniform", "hybrid", or "from_w_grid"
KK_GL_WMAX = 1  # |omega| <= KK_GL_WMAX uses GL nodes (hybrid only)
KK_GL_N = 120
KK_LIN_N = 200

# Omega grid (used for ImSigma and KK). Build around the positive-omega cusp.
OMEGA_GRID_MODE = "gl_cusp"  # "uniform" or "gl_cusp"
OMEGA_INNER_FRAC = 0.6  # fraction of positive-side points below the cusp
OMEGA_CUSP_FACTOR = 1.15  # expand cusp window: omega_cusp = factor * mu_bar
LOGW_DEFAULT_MIN = 1.0e-6
LOGW_DEFAULT_MAX = 1.0e-2
LOGW_DEFAULT_N = 160

_GL_CACHE = {}
































# Implements ImSigma^R(k, omega) = \int d^2p/(2pi)^2 ImGamma^R(|p+k|, omega+xi_bar(p))
# * [Theta(-xi_bar(p)) - Theta(-omega - xi_bar(p))]
# The theta difference is enforced by the xi-shell bounds in shell_bounds().



























