# =====================================================================
# SLIM copy of true_akw_pipeline/compute_sigma_from_pair_convolution.py
#
# 11 top-level symbols (637 lines, 40% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   analytical_configuration, build_dyson_qp_table_for_sigma, build_sigma_p_grid, compute_im_sigma_at_omega, compute_im_sigma_scan_at_k, compute_im_sigma_scan_at_k_from_table, detect_core_range, estimate_pair_q_feature, load_cube_a_convention, load_pair_table, pair_spectral_function, pair_spectral_function_from_table
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   parse_args
#   auto_find_latest_cube
#   auto_find_latest_pair_table
#   normalize_cube_spectral_weight
#   resolve_physics
#   internal_spin
#   _sigma_kernel_kink_tol
#   free_spectral
#   maybe_enrich_sigma_omega_grid
#   plot_sigma_scan
#   main
# =====================================================================
#!/usr/bin/env python3
"""Compute Sigma(k,omega) from the spectral pair-fermion convolution.

Implements the Enss-style spectral representation

    Im Sigma^R_sigma(k,omega)
      = -pi ∫ d^2p/(2pi)^2 ∫ d eps
            [f(eps) + b(omega+eps)]
            A_pair(|k+p|, omega+eps) A_{bar sigma}(p, eps)

in 2D with imbalanced chemical potentials.

The pair spectral function is taken from the analytic pair propagator
Gamma(Q, Omega+i0), i.e.

    A_pair(Q,Omega) = -(1/pi) Im Gamma^R(Q,Omega).

The internal fermion spectral function can be either:
  - free: narrow Lorentzian approximation to a delta peak
  - cube: the opposite-spin A(k,omega) cube from the existing pipeline

Re Sigma is reconstructed from Im Sigma using the same piecewise-linear
principal-value KK as the Pi pipeline.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
import os
from pathlib import Path
import sys

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fflo.proxy import Gamma as analytical_gamma
from fflo.proxy import configuration as analytical_configuration
from fflo.kramers_kronig import (
    _trapz,
    _trapz_axis,
    bilinear_eval_with_support,
    kk_re_with_optional_powerlaw_tail,
    kk_sigma_gamma_asymptote,
    load_cube_a_convention,
    load_cube_physics,
    normalize_spectral_rows,
    normalize_spectral_weight,
)
from fflo.adn_phi import build_eps_grid, enrich_grid_with_feature_windows, load_akw_cube
from fflo.decompose_qp_inc import extract_dyson_qp_from_cube


OUT_BASE = REPO_ROOT / "true_akw_pipeline" / "sigma_pairconv_runs"














def fermi_function(x: np.ndarray, temperature: float) -> np.ndarray:
    t = float(temperature)
    xx = np.asarray(x, dtype=float)
    if t <= 0.0:
        return (xx < 0.0).astype(float)
    y = xx / t
    out = np.empty_like(y)
    pos = y > 40.0
    neg = y < -40.0
    mid = ~(pos | neg)
    out[pos] = 0.0
    out[neg] = 1.0
    out[mid] = 1.0 / (np.exp(y[mid]) + 1.0)
    return out


def bose_function(x: np.ndarray, temperature: float) -> np.ndarray:
    t = float(temperature)
    xx = np.asarray(x, dtype=float)
    if t <= 0.0:
        return -(xx < 0.0).astype(float)
    y = xx / t
    out = np.empty_like(y)
    small = np.abs(y) < 1.0e-6
    pos = y > 40.0
    neg = y < -40.0
    mid = ~(small | pos | neg)
    out[pos] = 0.0
    out[neg] = -1.0
    out[small] = 1.0 / np.where(y[small] == 0.0, np.inf, y[small])
    out[mid] = 1.0 / np.expm1(y[mid])
    return out


def thermal_kernel(eps: np.ndarray, omega: float, temperature: float) -> np.ndarray:
    eps_arr = np.asarray(eps, dtype=float)
    return fermi_function(eps_arr, float(temperature)) + bose_function(float(omega) + eps_arr, float(temperature))




def _sigma_thermal_kernel_scalar_zero_temp(eps_mid: float, omega: float) -> float:
    eps_val = float(eps_mid)
    omega_val = float(omega)
    delta = max(1.0e-12, 1.0e-10 * (1.0 + abs(omega_val)))

    def _raw(x: float) -> float:
        return float((x < 0.0)) + float(-(omega_val + x < 0.0))

    is_zero_kink = np.isclose(eps_val, 0.0, atol=delta, rtol=0.0)
    is_minus_omega_kink = np.isclose(eps_val, -omega_val, atol=delta, rtol=0.0)
    if is_zero_kink or is_minus_omega_kink:
        left = _raw(eps_val - delta)
        right = _raw(eps_val + delta)
        return 0.5 * (left + right)
    return _raw(eps_val)


def _insert_eps_anchors_rows(
    x: np.ndarray,
    y_rows: np.ndarray,
    anchors: np.ndarray | list[float] | tuple[float, ...],
) -> tuple[np.ndarray, np.ndarray]:
    x_aug = np.asarray(x, dtype=float).reshape(-1)
    y_aug = np.asarray(y_rows, dtype=float)
    if y_aug.ndim != 2 or y_aug.shape[1] != x_aug.size:
        raise ValueError("y_rows must be 2D with shape (n_rows, x.size).")
    if x_aug.size < 2:
        return x_aug, y_aug

    dx_min = np.min(np.diff(x_aug))
    tol = max(1.0e-12, 1.0e-8 * float(dx_min))
    anchors_arr = np.asarray(anchors, dtype=float).reshape(-1)
    anchors_arr = anchors_arr[np.isfinite(anchors_arr)]
    if anchors_arr.size == 0:
        return x_aug, y_aug

    anchors_arr = np.unique(anchors_arr)
    anchors_arr = anchors_arr[(anchors_arr > float(x_aug[0]) + tol) & (anchors_arr < float(x_aug[-1]) - tol)]
    for aval in anchors_arr.tolist():
        if np.any(np.abs(x_aug - float(aval)) <= tol):
            continue
        j = int(np.searchsorted(x_aug, float(aval), side="left"))
        if not (0 < j < x_aug.size):
            continue
        x0 = float(x_aug[j - 1])
        x1 = float(x_aug[j])
        t = (float(aval) - x0) / max(x1 - x0, 1.0e-14)
        new_col = (1.0 - t) * y_aug[:, j - 1] + t * y_aug[:, j]
        x_aug = np.insert(x_aug, j, float(aval))
        y_aug = np.insert(y_aug, j, new_col, axis=1)
    return x_aug, y_aug


def _trapz_axis_panel_kernel_sigma(
    y_prod: np.ndarray,
    x: np.ndarray,
    omega: float,
) -> np.ndarray:
    x_aug, y_aug = _insert_eps_anchors_rows(x, y_prod, [0.0, -float(omega)])
    if x_aug.size < 2:
        return np.zeros(y_aug.shape[0], dtype=float)

    out = np.zeros(y_aug.shape[0], dtype=float)
    break_vals = [0.0, -float(omega)]
    break_idx: list[int] = [0]
    for aval in sorted(set(float(v) for v in break_vals if np.isfinite(v))):
        matches = np.where(np.isclose(x_aug, float(aval), atol=1.0e-12, rtol=0.0))[0]
        if matches.size > 0:
            idx = int(matches[0])
            if 0 < idx < x_aug.size - 1:
                break_idx.append(idx)
    break_idx.append(x_aug.size - 1)
    break_idx = sorted(set(break_idx))

    for i in range(len(break_idx) - 1):
        lo = int(break_idx[i])
        hi = int(break_idx[i + 1])
        if hi <= lo:
            continue
        x_seg = x_aug[lo : hi + 1]
        y_seg = y_aug[:, lo : hi + 1]
        eps_mid = 0.5 * (float(x_seg[0]) + float(x_seg[-1]))
        kval = float(_sigma_thermal_kernel_scalar_zero_temp(eps_mid, float(omega)))
        if kval == 0.0:
            continue
        out += kval * _trapz_axis(y_seg, x_seg, axis=1)
    return out




def pair_momentum_sum(p: np.ndarray, k_ext: float, phi: np.ndarray) -> np.ndarray:
    p2 = np.asarray(p, dtype=float)[:, None]
    phi2 = np.asarray(phi, dtype=float)[None, :]
    q2 = p2 * p2 + float(k_ext) * float(k_ext) + 2.0 * p2 * float(k_ext) * np.cos(phi2)
    return np.sqrt(np.maximum(q2, 0.0))


def pair_spectral_function(q_query: np.ndarray, omega_query: np.ndarray, eta_pair: float) -> np.ndarray:
    qq = np.asarray(q_query, dtype=float)
    ww = np.asarray(omega_query, dtype=float)
    qb, wb = np.broadcast_arrays(qq, ww)
    try:
        g = analytical_gamma(qb, wb + 1j * float(eta_pair))
        g_arr = np.asarray(g, dtype=complex)
        if g_arr.shape != qb.shape:
            g_arr = np.broadcast_to(g_arr, qb.shape).astype(complex, copy=False)
    except Exception:
        flat = np.empty(qb.size, dtype=complex)
        qf = qb.ravel()
        wf = wb.ravel()
        for i, (qv, wv) in enumerate(zip(qf, wf)):
            flat[i] = complex(analytical_gamma(float(qv), complex(float(wv), float(eta_pair))))
        g_arr = flat.reshape(qb.shape)
    return -(1.0 / np.pi) * np.imag(g_arr)


def load_pair_table(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    with np.load(path) as d:
        q = np.asarray(d["q"], dtype=float)
        omega = np.asarray(d["omega"], dtype=float)
        a_pair = np.asarray(d["A_pair"], dtype=float)
    if q.ndim != 1 or omega.ndim != 1 or a_pair.ndim != 2:
        raise ValueError(f"Invalid pair table shapes in {path}: q{q.shape}, omega{omega.shape}, A_pair{a_pair.shape}")
    if a_pair.shape != (q.size, omega.size):
        raise ValueError(f"A_pair shape mismatch in {path}: expected {(q.size, omega.size)}, got {a_pair.shape}")
    return q, omega, a_pair


def estimate_pair_q_feature(path: Path) -> float:
    with np.load(path) as d:
        q = np.asarray(d["q"], dtype=float)
        omega = np.asarray(d["omega"], dtype=float)
        if q.ndim != 1 or omega.ndim != 1 or q.size == 0 or omega.size == 0:
            return np.nan
        i0 = int(np.argmin(np.abs(omega)))
        if "ReInvGamma" in d.files:
            re_inv = np.asarray(d["ReInvGamma"], dtype=float)
            if re_inv.shape == (q.size, omega.size):
                return float(q[int(np.argmin(np.abs(re_inv[:, i0])))])
        if "A_pair" in d.files:
            a_pair = np.asarray(d["A_pair"], dtype=float)
            if a_pair.shape == (q.size, omega.size):
                return float(q[int(np.argmax(np.abs(a_pair[:, i0])))])
    return np.nan


def pair_spectral_function_from_table(
    q_query: np.ndarray,
    omega_query: np.ndarray,
    q_axis: np.ndarray,
    omega_axis: np.ndarray,
    a_pair: np.ndarray,
) -> np.ndarray:
    vals, inside = bilinear_eval_with_support(q_query, omega_query, q_axis, omega_axis, a_pair)
    return np.where(inside, vals, 0.0)


def _interp_pair_table_omega(
    omega_axis: np.ndarray,
    table_q: np.ndarray,
    omega_query: np.ndarray,
    *,
    mode: str,
) -> np.ndarray:
    """Interpolate q-preinterpolated A_pair along Omega.

    ``table_q`` has shape (..., n_omega).  The default linear path is the
    historical fast lookup.  ``pchip_omega`` is shape-preserving along Omega
    and is useful for testing whether linear interpolation across threshold
    windows is adding texture to Sigma.
    """
    om_axis = np.asarray(omega_axis, dtype=float)
    wq = np.asarray(omega_query, dtype=float)
    mode_l = str(mode).strip().lower()
    if mode_l in {"", "linear"}:
        wi = np.searchsorted(om_axis, wq, side="right") - 1
        wi = np.clip(wi, 0, om_axis.size - 2)
        w0 = om_axis[wi]
        w1 = om_axis[wi + 1]
        tw = (wq - w0) / np.maximum(w1 - w0, 1.0e-14)
        tw_b = tw.reshape((1,) * (np.ndim(table_q) - 1) + (tw.size,))
        return (1.0 - tw_b) * table_q[..., wi] + tw_b * table_q[..., wi + 1]
    if mode_l in {"pchip", "pchip_omega"}:
        from scipy.interpolate import PchipInterpolator

        interp = PchipInterpolator(om_axis, table_q, axis=-1, extrapolate=False)
        vals = interp(wq)
        return np.nan_to_num(vals, nan=0.0, posinf=0.0, neginf=0.0)
    raise ValueError(f"Unsupported SIGMA_PAIR_INTERP_MODE={mode!r}; use linear or pchip_omega")


def _interp_crossing(x0: float, y0: float, x1: float, y1: float, y_target: float) -> float:
    dy = float(y1) - float(y0)
    if abs(dy) <= 1.0e-300:
        return 0.5 * (float(x0) + float(x1))
    t = (float(y_target) - float(y0)) / dy
    return float(x0) + float(np.clip(t, 0.0, 1.0)) * (float(x1) - float(x0))


def estimate_internal_qp_lorentzians(
    eps_grid: np.ndarray,
    internal_a: np.ndarray,
    *,
    peak_threshold: float,
    width_floor: float,
) -> list[dict[str, float | int]]:
    """Fit one narrow Lorentzian control variate per p-row when a tall QP exists.

    The fit is intentionally local and conservative.  It only triggers on tall
    positive peaks, estimates gamma from the half-maximum width, and caps the
    inferred spectral weight by the captured row/local area.  This is a
    numerical control variate, not a quasiparticle analysis routine.
    """
    eps = np.asarray(eps_grid, dtype=float)
    arr = np.asarray(internal_a, dtype=float)
    if eps.ndim != 1 or arr.ndim != 2 or arr.shape[1] != eps.size or eps.size < 5:
        return []

    out: list[dict[str, float | int]] = []
    dx_min = float(np.min(np.diff(np.unique(eps)))) if eps.size > 1 else 1.0
    gamma_floor = max(float(width_floor), 0.1 * dx_min, 1.0e-8)
    threshold = float(peak_threshold)

    for ip in range(arr.shape[0]):
        row = np.asarray(arr[ip], dtype=float)
        finite = np.isfinite(row)
        if not np.any(finite):
            continue
        imax = int(np.nanargmax(np.where(finite, row, -np.inf)))
        peak = float(row[imax])
        if not np.isfinite(peak) or peak < threshold or imax <= 0 or imax >= eps.size - 1:
            continue

        half = 0.5 * peak
        il = imax
        while il > 0 and row[il] > half:
            il -= 1
        ir = imax
        while ir < eps.size - 1 and row[ir] > half:
            ir += 1
        if il == imax or ir == imax:
            continue

        left = _interp_crossing(float(eps[il]), float(row[il]), float(eps[il + 1]), float(row[il + 1]), half)
        right = _interp_crossing(float(eps[ir - 1]), float(row[ir - 1]), float(eps[ir]), float(row[ir]), half)
        fwhm = max(float(right - left), 2.0 * gamma_floor)
        gamma = max(0.5 * fwhm, gamma_floor)
        center = float(eps[imax])

        model_weight = peak * np.pi * gamma
        local = np.abs(eps - center) <= max(8.0 * gamma, 2.5 * dx_min)
        local_area = float(np.trapezoid(np.maximum(row[local], 0.0), eps[local])) if np.count_nonzero(local) >= 2 else model_weight
        row_area = float(np.trapezoid(np.maximum(row, 0.0), eps))
        cap = max(0.0, min(1.25 * max(local_area, 0.0), 1.10 * max(row_area, 0.0), 1.5))
        weight = float(min(max(model_weight, 0.0), cap))
        if not np.isfinite(weight) or weight <= 0.0:
            continue
        out.append({"ip": ip, "center": center, "gamma": gamma, "weight": weight, "peak": peak})
    return out


def build_dyson_qp_table_for_sigma(
    cube_path: Path,
    k_axis: np.ndarray,
    w_axis: np.ndarray,
    a_vals: np.ndarray,
    *,
    label: str,
    max_gamma: float,
    z_min: float,
    z_max: float,
    min_peak: float,
    peak_cap_factor: float,
) -> dict[str, np.ndarray]:
    """Extract a shifted-Dyson QP table once, then interpolate it per p-grid.

    The Sigma epsilon integral is exactly where missing a narrow internal QP
    peak is most expensive: the coarse trapezoid sees a tiny sampled remnant,
    while the physical Lorentzian carries O(Z) area.  This table lets the Sigma
    control variate use the same pole equation as the A rebuild instead of
    trusting the maximum sampled on the current epsilon grid.
    """
    with np.load(cube_path, allow_pickle=False) as source:
        if "ReS" not in source.files or "ImS" not in source.files:
            raise ValueError(f"Dyson Sigma CV requires ReS/ImS in {cube_path}")
        qp = extract_dyson_qp_from_cube(
            source,
            np.asarray(k_axis, dtype=float),
            np.asarray(w_axis, dtype=float),
            np.asarray(a_vals, dtype=float),
            label=str(label),
            max_gamma=float(max_gamma),
            z_min=float(z_min),
            z_max=float(z_max),
            min_peak=float(min_peak),
            peak_cap_factor=float(peak_cap_factor),
            enforce_positive_inc=False,
            positive_inc_qpcut=1.0e-5,
        )
    return {key: np.asarray(val) for key, val in qp.items() if isinstance(val, np.ndarray)}


def estimate_internal_qp_lorentzians_dyson(
    p_grid: np.ndarray,
    qp_table: dict[str, np.ndarray] | None,
    *,
    peak_threshold: float,
    width_floor: float,
) -> list[dict[str, float | int]]:
    """Interpolate Dyson QP parameters to the current Sigma p-grid."""
    if not qp_table:
        return []
    p = np.asarray(p_grid, dtype=float)
    k = np.asarray(qp_table.get("k", []), dtype=float)
    valid = np.asarray(qp_table.get("valid", np.zeros_like(k, dtype=bool)), dtype=bool)
    center = np.asarray(qp_table.get("center", np.full_like(k, np.nan)), dtype=float)
    gamma = np.asarray(qp_table.get("gamma", np.full_like(k, np.nan)), dtype=float)
    weight = np.asarray(qp_table.get("weight", np.zeros_like(k)), dtype=float)
    peak = np.asarray(qp_table.get("peak", np.zeros_like(k)), dtype=float)
    keep = (
        valid
        & np.isfinite(k)
        & np.isfinite(center)
        & np.isfinite(gamma)
        & np.isfinite(weight)
        & (gamma > 0.0)
        & (weight > 0.0)
    )
    if np.count_nonzero(keep) < 2:
        return []

    kk = k[keep]
    order = np.argsort(kk)
    kk = kk[order]
    cc = center[keep][order]
    gg = gamma[keep][order]
    ww = weight[keep][order]
    pp = peak[keep][order]
    unique = np.concatenate(([True], np.diff(kk) > 1.0e-12))
    kk, cc, gg, ww, pp = kk[unique], cc[unique], gg[unique], ww[unique], pp[unique]
    if kk.size < 2:
        return []

    inside = (p >= float(kk[0])) & (p <= float(kk[-1]))
    if not np.any(inside):
        return []
    c_i = np.interp(p[inside], kk, cc)
    g_i = np.maximum(np.maximum(np.interp(p[inside], kk, gg), float(width_floor)), 1.0e-12)
    w_i = np.interp(p[inside], kk, ww)
    p_i = np.interp(p[inside], kk, pp)
    idxs = np.where(inside)[0]

    out: list[dict[str, float | int]] = []
    threshold = float(peak_threshold)
    for ip, cen, gam, wt, pk in zip(idxs, c_i, g_i, w_i, p_i, strict=False):
        if not (np.isfinite(cen) and np.isfinite(gam) and np.isfinite(wt)):
            continue
        if gam <= 0.0 or wt <= 0.0:
            continue
        model_peak = float(wt) / (np.pi * float(gam))
        # Trigger on the physical Lorentzian height, not only on the sampled
        # A peak.  That is the whole point: the sampled peak can be the thing
        # that is wrong on a coarse epsilon grid.
        if max(model_peak, float(pk) if np.isfinite(pk) else 0.0) < threshold:
            continue
        out.append(
            {
                "ip": int(ip),
                "center": float(cen),
                "gamma": float(max(gam, width_floor)),
                "weight": float(wt),
                "peak": float(model_peak),
            }
        )
    return out


def lorentzian_area_density(eps: np.ndarray, center: float, gamma: float, weight: float) -> np.ndarray:
    x = np.asarray(eps, dtype=float)
    g = max(float(gamma), 1.0e-12)
    return (float(weight) / np.pi) * g / ((x - float(center)) ** 2 + g * g)




def build_sigma_p_grid(
    p_min: float,
    p_max: float,
    n_p_int: int,
    mode: str,
    *,
    mu_internal: float,
    k_ext: float,
    q_feature: float,
    feature_half_width: float,
    feature_n_local: int,
    feature_mode: str,
    tail_start: float,
    tail_n: int,
) -> tuple[np.ndarray, float]:
    p_min_f = float(p_min)
    p_max_f = float(p_max)
    if not np.isfinite(p_min_f) or not np.isfinite(p_max_f) or p_max_f <= p_min_f:
        raise ValueError(f"Invalid p range [{p_min_f}, {p_max_f}]")

    n_core = max(2, int(n_p_int))
    mode_l = str(mode).strip().lower()
    feature_mode_l = str(feature_mode).strip().lower()
    hw = float(feature_half_width)
    nloc = int(feature_n_local) if int(feature_n_local) > 0 else 31
    kf_internal = float(np.sqrt(max(float(mu_internal), 0.0))) if np.isfinite(mu_internal) else np.nan

    if mode_l == "linear":
        p_grid = np.linspace(p_min_f, p_max_f, n_core, dtype=float)
        tail_start_used = np.nan
    elif mode_l == "hybrid_log_tail":
        auto_tail = max(
            kf_internal if np.isfinite(kf_internal) else 0.0,
            abs(float(k_ext)),
        ) + max(0.25, 4.0 * max(hw, 0.0))
        tail_start_f = float(tail_start) if np.isfinite(float(tail_start)) else auto_tail
        min_tail = max(p_min_f + 1.0e-6 * max(1.0, abs(p_max_f)), 1.0e-8)
        max_tail = p_max_f - 1.0e-6 * max(1.0, abs(p_max_f))
        tail_start_f = min(max(tail_start_f, min_tail), max_tail)
        if int(tail_n) >= 2 and tail_start_f > p_min_f and p_max_f > tail_start_f:
            p_core = np.linspace(p_min_f, tail_start_f, n_core, dtype=float)
            p_tail = np.geomspace(tail_start_f, p_max_f, int(tail_n), dtype=float)
            p_grid = np.unique(np.concatenate([p_core, p_tail]))
            tail_start_used = float(tail_start_f)
        else:
            p_grid = np.linspace(p_min_f, p_max_f, n_core, dtype=float)
            tail_start_used = np.nan
    else:
        raise ValueError(f"Unsupported p-grid mode: {mode!r}")

    if hw > 0.0 and feature_mode_l != "none":
        features: list[float] = []
        if np.isfinite(kf_internal):
            features.append(kf_internal)
        if feature_mode_l in {"kf_and_shells", "auto_pair_shells"} and np.isfinite(float(q_feature)):
            q_abs = abs(float(q_feature))
            if np.isfinite(kf_internal):
                features.extend([abs(q_abs - kf_internal), q_abs + kf_internal])
            features.extend([abs(float(k_ext) - q_abs), abs(float(k_ext) + q_abs)])
        p_grid = enrich_grid_with_feature_windows(
            np.asarray(p_grid, dtype=float),
            a=p_min_f,
            b=p_max_f,
            features=features,
            half_width=hw,
            n_local=nloc,
        )
    return np.asarray(np.unique(p_grid), dtype=float), float(tail_start_used)


def compute_im_sigma_at_omega(
    omega: float,
    *,
    k_ext: float,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    phi_grid: np.ndarray,
    temperature: float,
    internal_a: np.ndarray,
    pair_eval,
    eps_integration_mode: str = "plain",
) -> float:
    q_pair = pair_momentum_sum(p_grid, float(k_ext), phi_grid)  # (n_p, n_phi)
    omega_pair = float(omega) + eps_grid
    a_pair = pair_eval(q_pair[:, :, None], omega_pair[None, None, :])
    _dphi_full = (2.0 * np.pi) / float(phi_grid.size)
    a_pair_phi = _dphi_full * np.sum(a_pair, axis=1)  # (n_p, n_eps)
    prod = internal_a * a_pair_phi
    integ_mode = str(eps_integration_mode).strip().lower()
    if integ_mode not in {"plain", "panel_kinks"}:
        raise ValueError("eps_integration_mode must be 'plain' or 'panel_kinks'.")
    if integ_mode == "panel_kinks" and float(temperature) <= 0.0:
        i_p = _trapz_axis_panel_kernel_sigma(prod, eps_grid, float(omega))
    else:
        kernel = thermal_kernel(eps_grid, float(omega), float(temperature))[None, :]
        i_p = _trapz_axis(kernel * prod, eps_grid, axis=1)
    i_total = _trapz(p_grid * i_p, p_grid)
    return float(-np.pi * i_total / ((2.0 * np.pi) ** 2))


def compute_im_sigma_scan_at_k(
    omega_grid: np.ndarray,
    *,
    k_ext: float,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    phi_grid: np.ndarray,
    temperature: float,
    internal_a: np.ndarray,
    pair_eval,
) -> np.ndarray:
    """Compute Im(Sigma)(omega) for all omega at once, vectorized over omega.

    Eliminates the per-omega Python loop by iterating over eps slices instead,
    each of which processes all (n_p, n_phi, n_omega) values with numpy.
    Uses plain-mode step-function kernel (no panel_kinks augmentation).
    """
    omega_arr = np.asarray(omega_grid, dtype=float)
    eps_arr = np.asarray(eps_grid, dtype=float)
    n_omega = omega_arr.size
    n_p = p_grid.size
    n_eps = eps_arr.size

    # Precompute q_pair once for this k: (n_p, n_phi)
    q_pair = pair_momentum_sum(p_grid, float(k_ext), phi_grid)

    # Build thermal kernel for all (omega, eps) pairs: (n_omega, n_eps)
    if float(temperature) <= 0.0:
        fe = (eps_arr[None, :] < 0.0).astype(float)
        fbe = (eps_arr[None, :] < -omega_arr[:, None]).astype(float)
        kernel_all = fe - fbe  # (n_omega, n_eps)
    else:
        fe = fermi_function(eps_arr[None, :], float(temperature))
        be = bose_function(omega_arr[:, None] + eps_arr[None, :], float(temperature))
        kernel_all = fe + be  # (n_omega, n_eps)

    # Accumulate the epsilon trapezoid directly.  The older route built the
    # full prod_all[omega,p,eps] cube and integrated it immediately, which is
    # pure memory traffic for large sigma scans.
    i_p = np.zeros((n_omega, n_p), dtype=float)
    prev_prod: np.ndarray | None = None
    dphi_full = (2.0 * np.pi) / float(phi_grid.size)
    internal_a_arr = np.asarray(internal_a, dtype=float)
    for ie in range(n_eps):
        omega_pair_ie = omega_arr + eps_arr[ie]  # (n_omega,)
        # Evaluate pair spectral function: (n_p, n_phi, n_omega)
        a_pair = pair_eval(
            q_pair[:, :, None],
            omega_pair_ie[None, None, :],
        )
        # Riemann sum with full-circle weight (phi_grid covers [0,pi), dphi=2pi/n covers symmetry factor)
        a_pair_phi = dphi_full * np.sum(a_pair, axis=1)  # (n_p, n_omega)
        kern_ie = kernel_all[:, ie]   # (n_omega,)
        ia_ie = internal_a_arr[:, ie]  # (n_p,)
        # prod_slice[io, ip] = kern[io] * ia[ip] * a_pair_phi[ip, io]
        prod_slice = kern_ie[:, None] * (ia_ie[None, :] * a_pair_phi.T)
        if prev_prod is not None:
            dx = float(eps_arr[ie] - eps_arr[ie - 1])
            i_p += 0.5 * dx * (prev_prod + prod_slice)
        prev_prod = prod_slice

    # Integrate over p after the streamed epsilon integration.
    p_arr = np.asarray(p_grid, dtype=float)
    if hasattr(np, "trapezoid"):
        i_total = np.trapezoid(p_arr[None, :] * i_p, p_arr, axis=1)
    else:
        i_total = np.trapz(p_arr[None, :] * i_p, p_arr, axis=1)  # pragma: no cover
    return -np.pi * i_total / ((2.0 * np.pi) ** 2)


def detect_core_range(omega_axis: np.ndarray, jump_factor: float = 2.5) -> tuple[float, float]:
    """Infer the uniformly sampled pair-omega core from a core+tail grid.

    The pair grid also carries very fine local feature nodes near thresholds.
    Using the median spacing therefore mistakes those feature patches for the
    "core" and can shrink a requested [-24,24] core to roughly [-2,12].  The
    robust rule below finds the dominant non-tiny spacing, then returns the
    contiguous block around omega=0 whose gaps stay below a tail-jump threshold.
    """
    omega = np.unique(np.asarray(omega_axis, dtype=float))
    if omega.size <= 1:
        return float(omega[0]), float(omega[-1])

    dw = np.diff(omega)
    positive = dw[dw > 1.0e-12]
    if positive.size == 0:
        return float(omega[0]), float(omega[-1])

    # Feature nodes are usually O(1e-2); the production core spacing is O(1e-1).
    # Pick the most common non-feature spacing as the core spacing estimate.
    non_tiny = positive[positive >= 5.0e-2]
    if non_tiny.size == 0:
        core_step = float(np.median(positive))
    else:
        rounded = np.round(non_tiny, 8)
        vals, counts = np.unique(rounded, return_counts=True)
        core_step = float(vals[int(np.argmax(counts))])
    if not np.isfinite(core_step) or core_step <= 0.0:
        core_step = float(np.median(positive))

    threshold = float(jump_factor) * core_step
    iz = int(np.searchsorted(omega, 0.0))
    iz = min(max(iz, 0), omega.size - 1)

    left = iz
    while left > 0 and dw[left - 1] <= threshold:
        left -= 1
    right = iz
    while right < dw.size and dw[right] <= threshold:
        right += 1

    return float(omega[left]), float(omega[right])


def compute_im_sigma_scan_at_k_from_table(
    omega_grid: np.ndarray,
    *,
    k_ext: float,
    p_grid: np.ndarray,
    eps_grid: np.ndarray,
    phi_grid: np.ndarray,
    temperature: float,
    internal_a: np.ndarray,
    q_axis_pair: np.ndarray,
    omega_axis_pair: np.ndarray,
    a_pair_table: np.ndarray,
    qp_subtraction: str = "none",
    qp_peak_threshold: float = 25.0,
    qp_dense_n: int = 121,
    qp_window_factor: float = 12.0,
    qp_width_floor: float = 5.0e-4,
    qp_dyson_table: dict[str, np.ndarray] | None = None,
    omega_axis_proxy: np.ndarray | None = None,
    a_proxy_table: np.ndarray | None = None,
    omega_core_min: float = -np.inf,
    omega_core_max: float = np.inf,
    pair_interp_mode: str = "linear",
) -> np.ndarray:
    """Fast table-specialized version of compute_im_sigma_scan_at_k.

    The generic pair_eval path broadcasts q to (p, phi, omega) and then calls
    searchsorted on that full array for every epsilon slice.  Here q depends
    only on (p, phi), so we precompute its interpolation cell once per k-row.
    Omega still changes with epsilon, but only as a 1D omega scan.
    """
    omega_arr = np.asarray(omega_grid, dtype=float)
    eps_arr = np.asarray(eps_grid, dtype=float)
    p_arr = np.asarray(p_grid, dtype=float)
    phi_arr = np.asarray(phi_grid, dtype=float)
    q_axis = np.asarray(q_axis_pair, dtype=float)
    om_axis = np.asarray(omega_axis_pair, dtype=float)
    table = np.asarray(a_pair_table, dtype=float)
    pair_interp_mode_l = str(pair_interp_mode).strip().lower()
    if pair_interp_mode_l not in {"", "linear", "pchip", "pchip_omega"}:
        raise ValueError(f"Unsupported SIGMA_PAIR_INTERP_MODE={pair_interp_mode!r}; use linear or pchip_omega")

    n_omega = int(omega_arr.size)
    n_p = int(p_arr.size)
    n_eps = int(eps_arr.size)

    q_pair = pair_momentum_sum(p_arr, float(k_ext), phi_arr)  # (n_p, n_phi)
    q_inside = (q_pair >= float(q_axis[0])) & (q_pair <= float(q_axis[-1]))
    qi = np.searchsorted(q_axis, q_pair, side="right") - 1
    qi = np.clip(qi, 0, q_axis.size - 2)
    q0 = q_axis[qi]
    q1 = q_axis[qi + 1]
    tq = (q_pair - q0) / np.maximum(q1 - q0, 1.0e-14)
    tq3 = tq[:, :, None]
    q_inside3 = q_inside[:, :, None]

    # Time/memory tradeoff: interpolate the pair table in q once for this
    # external k-row.  The remaining loop only interpolates along omega.
    table_q = (1.0 - tq3) * table[qi, :] + tq3 * table[qi + 1, :]
    table_q = np.where(q_inside3, table_q, 0.0)

    use_proxy = (omega_axis_proxy is not None and a_proxy_table is not None
                 and np.isfinite(omega_core_min) and np.isfinite(omega_core_max))
    if use_proxy:
        om_proxy = np.asarray(omega_axis_proxy, dtype=float)
        proxy_full = np.asarray(a_proxy_table, dtype=float)
        proxy_q = (1.0 - tq3) * proxy_full[qi, :] + tq3 * proxy_full[qi + 1, :]
        proxy_q = np.where(q_inside3, proxy_q, 0.0)

    if float(temperature) <= 0.0:
        fe = (eps_arr[None, :] < 0.0).astype(float)
        fbe = (eps_arr[None, :] < -omega_arr[:, None]).astype(float)
        kernel_all = fe - fbe
    else:
        fe = fermi_function(eps_arr[None, :], float(temperature))
        be = bose_function(omega_arr[:, None] + eps_arr[None, :], float(temperature))
        kernel_all = fe + be

    internal_a_arr = np.asarray(internal_a, dtype=float)
    qp_entries: list[dict[str, float | int]] = []
    qp_mode = str(qp_subtraction).strip().lower()
    if qp_mode == "lorentzian_cv":
        qp_entries = estimate_internal_qp_lorentzians(
            eps_arr,
            internal_a_arr,
            peak_threshold=float(qp_peak_threshold),
            width_floor=float(qp_width_floor),
        )
    elif qp_mode == "dyson_lorentzian_cv":
        qp_entries = estimate_internal_qp_lorentzians_dyson(
            p_arr,
            qp_dyson_table,
            peak_threshold=float(qp_peak_threshold),
            width_floor=float(qp_width_floor),
        )
    if qp_entries:
        if str(os.environ.get("SIGMA_QP_CV_VERBOSE", "0")).strip().lower() not in {"0", "false", "no", "off"}:
            print(f"[sigma-cv] mode={qp_mode} entries={len(qp_entries)}", flush=True)
        internal_res = np.array(internal_a_arr, copy=True)
        # SIGMA_QP_CV_WINDOWED_SUBTRACT=1: subtract the Lorentzian only inside the
        # SAME window the dense add-back reintegrates. The legacy full-lattice
        # subtraction removes the 1/eps^2 tails (mass fraction 1-(2/pi)atan(wf)
        # ~5.3% at wf=12) which the windowed add-back never restores.
        _cv_win_sub = str(os.environ.get("SIGMA_QP_CV_WINDOWED_SUBTRACT", "0")).strip().lower() not in {"0", "false", "no", "off"}
        if _cv_win_sub and not globals().get("_CV_WIN_ANNOUNCED", False):
            globals()["_CV_WIN_ANNOUNCED"] = True
            print(f"[sigma-cv] WINDOWED-SUBTRACT ON (wf={max(2.0, float(qp_window_factor)):g})", flush=True)
        if qp_entries:
            _wf_sub = max(2.0, float(qp_window_factor))
            for ent in qp_entries:
                ip = int(ent["ip"])
                _L = lorentzian_area_density(
                    eps_arr,
                    float(ent["center"]),
                    float(ent["gamma"]),
                    float(ent["weight"]),
                )
                if _cv_win_sub:
                    _g = max(float(ent["gamma"]), float(qp_width_floor), 1.0e-12)
                    _hw = max(_wf_sub * _g, 2.0 * _g)
                    _lo = max(float(eps_arr[0]), float(ent["center"]) - _hw)
                    _hi = min(float(eps_arr[-1]), float(ent["center"]) + _hw)
                    _L = np.where((eps_arr >= _lo) & (eps_arr <= _hi), _L, 0.0)
                internal_res[ip] -= _L
            internal_a_arr = internal_res

    i_p = np.zeros((n_omega, n_p), dtype=float)
    prev_prod: np.ndarray | None = None
    dphi_full = (2.0 * np.pi) / float(phi_arr.size)
    sparse_kernel = str(os.environ.get("SIGMA_SPARSE_KERNEL", "1")).strip().lower() not in {"0", "false", "no", "off"}

    for ie in range(n_eps):
        omega_pair_ie = omega_arr + eps_arr[ie]
        kern_ie = kernel_all[:, ie]
        ia_ie = internal_a_arr[:, ie]
        has_ia = bool(np.any(np.abs(ia_ie) > 0.0))

        w_in_core = (
            (omega_pair_ie >= float(omega_core_min)) & (omega_pair_ie <= float(omega_core_max))
            if use_proxy else np.ones(n_omega, dtype=bool)
        )
        w_inside = (omega_pair_ie >= float(om_axis[0])) & (omega_pair_ie <= float(om_axis[-1]))

        if sparse_kernel:
            active = (w_in_core & w_inside) & (np.abs(kern_ie) > 0.0) & has_ia
        else:
            active = w_in_core & w_inside

        prod_slice = np.zeros((n_omega, n_p), dtype=float)
        if np.any(active):
            omega_active = omega_pair_ie[active]
            vals = _interp_pair_table_omega(om_axis, table_q, omega_active, mode=pair_interp_mode_l)

            a_pair_phi = dphi_full * np.sum(vals, axis=1)  # (n_p, n_active)
            prod_slice[active, :] = kern_ie[active, None] * (ia_ie[None, :] * a_pair_phi.T)

        if use_proxy and has_ia:
            active_proxy = (~w_in_core) & (np.abs(kern_ie) > 0.0)
            if np.any(active_proxy):
                omega_proxy_ie = omega_pair_ie[active_proxy]
                w_clip_p = np.clip(omega_proxy_ie, float(om_proxy[0]), float(om_proxy[-1]))
                pi_v = np.searchsorted(om_proxy, w_clip_p, side="right") - 1
                pi_v = np.clip(pi_v, 0, om_proxy.size - 2)
                tp = (omega_proxy_ie - om_proxy[pi_v]) / np.maximum(om_proxy[pi_v + 1] - om_proxy[pi_v], 1.0e-14)
                tp = np.clip(tp, 0.0, 1.0)
                tp3 = tp[None, None, :]
                pv0 = proxy_q[:, :, pi_v]
                pv1 = proxy_q[:, :, pi_v + 1]
                proxy_vals = (1.0 - tp3) * pv0 + tp3 * pv1
                a_proxy_phi = dphi_full * np.sum(proxy_vals, axis=1)
                prod_slice[active_proxy, :] = kern_ie[active_proxy, None] * (ia_ie[None, :] * a_proxy_phi.T)

        if prev_prod is not None:
            dx = float(eps_arr[ie] - eps_arr[ie - 1])
            i_p += 0.5 * dx * (prev_prod + prod_slice)
        prev_prod = prod_slice

    if qp_entries:
        # Add the QP control variate back with a local dense epsilon rule.
        # This avoids letting a very tall, narrow sampled peak determine the
        # coarse trapezoid area.
        dense_n = max(21, int(qp_dense_n))
        if dense_n % 2 == 0:
            dense_n += 1
        window_factor = max(2.0, float(qp_window_factor))
        eps_min = float(eps_arr[0])
        eps_max = float(eps_arr[-1])
        for ent in qp_entries:
            ip = int(ent["ip"])
            center = float(ent["center"])
            gamma = max(float(ent["gamma"]), float(qp_width_floor), 1.0e-12)
            weight = float(ent["weight"])
            half_width = max(window_factor * gamma, 2.0 * gamma)
            lo = max(eps_min, center - half_width)
            hi = min(eps_max, center + half_width)
            if not (hi > lo):
                continue
            eps_dense = np.linspace(lo, hi, dense_n, dtype=float)
            qp_dense = lorentzian_area_density(eps_dense, center, gamma, weight)

            q_pair_ip = q_pair[ip : ip + 1, :]
            q_inside_ip = q_inside[ip : ip + 1, :]
            qi_ip = qi[ip : ip + 1, :]
            tq_ip = tq[ip : ip + 1, :]
            table_q_ip = (1.0 - tq_ip[:, :, None]) * table[qi_ip, :] + tq_ip[:, :, None] * table[qi_ip + 1, :]
            table_q_ip = np.where(q_inside_ip[:, :, None], table_q_ip, 0.0)

            add = np.zeros(n_omega, dtype=float)
            prev: np.ndarray | None = None
            for ie, eps_val in enumerate(eps_dense):
                omega_pair_ie = omega_arr + float(eps_val)
                w_inside = (omega_pair_ie >= float(om_axis[0])) & (omega_pair_ie <= float(om_axis[-1]))
                if float(temperature) <= 0.0:
                    kern = float(eps_val < 0.0) - (eps_val < -omega_arr).astype(float)
                else:
                    kern = fermi_function(np.array([eps_val]), float(temperature))[0] + bose_function(omega_arr + eps_val, float(temperature))
                active = w_inside & ((np.abs(kern) > 0.0) if sparse_kernel else np.ones_like(w_inside, dtype=bool))
                cur = np.zeros(n_omega, dtype=float)
                if np.any(active):
                    omega_active = omega_pair_ie[active]
                    vals = _interp_pair_table_omega(om_axis, table_q_ip, omega_active, mode=pair_interp_mode_l)
                    a_pair_phi = dphi_full * np.sum(vals[0], axis=0)
                    cur[active] = kern[active] * float(qp_dense[ie]) * a_pair_phi
                if prev is not None:
                    dx = float(eps_dense[ie] - eps_dense[ie - 1])
                    add += 0.5 * dx * (prev + cur)
                prev = cur
            i_p[:, ip] += add

    if hasattr(np, "trapezoid"):
        i_total = np.trapezoid(p_arr[None, :] * i_p, p_arr, axis=1)
    else:
        i_total = np.trapz(p_arr[None, :] * i_p, p_arr, axis=1)  # pragma: no cover
    return -np.pi * i_total / ((2.0 * np.pi) ** 2)





