# =====================================================================
# SLIM copy of true_akw_pipeline/make_true_akw_cubes_nomega_grid.py
#
# 9 top-level symbols (707 lines, 69% of the original) removed as
# unreachable from the live pipeline.  Required entry points here:
#   build_axes, spectral_from_g
#
# Generated by build_slim.py -- do not edit by hand, edit the source in
# ../X_FFLO_FULLGRID_PROD/ and re-run the build.
#
# Removed:
#   parse_args
#   resolve_mu
#   enforce_retarded_im_sigma
#   compute_sigma0_rand
#   build_true_cube_for_spin
#   save_cube
#   latest_run_dir
#   newest_matching
#   main
# =====================================================================
#!/usr/bin/env python3
"""Generate spin-up and spin-down true A(k,omega) cubes on Nomega-style grids.

This mirrors `make_lorentzian_akw_cubes.py` interface but computes:
  A(k,w) = -C * Im[ 1 / (w - xi_k - Sigma^R(k,w) + i*eta_g) ]
with Sigma^R(k,w) = ReS + i ImS coming from `simga_test.imsigma_ret`
and KK reconstruction for ReS.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
import os
from pathlib import Path
import sys

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fflo import sigma_test as st


PRODUCTION = True

OUT_BASE = REPO_ROOT / "true_akw_pipeline" / "true_akw_cubes_nomega_grid"






def build_split_axis(a: float, b: float, n: int, power: float) -> np.ndarray:
    a_f = float(a)
    b_f = float(b)
    n_i = int(max(3, n))
    if not (a_f < 0.0 < b_f):
        return np.linspace(a_f, b_f, n_i, dtype=float)

    pw = float(max(power, 1.0))
    n_left = n_i // 2
    n_right = n_i - 1 - n_left

    t_left = np.linspace(0.0, 1.0, n_left + 1, dtype=float)
    left = a_f * np.power(1.0 - t_left, pw)
    t_right = np.linspace(0.0, 1.0, n_right + 1, dtype=float)
    right = b_f * np.power(t_right, pw)

    grid = np.concatenate([left[:-1], right])
    i0 = int(np.argmin(np.abs(grid)))
    grid[i0] = 0.0
    if np.any(np.diff(grid) <= 0.0):
        grid = np.linspace(a_f, b_f, n_i, dtype=float)
        i0 = int(np.argmin(np.abs(grid)))
        grid[i0] = 0.0
    return grid


def build_k_grid_with_corridor(
    k_min: float,
    k_max: float,
    nk: int,
    *,
    mu_dn: float,
    mu_up: float,
    mass: float,
    enabled: bool,
    corridor_frac: float,
    corridor_margin: float,
    corridor_min_points: int,
) -> tuple[np.ndarray, float, float]:
    n_target = int(max(nk, 8))
    k_lin = np.linspace(float(k_min), float(k_max), n_target, dtype=float)
    if (not bool(enabled)) or (k_max <= k_min):
        return k_lin, np.nan, np.nan

    k_dn = float(np.sqrt(max(float(mass) * float(mu_dn), 0.0)))
    k_up = float(np.sqrt(max(float(mass) * float(mu_up), 0.0)))
    k_lo = max(float(k_min), min(k_dn, k_up) - float(max(corridor_margin, 0.0)))
    k_hi = min(float(k_max), max(k_dn, k_up) + float(max(corridor_margin, 0.0)))
    if not np.isfinite(k_lo) or not np.isfinite(k_hi) or k_hi <= (k_lo + 1.0e-12):
        return k_lin, np.nan, np.nan

    frac = float(np.clip(corridor_frac, 0.25, 0.95))
    n_mid = int(round(frac * n_target))
    n_mid = max(n_mid, int(max(3, min(corridor_min_points, n_target - 2))))
    n_mid = min(max(n_mid, 3), n_target - 2)
    n_rem = max(n_target - n_mid, 2)

    left_span = max(k_lo - float(k_min), 0.0)
    right_span = max(float(k_max) - k_hi, 0.0)
    if left_span <= 1.0e-14 and right_span <= 1.0e-14:
        return k_lin, float(k_lo), float(k_hi)
    if left_span <= 1.0e-14:
        n_left, n_right = 0, n_rem
    elif right_span <= 1.0e-14:
        n_left, n_right = n_rem, 0
    else:
        n_left = int(round(n_rem * left_span / (left_span + right_span)))
        n_left = int(max(1, min(n_left, n_rem - 1)))
        n_right = int(n_rem - n_left)

    parts: list[np.ndarray] = []
    if n_left > 0 and left_span > 0.0:
        parts.append(np.linspace(float(k_min), float(k_lo), n_left + 1, dtype=float)[:-1])
    parts.append(np.linspace(float(k_lo), float(k_hi), n_mid, dtype=float))
    if n_right > 0 and right_span > 0.0:
        parts.append(np.linspace(float(k_hi), float(k_max), n_right + 1, dtype=float)[1:])

    k_vals = np.unique(np.concatenate(parts))
    if k_vals[0] > float(k_min):
        k_vals = np.insert(k_vals, 0, float(k_min))
    if k_vals[-1] < float(k_max):
        k_vals = np.append(k_vals, float(k_max))

    if k_vals.size < n_target:
        k_vals = np.unique(np.concatenate([k_vals, np.linspace(float(k_min), float(k_max), n_target, dtype=float)]))
    if k_vals.size > n_target:
        idx = np.linspace(0, k_vals.size - 1, n_target)
        idx = np.unique(np.round(idx).astype(int))
        k_vals = k_vals[idx]
        if k_vals[0] > float(k_min):
            k_vals[0] = float(k_min)
        if k_vals[-1] < float(k_max):
            k_vals[-1] = float(k_max)

    return np.asarray(k_vals, dtype=float), float(k_lo), float(k_hi)


def append_outer_k_tails(k_grid: np.ndarray, k_tail_max: float | None, n_tail: int) -> np.ndarray:
    n_tail_i = int(max(n_tail, 0))
    if n_tail_i <= 0 or k_tail_max is None:
        return np.asarray(k_grid, dtype=float)
    k = np.asarray(k_grid, dtype=float)
    k_core = float(np.max(k))
    k_tail_max_f = float(k_tail_max)
    if not np.isfinite(k_tail_max_f) or k_tail_max_f <= k_core:
        return k
    tail = np.geomspace(k_core, k_tail_max_f, n_tail_i + 1, dtype=float)[1:]
    return np.unique(np.concatenate([k, tail]))


def enrich_with_zero_feature_window(
    base_grid: np.ndarray,
    *,
    half_width: float,
    n_local: int,
) -> np.ndarray:
    grid = np.asarray(base_grid, dtype=float).reshape(-1)
    if grid.size == 0:
        return grid

    hw = max(float(half_width), 0.0)
    nloc = int(max(0, n_local))
    if hw <= 0.0 or nloc < 3:
        return grid

    if nloc % 2 == 0:
        nloc += 1

    a = float(grid[0])
    b = float(grid[-1])
    local = np.linspace(-hw, hw, nloc, dtype=float)
    local = local[(local >= a) & (local <= b)]
    if local.size == 0:
        return grid

    out = np.unique(np.concatenate([grid, local, np.array([0.0], dtype=float)]))
    i0 = int(np.argmin(np.abs(out)))
    if abs(float(out[i0])) < 1.0e-12:
        out[i0] = 0.0
    return out


def merge_omega_log_nodes(w_grid: np.ndarray, wmin: float, wmax: float, n: int) -> np.ndarray:
    if int(n) <= 0:
        return np.asarray(w_grid, dtype=float)
    if not (float(wmin) > 0.0 and float(wmax) > 0.0 and float(wmax) > float(wmin)):
        raise ValueError("Require 0 < logw-min < logw-max when logw-n > 0.")
    pos = np.logspace(np.log10(float(wmin)), np.log10(float(wmax)), int(n))
    extra = np.concatenate([-pos[::-1], np.array([0.0], dtype=float), pos])
    return np.unique(np.concatenate([np.asarray(w_grid, dtype=float), extra]))


def append_outer_omega_tails(w_grid: np.ndarray, w_tail_max: float | None, n_tail: int) -> np.ndarray:
    n_tail_i = int(max(n_tail, 0))
    if n_tail_i <= 0 or w_tail_max is None:
        return np.asarray(w_grid, dtype=float)
    w = np.asarray(w_grid, dtype=float)
    w_core = float(np.max(np.abs(w)))
    w_tail_max_f = float(abs(w_tail_max))
    if w_tail_max_f <= w_core:
        return w
    pos = np.geomspace(w_core, w_tail_max_f, n_tail_i + 1)[1:]
    tail = np.concatenate([-pos[::-1], pos])
    return np.unique(np.concatenate([w, tail]))


def build_axes(
    nk: int,
    nw: int,
    wmax: float,
    k_tail_max: float | None,
    k_tail_n: int,
    w_tail_max: float | None,
    w_tail_n: int,
    omega_grid_mode: str,
    omega_inner_frac: float,
    omega_cusp_factor: float,
    omega_split_power: float,
    omega_feature_half_width: float,
    omega_feature_n_local: int,
    logw_min: float,
    logw_max: float,
    logw_n: int,
    mass: float,
    mu_up: float,
    mu_dn: float,
    kmax_factor: float,
    k_max_cover_wmax: bool,
    k_max_cover_margin: float,
    k_corridor_refine: bool,
    k_corridor_frac: float,
    k_corridor_margin: float,
    k_corridor_min_points: int,
) -> tuple[np.ndarray, np.ndarray, dict[str, float]]:
    nk_i = int(max(2, nk))
    nw_i = int(max(3, nw))
    wmax_f = float(wmax)
    if wmax_f <= 0.0:
        raise ValueError("wmax must be > 0.")
    kf_up = np.sqrt(max(float(mass) * float(mu_up), 0.0))
    kf_dn = np.sqrt(max(float(mass) * float(mu_dn), 0.0))
    omega_cover = float(wmax_f)
    if w_tail_max is not None:
        omega_cover = max(float(omega_cover), float(abs(w_tail_max)))
    k_max_base = float(max(kmax_factor, 0.05) * max(kf_up, kf_dn))
    k_res_cover = float(np.sqrt(max(max(float(mu_up), float(mu_dn)) + float(omega_cover), 0.0)))
    k_cover_target = float(k_res_cover + max(float(k_max_cover_margin), 0.0))
    kmax = max(k_max_base, k_cover_target) if bool(k_max_cover_wmax) else k_max_base
    k, k_corr_lo, k_corr_hi = build_k_grid_with_corridor(
        0.0,
        float(kmax),
        nk_i,
        mu_dn=float(mu_dn),
        mu_up=float(mu_up),
        mass=float(mass),
        enabled=bool(k_corridor_refine),
        corridor_frac=float(k_corridor_frac),
        corridor_margin=float(k_corridor_margin),
        corridor_min_points=int(k_corridor_min_points),
    )
    k = append_outer_k_tails(k, k_tail_max, int(k_tail_n))
    omega_mode = str(omega_grid_mode).strip().lower()
    if omega_mode == "split":
        w = build_split_axis(-wmax_f, +wmax_f, nw_i, float(omega_split_power))
        w = enrich_with_zero_feature_window(
            w,
            half_width=float(omega_feature_half_width),
            n_local=int(omega_feature_n_local),
        )
    elif omega_mode == "gl_cusp":
        mu_bar = float(min(float(mu_up), float(mu_dn)))
        omega_cusp = float(max(0.0, min(wmax_f, float(omega_cusp_factor) * mu_bar)))
        w = st.build_omega_grid(
            float(wmax_f),
            int(nw_i),
            float(omega_cusp),
            mode="gl_cusp",
            inner_frac=float(omega_inner_frac),
        )
    else:
        w = np.linspace(-wmax_f, +wmax_f, nw_i, dtype=float)
    w = merge_omega_log_nodes(w, float(logw_min), float(logw_max), int(logw_n))
    w = append_outer_omega_tails(w, w_tail_max, int(w_tail_n))
    meta = {
        "k_max_base": float(k_max_base),
        "k_res_cover": float(k_res_cover),
        "k_cover_target": float(k_cover_target),
        "k_max_used": float(kmax),
        "k_max_with_tail": float(np.max(k)),
        "k_corr_lo": float(k_corr_lo) if np.isfinite(k_corr_lo) else np.nan,
        "k_corr_hi": float(k_corr_hi) if np.isfinite(k_corr_hi) else np.nan,
        "omega_cover": float(omega_cover),
    }
    return k, np.asarray(w, dtype=float), meta


def spectral_from_g(g: np.ndarray, convention: str) -> np.ndarray:
    if str(convention) == "minus1_over_pi_im":
        return -(1.0 / np.pi) * np.imag(g)
    return -2.0 * np.imag(g)
















